/* Generated by Nim Compiler v2.2.10 */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   x86_64-w64-mingw32-gcc -c -w -fmax-errors=3 -mno-ms-bitfields -fno-strict-aliasing -DWIN32_LEAN_AND_MEAN -Os -fno-ident   -I/home/kali/.choosenim/toolchains/nim-2.2.10/lib -I/home/kali/c2/agents/agent-nim -o /home/kali/c2/agents/agent-nim/nimcache_nim5min/@mcrypto.nim.c.o /home/kali/c2/agents/agent-nim/nimcache_nim5min/@mcrypto.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ tySequence__6H5Oh5UUvVCLiakt9aTwtUQ;
typedef struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content;
typedef struct tyObject_HSlice__RmqVCB5rHyE9cs59bZ8FgkPA tyObject_HSlice__RmqVCB5rHyE9cs59bZ8FgkPA;
typedef struct tyObject_HSlice__gNm3PIFaVREVVU9cuqHQIFg tyObject_HSlice__gNm3PIFaVREVVU9cuqHQIFg;
typedef struct tyObject_GCM__eCD3Vqnb9c9cdir9bofS9aCo9aA tyObject_GCM__eCD3Vqnb9c9cdir9bofS9aCo9aA;
typedef struct tyObject_RijndaelContext__NKUvxdvWF0pP2HEDIjikiQ tyObject_RijndaelContext__NKUvxdvWF0pP2HEDIjikiQ;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ {
  NI len; tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content* p;
};
struct tyObject_HSlice__RmqVCB5rHyE9cs59bZ8FgkPA {
	NI a;
	NI b;
};
struct tyObject_HSlice__gNm3PIFaVREVVU9cuqHQIFg {
	NI a;
	NI b;
};
typedef NU64 tyArray__ey43Vigk7skIYtX9aBAXSdw[120];
struct tyObject_RijndaelContext__NKUvxdvWF0pP2HEDIjikiQ {
	tyArray__ey43Vigk7skIYtX9aBAXSdw skey;
	NI nr;
};
typedef NU8 tyArray__dnD8kjh6rJ1Yy5jHvid0Ow[16];
struct tyObject_GCM__eCD3Vqnb9c9cdir9bofS9aCo9aA {
	tyObject_RijndaelContext__NKUvxdvWF0pP2HEDIjikiQ cipher;
	tyArray__dnD8kjh6rJ1Yy5jHvid0Ow h;
	tyArray__dnD8kjh6rJ1Yy5jHvid0Ow y;
	tyArray__dnD8kjh6rJ1Yy5jHvid0Ow basectr;
	tyArray__dnD8kjh6rJ1Yy5jHvid0Ow buf;
	tyArray__dnD8kjh6rJ1Yy5jHvid0Ow hbuf;
	NU64 aadlen;
	NU64 datalen;
	NU8 coffset;
};
typedef NU8 tyArray__EByiwLR18qRt45X8RAcPbA[32];
typedef NU8 tyArray__Pu3SVivFPiiTdvogs5S4RQ[12];
typedef NU8 tyArray__XQcakUXYkFbc2tj2egOnrw[1];
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
typedef N_STDCALL_PTR(NI32, tyProc__xm9awtfGrxZ8fpQM1Tp6IpA) (NI hAlg_p0, NU8* pb_p1, NI32 cb_p2, NI32 flags_p3);
struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content { NI cap; NU8 data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NIMCALL(void*, newSeqPayload)(NI cap_p0, NI elemSize_p1, NI elemAlign_p2);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZtimes_u2656)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ dest_p0);
N_LIB_PRIVATE N_NIMCALL(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ, X5BX5D___crypto_u1710)(NU8* s_p0, NI s_p0Len_0, tyObject_HSlice__RmqVCB5rHyE9cs59bZ8FgkPA x_p1);
static N_INLINE(tyObject_HSlice__RmqVCB5rHyE9cs59bZ8FgkPA, dotdot___stdZstrbasics_u48)(NI a_p0, NI b_p1);
N_LIB_PRIVATE N_NIMCALL(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ, X5BX5D___crypto_u1771)(NU8* s_p0, NI s_p0Len_0, tyObject_HSlice__gNm3PIFaVREVVU9cuqHQIFg x_p1);
static N_INLINE(tyObject_HSlice__gNm3PIFaVREVVU9cuqHQIFg, dotdot___stdZenumutils_u105)(NI a_p0, NI b_p1);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__system_u2188)(void* a_p0, int v_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(void, init__crypto_u107)(tyObject_GCM__eCD3Vqnb9c9cdir9bofS9aCo9aA* ctx_p0, NU8* key_p1, NI key_p1Len_0, NU8* iv_p2, NI iv_p2Len_0, NU8* aad_p3, NI aad_p3Len_0);
N_LIB_PRIVATE N_NIMCALL(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ, newSeq__stdZsysrand_u55)(NI len_p0);
N_LIB_PRIVATE N_NIMCALL(void, decrypt__crypto_u1953)(tyObject_GCM__eCD3Vqnb9c9cdir9bofS9aCo9aA* ctx_p0, NU8* input_p1, NI input_p1Len_0, NU8* output_p2, NI output_p2Len_0);
N_LIB_PRIVATE N_NIMCALL(void, getTag__crypto_u1407)(tyObject_GCM__eCD3Vqnb9c9cdir9bofS9aCo9aA* ctx_p0, tyArray__dnD8kjh6rJ1Yy5jHvid0Ow Result);
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___pureZtimes_u2653)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ* dest_p0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ, randomBytes__crypto_u6)(NI n_p0);
N_LIB_PRIVATE N_NIMCALL(void*, nimLoadLibrary)(NimStringV2 path_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimLoadLibraryError)(NimStringV2 path_p0);
N_LIB_PRIVATE N_NIMCALL(void*, nimGetProcAddr)(void* lib_p0, NCSTRING name_p1);
N_LIB_PRIVATE N_NIMCALL(void, encrypt__crypto_u1281)(tyObject_GCM__eCD3Vqnb9c9cdir9bofS9aCo9aA* ctx_p0, NU8* input_p1, NI input_p1Len_0, NU8* output_p2, NI output_p2Len_0);
N_LIB_PRIVATE N_NIMCALL(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ, amp___crypto_u1543)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ x_p0, tySequence__6H5Oh5UUvVCLiakt9aTwtUQ y_p1);
N_LIB_PRIVATE N_NIMCALL(void, add__pureZtimes_u2614)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ* x_p0, NU8 y_p1);
static const struct {
  NI cap; NIM_CHAR data[6+1];
} TM__Lui2ZiWpolvHLyCbWRBk7A_4 = { 6 | NIM_STRLIT_FLAG, "bcrypt" };
static const NimStringV2 TM__Lui2ZiWpolvHLyCbWRBk7A_5 = {6, (NimStrPayload*)&TM__Lui2ZiWpolvHLyCbWRBk7A_4};
static const struct {
  NI cap; NIM_CHAR data[6+1];
} TM__Lui2ZiWpolvHLyCbWRBk7A_6 = { 6 | NIM_STRLIT_FLAG, "bcrypt" };
static const NimStringV2 TM__Lui2ZiWpolvHLyCbWRBk7A_7 = {6, (NimStrPayload*)&TM__Lui2ZiWpolvHLyCbWRBk7A_6};
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4172;
static void* TM__Lui2ZiWpolvHLyCbWRBk7A_2;
tyProc__xm9awtfGrxZ8fpQM1Tp6IpA Dl_2432696349_;
static N_INLINE(tyObject_HSlice__RmqVCB5rHyE9cs59bZ8FgkPA, dotdot___stdZstrbasics_u48)(NI a_p0, NI b_p1) {
	tyObject_HSlice__RmqVCB5rHyE9cs59bZ8FgkPA result;
	result.a = a_p0;
	result.b = b_p1;
	return result;
}
static N_INLINE(tyObject_HSlice__gNm3PIFaVREVVU9cuqHQIFg, dotdot___stdZenumutils_u105)(NI a_p0, NI b_p1) {
	tyObject_HSlice__gNm3PIFaVREVVU9cuqHQIFg result;
	result.a = a_p0;
	result.b = b_p1;
	return result;
}
static N_INLINE(void, nimSetMem__system_u2188)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
	nimSetMem__system_u2188(p_p0, ((int)0), size_p1);
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4172);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ, openGCM__crypto_u1684)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ key_p0, tySequence__6H5Oh5UUvVCLiakt9aTwtUQ data_p1) {
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ result;
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ nonce_1;
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ ct_1;
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ tag_1;
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ pt_1;
	tyObject_HSlice__RmqVCB5rHyE9cs59bZ8FgkPA T7_;
	NI T8_;
	tyObject_HSlice__RmqVCB5rHyE9cs59bZ8FgkPA T9_;
	NI T10_;
	tyObject_HSlice__gNm3PIFaVREVVU9cuqHQIFg T11_;
	tyObject_GCM__eCD3Vqnb9c9cdir9bofS9aCo9aA ctx_1;
	tyArray__EByiwLR18qRt45X8RAcPbA k32_1;
	tyArray__Pu3SVivFPiiTdvogs5S4RQ n12_1;
	tyArray__XQcakUXYkFbc2tj2egOnrw T18_;
	NI T19_;
	tyArray__dnD8kjh6rJ1Yy5jHvid0Ow computedTag_1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nonce_1.len = 0; nonce_1.p = NIM_NIL;
	ct_1.len = 0; ct_1.p = NIM_NIL;
	tag_1.len = 0; tag_1.p = NIM_NIL;
	pt_1.len = 0; pt_1.p = NIM_NIL;
	{
		NI T4_;
		T4_ = data_p1.len;
		if (!(T4_ < ((NI)28))) goto LA5_;
		result.len = 0; result.p = (tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content*) newSeqPayload(0, sizeof(NU8), NIM_ALIGNOF(NU8));
		eqdestroy___pureZtimes_u2656(pt_1);
		eqdestroy___pureZtimes_u2656(tag_1);
		eqdestroy___pureZtimes_u2656(ct_1);
		eqdestroy___pureZtimes_u2656(nonce_1);
		goto BeforeRet_;
	}
LA5_: ;
	T7_ = dotdot___stdZstrbasics_u48(((NI)0), ((NI)11));
	nonce_1 = X5BX5D___crypto_u1710(((data_p1).p) ? (data_p1.p->data) : NIM_NIL, data_p1.len, T7_);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T8_ = data_p1.len;
	T9_ = dotdot___stdZstrbasics_u48(((NI)12), (NI)((NI)(T8_ - ((NI)16)) - ((NI)1)));
	ct_1 = X5BX5D___crypto_u1710(((data_p1).p) ? (data_p1.p->data) : NIM_NIL, data_p1.len, T9_);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T10_ = data_p1.len;
	T11_ = dotdot___stdZenumutils_u105((NI)(T10_ - ((NI)16)), ((NI)1));
	tag_1 = X5BX5D___crypto_u1771(((data_p1).p) ? (data_p1.p->data) : NIM_NIL, data_p1.len, T11_);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimZeroMem((void*)(&ctx_1), sizeof(tyObject_GCM__eCD3Vqnb9c9cdir9bofS9aCo9aA));
	nimZeroMem((void*)k32_1, sizeof(tyArray__EByiwLR18qRt45X8RAcPbA));
	nimZeroMem((void*)n12_1, sizeof(tyArray__Pu3SVivFPiiTdvogs5S4RQ));
	{
		NI i_1;
		NI i_2;
		i_1 = (NI)0;
		i_2 = ((NI)0);
		{
			while (1) {
				if (!(i_2 < ((NI)32))) goto LA14;
				i_1 = i_2;
				k32_1[(i_1)- 0] = key_p0.p->data[i_1];
				i_2 += ((NI)1);
			} LA14: ;
		}
	}
	{
		NI i_3;
		NI i_4;
		i_3 = (NI)0;
		i_4 = ((NI)0);
		{
			while (1) {
				if (!(i_4 < ((NI)12))) goto LA17;
				i_3 = i_4;
				n12_1[(i_3)- 0] = nonce_1.p->data[i_3];
				i_4 += ((NI)1);
			} LA17: ;
		}
	}
	init__crypto_u107((&ctx_1), k32_1, 32, n12_1, 12, T18_, 0);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T19_ = ct_1.len;
	pt_1 = newSeq__stdZsysrand_u55((T19_));
	{
		NI T22_;
		T22_ = ct_1.len;
		if (!(((NI)0) < T22_)) goto LA23_;
		decrypt__crypto_u1953((&ctx_1), ((ct_1).p) ? (ct_1.p->data) : NIM_NIL, ct_1.len, ((pt_1).p) ? (pt_1.p->data) : NIM_NIL, pt_1.len);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	}
LA23_: ;
	nimZeroMem((void*)computedTag_1, sizeof(tyArray__dnD8kjh6rJ1Yy5jHvid0Ow));
	getTag__crypto_u1407((&ctx_1), computedTag_1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		NI i_5;
		NI i_6;
		i_5 = (NI)0;
		i_6 = ((NI)0);
		{
			while (1) {
				if (!(i_6 < ((NI)16))) goto LA27;
				i_5 = i_6;
				{
					if (!!((computedTag_1[(i_5)- 0] == tag_1.p->data[i_5]))) goto LA30_;
					result.len = 0; result.p = (tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content*) newSeqPayload(0, sizeof(NU8), NIM_ALIGNOF(NU8));
					eqdestroy___pureZtimes_u2656(pt_1);
					eqdestroy___pureZtimes_u2656(tag_1);
					eqdestroy___pureZtimes_u2656(ct_1);
					eqdestroy___pureZtimes_u2656(nonce_1);
					goto BeforeRet_;
				}
LA30_: ;
				i_6 += ((NI)1);
			} LA27: ;
		}
	}
	result = pt_1;
	eqwasMoved___pureZtimes_u2653((&pt_1));
	eqdestroy___pureZtimes_u2656(pt_1);
	eqdestroy___pureZtimes_u2656(tag_1);
	eqdestroy___pureZtimes_u2656(ct_1);
	eqdestroy___pureZtimes_u2656(nonce_1);
	goto BeforeRet_;
	{
		LA1_:;
	}
	{
		eqdestroy___pureZtimes_u2656(pt_1);
		eqdestroy___pureZtimes_u2656(tag_1);
		eqdestroy___pureZtimes_u2656(ct_1);
		eqdestroy___pureZtimes_u2656(nonce_1);
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ, randomBytes__crypto_u6)(NI n_p0) {
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ result;
	NI32 T1_;
	result.len = 0; result.p = NIM_NIL;
	result = newSeq__stdZsysrand_u55((n_p0));
	T1_ = (NI32)0;
	T1_ = Dl_2432696349_(((NI)0), (&result.p->data[((NI)0)]), ((NI32) (n_p0)), ((NI32)2));
	(void)(T1_);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ, sealGCM__crypto_u34)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ key_p0, tySequence__6H5Oh5UUvVCLiakt9aTwtUQ plaintext_p1) {
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ result;
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ nonce_1;
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ ct_1;
	tyObject_GCM__eCD3Vqnb9c9cdir9bofS9aCo9aA ctx_1;
	tyArray__EByiwLR18qRt45X8RAcPbA k32_1;
	tyArray__Pu3SVivFPiiTdvogs5S4RQ n12_1;
	tyArray__XQcakUXYkFbc2tj2egOnrw T8_;
	NI T9_;
	tyArray__dnD8kjh6rJ1Yy5jHvid0Ow tag_1;
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ blitTmp_1;
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ blitTmp_2;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nonce_1.len = 0; nonce_1.p = NIM_NIL;
	ct_1.len = 0; ct_1.p = NIM_NIL;
	nonce_1 = randomBytes__crypto_u6(((NI)12));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimZeroMem((void*)(&ctx_1), sizeof(tyObject_GCM__eCD3Vqnb9c9cdir9bofS9aCo9aA));
	nimZeroMem((void*)k32_1, sizeof(tyArray__EByiwLR18qRt45X8RAcPbA));
	nimZeroMem((void*)n12_1, sizeof(tyArray__Pu3SVivFPiiTdvogs5S4RQ));
	{
		NI i_1;
		NI i_2;
		i_1 = (NI)0;
		i_2 = ((NI)0);
		{
			while (1) {
				if (!(i_2 < ((NI)32))) goto LA4;
				i_1 = i_2;
				k32_1[(i_1)- 0] = key_p0.p->data[i_1];
				i_2 += ((NI)1);
			} LA4: ;
		}
	}
	{
		NI i_3;
		NI i_4;
		i_3 = (NI)0;
		i_4 = ((NI)0);
		{
			while (1) {
				if (!(i_4 < ((NI)12))) goto LA7;
				i_3 = i_4;
				n12_1[(i_3)- 0] = nonce_1.p->data[i_3];
				i_4 += ((NI)1);
			} LA7: ;
		}
	}
	init__crypto_u107((&ctx_1), k32_1, 32, n12_1, 12, T8_, 0);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T9_ = plaintext_p1.len;
	ct_1 = newSeq__stdZsysrand_u55((T9_));
	{
		NI T12_;
		T12_ = plaintext_p1.len;
		if (!(((NI)0) < T12_)) goto LA13_;
		encrypt__crypto_u1281((&ctx_1), ((plaintext_p1).p) ? (plaintext_p1.p->data) : NIM_NIL, plaintext_p1.len, ((ct_1).p) ? (ct_1.p->data) : NIM_NIL, ct_1.len);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	}
LA13_: ;
	nimZeroMem((void*)tag_1, sizeof(tyArray__dnD8kjh6rJ1Yy5jHvid0Ow));
	getTag__crypto_u1407((&ctx_1), tag_1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	blitTmp_1 = nonce_1;
	blitTmp_2 = ct_1;
	result = amp___crypto_u1543(blitTmp_1, blitTmp_2);
	{
		NU8 b_1;
		NI i_5;
		b_1 = (NU8)0;
		i_5 = ((NI)0);
		{
			while (1) {
				b_1 = tag_1[(i_5)- 0];
				add__pureZtimes_u2614((&result), b_1);
				{
					if (!(((NI)15) <= i_5)) goto LA20_;
					goto LA16;
				}
LA20_: ;
				i_5 += ((NI)1);
			}
		} LA16: ;
	}
	{
		LA1_:;
	}
	{
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, atmcryptodotnim_DatInit000)(void) {
if (!((TM__Lui2ZiWpolvHLyCbWRBk7A_2 = nimLoadLibrary(TM__Lui2ZiWpolvHLyCbWRBk7A_5))
)) nimLoadLibraryError(TM__Lui2ZiWpolvHLyCbWRBk7A_7);
	Dl_2432696349_ = (tyProc__xm9awtfGrxZ8fpQM1Tp6IpA) nimGetProcAddr(TM__Lui2ZiWpolvHLyCbWRBk7A_2, "BCryptGenRandom");
}

