/* Generated by Nim Compiler v2.2.10 */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   x86_64-w64-mingw32-gcc -c -w -fmax-errors=3 -mno-ms-bitfields -fno-strict-aliasing -DWIN32_LEAN_AND_MEAN -Os -fno-ident   -I/home/kali/.choosenim/toolchains/nim-2.2.10/lib -I/home/kali/c2/agents/agent-nim -o /home/kali/c2/agents/agent-nim/nimcache_nim5min/@mtransport.nim.c.o /home/kali/c2/agents/agent-nim/nimcache_nim5min/@mtransport.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tyObject_AgentTransport__5qQy6rhkf3jaeikY8XXtPQ tyObject_AgentTransport__5qQy6rhkf3jaeikY8XXtPQ;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ tySequence__6H5Oh5UUvVCLiakt9aTwtUQ;
typedef struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ tySequence__sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content;
typedef struct tyObject_JsonNodeObj__HuNCd9cjVf1RGJ8WXqZvVog tyObject_JsonNodeObj__HuNCd9cjVf1RGJ8WXqZvVog;
typedef struct tyTuple__hnCuDR9cLe2lA3YIkwKIyuA tyTuple__hnCuDR9cLe2lA3YIkwKIyuA;
typedef struct tyObject_OrderedTable__alibvEreYoDQX0zEzfTleQ tyObject_OrderedTable__alibvEreYoDQX0zEzfTleQ;
typedef struct tySequence__xUV33m0d5HZLvMGUKDBm7Q tySequence__xUV33m0d5HZLvMGUKDBm7Q;
typedef struct tySequence__xUV33m0d5HZLvMGUKDBm7Q_Content tySequence__xUV33m0d5HZLvMGUKDBm7Q_Content;
typedef struct tySequence__YWxjq9aB9anxKHaOq65jIGKw tySequence__YWxjq9aB9anxKHaOq65jIGKw;
typedef struct tySequence__YWxjq9aB9anxKHaOq65jIGKw_Content tySequence__YWxjq9aB9anxKHaOq65jIGKw_Content;
typedef struct tyTuple__BU3523wAnglxkwDbWscqhQ tyTuple__BU3523wAnglxkwDbWscqhQ;
typedef struct tyObject_WideCStringObj__jQbOKocsbu7Z9bKTSFtX4TQ tyObject_WideCStringObj__jQbOKocsbu7Z9bKTSFtX4TQ;
typedef struct tyObject_HSlice__gNm3PIFaVREVVU9cuqHQIFg tyObject_HSlice__gNm3PIFaVREVVU9cuqHQIFg;
typedef struct tyObject_HSlice__RmqVCB5rHyE9cs59bZ8FgkPA tyObject_HSlice__RmqVCB5rHyE9cs59bZ8FgkPA;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tySequence__UIJx6FJrflnhA9a3u1VF1vA tySequence__UIJx6FJrflnhA9a3u1VF1vA;
typedef struct tySequence__UIJx6FJrflnhA9a3u1VF1vA_Content tySequence__UIJx6FJrflnhA9a3u1VF1vA_Content;
typedef struct tySequence__9c9a9ceFj9bCgncwLIjnR3kpJg tySequence__9c9a9ceFj9bCgncwLIjnR3kpJg;
typedef struct tySequence__9c9a9ceFj9bCgncwLIjnR3kpJg_Content tySequence__9c9a9ceFj9bCgncwLIjnR3kpJg_Content;
typedef struct tyObject_TaskWire__mbM5G2Ws36WZ5MBZxEz9bWw tyObject_TaskWire__mbM5G2Ws36WZ5MBZxEz9bWw;
typedef struct tyTuple__s8qsQCcBOMNS7M9aFeWibtQ tyTuple__s8qsQCcBOMNS7M9aFeWibtQ;
typedef struct tyObject_StackTraceEntry__UznwMnjUHK6AxZHnP9bMXEA tyObject_StackTraceEntry__UznwMnjUHK6AxZHnP9bMXEA;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ {
  NI len; tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content* p;
};
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ {
  NI len; tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content* p;
};
struct tyObject_AgentTransport__5qQy6rhkf3jaeikY8XXtPQ {
	NimStringV2 serverUrl;
	NimStringV2 agentId;
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ aesKey;
	NI uriIdx;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ uriList;
};
struct tyTuple__hnCuDR9cLe2lA3YIkwKIyuA {
	NI Field0;
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ Field1;
};
typedef NU8 tyEnum_JsonNodeKind__AgEdEY3Szs9c2LYpGqyQ2lA;
struct tySequence__xUV33m0d5HZLvMGUKDBm7Q {
  NI len; tySequence__xUV33m0d5HZLvMGUKDBm7Q_Content* p;
};
struct tyObject_OrderedTable__alibvEreYoDQX0zEzfTleQ {
	tySequence__xUV33m0d5HZLvMGUKDBm7Q data;
	NI counter;
	NI first;
	NI last;
};
struct tySequence__YWxjq9aB9anxKHaOq65jIGKw {
  NI len; tySequence__YWxjq9aB9anxKHaOq65jIGKw_Content* p;
};
struct tyObject_JsonNodeObj__HuNCd9cjVf1RGJ8WXqZvVog {
	NIM_BOOL isUnquoted;
	tyEnum_JsonNodeKind__AgEdEY3Szs9c2LYpGqyQ2lA kind;
union{
	struct {
	NimStringV2 str;
} _kind_1;
	struct {
	NI64 num;
} _kind_2;
	struct {
	NF fnum;
} _kind_3;
	struct {
	NIM_BOOL bval;
} _kind_4;
	struct {
	tyObject_OrderedTable__alibvEreYoDQX0zEzfTleQ fields;
} _kind_6;
	struct {
	tySequence__YWxjq9aB9anxKHaOq65jIGKw elems;
} _kind_7;
};
};
struct tyTuple__BU3523wAnglxkwDbWscqhQ {
	NimStringV2 Field0;
	tyObject_JsonNodeObj__HuNCd9cjVf1RGJ8WXqZvVog* Field1;
};
typedef tyTuple__BU3523wAnglxkwDbWscqhQ tyArray__r0mq37zJ5pjlN4CzdC9coUg[8];
struct tyObject_WideCStringObj__jQbOKocsbu7Z9bKTSFtX4TQ {
	NI bytes;
	NI16* data;
};
typedef N_STDCALL_PTR(NI32, tyProc__RqPJ327ezwqplysPaezU3Q) (NU16* lpName_p0, NU16* lpBuffer_p1, NI32 nSize_p2);
typedef N_STDCALL_PTR(NI32, tyProc__9bXer9a4ps9aSGctILcxWReVw) (void);
typedef N_STDCALL_PTR(NI32, tyProc__zs1G9aN0hsG4qr4I6t6Agtg) (NI hModule_p0, NU16* lpFilename_p1, NI32 nSize_p2);
struct tyObject_HSlice__gNm3PIFaVREVVU9cuqHQIFg {
	NI a;
	NI b;
};
typedef N_STDCALL_PTR(void*, tyProc__81VIzYkqwzDl7rl3af0pZg) (NU16* P1_p0, NI32 P2_p1, NU16* P3_p2, NU16* P4_p3, NI32 P5_p4);
struct tyObject_HSlice__RmqVCB5rHyE9cs59bZ8FgkPA {
	NI a;
	NI b;
};
typedef N_STDCALL_PTR(void*, tyProc__RFwzZ679c39c5tm4O7Tpzjeg) (void* P1_p0, NU16* P2_p1, NU16 P3_p2, NI32 P4_p3);
typedef N_STDCALL_PTR(NI32, tyProc__ah5wcFv3UG20t2vgXBy0Fg) (void* P1_p0);
typedef N_STDCALL_PTR(void*, tyProc__VvL5F9ctiPFd9cY0CxFJmncg) (void* P1_p0, NU16* P2_p1, NU16* P3_p2, NU16* P4_p3, NU16* P5_p4, NU16** P6_p5, NI32 P7_p6);
typedef N_STDCALL_PTR(NI32, tyProc__OygtxCk9aDjhab6i7UhdJdQ) (void* P1_p0, NI32 P2_p1, void* P3_p2, NI32 P4_p3);
typedef N_STDCALL_PTR(NI32, tyProc__HfA740GE5GucMArbWnkCkw) (void* P1_p0, NU16* P2_p1, NI32 P3_p2, void* P4_p3, NI32 P5_p4, NI32 P6_p5, NI64 P7_p6);
typedef N_STDCALL_PTR(NI32, tyProc__wS8JrJMcfFBzgzuqJGOAAg) (void* P1_p0, void* P2_p1);
typedef N_STDCALL_PTR(NI32, tyProc__5V5gHAr7e9bsH0OKztxYmCw) (void* P1_p0, NI32 P2_p1, NU16* P3_p2, void* P4_p3, NI32* P5_p4, NI32* P6_p5);
typedef N_STDCALL_PTR(NI32, tyProc__mID4zaJ5rXbvlxUmzwPGLw) (void* P1_p0, void* P2_p1, NI32 P3_p2, NI32* P4_p3);
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct RootObj {
	TNimTypeV2* m_type;
};
struct tySequence__UIJx6FJrflnhA9a3u1VF1vA {
  NI len; tySequence__UIJx6FJrflnhA9a3u1VF1vA_Content* p;
};
struct Exception {
	RootObj Sup;
	Exception* parent;
	NCSTRING name;
	NimStringV2 message;
	tySequence__UIJx6FJrflnhA9a3u1VF1vA trace;
	Exception* up;
};
struct tySequence__9c9a9ceFj9bCgncwLIjnR3kpJg {
  NI len; tySequence__9c9a9ceFj9bCgncwLIjnR3kpJg_Content* p;
};
struct tyObject_TaskWire__mbM5G2Ws36WZ5MBZxEz9bWw {
	NI64 id;
	NimStringV2 typ;
	NimStringV2 args;
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ payload;
};
typedef tyTuple__BU3523wAnglxkwDbWscqhQ tyArray__sJUNyoTANwaMIsGxVULdtg[3];
struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content { NI cap; NU8 data[SEQ_DECL_SIZE]; };
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content { NI cap; NimStringV2 data[SEQ_DECL_SIZE]; };
struct tyTuple__s8qsQCcBOMNS7M9aFeWibtQ {
	NI Field0;
	NI Field1;
	NimStringV2 Field2;
	tyObject_JsonNodeObj__HuNCd9cjVf1RGJ8WXqZvVog* Field3;
};
struct tySequence__xUV33m0d5HZLvMGUKDBm7Q_Content { NI cap; tyTuple__s8qsQCcBOMNS7M9aFeWibtQ data[SEQ_DECL_SIZE]; };
struct tySequence__YWxjq9aB9anxKHaOq65jIGKw_Content { NI cap; tyObject_JsonNodeObj__HuNCd9cjVf1RGJ8WXqZvVog* data[SEQ_DECL_SIZE]; };
struct tyObject_StackTraceEntry__UznwMnjUHK6AxZHnP9bMXEA {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};
struct tySequence__UIJx6FJrflnhA9a3u1VF1vA_Content { NI cap; tyObject_StackTraceEntry__UznwMnjUHK6AxZHnP9bMXEA data[SEQ_DECL_SIZE]; };
struct tySequence__9c9a9ceFj9bCgncwLIjnR3kpJg_Content { NI cap; tyObject_TaskWire__mbM5G2Ws36WZ5MBZxEz9bWw data[SEQ_DECL_SIZE]; };
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__system_u2188)(void* a_p0, int v_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___system_u2729)(NimStringV2* dest_p0, NimStringV2 src_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___system_u5541)(tySequence__sM4lkSb7zS6F7OVMvW9cffQ* dest_p0, tySequence__sM4lkSb7zS6F7OVMvW9cffQ src_p1);
N_LIB_PRIVATE N_NIMCALL(tySequence__sM4lkSb7zS6F7OVMvW9cffQ, nsuSplitChar)(NimStringV2 s_p0, NIM_CHAR sep_p1, NI maxsplit_p2);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u5532)(tySequence__sM4lkSb7zS6F7OVMvW9cffQ dest_p0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__HuNCd9cjVf1RGJ8WXqZvVog*, percent___pureZjson_u2185)(tyTuple__BU3523wAnglxkwDbWscqhQ* keyVals_p0, NI keyVals_p0Len_0);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__HuNCd9cjVf1RGJ8WXqZvVog*, percent___pureZjson_u2156)(NimStringV2 s_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, getEnvStr__transport_u8)(NimStringV2 k_p0, NimStringV2 default_p1);
N_LIB_PRIVATE N_NIMCALL(tyObject_WideCStringObj__jQbOKocsbu7Z9bKTSFtX4TQ, newWideCString__stdZwidestrs_u325)(NimStringV2 s_p0);
N_NIMCALL(NimStringV2, mnewString)(NI len_p0);
N_LIB_PRIVATE N_NIMCALL(NU16*, winstrConverterWideCStringToLPWSTR__pkgZwinimZwinstr_u807)(tyObject_WideCStringObj__jQbOKocsbu7Z9bKTSFtX4TQ x_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___system_u2723)(NimStringV2* dest_p0, NimStringV2 src_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___stdZwidestrs_u7)(tyObject_WideCStringObj__jQbOKocsbu7Z9bKTSFtX4TQ a_p0);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___stdZwidestrs_u402)(tyObject_WideCStringObj__jQbOKocsbu7Z9bKTSFtX4TQ s_p0);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__HuNCd9cjVf1RGJ8WXqZvVog*, percent___pureZjson_u2166)(NI n_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, exeName__transport_u14)(void);
N_LIB_PRIVATE N_NIMCALL(NI, nsuRFindChar)(NimStringV2 s_p0, NIM_CHAR sub_p1, NI start_p2, NI last_p3);
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___system_u2720)(NimStringV2* dest_p0);
static N_INLINE(NimStringV2, X5BX5D___pureZstrutils_u1313)(NimStringV2 s_p0, tyObject_HSlice__gNm3PIFaVREVVU9cuqHQIFg x_p1);
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2* s_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimPrepareStrMutationImpl__system_u2462)(NimStringV2* s_p0);
static N_INLINE(tyObject_HSlice__gNm3PIFaVREVVU9cuqHQIFg, dotdot___stdZenumutils_u105)(NI a_p0, NI b_p1);
N_LIB_PRIVATE N_NIMCALL(tyTuple__hnCuDR9cLe2lA3YIkwKIyuA, winHttpDo__transport_u46)(tyObject_AgentTransport__5qQy6rhkf3jaeikY8XXtPQ* t_p0, NimStringV2 meth_p1, NimStringV2 path_p2, tySequence__6H5Oh5UUvVCLiakt9aTwtUQ body_p3);
N_LIB_PRIVATE N_NIMCALL(void*, newSeqPayload)(NI cap_p0, NI elemSize_p1, NI elemAlign_p2);
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___pureZtimes_u2653)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZtimes_u2656)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ dest_p0);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nsuStartsWith)(NimStringV2 s_p0, NimStringV2 prefix_p1);
static N_INLINE(void, eqdestroy___system_u281)(NimStringV2 x_p0);
N_LIB_PRIVATE N_NIMCALL(NI, nsuFindChar)(NimStringV2 s_p0, NIM_CHAR sub_p1, NI start_p2, NI last_p3);
static N_INLINE(NimStringV2, X5BX5D___pureZstrutils_u1285)(NimStringV2 s_p0, tyObject_HSlice__RmqVCB5rHyE9cs59bZ8FgkPA x_p1);
static N_INLINE(tyObject_HSlice__RmqVCB5rHyE9cs59bZ8FgkPA, dotdot___stdZstrbasics_u48)(NI a_p0, NI b_p1);
static N_INLINE(NIM_BOOL, contains__stdZenvvars_u53)(NIM_CHAR* a_p0, NI a_p0Len_0, NIM_CHAR item_p1);
static N_INLINE(NI, find__stdZenvvars_u58)(NIM_CHAR* a_p0, NI a_p0Len_0, NIM_CHAR item_p1);
N_LIB_PRIVATE N_NIMCALL(NI, nsuParseInt)(NimStringV2 s_p0);
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(void, copyMem__system_u1755)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, rawNewString)(NI space_p0);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringV2 a_p0, NimStringV2 b_p1);
static N_INLINE(NIM_BOOL, equalMem__system_u1763)(void* a_p0, void* b_p1, NI size_p2);
static N_INLINE(int, nimCmpMem)(void* a_p0, void* b_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ, newSeq__stdZsysrand_u55)(NI len_p0);
N_LIB_PRIVATE N_NIMCALL(void, add__transport_u283)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ* x_p0, NU8* y_p1, NI y_p1Len_0);
N_LIB_PRIVATE N_NIMCALL(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ, X5BX5D___crypto_u1710)(NU8* s_p0, NI s_p0Len_0, tyObject_HSlice__RmqVCB5rHyE9cs59bZ8FgkPA x_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___pureZjson_u4933)(tyObject_JsonNodeObj__HuNCd9cjVf1RGJ8WXqZvVog* node_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___transport_u309)(tyTuple__hnCuDR9cLe2lA3YIkwKIyuA* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZjson_u321)(tyObject_JsonNodeObj__HuNCd9cjVf1RGJ8WXqZvVog* dest_p0);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__HuNCd9cjVf1RGJ8WXqZvVog*, parseJson__pureZjson_u5692)(NimStringV2 buffer_p0, NIM_BOOL rawIntegers_p1, NIM_BOOL rawFloats_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, getStr__pureZjson_u551)(tyObject_JsonNodeObj__HuNCd9cjVf1RGJ8WXqZvVog* n_p0, NimStringV2 default_p1);
static N_INLINE(tyObject_JsonNodeObj__HuNCd9cjVf1RGJ8WXqZvVog*, X5BX5D___pureZjson_u3580)(tyObject_JsonNodeObj__HuNCd9cjVf1RGJ8WXqZvVog* node_p0, NimStringV2 name_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___pureZjson_u324)(tyObject_JsonNodeObj__HuNCd9cjVf1RGJ8WXqZvVog** dest_p0, tyObject_JsonNodeObj__HuNCd9cjVf1RGJ8WXqZvVog* src_p1);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__HuNCd9cjVf1RGJ8WXqZvVog**, X5BX5D___pureZjson_u3088)(tyObject_OrderedTable__alibvEreYoDQX0zEzfTleQ* t_p0, NimStringV2 key_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___pureZtimes_u2665)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ* dest_p0, tySequence__6H5Oh5UUvVCLiakt9aTwtUQ src_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, decode__pureZbase64_u481)(NimStringV2 s_p0);
N_LIB_PRIVATE N_NIMCALL(void, raiseDefect)(void);
static N_INLINE(void, popCurrentException)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___system_u3693)(Exception** dest_p0, Exception* src_p1, NIM_BOOL cyclic_p2);
N_LIB_PRIVATE N_NIMCALL(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ, openGCM__crypto_u1684)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ key_p0, tySequence__6H5Oh5UUvVCLiakt9aTwtUQ data_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___pureZjson_u257)(tySequence__YWxjq9aB9anxKHaOq65jIGKw* dest_p0, tySequence__YWxjq9aB9anxKHaOq65jIGKw src_p1);
N_LIB_PRIVATE N_NIMCALL(NI64, getBiggestInt__pureZjson_u574)(tyObject_JsonNodeObj__HuNCd9cjVf1RGJ8WXqZvVog* n_p0, NI64 default_p1);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__HuNCd9cjVf1RGJ8WXqZvVog*, X7BX7D___pureZjson_u4070)(tyObject_JsonNodeObj__HuNCd9cjVf1RGJ8WXqZvVog* node_p0, NimStringV2 key_p1);
N_LIB_PRIVATE N_NIMCALL(void, add__transport_u469)(tySequence__9c9a9ceFj9bCgncwLIjnR3kpJg* x_p0, tyObject_TaskWire__mbM5G2Ws36WZ5MBZxEz9bWw* y_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___transport_u559)(tyObject_TaskWire__mbM5G2Ws36WZ5MBZxEz9bWw* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___transport_u562)(tyObject_TaskWire__mbM5G2Ws36WZ5MBZxEz9bWw* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZjson_u254)(tySequence__YWxjq9aB9anxKHaOq65jIGKw dest_p0);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__HuNCd9cjVf1RGJ8WXqZvVog*, percent___pureZjson_u2176)(NI64 n_p0);
N_LIB_PRIVATE N_NIMCALL(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ, sealGCM__crypto_u34)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ key_p0, tySequence__6H5Oh5UUvVCLiakt9aTwtUQ plaintext_p1);
static const struct {
  NI cap; NIM_CHAR data[23+1];
} TM__7gIcePhgbItPdDBxBodgMQ_2 = { 23 | NIM_STRLIT_FLAG, "http://10.2.20.200:8080" };
static const NimStringV2 TM__7gIcePhgbItPdDBxBodgMQ_3 = {23, (NimStrPayload*)&TM__7gIcePhgbItPdDBxBodgMQ_2};
static const struct {
  NI cap; NIM_CHAR data[0+1];
} TM__7gIcePhgbItPdDBxBodgMQ_4 = { 0 | NIM_STRLIT_FLAG, "" };
static const NimStringV2 TM__7gIcePhgbItPdDBxBodgMQ_5 = {0, (NimStrPayload*)&TM__7gIcePhgbItPdDBxBodgMQ_4};
static const struct {
  NI cap; NIM_CHAR data[8+1];
} TM__7gIcePhgbItPdDBxBodgMQ_6 = { 8 | NIM_STRLIT_FLAG, "hostname" };
static const NimStringV2 TM__7gIcePhgbItPdDBxBodgMQ_7 = {8, (NimStrPayload*)&TM__7gIcePhgbItPdDBxBodgMQ_6};
static const struct {
  NI cap; NIM_CHAR data[12+1];
} TM__7gIcePhgbItPdDBxBodgMQ_8 = { 12 | NIM_STRLIT_FLAG, "COMPUTERNAME" };
static const NimStringV2 TM__7gIcePhgbItPdDBxBodgMQ_9 = {12, (NimStrPayload*)&TM__7gIcePhgbItPdDBxBodgMQ_8};
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__7gIcePhgbItPdDBxBodgMQ_10 = { 7 | NIM_STRLIT_FLAG, "UNKNOWN" };
static const NimStringV2 TM__7gIcePhgbItPdDBxBodgMQ_11 = {7, (NimStrPayload*)&TM__7gIcePhgbItPdDBxBodgMQ_10};
static const struct {
  NI cap; NIM_CHAR data[8+1];
} TM__7gIcePhgbItPdDBxBodgMQ_12 = { 8 | NIM_STRLIT_FLAG, "username" };
static const NimStringV2 TM__7gIcePhgbItPdDBxBodgMQ_13 = {8, (NimStrPayload*)&TM__7gIcePhgbItPdDBxBodgMQ_12};
static const struct {
  NI cap; NIM_CHAR data[8+1];
} TM__7gIcePhgbItPdDBxBodgMQ_14 = { 8 | NIM_STRLIT_FLAG, "USERNAME" };
static const NimStringV2 TM__7gIcePhgbItPdDBxBodgMQ_15 = {8, (NimStrPayload*)&TM__7gIcePhgbItPdDBxBodgMQ_14};
static const NimStringV2 TM__7gIcePhgbItPdDBxBodgMQ_16 = {7, (NimStrPayload*)&TM__7gIcePhgbItPdDBxBodgMQ_10};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__7gIcePhgbItPdDBxBodgMQ_17 = { 2 | NIM_STRLIT_FLAG, "os" };
static const NimStringV2 TM__7gIcePhgbItPdDBxBodgMQ_18 = {2, (NimStrPayload*)&TM__7gIcePhgbItPdDBxBodgMQ_17};
static const struct {
  NI cap; NIM_CHAR data[13+1];
} TM__7gIcePhgbItPdDBxBodgMQ_19 = { 13 | NIM_STRLIT_FLAG, "windows/amd64" };
static const NimStringV2 TM__7gIcePhgbItPdDBxBodgMQ_20 = {13, (NimStrPayload*)&TM__7gIcePhgbItPdDBxBodgMQ_19};
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__7gIcePhgbItPdDBxBodgMQ_21 = { 3 | NIM_STRLIT_FLAG, "pid" };
static const NimStringV2 TM__7gIcePhgbItPdDBxBodgMQ_22 = {3, (NimStrPayload*)&TM__7gIcePhgbItPdDBxBodgMQ_21};
static const struct {
  NI cap; NIM_CHAR data[9+1];
} TM__7gIcePhgbItPdDBxBodgMQ_23 = { 9 | NIM_STRLIT_FLAG, "transport" };
static const NimStringV2 TM__7gIcePhgbItPdDBxBodgMQ_24 = {9, (NimStrPayload*)&TM__7gIcePhgbItPdDBxBodgMQ_23};
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__7gIcePhgbItPdDBxBodgMQ_25 = { 4 | NIM_STRLIT_FLAG, "http" };
static const NimStringV2 TM__7gIcePhgbItPdDBxBodgMQ_26 = {4, (NimStrPayload*)&TM__7gIcePhgbItPdDBxBodgMQ_25};
static const struct {
  NI cap; NIM_CHAR data[9+1];
} TM__7gIcePhgbItPdDBxBodgMQ_27 = { 9 | NIM_STRLIT_FLAG, "sleep_sec" };
static const NimStringV2 TM__7gIcePhgbItPdDBxBodgMQ_28 = {9, (NimStrPayload*)&TM__7gIcePhgbItPdDBxBodgMQ_27};
static const struct {
  NI cap; NIM_CHAR data[10+1];
} TM__7gIcePhgbItPdDBxBodgMQ_29 = { 10 | NIM_STRLIT_FLAG, "jitter_pct" };
static const NimStringV2 TM__7gIcePhgbItPdDBxBodgMQ_30 = {10, (NimStrPayload*)&TM__7gIcePhgbItPdDBxBodgMQ_29};
static const struct {
  NI cap; NIM_CHAR data[12+1];
} TM__7gIcePhgbItPdDBxBodgMQ_31 = { 12 | NIM_STRLIT_FLAG, "process_name" };
static const NimStringV2 TM__7gIcePhgbItPdDBxBodgMQ_32 = {12, (NimStrPayload*)&TM__7gIcePhgbItPdDBxBodgMQ_31};
static const struct {
  NI cap; NIM_CHAR data[9+1];
} TM__7gIcePhgbItPdDBxBodgMQ_33 = { 9 | NIM_STRLIT_FLAG, "agent.exe" };
static const NimStringV2 TM__7gIcePhgbItPdDBxBodgMQ_34 = {9, (NimStrPayload*)&TM__7gIcePhgbItPdDBxBodgMQ_33};
static const struct {
  NI cap; NIM_CHAR data[111+1];
} TM__7gIcePhgbItPdDBxBodgMQ_35 = { 111 | NIM_STRLIT_FLAG, "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36" };
static const NimStringV2 TM__7gIcePhgbItPdDBxBodgMQ_36 = {111, (NimStrPayload*)&TM__7gIcePhgbItPdDBxBodgMQ_35};
static const NimStringV2 TM__7gIcePhgbItPdDBxBodgMQ_37 = {4, (NimStrPayload*)&TM__7gIcePhgbItPdDBxBodgMQ_25};
static const NimStringV2 TM__7gIcePhgbItPdDBxBodgMQ_38 = {0, (NimStrPayload*)&TM__7gIcePhgbItPdDBxBodgMQ_4};
static const NimStringV2 TM__7gIcePhgbItPdDBxBodgMQ_39 = {0, (NimStrPayload*)&TM__7gIcePhgbItPdDBxBodgMQ_4};
static const struct {
  NI cap; NIM_CHAR data[8+1];
} TM__7gIcePhgbItPdDBxBodgMQ_40 = { 8 | NIM_STRLIT_FLAG, "https://" };
static const NimStringV2 TM__7gIcePhgbItPdDBxBodgMQ_41 = {8, (NimStrPayload*)&TM__7gIcePhgbItPdDBxBodgMQ_40};
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__7gIcePhgbItPdDBxBodgMQ_42 = { 5 | NIM_STRLIT_FLAG, "https" };
static const NimStringV2 TM__7gIcePhgbItPdDBxBodgMQ_43 = {5, (NimStrPayload*)&TM__7gIcePhgbItPdDBxBodgMQ_42};
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__7gIcePhgbItPdDBxBodgMQ_44 = { 7 | NIM_STRLIT_FLAG, "http://" };
static const NimStringV2 TM__7gIcePhgbItPdDBxBodgMQ_45 = {7, (NimStrPayload*)&TM__7gIcePhgbItPdDBxBodgMQ_44};
static const NimStringV2 TM__7gIcePhgbItPdDBxBodgMQ_46 = {5, (NimStrPayload*)&TM__7gIcePhgbItPdDBxBodgMQ_42};
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__7gIcePhgbItPdDBxBodgMQ_47 = { 4 | NIM_STRLIT_FLAG, "POST" };
static const NimStringV2 TM__7gIcePhgbItPdDBxBodgMQ_48 = {4, (NimStrPayload*)&TM__7gIcePhgbItPdDBxBodgMQ_47};
static const struct {
  NI cap; NIM_CHAR data[9+1];
} TM__7gIcePhgbItPdDBxBodgMQ_49 = { 9 | NIM_STRLIT_FLAG, "/register" };
static const NimStringV2 TM__7gIcePhgbItPdDBxBodgMQ_50 = {9, (NimStrPayload*)&TM__7gIcePhgbItPdDBxBodgMQ_49};
static const struct {
  NI cap; NIM_CHAR data[8+1];
} TM__7gIcePhgbItPdDBxBodgMQ_51 = { 8 | NIM_STRLIT_FLAG, "agent_id" };
static const NimStringV2 TM__7gIcePhgbItPdDBxBodgMQ_52 = {8, (NimStrPayload*)&TM__7gIcePhgbItPdDBxBodgMQ_51};
static const NimStringV2 TM__7gIcePhgbItPdDBxBodgMQ_53 = {0, (NimStrPayload*)&TM__7gIcePhgbItPdDBxBodgMQ_4};
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__7gIcePhgbItPdDBxBodgMQ_54 = { 7 | NIM_STRLIT_FLAG, "aes_key" };
static const NimStringV2 TM__7gIcePhgbItPdDBxBodgMQ_55 = {7, (NimStrPayload*)&TM__7gIcePhgbItPdDBxBodgMQ_54};
static const NimStringV2 TM__7gIcePhgbItPdDBxBodgMQ_56 = {0, (NimStrPayload*)&TM__7gIcePhgbItPdDBxBodgMQ_4};
static const struct {
  NI cap; NIM_CHAR data[8+1];
} TM__7gIcePhgbItPdDBxBodgMQ_57 = { 8 | NIM_STRLIT_FLAG, "/beacon/" };
static const NimStringV2 TM__7gIcePhgbItPdDBxBodgMQ_58 = {8, (NimStrPayload*)&TM__7gIcePhgbItPdDBxBodgMQ_57};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__7gIcePhgbItPdDBxBodgMQ_59 = { 1 | NIM_STRLIT_FLAG, "/" };
static const NimStringV2 TM__7gIcePhgbItPdDBxBodgMQ_60 = {1, (NimStrPayload*)&TM__7gIcePhgbItPdDBxBodgMQ_59};
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__7gIcePhgbItPdDBxBodgMQ_61 = { 3 | NIM_STRLIT_FLAG, "GET" };
static const NimStringV2 TM__7gIcePhgbItPdDBxBodgMQ_62 = {3, (NimStrPayload*)&TM__7gIcePhgbItPdDBxBodgMQ_61};
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__7gIcePhgbItPdDBxBodgMQ_63 = { 5 | NIM_STRLIT_FLAG, "tasks" };
static const NimStringV2 TM__7gIcePhgbItPdDBxBodgMQ_64 = {5, (NimStrPayload*)&TM__7gIcePhgbItPdDBxBodgMQ_63};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__7gIcePhgbItPdDBxBodgMQ_65 = { 2 | NIM_STRLIT_FLAG, "id" };
static const NimStringV2 TM__7gIcePhgbItPdDBxBodgMQ_66 = {2, (NimStrPayload*)&TM__7gIcePhgbItPdDBxBodgMQ_65};
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__7gIcePhgbItPdDBxBodgMQ_67 = { 4 | NIM_STRLIT_FLAG, "type" };
static const NimStringV2 TM__7gIcePhgbItPdDBxBodgMQ_68 = {4, (NimStrPayload*)&TM__7gIcePhgbItPdDBxBodgMQ_67};
static const NimStringV2 TM__7gIcePhgbItPdDBxBodgMQ_69 = {0, (NimStrPayload*)&TM__7gIcePhgbItPdDBxBodgMQ_4};
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__7gIcePhgbItPdDBxBodgMQ_70 = { 4 | NIM_STRLIT_FLAG, "args" };
static const NimStringV2 TM__7gIcePhgbItPdDBxBodgMQ_71 = {4, (NimStrPayload*)&TM__7gIcePhgbItPdDBxBodgMQ_70};
static const NimStringV2 TM__7gIcePhgbItPdDBxBodgMQ_72 = {0, (NimStrPayload*)&TM__7gIcePhgbItPdDBxBodgMQ_4};
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__7gIcePhgbItPdDBxBodgMQ_73 = { 7 | NIM_STRLIT_FLAG, "payload" };
static const NimStringV2 TM__7gIcePhgbItPdDBxBodgMQ_74 = {7, (NimStrPayload*)&TM__7gIcePhgbItPdDBxBodgMQ_73};
static const NimStringV2 TM__7gIcePhgbItPdDBxBodgMQ_75 = {0, (NimStrPayload*)&TM__7gIcePhgbItPdDBxBodgMQ_4};
static const NimStringV2 TM__7gIcePhgbItPdDBxBodgMQ_76 = {7, (NimStrPayload*)&TM__7gIcePhgbItPdDBxBodgMQ_73};
static const NimStringV2 TM__7gIcePhgbItPdDBxBodgMQ_77 = {0, (NimStrPayload*)&TM__7gIcePhgbItPdDBxBodgMQ_4};
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__7gIcePhgbItPdDBxBodgMQ_78 = { 7 | NIM_STRLIT_FLAG, "task_id" };
static const NimStringV2 TM__7gIcePhgbItPdDBxBodgMQ_79 = {7, (NimStrPayload*)&TM__7gIcePhgbItPdDBxBodgMQ_78};
static const struct {
  NI cap; NIM_CHAR data[6+1];
} TM__7gIcePhgbItPdDBxBodgMQ_80 = { 6 | NIM_STRLIT_FLAG, "output" };
static const NimStringV2 TM__7gIcePhgbItPdDBxBodgMQ_81 = {6, (NimStrPayload*)&TM__7gIcePhgbItPdDBxBodgMQ_80};
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__7gIcePhgbItPdDBxBodgMQ_82 = { 5 | NIM_STRLIT_FLAG, "error" };
static const NimStringV2 TM__7gIcePhgbItPdDBxBodgMQ_83 = {5, (NimStrPayload*)&TM__7gIcePhgbItPdDBxBodgMQ_82};
static const NimStringV2 TM__7gIcePhgbItPdDBxBodgMQ_84 = {4, (NimStrPayload*)&TM__7gIcePhgbItPdDBxBodgMQ_47};
static const struct {
  NI cap; NIM_CHAR data[8+1];
} TM__7gIcePhgbItPdDBxBodgMQ_85 = { 8 | NIM_STRLIT_FLAG, "/result/" };
static const NimStringV2 TM__7gIcePhgbItPdDBxBodgMQ_86 = {8, (NimStrPayload*)&TM__7gIcePhgbItPdDBxBodgMQ_85};
static const NimStringV2 TM__7gIcePhgbItPdDBxBodgMQ_87 = {3, (NimStrPayload*)&TM__7gIcePhgbItPdDBxBodgMQ_61};
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__7gIcePhgbItPdDBxBodgMQ_88 = { 4 | NIM_STRLIT_FLAG, "/dl/" };
static const NimStringV2 TM__7gIcePhgbItPdDBxBodgMQ_89 = {4, (NimStrPayload*)&TM__7gIcePhgbItPdDBxBodgMQ_88};
static const NimStringV2 TM__7gIcePhgbItPdDBxBodgMQ_90 = {1, (NimStrPayload*)&TM__7gIcePhgbItPdDBxBodgMQ_59};
static const NimStringV2 TM__7gIcePhgbItPdDBxBodgMQ_91 = {4, (NimStrPayload*)&TM__7gIcePhgbItPdDBxBodgMQ_47};
static const struct {
  NI cap; NIM_CHAR data[8+1];
} TM__7gIcePhgbItPdDBxBodgMQ_92 = { 8 | NIM_STRLIT_FLAG, "/upload/" };
static const NimStringV2 TM__7gIcePhgbItPdDBxBodgMQ_93 = {8, (NimStrPayload*)&TM__7gIcePhgbItPdDBxBodgMQ_92};
static const NimStringV2 TM__7gIcePhgbItPdDBxBodgMQ_94 = {1, (NimStrPayload*)&TM__7gIcePhgbItPdDBxBodgMQ_59};
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4172;
extern tyProc__RqPJ327ezwqplysPaezU3Q Dl_2013268753_;
extern tyProc__9bXer9a4ps9aSGctILcxWReVw Dl_2013268980_;
extern tyProc__zs1G9aN0hsG4qr4I6t6Agtg Dl_2013268390_;
extern tyProc__81VIzYkqwzDl7rl3af0pZg Dl_2248147427_;
extern tyProc__RFwzZ679c39c5tm4O7Tpzjeg Dl_2248147403_;
extern tyProc__ah5wcFv3UG20t2vgXBy0Fg Dl_2248147401_;
extern tyProc__VvL5F9ctiPFd9cY0CxFJmncg Dl_2248147433_;
extern tyProc__OygtxCk9aDjhab6i7UhdJdQ Dl_2248147486_;
extern tyProc__HfA740GE5GucMArbWnkCkw Dl_2248147469_;
extern tyProc__wS8JrJMcfFBzgzuqJGOAAg Dl_2248147466_;
extern tyProc__5V5gHAr7e9bsH0OKztxYmCw Dl_2248147449_;
extern tyProc__mID4zaJ5rXbvlxUmzwPGLw Dl_2248147461_;
extern NIM_THREADVAR Exception* currException__system_u3660;
static N_INLINE(void, nimSetMem__system_u2188)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
	nimSetMem__system_u2188(p_p0, ((int)0), size_p1);
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4172);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, newTransport__transport_u44)(tyObject_AgentTransport__5qQy6rhkf3jaeikY8XXtPQ* Result) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)Result, sizeof(tyObject_AgentTransport__5qQy6rhkf3jaeikY8XXtPQ));
	eqsink___system_u2729((&(*Result).serverUrl), TM__7gIcePhgbItPdDBxBodgMQ_3);
	{
		tySequence__sM4lkSb7zS6F7OVMvW9cffQ T5_;
		if (!NIM_FALSE) goto LA3_;
		T5_.len = 0; T5_.p = NIM_NIL;
		T5_ = nsuSplitChar(TM__7gIcePhgbItPdDBxBodgMQ_5, 44, ((NI)-1));
		if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u5532(T5_); goto BeforeRet_;}
		eqsink___system_u5541((&(*Result).uriList), T5_);
	}
LA3_: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, getEnvStr__transport_u8)(NimStringV2 k_p0, NimStringV2 default_p1) {
	NimStringV2 result;
	tyObject_WideCStringObj__jQbOKocsbu7Z9bKTSFtX4TQ buf_1;
	NimStringV2 colontmpD_;
	tyObject_WideCStringObj__jQbOKocsbu7Z9bKTSFtX4TQ colontmpD__2;
	NI32 n_1;
	NU16* T2_;
	NU16* T3_;
NIM_BOOL oldNimErrFin1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimZeroMem((void*)(&buf_1), sizeof(tyObject_WideCStringObj__jQbOKocsbu7Z9bKTSFtX4TQ));
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	nimZeroMem((void*)(&colontmpD__2), sizeof(tyObject_WideCStringObj__jQbOKocsbu7Z9bKTSFtX4TQ));
	colontmpD_ = mnewString(((NI)512));
	buf_1 = newWideCString__stdZwidestrs_u325(colontmpD_);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	colontmpD__2 = newWideCString__stdZwidestrs_u325(k_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T2_ = (NU16*)0;
	T2_ = winstrConverterWideCStringToLPWSTR__pkgZwinimZwinstr_u807(colontmpD__2);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T3_ = (NU16*)0;
	T3_ = winstrConverterWideCStringToLPWSTR__pkgZwinimZwinstr_u807(buf_1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	n_1 = Dl_2013268753_(T2_, T3_, ((NI32)512));
	{
		if (!(n_1 == ((NI32)0))) goto LA6_;
		eqcopy___system_u2723((&result), default_p1);
		eqdestroy___stdZwidestrs_u7(colontmpD__2);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
		eqdestroy___stdZwidestrs_u7(buf_1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		goto BeforeRet_;
	}
LA6_: ;
	result = dollar___stdZwidestrs_u402(buf_1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	eqdestroy___stdZwidestrs_u7(colontmpD__2);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
	eqdestroy___stdZwidestrs_u7(buf_1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	goto BeforeRet_;
	{
		LA1_:;
	}
	{
		oldNimErrFin1_ = *nimErr_; *nimErr_ = NIM_FALSE;
		eqdestroy___stdZwidestrs_u7(colontmpD__2);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
		eqdestroy___stdZwidestrs_u7(buf_1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		*nimErr_ = oldNimErrFin1_;
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2* s_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = !(((*s_p0).p == ((NimStrPayload*) NIM_NIL)));
		if (!(T3_)) goto LA4_;
		T3_ = ((NI)((*(*s_p0).p).cap & ((NI)IL64(4611686018427387904))) == ((NI)IL64(4611686018427387904)));
LA4_: ;
		if (!T3_) goto LA5_;
		nimPrepareStrMutationImpl__system_u2462(s_p0);
	}
LA5_: ;
}
static N_INLINE(NimStringV2, X5BX5D___pureZstrutils_u1313)(NimStringV2 s_p0, tyObject_HSlice__gNm3PIFaVREVVU9cuqHQIFg x_p1) {
	NimStringV2 result;
	NI a_1;
	NI L_1;
	result.len = 0; result.p = NIM_NIL;
	a_1 = x_p1.a;
	L_1 = (NI)((NI)((NI)(s_p0.len - x_p1.b) - a_1) + ((NI)1));
	result = mnewString((L_1));
	{
		NI i_1;
		NI i_2;
		i_1 = (NI)0;
		i_2 = ((NI)0);
		{
			while (1) {
				if (!(i_2 < L_1)) goto LA3;
				i_1 = i_2;
				nimPrepareStrMutationV2((&result));
				result.p->data[i_1] = s_p0.p->data[(NI)(i_1 + a_1)];
				i_2 += ((NI)1);
			} LA3: ;
		}
	}
	return result;
}
static N_INLINE(tyObject_HSlice__gNm3PIFaVREVVU9cuqHQIFg, dotdot___stdZenumutils_u105)(NI a_p0, NI b_p1) {
	tyObject_HSlice__gNm3PIFaVREVVU9cuqHQIFg result;
	result.a = a_p0;
	result.b = b_p1;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, exeName__transport_u14)(void) {
	NimStringV2 result;
	tyObject_WideCStringObj__jQbOKocsbu7Z9bKTSFtX4TQ buf_1;
	NimStringV2 colontmpD_;
	NimStringV2 full_1;
	NI32 n_1;
	NU16* T2_;
	NI i_1;
	NI T7_;
	NI T8_;
	NimStringV2 T9_;
NIM_BOOL oldNimErrFin1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimZeroMem((void*)(&buf_1), sizeof(tyObject_WideCStringObj__jQbOKocsbu7Z9bKTSFtX4TQ));
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	full_1.len = 0; full_1.p = NIM_NIL;
	colontmpD_ = mnewString(((NI)260));
	buf_1 = newWideCString__stdZwidestrs_u325(colontmpD_);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T2_ = (NU16*)0;
	T2_ = winstrConverterWideCStringToLPWSTR__pkgZwinimZwinstr_u807(buf_1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	n_1 = Dl_2013268390_(((NI)0), T2_, ((NI32)260));
	{
		if (!(n_1 == ((NI32)0))) goto LA5_;
		result = TM__7gIcePhgbItPdDBxBodgMQ_34;
		if (full_1.p && !(full_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(full_1.p);
}
		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
		eqdestroy___stdZwidestrs_u7(buf_1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		goto BeforeRet_;
	}
LA5_: ;
	full_1 = dollar___stdZwidestrs_u402(buf_1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T7_ = (NI)0;
	T7_ = nsuRFindChar(full_1, 92, ((NI)0), ((NI)-1));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T8_ = (NI)0;
	T8_ = nsuRFindChar(full_1, 47, ((NI)0), ((NI)-1));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	i_1 = ((T7_ >= T8_) ? T7_ : T8_);
	T9_.len = 0; T9_.p = NIM_NIL;
	{
		if (!(i_1 < ((NI)0))) goto LA12_;
		result = full_1;
		eqwasMoved___system_u2720((&full_1));
	}
	goto LA10_;
LA12_: ;
	{
		tyObject_HSlice__gNm3PIFaVREVVU9cuqHQIFg T15_;
		T15_ = dotdot___stdZenumutils_u105((NI)(i_1 + ((NI)1)), ((NI)1));
		result = X5BX5D___pureZstrutils_u1313(full_1, T15_);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	}
LA10_: ;
	if (full_1.p && !(full_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(full_1.p);
}
	if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
	eqdestroy___stdZwidestrs_u7(buf_1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	goto BeforeRet_;
	{
		LA1_:;
	}
	{
		oldNimErrFin1_ = *nimErr_; *nimErr_ = NIM_FALSE;
		if (full_1.p && !(full_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(full_1.p);
}
		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
		eqdestroy___stdZwidestrs_u7(buf_1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		*nimErr_ = oldNimErrFin1_;
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(void, eqdestroy___system_u281)(NimStringV2 x_p0) {
}
static N_INLINE(NimStringV2, X5BX5D___pureZstrutils_u1285)(NimStringV2 s_p0, tyObject_HSlice__RmqVCB5rHyE9cs59bZ8FgkPA x_p1) {
	NimStringV2 result;
	NI a_1;
	NI L_1;
	result.len = 0; result.p = NIM_NIL;
	a_1 = x_p1.a;
	L_1 = (NI)((NI)(x_p1.b - a_1) + ((NI)1));
	result = mnewString((L_1));
	{
		NI i_1;
		NI i_2;
		i_1 = (NI)0;
		i_2 = ((NI)0);
		{
			while (1) {
				if (!(i_2 < L_1)) goto LA3;
				i_1 = i_2;
				nimPrepareStrMutationV2((&result));
				result.p->data[i_1] = s_p0.p->data[(NI)(i_1 + a_1)];
				i_2 += ((NI)1);
			} LA3: ;
		}
	}
	return result;
}
static N_INLINE(tyObject_HSlice__RmqVCB5rHyE9cs59bZ8FgkPA, dotdot___stdZstrbasics_u48)(NI a_p0, NI b_p1) {
	tyObject_HSlice__RmqVCB5rHyE9cs59bZ8FgkPA result;
	result.a = a_p0;
	result.b = b_p1;
	return result;
}
static N_INLINE(NI, find__stdZenvvars_u58)(NIM_CHAR* a_p0, NI a_p0Len_0, NIM_CHAR item_p1) {
	NI result;
{	result = ((NI)0);
	{
		NIM_CHAR i_1;
		NI i_2;
		i_1 = (NIM_CHAR)0;
		i_2 = ((NI)0);
		{
			while (1) {
				if (!(i_2 < a_p0Len_0)) goto LA3;
				i_1 = a_p0[i_2];
				{
					if (!((NU8)(i_1) == (NU8)(item_p1))) goto LA6_;
					goto BeforeRet_;
				}
LA6_: ;
				result += ((NI)1);
				i_2 += ((NI)1);
			} LA3: ;
		}
	}
	result = ((NI)-1);
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NIM_BOOL, contains__stdZenvvars_u53)(NIM_CHAR* a_p0, NI a_p0Len_0, NIM_CHAR item_p1) {
	NIM_BOOL result;
	NI T1_;
{	T1_ = (NI)0;
	T1_ = find__stdZenvvars_u58(a_p0, a_p0Len_0, item_p1);
	result = (((NI)0) <= T1_);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, copyMem__system_u1755)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1) {
	{
		if (!(((NI)0) < src_p1.len)) goto LA3_;
		copyMem__system_u1755(((void*) ((&(*(*dest_p0).p).data[(*dest_p0).len]))), ((void*) ((&(*src_p1.p).data[((NI)0)]))), (src_p1.len));
		(*dest_p0).len += src_p1.len;
		(*(*dest_p0).p).data[(*dest_p0).len] = 0;
	}
LA3_: ;
}
static N_INLINE(int, nimCmpMem)(void* a_p0, void* b_p1, NI size_p2) {
	int result;
	result = memcmp(a_p0, b_p1, ((size_t) (size_p2)));
	return result;
}
static N_INLINE(NIM_BOOL, equalMem__system_u1763)(void* a_p0, void* b_p1, NI size_p2) {
	NIM_BOOL result;
	int T1_;
	T1_ = (int)0;
	T1_ = nimCmpMem(a_p0, b_p1, size_p2);
	result = (T1_ == ((NI32)0));
	return result;
}
static N_INLINE(NIM_BOOL, eqStrings)(NimStringV2 a_p0, NimStringV2 b_p1) {
	NIM_BOOL result;
	NI alen_1;
	NI blen_1;
{	result = NIM_FALSE;
	alen_1 = a_p0.len;
	blen_1 = b_p1.len;
	{
		if (!(alen_1 == blen_1)) goto LA3_;
		{
			if (!(alen_1 == ((NI)0))) goto LA7_;
			result = NIM_TRUE;
			goto BeforeRet_;
		}
LA7_: ;
		result = equalMem__system_u1763(((void*) ((&a_p0.p->data[((NI)0)]))), ((void*) ((&b_p1.p->data[((NI)0)]))), (alen_1));
		goto BeforeRet_;
	}
LA3_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyTuple__hnCuDR9cLe2lA3YIkwKIyuA, winHttpDo__transport_u46)(tyObject_AgentTransport__5qQy6rhkf3jaeikY8XXtPQ* t_p0, NimStringV2 meth_p1, NimStringV2 path_p2, tySequence__6H5Oh5UUvVCLiakt9aTwtUQ body_p3) {
	tyTuple__hnCuDR9cLe2lA3YIkwKIyuA result;
	tyObject_WideCStringObj__jQbOKocsbu7Z9bKTSFtX4TQ colontmpD_;
	void* hSess_1;
	NU16* T2_;
	NimStringV2 scheme_1;
	NimStringV2 host_1;
	NimStringV2 rest_1;
	NimStringV2 fullPath_1;
	tyObject_WideCStringObj__jQbOKocsbu7Z9bKTSFtX4TQ colontmpD__2;
	NU16 port_1;
	NI slash_1;
	NimStringV2 T25_;
	NimStringV2 T45_;
	void* hConn_1;
	NU16* T53_;
	NI32 colontmpD__5;
	NI32 colontmpD__6;
	tyObject_WideCStringObj__jQbOKocsbu7Z9bKTSFtX4TQ colontmpD__7;
	tyObject_WideCStringObj__jQbOKocsbu7Z9bKTSFtX4TQ colontmpD__8;
	NI32 flags_1;
	void* hReq_1;
	NU16* T69_;
	NU16* T70_;
	void* colontmpD__9;
	void* colontmpD__10;
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ resp_1;
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ buf_1;
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ colontmp__7;
	NI32 secFlags_1;
	NI32 T82_;
	void* bodyPtr_1;
	NI32 code_1;
	NI32 codeSize_1;
	NI32 T113_;
	NI32 got_1;
	NI colontmp__12;
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ blitTmp_6;
	NI32 T130_;
	NI32 T131_;
	NI32 T132_;
NIM_BOOL oldNimErrFin63_;
NIM_BOOL oldNimErrFin11_;
NIM_BOOL oldNimErrFin1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&result), sizeof(tyTuple__hnCuDR9cLe2lA3YIkwKIyuA));
	nimZeroMem((void*)(&colontmpD_), sizeof(tyObject_WideCStringObj__jQbOKocsbu7Z9bKTSFtX4TQ));
	colontmpD_ = newWideCString__stdZwidestrs_u325(TM__7gIcePhgbItPdDBxBodgMQ_36);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T2_ = (NU16*)0;
	T2_ = winstrConverterWideCStringToLPWSTR__pkgZwinimZwinstr_u807(colontmpD_);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	hSess_1 = Dl_2248147427_(T2_, ((NI32)1), ((NU16*) NIM_NIL), ((NU16*) NIM_NIL), ((NI32)0));
	{
		tySequence__6H5Oh5UUvVCLiakt9aTwtUQ colontmp_;
		NI colontmp__2;
		tySequence__6H5Oh5UUvVCLiakt9aTwtUQ blitTmp_1;
		if (!(hSess_1 == NIM_NIL)) goto LA5_;
		colontmp_.len = 0; colontmp_.p = NIM_NIL;
		colontmp__2 = ((NI)0);
		colontmp_.len = 0; colontmp_.p = (tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content*) newSeqPayload(0, sizeof(NU8), NIM_ALIGNOF(NU8));
		result.Field0 = colontmp__2;
		blitTmp_1 = colontmp_;
		eqwasMoved___pureZtimes_u2653((&colontmp_));
		result.Field1 = blitTmp_1;
		eqdestroy___pureZtimes_u2656(colontmp_);
		eqdestroy___stdZwidestrs_u7(colontmpD_);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		goto BeforeRet_;
		{
			LA7_:;
		}
		{
			eqdestroy___pureZtimes_u2656(colontmp_);
		}
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	}
LA5_: ;
	scheme_1.len = 0; scheme_1.p = NIM_NIL;
	host_1.len = 0; host_1.p = NIM_NIL;
	rest_1.len = 0; rest_1.p = NIM_NIL;
	fullPath_1.len = 0; fullPath_1.p = NIM_NIL;
	nimZeroMem((void*)(&colontmpD__2), sizeof(tyObject_WideCStringObj__jQbOKocsbu7Z9bKTSFtX4TQ));
	scheme_1 = TM__7gIcePhgbItPdDBxBodgMQ_37;
	host_1 = TM__7gIcePhgbItPdDBxBodgMQ_38;
	port_1 = ((NU16)80);
	rest_1 = TM__7gIcePhgbItPdDBxBodgMQ_39;
	{
		NIM_BOOL T14_;
		tyObject_HSlice__gNm3PIFaVREVVU9cuqHQIFg T17_;
		NimStringV2 T18_;
		T14_ = (NIM_BOOL)0;
		T14_ = nsuStartsWith((*t_p0).serverUrl, TM__7gIcePhgbItPdDBxBodgMQ_41);
		if (NIM_UNLIKELY(*nimErr_)) goto LA11_;
		if (!T14_) goto LA15_;
		scheme_1 = TM__7gIcePhgbItPdDBxBodgMQ_43;
		port_1 = ((NU16)443);
		T17_ = dotdot___stdZenumutils_u105(((NI)8), ((NI)1));
		T18_.len = 0; T18_.p = NIM_NIL;
		T18_ = X5BX5D___pureZstrutils_u1313((*t_p0).serverUrl, T17_);
		if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u281(T18_); goto LA11_;}
		eqsink___system_u2729((&rest_1), T18_);
	}
	goto LA12_;
LA15_: ;
	{
		NIM_BOOL T20_;
		tyObject_HSlice__gNm3PIFaVREVVU9cuqHQIFg T23_;
		NimStringV2 T24_;
		T20_ = (NIM_BOOL)0;
		T20_ = nsuStartsWith((*t_p0).serverUrl, TM__7gIcePhgbItPdDBxBodgMQ_45);
		if (NIM_UNLIKELY(*nimErr_)) goto LA11_;
		if (!T20_) goto LA21_;
		T23_ = dotdot___stdZenumutils_u105(((NI)7), ((NI)1));
		T24_.len = 0; T24_.p = NIM_NIL;
		T24_ = X5BX5D___pureZstrutils_u1313((*t_p0).serverUrl, T23_);
		if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u281(T24_); goto LA11_;}
		eqsink___system_u2729((&rest_1), T24_);
	}
	goto LA12_;
LA21_: ;
LA12_: ;
	slash_1 = nsuFindChar(rest_1, 47, ((NI)0), ((NI)-1));
	if (NIM_UNLIKELY(*nimErr_)) goto LA11_;
	T25_.len = 0; T25_.p = NIM_NIL;
	{
		if (!(slash_1 < ((NI)0))) goto LA28_;
		eqcopy___system_u2723((&host_1), rest_1);
	}
	goto LA26_;
LA28_: ;
	{
		tyObject_HSlice__RmqVCB5rHyE9cs59bZ8FgkPA T31_;
		NimStringV2 T32_;
		T31_ = dotdot___stdZstrbasics_u48(((NI)0), (NI)(slash_1 - ((NI)1)));
		T32_.len = 0; T32_.p = NIM_NIL;
		T32_ = X5BX5D___pureZstrutils_u1285(rest_1, T31_);
		if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u281(T32_); goto LA11_;}
		eqsink___system_u2729((&host_1), T32_);
	}
LA26_: ;
	{
		NIM_BOOL T35_;
		NimStringV2 colontmpD__3;
		NI p_1;
		tyObject_HSlice__gNm3PIFaVREVVU9cuqHQIFg T39_;
		NI T40_;
		tyObject_HSlice__RmqVCB5rHyE9cs59bZ8FgkPA T41_;
		NimStringV2 T42_;
		T35_ = (NIM_BOOL)0;
		T35_ = contains__stdZenvvars_u53(((host_1).p) ? (host_1.p->data) : NIM_NIL, host_1.len, 58);
		if (!T35_) goto LA36_;
		colontmpD__3.len = 0; colontmpD__3.p = NIM_NIL;
		p_1 = nsuRFindChar(host_1, 58, ((NI)0), ((NI)-1));
		if (NIM_UNLIKELY(*nimErr_)) goto LA38_;
		T39_ = dotdot___stdZenumutils_u105((NI)(p_1 + ((NI)1)), ((NI)1));
		colontmpD__3 = X5BX5D___pureZstrutils_u1313(host_1, T39_);
		if (NIM_UNLIKELY(*nimErr_)) goto LA38_;
		T40_ = (NI)0;
		T40_ = nsuParseInt(colontmpD__3);
		if (NIM_UNLIKELY(*nimErr_)) goto LA38_;
		port_1 = ((NU16) (T40_));
		T41_ = dotdot___stdZstrbasics_u48(((NI)0), (NI)(p_1 - ((NI)1)));
		T42_.len = 0; T42_.p = NIM_NIL;
		T42_ = X5BX5D___pureZstrutils_u1285(host_1, T41_);
		if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u281(T42_); goto LA38_;}
		eqsink___system_u2729((&host_1), T42_);
		{
			LA38_:;
		}
		{
			if (colontmpD__3.p && !(colontmpD__3.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__3.p);
}
		}
		if (NIM_UNLIKELY(*nimErr_)) goto LA11_;
	}
LA36_: ;
	T45_.len = 0; T45_.p = NIM_NIL;
	{
		if (!(slash_1 < ((NI)0))) goto LA48_;
		eqcopy___system_u2723((&fullPath_1), path_p2);
	}
	goto LA46_;
LA48_: ;
	{
		NimStringV2 colontmpD__4;
		NimStringV2 T51_;
		tyObject_HSlice__gNm3PIFaVREVVU9cuqHQIFg T52_;
		colontmpD__4.len = 0; colontmpD__4.p = NIM_NIL;
		T51_.len = 0; T51_.p = NIM_NIL;
		T52_ = dotdot___stdZenumutils_u105(slash_1, ((NI)1));
		colontmpD__4 = X5BX5D___pureZstrutils_u1313(rest_1, T52_);
		if (NIM_UNLIKELY(*nimErr_)) goto LA11_;
		T51_ = rawNewString(colontmpD__4.len + path_p2.len + 0);
appendString((&T51_), colontmpD__4);
appendString((&T51_), path_p2);
		fullPath_1 = T51_;
		if (colontmpD__4.p && !(colontmpD__4.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__4.p);
}
	}
LA46_: ;
	colontmpD__2 = newWideCString__stdZwidestrs_u325(host_1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA11_;
	T53_ = (NU16*)0;
	T53_ = winstrConverterWideCStringToLPWSTR__pkgZwinimZwinstr_u807(colontmpD__2);
	if (NIM_UNLIKELY(*nimErr_)) goto LA11_;
	hConn_1 = Dl_2248147403_(hSess_1, T53_, port_1, ((NI32)0));
	{
		tySequence__6H5Oh5UUvVCLiakt9aTwtUQ colontmp__3;
		NI colontmp__4;
		tySequence__6H5Oh5UUvVCLiakt9aTwtUQ blitTmp_2;
		NI32 T59_;
		if (!(hConn_1 == NIM_NIL)) goto LA56_;
		colontmp__3.len = 0; colontmp__3.p = NIM_NIL;
		colontmp__4 = ((NI)0);
		colontmp__3.len = 0; colontmp__3.p = (tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content*) newSeqPayload(0, sizeof(NU8), NIM_ALIGNOF(NU8));
		result.Field0 = colontmp__4;
		blitTmp_2 = colontmp__3;
		eqwasMoved___pureZtimes_u2653((&colontmp__3));
		result.Field1 = blitTmp_2;
		eqdestroy___pureZtimes_u2656(colontmp__3);
		eqdestroy___stdZwidestrs_u7(colontmpD__2);
		if (NIM_UNLIKELY(*nimErr_)) goto LA10_;
		if (fullPath_1.p && !(fullPath_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(fullPath_1.p);
}
		if (rest_1.p && !(rest_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(rest_1.p);
}
		if (host_1.p && !(host_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(host_1.p);
}
		T59_ = (NI32)0;
		T59_ = Dl_2248147401_(hSess_1);
		(void)(T59_);
		eqdestroy___stdZwidestrs_u7(colontmpD_);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		goto BeforeRet_;
		{
			LA58_:;
		}
		{
			eqdestroy___pureZtimes_u2656(colontmp__3);
		}
		if (NIM_UNLIKELY(*nimErr_)) goto LA11_;
	}
LA56_: ;
	colontmpD__5 = (NI32)0;
	colontmpD__6 = (NI32)0;
	nimZeroMem((void*)(&colontmpD__7), sizeof(tyObject_WideCStringObj__jQbOKocsbu7Z9bKTSFtX4TQ));
	nimZeroMem((void*)(&colontmpD__8), sizeof(tyObject_WideCStringObj__jQbOKocsbu7Z9bKTSFtX4TQ));
	{
		if (!eqStrings(scheme_1, TM__7gIcePhgbItPdDBxBodgMQ_46)) goto LA66_;
		colontmpD__5 = ((NI32)8388608);
		flags_1 = colontmpD__5;
	}
	goto LA64_;
LA66_: ;
	{
		colontmpD__6 = ((NI32)0);
		flags_1 = colontmpD__6;
	}
LA64_: ;
	colontmpD__7 = newWideCString__stdZwidestrs_u325(meth_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA63_;
	T69_ = (NU16*)0;
	T69_ = winstrConverterWideCStringToLPWSTR__pkgZwinimZwinstr_u807(colontmpD__7);
	if (NIM_UNLIKELY(*nimErr_)) goto LA63_;
	colontmpD__8 = newWideCString__stdZwidestrs_u325(fullPath_1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA63_;
	T70_ = (NU16*)0;
	T70_ = winstrConverterWideCStringToLPWSTR__pkgZwinimZwinstr_u807(colontmpD__8);
	if (NIM_UNLIKELY(*nimErr_)) goto LA63_;
	hReq_1 = Dl_2248147433_(hConn_1, T69_, T70_, ((NU16*) NIM_NIL), ((NU16*) NIM_NIL), ((NU16**) NIM_NIL), flags_1);
	{
		tySequence__6H5Oh5UUvVCLiakt9aTwtUQ colontmp__5;
		NI colontmp__6;
		tySequence__6H5Oh5UUvVCLiakt9aTwtUQ blitTmp_3;
		NI32 T76_;
		NI32 T77_;
		if (!(hReq_1 == NIM_NIL)) goto LA73_;
		colontmp__5.len = 0; colontmp__5.p = NIM_NIL;
		colontmp__6 = ((NI)0);
		colontmp__5.len = 0; colontmp__5.p = (tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content*) newSeqPayload(0, sizeof(NU8), NIM_ALIGNOF(NU8));
		result.Field0 = colontmp__6;
		blitTmp_3 = colontmp__5;
		eqwasMoved___pureZtimes_u2653((&colontmp__5));
		result.Field1 = blitTmp_3;
		eqdestroy___pureZtimes_u2656(colontmp__5);
		eqdestroy___stdZwidestrs_u7(colontmpD__8);
		if (NIM_UNLIKELY(*nimErr_)) goto LA62_;
		eqdestroy___stdZwidestrs_u7(colontmpD__7);
		if (NIM_UNLIKELY(*nimErr_)) goto LA62_;
		T76_ = (NI32)0;
		T76_ = Dl_2248147401_(hConn_1);
		(void)(T76_);
		eqdestroy___stdZwidestrs_u7(colontmpD__2);
		if (NIM_UNLIKELY(*nimErr_)) goto LA10_;
		if (fullPath_1.p && !(fullPath_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(fullPath_1.p);
}
		if (rest_1.p && !(rest_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(rest_1.p);
}
		if (host_1.p && !(host_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(host_1.p);
}
		T77_ = (NI32)0;
		T77_ = Dl_2248147401_(hSess_1);
		(void)(T77_);
		eqdestroy___stdZwidestrs_u7(colontmpD_);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		goto BeforeRet_;
		{
			LA75_:;
		}
		{
			eqdestroy___pureZtimes_u2656(colontmp__5);
		}
		if (NIM_UNLIKELY(*nimErr_)) goto LA63_;
	}
LA73_: ;
	colontmpD__9 = (void*)0;
	colontmpD__10 = (void*)0;
	resp_1.len = 0; resp_1.p = NIM_NIL;
	buf_1.len = 0; buf_1.p = NIM_NIL;
	colontmp__7.len = 0; colontmp__7.p = NIM_NIL;
	secFlags_1 = ((NI32)13056);
	T82_ = (NI32)0;
	T82_ = Dl_2248147486_(hReq_1, ((NI32)31), ((void*) ((&secFlags_1))), ((NI32)4));
	(void)(T82_);
	{
		NI T85_;
		T85_ = body_p3.len;
		if (!(((NI)0) < T85_)) goto LA86_;
		colontmpD__9 = ((void*) ((&body_p3.p->data[((NI)0)])));
		bodyPtr_1 = colontmpD__9;
	}
	goto LA83_;
LA86_: ;
	{
		colontmpD__10 = NIM_NIL;
		bodyPtr_1 = colontmpD__10;
	}
LA83_: ;
	{
		NI T91_;
		NI T92_;
		NI32 T93_;
		tySequence__6H5Oh5UUvVCLiakt9aTwtUQ colontmp__8;
		NI colontmp__9;
		tySequence__6H5Oh5UUvVCLiakt9aTwtUQ blitTmp_4;
		NI32 T97_;
		NI32 T98_;
		NI32 T99_;
		T91_ = body_p3.len;
		T92_ = body_p3.len;
		T93_ = (NI32)0;
		T93_ = Dl_2248147469_(hReq_1, ((NU16*) NIM_NIL), ((NI32)0), bodyPtr_1, ((NI32) (T91_)), ((NI32) (T92_)), IL64(0));
		if (!!(((T93_) != 0))) goto LA94_;
		colontmp__8.len = 0; colontmp__8.p = NIM_NIL;
		colontmp__9 = ((NI)0);
		colontmp__8.len = 0; colontmp__8.p = (tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content*) newSeqPayload(0, sizeof(NU8), NIM_ALIGNOF(NU8));
		result.Field0 = colontmp__9;
		blitTmp_4 = colontmp__8;
		eqwasMoved___pureZtimes_u2653((&colontmp__8));
		result.Field1 = blitTmp_4;
		eqdestroy___pureZtimes_u2656(colontmp__8);
		eqdestroy___pureZtimes_u2656(colontmp__7);
		eqdestroy___pureZtimes_u2656(buf_1);
		eqdestroy___pureZtimes_u2656(resp_1);
		T97_ = (NI32)0;
		T97_ = Dl_2248147401_(hReq_1);
		(void)(T97_);
		eqdestroy___stdZwidestrs_u7(colontmpD__8);
		if (NIM_UNLIKELY(*nimErr_)) goto LA62_;
		eqdestroy___stdZwidestrs_u7(colontmpD__7);
		if (NIM_UNLIKELY(*nimErr_)) goto LA62_;
		T98_ = (NI32)0;
		T98_ = Dl_2248147401_(hConn_1);
		(void)(T98_);
		eqdestroy___stdZwidestrs_u7(colontmpD__2);
		if (NIM_UNLIKELY(*nimErr_)) goto LA10_;
		if (fullPath_1.p && !(fullPath_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(fullPath_1.p);
}
		if (rest_1.p && !(rest_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(rest_1.p);
}
		if (host_1.p && !(host_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(host_1.p);
}
		T99_ = (NI32)0;
		T99_ = Dl_2248147401_(hSess_1);
		(void)(T99_);
		eqdestroy___stdZwidestrs_u7(colontmpD_);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		goto BeforeRet_;
		{
			LA96_:;
		}
		{
			eqdestroy___pureZtimes_u2656(colontmp__8);
		}
		if (NIM_UNLIKELY(*nimErr_)) goto LA81_;
	}
LA94_: ;
	{
		NI32 T104_;
		tySequence__6H5Oh5UUvVCLiakt9aTwtUQ colontmp__10;
		NI colontmp__11;
		tySequence__6H5Oh5UUvVCLiakt9aTwtUQ blitTmp_5;
		NI32 T108_;
		NI32 T109_;
		NI32 T110_;
		T104_ = (NI32)0;
		T104_ = Dl_2248147466_(hReq_1, NIM_NIL);
		if (!!(((T104_) != 0))) goto LA105_;
		colontmp__10.len = 0; colontmp__10.p = NIM_NIL;
		colontmp__11 = ((NI)0);
		colontmp__10.len = 0; colontmp__10.p = (tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content*) newSeqPayload(0, sizeof(NU8), NIM_ALIGNOF(NU8));
		result.Field0 = colontmp__11;
		blitTmp_5 = colontmp__10;
		eqwasMoved___pureZtimes_u2653((&colontmp__10));
		result.Field1 = blitTmp_5;
		eqdestroy___pureZtimes_u2656(colontmp__10);
		eqdestroy___pureZtimes_u2656(colontmp__7);
		eqdestroy___pureZtimes_u2656(buf_1);
		eqdestroy___pureZtimes_u2656(resp_1);
		T108_ = (NI32)0;
		T108_ = Dl_2248147401_(hReq_1);
		(void)(T108_);
		eqdestroy___stdZwidestrs_u7(colontmpD__8);
		if (NIM_UNLIKELY(*nimErr_)) goto LA62_;
		eqdestroy___stdZwidestrs_u7(colontmpD__7);
		if (NIM_UNLIKELY(*nimErr_)) goto LA62_;
		T109_ = (NI32)0;
		T109_ = Dl_2248147401_(hConn_1);
		(void)(T109_);
		eqdestroy___stdZwidestrs_u7(colontmpD__2);
		if (NIM_UNLIKELY(*nimErr_)) goto LA10_;
		if (fullPath_1.p && !(fullPath_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(fullPath_1.p);
}
		if (rest_1.p && !(rest_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(rest_1.p);
}
		if (host_1.p && !(host_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(host_1.p);
}
		T110_ = (NI32)0;
		T110_ = Dl_2248147401_(hSess_1);
		(void)(T110_);
		eqdestroy___stdZwidestrs_u7(colontmpD_);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		goto BeforeRet_;
		{
			LA107_:;
		}
		{
			eqdestroy___pureZtimes_u2656(colontmp__10);
		}
		if (NIM_UNLIKELY(*nimErr_)) goto LA81_;
	}
LA105_: ;
	code_1 = (NI32)0;
	codeSize_1 = ((NI32)4);
	T113_ = (NI32)0;
	T113_ = Dl_2248147449_(hReq_1, ((NI32)536870931), ((NU16*) NIM_NIL), ((void*) ((&code_1))), (&codeSize_1), ((NI32*) NIM_NIL));
	(void)(T113_);
	buf_1 = newSeq__stdZsysrand_u55(((NI)8192));
	got_1 = (NI32)0;
	{
		while (1) {
			tySequence__6H5Oh5UUvVCLiakt9aTwtUQ colontmpD__11;
			tyObject_HSlice__RmqVCB5rHyE9cs59bZ8FgkPA T127_;
			colontmpD__11.len = 0; colontmpD__11.p = NIM_NIL;
			{
				NI T119_;
				NI32 T120_;
				T119_ = buf_1.len;
				T120_ = (NI32)0;
				T120_ = Dl_2248147461_(hReq_1, ((void*) ((&buf_1.p->data[((NI)0)]))), ((NI32) (T119_)), (&got_1));
				if (!!(((T120_) != 0))) goto LA121_;
				eqdestroy___pureZtimes_u2656(colontmpD__11);
				goto LA114;
			}
LA121_: ;
			{
				if (!(got_1 == ((NI32)0))) goto LA125_;
				eqdestroy___pureZtimes_u2656(colontmpD__11);
				goto LA114;
			}
LA125_: ;
			T127_ = dotdot___stdZstrbasics_u48(((NI)0), (NI)(((NI) (got_1)) - ((NI)1)));
			colontmpD__11 = X5BX5D___crypto_u1710(((buf_1).p) ? (buf_1.p->data) : NIM_NIL, buf_1.len, T127_);
			if (NIM_UNLIKELY(*nimErr_)) goto LA116_;
			add__transport_u283((&resp_1), ((colontmpD__11).p) ? (colontmpD__11.p->data) : NIM_NIL, colontmpD__11.len);
			{
				LA116_:;
			}
			{
				eqdestroy___pureZtimes_u2656(colontmpD__11);
			}
			if (NIM_UNLIKELY(*nimErr_)) goto LA81_;
		}
	} LA114: ;
	colontmp__12 = ((NI) (code_1));
	colontmp__7 = resp_1;
	eqwasMoved___pureZtimes_u2653((&resp_1));
	result.Field0 = colontmp__12;
	blitTmp_6 = colontmp__7;
	eqwasMoved___pureZtimes_u2653((&colontmp__7));
	result.Field1 = blitTmp_6;
	eqdestroy___pureZtimes_u2656(colontmp__7);
	eqdestroy___pureZtimes_u2656(buf_1);
	eqdestroy___pureZtimes_u2656(resp_1);
	T130_ = (NI32)0;
	T130_ = Dl_2248147401_(hReq_1);
	(void)(T130_);
	eqdestroy___stdZwidestrs_u7(colontmpD__8);
	if (NIM_UNLIKELY(*nimErr_)) goto LA62_;
	eqdestroy___stdZwidestrs_u7(colontmpD__7);
	if (NIM_UNLIKELY(*nimErr_)) goto LA62_;
	T131_ = (NI32)0;
	T131_ = Dl_2248147401_(hConn_1);
	(void)(T131_);
	eqdestroy___stdZwidestrs_u7(colontmpD__2);
	if (NIM_UNLIKELY(*nimErr_)) goto LA10_;
	if (fullPath_1.p && !(fullPath_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(fullPath_1.p);
}
	if (rest_1.p && !(rest_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(rest_1.p);
}
	if (host_1.p && !(host_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(host_1.p);
}
	T132_ = (NI32)0;
	T132_ = Dl_2248147401_(hSess_1);
	(void)(T132_);
	eqdestroy___stdZwidestrs_u7(colontmpD_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	goto BeforeRet_;
	{
		LA81_:;
	}
	{
		eqdestroy___pureZtimes_u2656(colontmp__7);
		eqdestroy___pureZtimes_u2656(buf_1);
		eqdestroy___pureZtimes_u2656(resp_1);
	}
	if (NIM_UNLIKELY(*nimErr_)) goto LA80_;
	{
		LA80_:;
	}
	{
		NI32 T137_;
		T137_ = (NI32)0;
		T137_ = Dl_2248147401_(hReq_1);
		(void)(T137_);
	}
	if (NIM_UNLIKELY(*nimErr_)) goto LA63_;
	{
		LA63_:;
	}
	{
		oldNimErrFin63_ = *nimErr_; *nimErr_ = NIM_FALSE;
		eqdestroy___stdZwidestrs_u7(colontmpD__8);
		if (NIM_UNLIKELY(*nimErr_)) goto LA62_;
		eqdestroy___stdZwidestrs_u7(colontmpD__7);
		if (NIM_UNLIKELY(*nimErr_)) goto LA62_;
		*nimErr_ = oldNimErrFin63_;
	}
	if (NIM_UNLIKELY(*nimErr_)) goto LA62_;
	{
		LA62_:;
	}
	{
		NI32 T142_;
		T142_ = (NI32)0;
		T142_ = Dl_2248147401_(hConn_1);
		(void)(T142_);
	}
	if (NIM_UNLIKELY(*nimErr_)) goto LA11_;
	{
		LA11_:;
	}
	{
		oldNimErrFin11_ = *nimErr_; *nimErr_ = NIM_FALSE;
		eqdestroy___stdZwidestrs_u7(colontmpD__2);
		if (NIM_UNLIKELY(*nimErr_)) goto LA10_;
		if (fullPath_1.p && !(fullPath_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(fullPath_1.p);
}
		if (rest_1.p && !(rest_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(rest_1.p);
}
		if (host_1.p && !(host_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(host_1.p);
}
		*nimErr_ = oldNimErrFin11_;
	}
	if (NIM_UNLIKELY(*nimErr_)) goto LA10_;
	{
		LA10_:;
	}
	{
		NI32 T147_;
		T147_ = (NI32)0;
		T147_ = Dl_2248147401_(hSess_1);
		(void)(T147_);
	}
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		LA1_:;
	}
	{
		oldNimErrFin1_ = *nimErr_; *nimErr_ = NIM_FALSE;
		eqdestroy___stdZwidestrs_u7(colontmpD_);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		*nimErr_ = oldNimErrFin1_;
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___transport_u309)(tyTuple__hnCuDR9cLe2lA3YIkwKIyuA* dest_p0) {
	eqdestroy___pureZtimes_u2656((*dest_p0).Field1);
}
static N_INLINE(tyObject_JsonNodeObj__HuNCd9cjVf1RGJ8WXqZvVog*, X5BX5D___pureZjson_u3580)(tyObject_JsonNodeObj__HuNCd9cjVf1RGJ8WXqZvVog* node_p0, NimStringV2 name_p1) {
	tyObject_JsonNodeObj__HuNCd9cjVf1RGJ8WXqZvVog* result;
	tyObject_JsonNodeObj__HuNCd9cjVf1RGJ8WXqZvVog** T1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	T1_ = (tyObject_JsonNodeObj__HuNCd9cjVf1RGJ8WXqZvVog**)0;
	T1_ = X5BX5D___pureZjson_u3088((&(*node_p0)._kind_6.fields), name_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	eqcopy___pureZjson_u324(&result, (*T1_));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(void, popCurrentException)(void) {
	eqcopy___system_u3693(&currException__system_u3660, (*currException__system_u3660).up, NIM_FALSE);
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, register__transport_u327)(tyObject_AgentTransport__5qQy6rhkf3jaeikY8XXtPQ* t_p0) {
	NIM_BOOL result;
	tyObject_JsonNodeObj__HuNCd9cjVf1RGJ8WXqZvVog* info_1;
	NimStringV2 colontmpD_;
	tyObject_JsonNodeObj__HuNCd9cjVf1RGJ8WXqZvVog* colontmpD__2;
	NimStringV2 colontmpD__3;
	tyObject_JsonNodeObj__HuNCd9cjVf1RGJ8WXqZvVog* colontmpD__4;
	tyObject_JsonNodeObj__HuNCd9cjVf1RGJ8WXqZvVog* colontmpD__5;
	tyObject_JsonNodeObj__HuNCd9cjVf1RGJ8WXqZvVog* colontmpD__6;
	tyObject_JsonNodeObj__HuNCd9cjVf1RGJ8WXqZvVog* colontmpD__7;
	tyObject_JsonNodeObj__HuNCd9cjVf1RGJ8WXqZvVog* colontmpD__8;
	tyObject_JsonNodeObj__HuNCd9cjVf1RGJ8WXqZvVog* colontmpD__9;
	NimStringV2 colontmpD__10;
	tyObject_JsonNodeObj__HuNCd9cjVf1RGJ8WXqZvVog* colontmpD__11;
	tyTuple__hnCuDR9cLe2lA3YIkwKIyuA tmpTuple_1;
	NimStringV2 colontmpD__12;
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ resp_1;
	tyArray__r0mq37zJ5pjlN4CzdC9coUg T2_;
	NI32 T3_;
	NI code_1;
	tyObject_JsonNodeObj__HuNCd9cjVf1RGJ8WXqZvVog* j_1;
	tyObject_JsonNodeObj__HuNCd9cjVf1RGJ8WXqZvVog* colontmpD__13;
	tyObject_JsonNodeObj__HuNCd9cjVf1RGJ8WXqZvVog* colontmpD__14;
	NimStringV2 colontmpD__15;
	tyObject_JsonNodeObj__HuNCd9cjVf1RGJ8WXqZvVog* T13_;
	tyObject_JsonNodeObj__HuNCd9cjVf1RGJ8WXqZvVog* T14_;
	NimStringV2 T15_;
	tyObject_JsonNodeObj__HuNCd9cjVf1RGJ8WXqZvVog* T16_;
	NimStringV2 T17_;
	NimStringV2 T18_;
NIM_BOOL oldNimErrFin12_;
NIM_BOOL oldNimErrFin1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	info_1 = NIM_NIL;
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	colontmpD__2 = NIM_NIL;
	colontmpD__3.len = 0; colontmpD__3.p = NIM_NIL;
	colontmpD__4 = NIM_NIL;
	colontmpD__5 = NIM_NIL;
	colontmpD__6 = NIM_NIL;
	colontmpD__7 = NIM_NIL;
	colontmpD__8 = NIM_NIL;
	colontmpD__9 = NIM_NIL;
	colontmpD__10.len = 0; colontmpD__10.p = NIM_NIL;
	colontmpD__11 = NIM_NIL;
	nimZeroMem((void*)(&tmpTuple_1), sizeof(tyTuple__hnCuDR9cLe2lA3YIkwKIyuA));
	colontmpD__12.len = 0; colontmpD__12.p = NIM_NIL;
	resp_1.len = 0; resp_1.p = NIM_NIL;
	nimZeroMem((void*)T2_, sizeof(tyArray__r0mq37zJ5pjlN4CzdC9coUg));
	T2_[0].Field0 = TM__7gIcePhgbItPdDBxBodgMQ_7;
	colontmpD_ = getEnvStr__transport_u8(TM__7gIcePhgbItPdDBxBodgMQ_9, TM__7gIcePhgbItPdDBxBodgMQ_11);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	colontmpD__2 = percent___pureZjson_u2156(colontmpD_);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T2_[0].Field1 = colontmpD__2;
	T2_[1].Field0 = TM__7gIcePhgbItPdDBxBodgMQ_13;
	colontmpD__3 = getEnvStr__transport_u8(TM__7gIcePhgbItPdDBxBodgMQ_15, TM__7gIcePhgbItPdDBxBodgMQ_16);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	colontmpD__4 = percent___pureZjson_u2156(colontmpD__3);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T2_[1].Field1 = colontmpD__4;
	T2_[2].Field0 = TM__7gIcePhgbItPdDBxBodgMQ_18;
	colontmpD__5 = percent___pureZjson_u2156(TM__7gIcePhgbItPdDBxBodgMQ_20);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T2_[2].Field1 = colontmpD__5;
	T2_[3].Field0 = TM__7gIcePhgbItPdDBxBodgMQ_22;
	T3_ = (NI32)0;
	T3_ = Dl_2013268980_();
	colontmpD__6 = percent___pureZjson_u2166(((NI) (T3_)));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T2_[3].Field1 = colontmpD__6;
	T2_[4].Field0 = TM__7gIcePhgbItPdDBxBodgMQ_24;
	colontmpD__7 = percent___pureZjson_u2156(TM__7gIcePhgbItPdDBxBodgMQ_26);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T2_[4].Field1 = colontmpD__7;
	T2_[5].Field0 = TM__7gIcePhgbItPdDBxBodgMQ_28;
	colontmpD__8 = percent___pureZjson_u2166(((NI)30));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T2_[5].Field1 = colontmpD__8;
	T2_[6].Field0 = TM__7gIcePhgbItPdDBxBodgMQ_30;
	colontmpD__9 = percent___pureZjson_u2166(((NI)20));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T2_[6].Field1 = colontmpD__9;
	T2_[7].Field0 = TM__7gIcePhgbItPdDBxBodgMQ_32;
	colontmpD__10 = exeName__transport_u14();
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	colontmpD__11 = percent___pureZjson_u2156(colontmpD__10);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T2_[7].Field1 = colontmpD__11;
	info_1 = percent___pureZjson_u2185(T2_, 8);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	colontmpD__12 = dollar___pureZjson_u4933(info_1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	tmpTuple_1 = winHttpDo__transport_u46(t_p0, TM__7gIcePhgbItPdDBxBodgMQ_48, TM__7gIcePhgbItPdDBxBodgMQ_50, (*(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ*) (&colontmpD__12)));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	code_1 = tmpTuple_1.Field0;
	resp_1 = tmpTuple_1.Field1;
	eqwasMoved___pureZtimes_u2653((&tmpTuple_1.Field1));
	{
		NIM_BOOL T6_;
		NI T8_;
		T6_ = (NIM_BOOL)0;
		T6_ = !((code_1 == ((NI)200)));
		if (T6_) goto LA7_;
		T8_ = resp_1.len;
		T6_ = (T8_ == ((NI)0));
LA7_: ;
		if (!T6_) goto LA9_;
		result = NIM_FALSE;
		eqdestroy___pureZtimes_u2656(resp_1);
		if (colontmpD__12.p && !(colontmpD__12.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__12.p);
}
		eqdestroy___transport_u309((&tmpTuple_1));
		eqdestroy___pureZjson_u321(colontmpD__11);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (colontmpD__10.p && !(colontmpD__10.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__10.p);
}
		eqdestroy___pureZjson_u321(colontmpD__9);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		eqdestroy___pureZjson_u321(colontmpD__8);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		eqdestroy___pureZjson_u321(colontmpD__7);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		eqdestroy___pureZjson_u321(colontmpD__6);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		eqdestroy___pureZjson_u321(colontmpD__5);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		eqdestroy___pureZjson_u321(colontmpD__4);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (colontmpD__3.p && !(colontmpD__3.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__3.p);
}
		eqdestroy___pureZjson_u321(colontmpD__2);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
		eqdestroy___pureZjson_u321(info_1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		goto BeforeRet_;
	}
LA9_: ;
	j_1 = NIM_NIL;
	colontmpD__13 = NIM_NIL;
	colontmpD__14 = NIM_NIL;
	colontmpD__15.len = 0; colontmpD__15.p = NIM_NIL;
	T13_ = NIM_NIL;
	T13_ = parseJson__pureZjson_u5692((*(NimStringV2*) (&resp_1)), NIM_FALSE, NIM_FALSE);
	if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___pureZjson_u321(T13_); goto LA12_;}
	j_1 = T13_;
	T14_ = NIM_NIL;
	T14_ = X5BX5D___pureZjson_u3580(j_1, TM__7gIcePhgbItPdDBxBodgMQ_52);
	if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___pureZjson_u321(T14_); goto LA12_;}
	colontmpD__13 = T14_;
	T15_.len = 0; T15_.p = NIM_NIL;
	T15_ = getStr__pureZjson_u551(colontmpD__13, TM__7gIcePhgbItPdDBxBodgMQ_53);
	if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u281(T15_); goto LA12_;}
	eqsink___system_u2729((&(*t_p0).agentId), T15_);
	T16_ = NIM_NIL;
	T16_ = X5BX5D___pureZjson_u3580(j_1, TM__7gIcePhgbItPdDBxBodgMQ_55);
	if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___pureZjson_u321(T16_); goto LA12_;}
	colontmpD__14 = T16_;
	T17_.len = 0; T17_.p = NIM_NIL;
	T17_ = getStr__pureZjson_u551(colontmpD__14, TM__7gIcePhgbItPdDBxBodgMQ_56);
	if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u281(T17_); goto LA12_;}
	colontmpD__15 = T17_;
	T18_.len = 0; T18_.p = NIM_NIL;
	T18_ = decode__pureZbase64_u481(colontmpD__15);
	if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u281(T18_); goto LA12_;}
	eqsink___pureZtimes_u2665((&(*t_p0).aesKey), (*(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ*) (&T18_)));
	result = NIM_TRUE;
	if (colontmpD__15.p && !(colontmpD__15.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__15.p);
}
	eqdestroy___pureZjson_u321(colontmpD__14);
	if (NIM_UNLIKELY(*nimErr_)) goto LA11_;
	eqdestroy___pureZjson_u321(colontmpD__13);
	if (NIM_UNLIKELY(*nimErr_)) goto LA11_;
	eqdestroy___pureZjson_u321(j_1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA11_;
	eqdestroy___pureZtimes_u2656(resp_1);
	if (colontmpD__12.p && !(colontmpD__12.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__12.p);
}
	eqdestroy___transport_u309((&tmpTuple_1));
	eqdestroy___pureZjson_u321(colontmpD__11);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	if (colontmpD__10.p && !(colontmpD__10.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__10.p);
}
	eqdestroy___pureZjson_u321(colontmpD__9);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	eqdestroy___pureZjson_u321(colontmpD__8);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	eqdestroy___pureZjson_u321(colontmpD__7);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	eqdestroy___pureZjson_u321(colontmpD__6);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	eqdestroy___pureZjson_u321(colontmpD__5);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	eqdestroy___pureZjson_u321(colontmpD__4);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	if (colontmpD__3.p && !(colontmpD__3.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__3.p);
}
	eqdestroy___pureZjson_u321(colontmpD__2);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
	eqdestroy___pureZjson_u321(info_1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	goto BeforeRet_;
	{
		LA12_:;
	}
	{
		oldNimErrFin12_ = *nimErr_; *nimErr_ = NIM_FALSE;
		if (colontmpD__15.p && !(colontmpD__15.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__15.p);
}
		eqdestroy___pureZjson_u321(colontmpD__14);
		if (NIM_UNLIKELY(*nimErr_)) goto LA11_;
		eqdestroy___pureZjson_u321(colontmpD__13);
		if (NIM_UNLIKELY(*nimErr_)) goto LA11_;
		eqdestroy___pureZjson_u321(j_1);
		if (NIM_UNLIKELY(*nimErr_)) goto LA11_;
		*nimErr_ = oldNimErrFin12_;
	}
	if (NIM_UNLIKELY(*nimErr_)) goto LA11_;
	if (NIM_UNLIKELY(*nimErr_)) {
		LA11_:;
		{
			*nimErr_ = NIM_FALSE;
			raiseDefect();
			result = NIM_FALSE;
			eqdestroy___pureZtimes_u2656(resp_1);
			if (colontmpD__12.p && !(colontmpD__12.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__12.p);
}
			eqdestroy___transport_u309((&tmpTuple_1));
			eqdestroy___pureZjson_u321(colontmpD__11);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (colontmpD__10.p && !(colontmpD__10.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__10.p);
}
			eqdestroy___pureZjson_u321(colontmpD__9);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			eqdestroy___pureZjson_u321(colontmpD__8);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			eqdestroy___pureZjson_u321(colontmpD__7);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			eqdestroy___pureZjson_u321(colontmpD__6);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			eqdestroy___pureZjson_u321(colontmpD__5);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			eqdestroy___pureZjson_u321(colontmpD__4);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (colontmpD__3.p && !(colontmpD__3.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__3.p);
}
			eqdestroy___pureZjson_u321(colontmpD__2);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
			eqdestroy___pureZjson_u321(info_1);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			popCurrentException();
			goto BeforeRet_;
			popCurrentException();
			LA22_:;
		}
	}
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		LA1_:;
	}
	{
		oldNimErrFin1_ = *nimErr_; *nimErr_ = NIM_FALSE;
		eqdestroy___pureZtimes_u2656(resp_1);
		if (colontmpD__12.p && !(colontmpD__12.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__12.p);
}
		eqdestroy___transport_u309((&tmpTuple_1));
		eqdestroy___pureZjson_u321(colontmpD__11);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (colontmpD__10.p && !(colontmpD__10.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__10.p);
}
		eqdestroy___pureZjson_u321(colontmpD__9);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		eqdestroy___pureZjson_u321(colontmpD__8);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		eqdestroy___pureZjson_u321(colontmpD__7);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		eqdestroy___pureZjson_u321(colontmpD__6);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		eqdestroy___pureZjson_u321(colontmpD__5);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		eqdestroy___pureZjson_u321(colontmpD__4);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (colontmpD__3.p && !(colontmpD__3.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__3.p);
}
		eqdestroy___pureZjson_u321(colontmpD__2);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
		eqdestroy___pureZjson_u321(info_1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		*nimErr_ = oldNimErrFin1_;
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___transport_u559)(tyObject_TaskWire__mbM5G2Ws36WZ5MBZxEz9bWw* dest_p0) {
	(*dest_p0).id = 0;
	(*dest_p0).typ.len = 0; (*dest_p0).typ.p = NIM_NIL;
	(*dest_p0).args.len = 0; (*dest_p0).args.p = NIM_NIL;
	(*dest_p0).payload.len = 0; (*dest_p0).payload.p = NIM_NIL;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___transport_u562)(tyObject_TaskWire__mbM5G2Ws36WZ5MBZxEz9bWw* dest_p0) {
	eqdestroy___pureZtimes_u2656((*dest_p0).payload);
	if ((*dest_p0).args.p && !((*dest_p0).args.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).args.p);
}
	if ((*dest_p0).typ.p && !((*dest_p0).typ.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).typ.p);
}
}
N_LIB_PRIVATE N_NIMCALL(tySequence__9c9a9ceFj9bCgncwLIjnR3kpJg, beacon__transport_u433)(tyObject_AgentTransport__5qQy6rhkf3jaeikY8XXtPQ* t_p0) {
	tySequence__9c9a9ceFj9bCgncwLIjnR3kpJg result;
	NimStringV2 path_1;
	tyTuple__hnCuDR9cLe2lA3YIkwKIyuA tmpTuple_1;
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ resp_1;
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ plain_1;
	NimStringV2 T2_;
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ T10_;
	NI code_1;
	tyObject_JsonNodeObj__HuNCd9cjVf1RGJ8WXqZvVog* j_1;
	tyObject_JsonNodeObj__HuNCd9cjVf1RGJ8WXqZvVog* T27_;
NIM_BOOL oldNimErrFin49_;
NIM_BOOL oldNimErrFin36_;
NIM_BOOL oldNimErrFin32_;
NIM_BOOL oldNimErrFin29_;
NIM_BOOL oldNimErrFin26_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	path_1.len = 0; path_1.p = NIM_NIL;
	nimZeroMem((void*)(&tmpTuple_1), sizeof(tyTuple__hnCuDR9cLe2lA3YIkwKIyuA));
	resp_1.len = 0; resp_1.p = NIM_NIL;
	plain_1.len = 0; plain_1.p = NIM_NIL;
	T2_.len = 0; T2_.p = NIM_NIL;
	T2_ = rawNewString((*t_p0).agentId.len + 8);
appendString((&T2_), TM__7gIcePhgbItPdDBxBodgMQ_58);
appendString((&T2_), (*t_p0).agentId);
	path_1 = T2_;
	{
		NI T5_;
		NimStringV2 T8_;
		NI T9_;
		T5_ = (*t_p0).uriList.len;
		if (!(((NI)0) < T5_)) goto LA6_;
		T8_.len = 0; T8_.p = NIM_NIL;
		T9_ = (*t_p0).uriList.len;
		T8_ = rawNewString((*t_p0).uriList.p->data[(NI)((*t_p0).uriIdx % T9_)].len + (*t_p0).agentId.len + 1);
appendString((&T8_), (*t_p0).uriList.p->data[(NI)((*t_p0).uriIdx % T9_)]);
appendString((&T8_), TM__7gIcePhgbItPdDBxBodgMQ_60);
appendString((&T8_), (*t_p0).agentId);
		eqsink___system_u2729((&path_1), T8_);
		(*t_p0).uriIdx += ((NI)1);
	}
LA6_: ;
	T10_.len = 0; T10_.p = NIM_NIL;
	T10_.len = 0; T10_.p = (tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content*) newSeqPayload(0, sizeof(NU8), NIM_ALIGNOF(NU8));
	tmpTuple_1 = winHttpDo__transport_u46(t_p0, TM__7gIcePhgbItPdDBxBodgMQ_62, path_1, T10_);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	code_1 = tmpTuple_1.Field0;
	resp_1 = tmpTuple_1.Field1;
	eqwasMoved___pureZtimes_u2653((&tmpTuple_1.Field1));
	{
		NIM_BOOL T13_;
		NIM_BOOL T14_;
		NI T16_;
		T13_ = (NIM_BOOL)0;
		T14_ = (NIM_BOOL)0;
		T14_ = (code_1 == ((NI)204));
		if (T14_) goto LA15_;
		T16_ = resp_1.len;
		T14_ = (T16_ == ((NI)0));
LA15_: ;
		T13_ = T14_;
		if (T13_) goto LA17_;
		T13_ = !((code_1 == ((NI)200)));
LA17_: ;
		if (!T13_) goto LA18_;
		result.len = 0; result.p = (tySequence__9c9a9ceFj9bCgncwLIjnR3kpJg_Content*) newSeqPayload(0, sizeof(tyObject_TaskWire__mbM5G2Ws36WZ5MBZxEz9bWw), NIM_ALIGNOF(tyObject_TaskWire__mbM5G2Ws36WZ5MBZxEz9bWw));
		eqdestroy___pureZtimes_u2656(plain_1);
		eqdestroy___pureZtimes_u2656(resp_1);
		eqdestroy___transport_u309((&tmpTuple_1));
		if (path_1.p && !(path_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(path_1.p);
}
		goto BeforeRet_;
	}
LA18_: ;
	plain_1 = openGCM__crypto_u1684((*t_p0).aesKey, resp_1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		NI T22_;
		T22_ = plain_1.len;
		if (!(T22_ == ((NI)0))) goto LA23_;
		result.len = 0; result.p = (tySequence__9c9a9ceFj9bCgncwLIjnR3kpJg_Content*) newSeqPayload(0, sizeof(tyObject_TaskWire__mbM5G2Ws36WZ5MBZxEz9bWw), NIM_ALIGNOF(tyObject_TaskWire__mbM5G2Ws36WZ5MBZxEz9bWw));
		eqdestroy___pureZtimes_u2656(plain_1);
		eqdestroy___pureZtimes_u2656(resp_1);
		eqdestroy___transport_u309((&tmpTuple_1));
		if (path_1.p && !(path_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(path_1.p);
}
		goto BeforeRet_;
	}
LA23_: ;
	j_1 = NIM_NIL;
	T27_ = NIM_NIL;
	T27_ = parseJson__pureZjson_u5692((*(NimStringV2*) (&plain_1)), NIM_FALSE, NIM_FALSE);
	if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___pureZjson_u321(T27_); goto LA26_;}
	j_1 = T27_;
	{
		tyObject_JsonNodeObj__HuNCd9cjVf1RGJ8WXqZvVog* tw_1;
		tyObject_JsonNodeObj__HuNCd9cjVf1RGJ8WXqZvVog* colontmp_;
		tyObject_JsonNodeObj__HuNCd9cjVf1RGJ8WXqZvVog* T30_;
		tw_1 = NIM_NIL;
		colontmp_ = NIM_NIL;
		T30_ = NIM_NIL;
		T30_ = X5BX5D___pureZjson_u3580(j_1, TM__7gIcePhgbItPdDBxBodgMQ_64);
		if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___pureZjson_u321(T30_); goto LA29_;}
		colontmp_ = T30_;
		{
			tySequence__YWxjq9aB9anxKHaOq65jIGKw colontmp__2;
			tyObject_JsonNodeObj__HuNCd9cjVf1RGJ8WXqZvVog** i_1;
			NI i_2;
			NI L_1;
			NI T33_;
			colontmp__2.len = 0; colontmp__2.p = NIM_NIL;
			i_1 = (tyObject_JsonNodeObj__HuNCd9cjVf1RGJ8WXqZvVog**)0;
			eqcopy___pureZjson_u257((&colontmp__2), (*colontmp_)._kind_7.elems);
			if (NIM_UNLIKELY(*nimErr_)) goto LA32_;
			i_2 = ((NI)0);
			T33_ = colontmp__2.len;
			L_1 = T33_;
			{
				while (1) {
					tyObject_TaskWire__mbM5G2Ws36WZ5MBZxEz9bWw task_1;
					tyObject_JsonNodeObj__HuNCd9cjVf1RGJ8WXqZvVog* colontmpD_;
					tyObject_JsonNodeObj__HuNCd9cjVf1RGJ8WXqZvVog* colontmpD__2;
					tyObject_JsonNodeObj__HuNCd9cjVf1RGJ8WXqZvVog* colontmpD__3;
					tyObject_JsonNodeObj__HuNCd9cjVf1RGJ8WXqZvVog* colontmpD__4;
					NimStringV2 colontmpD__5;
					tyObject_JsonNodeObj__HuNCd9cjVf1RGJ8WXqZvVog* T37_;
					NI64 T38_;
					tyObject_JsonNodeObj__HuNCd9cjVf1RGJ8WXqZvVog* T39_;
					NimStringV2 T40_;
					tyObject_JsonNodeObj__HuNCd9cjVf1RGJ8WXqZvVog* T41_;
					NimStringV2 T42_;
					tyObject_TaskWire__mbM5G2Ws36WZ5MBZxEz9bWw blitTmp_1;
					if (!(i_2 < L_1)) goto LA35;
					nimZeroMem((void*)(&task_1), sizeof(tyObject_TaskWire__mbM5G2Ws36WZ5MBZxEz9bWw));
					colontmpD_ = NIM_NIL;
					colontmpD__2 = NIM_NIL;
					colontmpD__3 = NIM_NIL;
					colontmpD__4 = NIM_NIL;
					colontmpD__5.len = 0; colontmpD__5.p = NIM_NIL;
					i_1 = &colontmp__2.p->data[i_2];
					eqcopy___pureZjson_u324(&tw_1, (*i_1));
					if (NIM_UNLIKELY(*nimErr_)) goto LA36_;
					nimZeroMem((void*)(&task_1), sizeof(tyObject_TaskWire__mbM5G2Ws36WZ5MBZxEz9bWw));
					T37_ = NIM_NIL;
					T37_ = X5BX5D___pureZjson_u3580(tw_1, TM__7gIcePhgbItPdDBxBodgMQ_66);
					if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___pureZjson_u321(T37_); goto LA36_;}
					colontmpD_ = T37_;
					T38_ = (NI64)0;
					T38_ = getBiggestInt__pureZjson_u574(colontmpD_, IL64(0));
					if (NIM_UNLIKELY(*nimErr_)) goto LA36_;
					task_1.id = T38_;
					T39_ = NIM_NIL;
					T39_ = X5BX5D___pureZjson_u3580(tw_1, TM__7gIcePhgbItPdDBxBodgMQ_68);
					if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___pureZjson_u321(T39_); goto LA36_;}
					colontmpD__2 = T39_;
					T40_.len = 0; T40_.p = NIM_NIL;
					T40_ = getStr__pureZjson_u551(colontmpD__2, TM__7gIcePhgbItPdDBxBodgMQ_69);
					if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u281(T40_); goto LA36_;}
					task_1.typ = T40_;
					T41_ = NIM_NIL;
					T41_ = X7BX7D___pureZjson_u4070(tw_1, TM__7gIcePhgbItPdDBxBodgMQ_71);
					if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___pureZjson_u321(T41_); goto LA36_;}
					colontmpD__3 = T41_;
					T42_.len = 0; T42_.p = NIM_NIL;
					T42_ = getStr__pureZjson_u551(colontmpD__3, TM__7gIcePhgbItPdDBxBodgMQ_72);
					if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u281(T42_); goto LA36_;}
					task_1.args = T42_;
					{
						tyObject_JsonNodeObj__HuNCd9cjVf1RGJ8WXqZvVog* T45_;
						NimStringV2 T46_;
						tyObject_JsonNodeObj__HuNCd9cjVf1RGJ8WXqZvVog* colontmpD__6;
						NimStringV2 colontmpD__7;
						tyObject_JsonNodeObj__HuNCd9cjVf1RGJ8WXqZvVog* T50_;
						NimStringV2 T51_;
						NimStringV2 T52_;
						T45_ = NIM_NIL;
						T45_ = X7BX7D___pureZjson_u4070(tw_1, TM__7gIcePhgbItPdDBxBodgMQ_74);
						if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___pureZjson_u321(T45_); goto LA36_;}
						colontmpD__4 = T45_;
						T46_.len = 0; T46_.p = NIM_NIL;
						T46_ = getStr__pureZjson_u551(colontmpD__4, TM__7gIcePhgbItPdDBxBodgMQ_75);
						if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u281(T46_); goto LA36_;}
						colontmpD__5 = T46_;
						if (!!((colontmpD__5.len == 0))) goto LA47_;
						colontmpD__6 = NIM_NIL;
						colontmpD__7.len = 0; colontmpD__7.p = NIM_NIL;
						T50_ = NIM_NIL;
						T50_ = X5BX5D___pureZjson_u3580(tw_1, TM__7gIcePhgbItPdDBxBodgMQ_76);
						if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___pureZjson_u321(T50_); goto LA49_;}
						colontmpD__6 = T50_;
						T51_.len = 0; T51_.p = NIM_NIL;
						T51_ = getStr__pureZjson_u551(colontmpD__6, TM__7gIcePhgbItPdDBxBodgMQ_77);
						if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u281(T51_); goto LA49_;}
						colontmpD__7 = T51_;
						T52_.len = 0; T52_.p = NIM_NIL;
						T52_ = decode__pureZbase64_u481(colontmpD__7);
						if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u281(T52_); goto LA49_;}
						eqsink___pureZtimes_u2665((&task_1.payload), (*(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ*) (&T52_)));
						{
							LA49_:;
						}
						{
							oldNimErrFin49_ = *nimErr_; *nimErr_ = NIM_FALSE;
							if (colontmpD__7.p && !(colontmpD__7.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__7.p);
}
							eqdestroy___pureZjson_u321(colontmpD__6);
							if (NIM_UNLIKELY(*nimErr_)) goto LA36_;
							*nimErr_ = oldNimErrFin49_;
						}
						if (NIM_UNLIKELY(*nimErr_)) goto LA36_;
					}
LA47_: ;
					nimZeroMem((void*)(&blitTmp_1), sizeof(tyObject_TaskWire__mbM5G2Ws36WZ5MBZxEz9bWw));
					blitTmp_1 = task_1;
					eqwasMoved___transport_u559((&task_1));
					add__transport_u469((&result), (&blitTmp_1));
					i_2 += ((NI)1);
					{
						LA36_:;
					}
					{
						oldNimErrFin36_ = *nimErr_; *nimErr_ = NIM_FALSE;
						if (colontmpD__5.p && !(colontmpD__5.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__5.p);
}
						eqdestroy___pureZjson_u321(colontmpD__4);
						if (NIM_UNLIKELY(*nimErr_)) goto LA32_;
						eqdestroy___pureZjson_u321(colontmpD__3);
						if (NIM_UNLIKELY(*nimErr_)) goto LA32_;
						eqdestroy___pureZjson_u321(colontmpD__2);
						if (NIM_UNLIKELY(*nimErr_)) goto LA32_;
						eqdestroy___pureZjson_u321(colontmpD_);
						if (NIM_UNLIKELY(*nimErr_)) goto LA32_;
						eqdestroy___transport_u562((&task_1));
						*nimErr_ = oldNimErrFin36_;
					}
					if (NIM_UNLIKELY(*nimErr_)) goto LA32_;
				} LA35: ;
			}
			{
				LA32_:;
			}
			{
				oldNimErrFin32_ = *nimErr_; *nimErr_ = NIM_FALSE;
				eqdestroy___pureZjson_u254(colontmp__2);
				if (NIM_UNLIKELY(*nimErr_)) goto LA29_;
				*nimErr_ = oldNimErrFin32_;
			}
			if (NIM_UNLIKELY(*nimErr_)) goto LA29_;
		}
		{
			LA29_:;
		}
		{
			oldNimErrFin29_ = *nimErr_; *nimErr_ = NIM_FALSE;
			eqdestroy___pureZjson_u321(colontmp_);
			if (NIM_UNLIKELY(*nimErr_)) goto LA26_;
			eqdestroy___pureZjson_u321(tw_1);
			if (NIM_UNLIKELY(*nimErr_)) goto LA26_;
			*nimErr_ = oldNimErrFin29_;
		}
		if (NIM_UNLIKELY(*nimErr_)) goto LA26_;
	}
	{
		LA26_:;
	}
	{
		oldNimErrFin26_ = *nimErr_; *nimErr_ = NIM_FALSE;
		eqdestroy___pureZjson_u321(j_1);
		if (NIM_UNLIKELY(*nimErr_)) goto LA25_;
		*nimErr_ = oldNimErrFin26_;
	}
	if (NIM_UNLIKELY(*nimErr_)) goto LA25_;
	if (NIM_UNLIKELY(*nimErr_)) {
		LA25_:;
		{
			*nimErr_ = NIM_FALSE;
			raiseDefect();
			popCurrentException();
			LA64_:;
		}
	}
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		LA1_:;
	}
	{
		eqdestroy___pureZtimes_u2656(plain_1);
		eqdestroy___pureZtimes_u2656(resp_1);
		eqdestroy___transport_u309((&tmpTuple_1));
		if (path_1.p && !(path_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(path_1.p);
}
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, sendResult__transport_u683)(tyObject_AgentTransport__5qQy6rhkf3jaeikY8XXtPQ* t_p0, NI64 taskId_p1, NimStringV2 output_p2, NimStringV2 errStr_p3) {
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ plain_1;
	tyObject_JsonNodeObj__HuNCd9cjVf1RGJ8WXqZvVog* colontmpD_;
	tyObject_JsonNodeObj__HuNCd9cjVf1RGJ8WXqZvVog* colontmpD__2;
	tyObject_JsonNodeObj__HuNCd9cjVf1RGJ8WXqZvVog* colontmpD__3;
	tyObject_JsonNodeObj__HuNCd9cjVf1RGJ8WXqZvVog* colontmpD__4;
	NimStringV2 colontmpD__5;
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ colontmpD__6;
	tyTuple__hnCuDR9cLe2lA3YIkwKIyuA colontmpD__7;
	tyArray__sJUNyoTANwaMIsGxVULdtg T2_;
	NimStringV2 T3_;
	NimStringV2 T4_;
NIM_BOOL oldNimErrFin1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	plain_1.len = 0; plain_1.p = NIM_NIL;
	colontmpD_ = NIM_NIL;
	colontmpD__2 = NIM_NIL;
	colontmpD__3 = NIM_NIL;
	colontmpD__4 = NIM_NIL;
	colontmpD__5.len = 0; colontmpD__5.p = NIM_NIL;
	colontmpD__6.len = 0; colontmpD__6.p = NIM_NIL;
	nimZeroMem((void*)(&colontmpD__7), sizeof(tyTuple__hnCuDR9cLe2lA3YIkwKIyuA));
	nimZeroMem((void*)T2_, sizeof(tyArray__sJUNyoTANwaMIsGxVULdtg));
	T2_[0].Field0 = TM__7gIcePhgbItPdDBxBodgMQ_79;
	colontmpD_ = percent___pureZjson_u2176(taskId_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T2_[0].Field1 = colontmpD_;
	T2_[1].Field0 = TM__7gIcePhgbItPdDBxBodgMQ_81;
	colontmpD__2 = percent___pureZjson_u2156(output_p2);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T2_[1].Field1 = colontmpD__2;
	T2_[2].Field0 = TM__7gIcePhgbItPdDBxBodgMQ_83;
	colontmpD__3 = percent___pureZjson_u2156(errStr_p3);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T2_[2].Field1 = colontmpD__3;
	colontmpD__4 = percent___pureZjson_u2185(T2_, 3);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T3_.len = 0; T3_.p = NIM_NIL;
	T3_ = dollar___pureZjson_u4933(colontmpD__4);
	if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u281(T3_); goto LA1_;}
	plain_1 = (*(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ*) (&T3_));
	T4_.len = 0; T4_.p = NIM_NIL;
	T4_ = rawNewString((*t_p0).agentId.len + 8);
appendString((&T4_), TM__7gIcePhgbItPdDBxBodgMQ_86);
appendString((&T4_), (*t_p0).agentId);
	colontmpD__5 = T4_;
	colontmpD__6 = sealGCM__crypto_u34((*t_p0).aesKey, plain_1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	colontmpD__7 = winHttpDo__transport_u46(t_p0, TM__7gIcePhgbItPdDBxBodgMQ_84, colontmpD__5, colontmpD__6);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	(void)(colontmpD__7);
	{
		LA1_:;
	}
	{
		oldNimErrFin1_ = *nimErr_; *nimErr_ = NIM_FALSE;
		eqdestroy___transport_u309((&colontmpD__7));
		eqdestroy___pureZtimes_u2656(colontmpD__6);
		if (colontmpD__5.p && !(colontmpD__5.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__5.p);
}
		eqdestroy___pureZjson_u321(colontmpD__4);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		eqdestroy___pureZjson_u321(colontmpD__3);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		eqdestroy___pureZjson_u321(colontmpD__2);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		eqdestroy___pureZjson_u321(colontmpD_);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		eqdestroy___pureZtimes_u2656(plain_1);
		*nimErr_ = oldNimErrFin1_;
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ, downloadFile__transport_u754)(tyObject_AgentTransport__5qQy6rhkf3jaeikY8XXtPQ* t_p0, NimStringV2 filename_p1) {
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ result;
	tyTuple__hnCuDR9cLe2lA3YIkwKIyuA tmpTuple_1;
	NimStringV2 colontmpD_;
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ resp_1;
	NimStringV2 T2_;
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ T3_;
	NI code_1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimZeroMem((void*)(&tmpTuple_1), sizeof(tyTuple__hnCuDR9cLe2lA3YIkwKIyuA));
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	resp_1.len = 0; resp_1.p = NIM_NIL;
	T2_.len = 0; T2_.p = NIM_NIL;
	T2_ = rawNewString((*t_p0).agentId.len + filename_p1.len + 5);
appendString((&T2_), TM__7gIcePhgbItPdDBxBodgMQ_89);
appendString((&T2_), (*t_p0).agentId);
appendString((&T2_), TM__7gIcePhgbItPdDBxBodgMQ_90);
appendString((&T2_), filename_p1);
	colontmpD_ = T2_;
	T3_.len = 0; T3_.p = NIM_NIL;
	T3_.len = 0; T3_.p = (tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content*) newSeqPayload(0, sizeof(NU8), NIM_ALIGNOF(NU8));
	tmpTuple_1 = winHttpDo__transport_u46(t_p0, TM__7gIcePhgbItPdDBxBodgMQ_87, colontmpD_, T3_);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	code_1 = tmpTuple_1.Field0;
	resp_1 = tmpTuple_1.Field1;
	eqwasMoved___pureZtimes_u2653((&tmpTuple_1.Field1));
	{
		NIM_BOOL T6_;
		NI T8_;
		T6_ = (NIM_BOOL)0;
		T6_ = !((code_1 == ((NI)200)));
		if (T6_) goto LA7_;
		T8_ = resp_1.len;
		T6_ = (T8_ == ((NI)0));
LA7_: ;
		if (!T6_) goto LA9_;
		result.len = 0; result.p = (tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content*) newSeqPayload(0, sizeof(NU8), NIM_ALIGNOF(NU8));
		eqdestroy___pureZtimes_u2656(resp_1);
		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
		eqdestroy___transport_u309((&tmpTuple_1));
		goto BeforeRet_;
	}
LA9_: ;
	result = openGCM__crypto_u1684((*t_p0).aesKey, resp_1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	eqdestroy___pureZtimes_u2656(resp_1);
	if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
	eqdestroy___transport_u309((&tmpTuple_1));
	goto BeforeRet_;
	{
		LA1_:;
	}
	{
		eqdestroy___pureZtimes_u2656(resp_1);
		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
		eqdestroy___transport_u309((&tmpTuple_1));
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, uploadFile__transport_u749)(tyObject_AgentTransport__5qQy6rhkf3jaeikY8XXtPQ* t_p0, NI64 taskId_p1, NimStringV2 filename_p2, tySequence__6H5Oh5UUvVCLiakt9aTwtUQ data_p3) {
	NimStringV2 colontmpD_;
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ colontmpD__2;
	tyTuple__hnCuDR9cLe2lA3YIkwKIyuA colontmpD__3;
	NimStringV2 T2_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
	nimZeroMem((void*)(&colontmpD__3), sizeof(tyTuple__hnCuDR9cLe2lA3YIkwKIyuA));
	T2_.len = 0; T2_.p = NIM_NIL;
	T2_ = rawNewString((*t_p0).agentId.len + filename_p2.len + 9);
appendString((&T2_), TM__7gIcePhgbItPdDBxBodgMQ_93);
appendString((&T2_), (*t_p0).agentId);
appendString((&T2_), TM__7gIcePhgbItPdDBxBodgMQ_94);
appendString((&T2_), filename_p2);
	colontmpD_ = T2_;
	colontmpD__2 = sealGCM__crypto_u34((*t_p0).aesKey, data_p3);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	colontmpD__3 = winHttpDo__transport_u46(t_p0, TM__7gIcePhgbItPdDBxBodgMQ_91, colontmpD_, colontmpD__2);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	(void)(colontmpD__3);
	{
		LA1_:;
	}
	{
		eqdestroy___transport_u309((&colontmpD__3));
		eqdestroy___pureZtimes_u2656(colontmpD__2);
		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___agent_u37)(tyObject_AgentTransport__5qQy6rhkf3jaeikY8XXtPQ* dest_p0) {
	eqdestroy___system_u5532((*dest_p0).uriList);
	eqdestroy___pureZtimes_u2656((*dest_p0).aesKey);
	if ((*dest_p0).agentId.p && !((*dest_p0).agentId.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).agentId.p);
}
	if ((*dest_p0).serverUrl.p && !((*dest_p0).serverUrl.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).serverUrl.p);
}
}
