/* Generated by Nim Compiler v2.2.10 */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   x86_64-w64-mingw32-gcc -c -w -fmax-errors=3 -mno-ms-bitfields -fno-strict-aliasing -DWIN32_LEAN_AND_MEAN -Os -fno-ident   -I/home/kali/.choosenim/toolchains/nim-2.2.10/lib -I/home/kali/c2/agents/agent-nim -o /home/kali/c2/agents/agent-nim/nimcache_nim5min/@nnimcrypto-0.7.3-f72b90fe3f4da09efa482de4f8729e7ee4abea2f@snimcrypto@sbcmode.nim.c.o /home/kali/c2/agents/agent-nim/nimcache_nim5min/@nnimcrypto-0.7.3-f72b90fe3f4da09efa482de4f8729e7ee4abea2f@snimcrypto@sbcmode.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tyObject_GCM__eCD3Vqnb9c9cdir9bofS9aCo9aA tyObject_GCM__eCD3Vqnb9c9cdir9bofS9aCo9aA;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_RijndaelContext__NKUvxdvWF0pP2HEDIjikiQ tyObject_RijndaelContext__NKUvxdvWF0pP2HEDIjikiQ;
typedef struct tyObject_HSlice__RmqVCB5rHyE9cs59bZ8FgkPA tyObject_HSlice__RmqVCB5rHyE9cs59bZ8FgkPA;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
typedef NU64 tyArray__ey43Vigk7skIYtX9aBAXSdw[120];
struct tyObject_RijndaelContext__NKUvxdvWF0pP2HEDIjikiQ {
	tyArray__ey43Vigk7skIYtX9aBAXSdw skey;
	NI nr;
};
typedef NU8 tyArray__dnD8kjh6rJ1Yy5jHvid0Ow[16];
struct tyObject_GCM__eCD3Vqnb9c9cdir9bofS9aCo9aA {
	tyObject_RijndaelContext__NKUvxdvWF0pP2HEDIjikiQ cipher;
	tyArray__dnD8kjh6rJ1Yy5jHvid0Ow h;
	tyArray__dnD8kjh6rJ1Yy5jHvid0Ow y;
	tyArray__dnD8kjh6rJ1Yy5jHvid0Ow basectr;
	tyArray__dnD8kjh6rJ1Yy5jHvid0Ow buf;
	tyArray__dnD8kjh6rJ1Yy5jHvid0Ow hbuf;
	NU64 aadlen;
	NU64 datalen;
	NU8 coffset;
};
struct tyObject_HSlice__RmqVCB5rHyE9cs59bZ8FgkPA {
	NI a;
	NI b;
};
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__stdZassertions_u95)(NimStringV2 msg_p0);
static N_INLINE(void, burnMem__crypto_u130)(tyObject_GCM__eCD3Vqnb9c9cdir9bofS9aCo9aA* a_p0);
N_LIB_PRIVATE N_NIMCALL(void, burnMem__pkgZnimcryptoZutils_u303)(void* p_p0, NI size_p1);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static N_INLINE(void, init__crypto_u200)(tyObject_RijndaelContext__NKUvxdvWF0pP2HEDIjikiQ* ctx_p0, NU8* key_p1, NI key_p1Len_0);
N_LIB_PRIVATE N_NIMCALL(void, keySchedule__crypto_u204)(tyObject_RijndaelContext__NKUvxdvWF0pP2HEDIjikiQ* ctx_p0, NU8* key_p1, NI key_p1Len_0);
N_LIB_PRIVATE N_NIMCALL(void, encrypt__crypto_u614)(tyObject_RijndaelContext__NKUvxdvWF0pP2HEDIjikiQ* ctx_p0, NU8* input_p1, NI input_p1Len_0, NU8* output_p2, NI output_p2Len_0);
N_LIB_PRIVATE N_NIMCALL(void, X5BX5Deq___pkgZnimcryptoZbcmode_u762)(NU8* a_p0, tyObject_HSlice__RmqVCB5rHyE9cs59bZ8FgkPA x_p1, NU8* b_p2, NI b_p2Len_0);
static N_INLINE(tyObject_HSlice__RmqVCB5rHyE9cs59bZ8FgkPA, dotdot___stdZstrbasics_u48)(NI a_p0, NI b_p1);
N_LIB_PRIVATE N_NIMCALL(void, inc128__pkgZnimcryptoZbcmode_u178)(NU8* counter_p0, NI counter_p0Len_0);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__system_u2188)(void* a_p0, int v_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(void, ghash__pkgZnimcryptoZbcmode_u472)(NU8* y_p0, NI y_p0Len_0, NU8* h_p1, NI h_p1Len_0, NU8* data_p2, NI data_p2Len_0);
static N_INLINE(void, copyMem__system_u1755)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(NU64, rev64__pkgZnimcryptoZbcmode_u420)(NU64 x_p0);
N_LIB_PRIVATE N_NIMCALL(NU64, bmul64__pkgZnimcryptoZbcmode_u400)(NU64 x_p0, NU64 y_p1);
N_LIB_PRIVATE N_NIMCALL(void, getTag__crypto_u1429)(tyObject_GCM__eCD3Vqnb9c9cdir9bofS9aCo9aA* ctx_p0, NU8* tag_p1, NI tag_p1Len_0);
static const struct {
  NI cap; NIM_CHAR data[55+1];
} TM__40YfnbOcmramUFyaunCxCg_2 = { 55 | NIM_STRLIT_FLAG, "bcmode.nim(1111, 11) `ctx.sizeBlock() == GCMBlockSize` " };
static const NimStringV2 TM__40YfnbOcmramUFyaunCxCg_3 = {55, (NimStrPayload*)&TM__40YfnbOcmramUFyaunCxCg_2};
static const struct {
  NI cap; NIM_CHAR data[50+1];
} TM__40YfnbOcmramUFyaunCxCg_4 = { 50 | NIM_STRLIT_FLAG, "bcmode.nim(1112, 11) `\012ctx.sizeKey() <= len(key)` " };
static const NimStringV2 TM__40YfnbOcmramUFyaunCxCg_5 = {50, (NimStrPayload*)&TM__40YfnbOcmramUFyaunCxCg_4};
static const struct {
  NI cap; NIM_CHAR data[49+1];
} TM__40YfnbOcmramUFyaunCxCg_6 = { 49 | NIM_STRLIT_FLAG, "bcmode.nim(1180, 11) `len(input) <= len(output)` " };
static const NimStringV2 TM__40YfnbOcmramUFyaunCxCg_7 = {49, (NimStrPayload*)&TM__40YfnbOcmramUFyaunCxCg_6};
static const struct {
  NI cap; NIM_CHAR data[49+1];
} TM__40YfnbOcmramUFyaunCxCg_8 = { 49 | NIM_STRLIT_FLAG, "bcmode.nim(1141, 11) `len(input) <= len(output)` " };
static const NimStringV2 TM__40YfnbOcmramUFyaunCxCg_9 = {49, (NimStrPayload*)&TM__40YfnbOcmramUFyaunCxCg_8};
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4172;
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4172);
	return result;
}
static N_INLINE(void, burnMem__crypto_u130)(tyObject_GCM__eCD3Vqnb9c9cdir9bofS9aCo9aA* a_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	burnMem__pkgZnimcryptoZutils_u303(((void*) (a_p0)), ((NI)1072));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(void, init__crypto_u200)(tyObject_RijndaelContext__NKUvxdvWF0pP2HEDIjikiQ* ctx_p0, NU8* key_p1, NI key_p1Len_0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	keySchedule__crypto_u204(ctx_p0, key_p1, key_p1Len_0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(tyObject_HSlice__RmqVCB5rHyE9cs59bZ8FgkPA, dotdot___stdZstrbasics_u48)(NI a_p0, NI b_p1) {
	tyObject_HSlice__RmqVCB5rHyE9cs59bZ8FgkPA result;
	result.a = a_p0;
	result.b = b_p1;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, inc128__pkgZnimcryptoZbcmode_u178)(NU8* counter_p0, NI counter_p0Len_0) {
	NU32 n_1;
	NU32 c_1;
	n_1 = ((NU32)16);
	c_1 = ((NU32)1);
	{
		while (1) {
			n_1 -= ((NI)1);
			c_1 = (NU32)((NU32)(c_1) + (NU32)(((NU32) (counter_p0[n_1]))));
			counter_p0[n_1] = ((NU8) (c_1));
			c_1 = (NU32)((NU32)(c_1) >> (NU64)(((NI)8) & (32 - 1)));
			{
				if (!(n_1 == ((NU32)0))) goto LA5_;
				goto LA1;
			}
LA5_: ;
		}
	} LA1: ;
}
static N_INLINE(void, nimSetMem__system_u2188)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
	nimSetMem__system_u2188(p_p0, ((int)0), size_p1);
}
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, copyMem__system_u1755)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
N_LIB_PRIVATE N_NIMCALL(NU64, rev64__pkgZnimcryptoZbcmode_u420)(NU64 x_p0) {
	NU64 result;
	NU64 xx_1;
	xx_1 = x_p0;
	xx_1 = (NU64)((NU64)((NU64)((NU64)(xx_1 & 6148914691236517205ULL)) << (NU64)(((NI)1) & (64 - 1))) | (NU64)((NU64)((NU64)(xx_1) >> (NU64)(((NI)1) & (64 - 1))) & 6148914691236517205ULL));
	xx_1 = (NU64)((NU64)((NU64)((NU64)(xx_1 & 3689348814741910323ULL)) << (NU64)(((NI)2) & (64 - 1))) | (NU64)((NU64)((NU64)(xx_1) >> (NU64)(((NI)2) & (64 - 1))) & 3689348814741910323ULL));
	xx_1 = (NU64)((NU64)((NU64)((NU64)(xx_1 & 1085102592571150095ULL)) << (NU64)(((NI)4) & (64 - 1))) | (NU64)((NU64)((NU64)(xx_1) >> (NU64)(((NI)4) & (64 - 1))) & 1085102592571150095ULL));
	xx_1 = (NU64)((NU64)((NU64)((NU64)(xx_1 & 71777214294589695ULL)) << (NU64)(((NI)8) & (64 - 1))) | (NU64)((NU64)((NU64)(xx_1) >> (NU64)(((NI)8) & (64 - 1))) & 71777214294589695ULL));
	xx_1 = (NU64)((NU64)((NU64)((NU64)(xx_1 & 281470681808895ULL)) << (NU64)(((NI)16) & (64 - 1))) | (NU64)((NU64)((NU64)(xx_1) >> (NU64)(((NI)16) & (64 - 1))) & 281470681808895ULL));
	result = (NU64)((NU64)((NU64)(xx_1) << (NU64)(((NI)32) & (64 - 1))) | (NU64)((NU64)(xx_1) >> (NU64)(((NI)32) & (64 - 1))));
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NU64, bmul64__pkgZnimcryptoZbcmode_u400)(NU64 x_p0, NU64 y_p1) {
	NU64 result;
	NU64 x0_1;
	NU64 x1_1;
	NU64 x2_1;
	NU64 x3_1;
	NU64 y0_1;
	NU64 y1_1;
	NU64 y2_1;
	NU64 y3_1;
	NU64 z0_1;
	NU64 z1_1;
	NU64 z2_1;
	NU64 z3_1;
	x0_1 = (NU64)0;
	x1_1 = (NU64)0;
	x2_1 = (NU64)0;
	x3_1 = (NU64)0;
	y0_1 = (NU64)0;
	y1_1 = (NU64)0;
	y2_1 = (NU64)0;
	y3_1 = (NU64)0;
	z0_1 = (NU64)0;
	z1_1 = (NU64)0;
	z2_1 = (NU64)0;
	z3_1 = (NU64)0;
	x0_1 = (NU64)(x_p0 & 1229782938247303441ULL);
	x1_1 = (NU64)(x_p0 & 2459565876494606882ULL);
	x2_1 = (NU64)(x_p0 & 4919131752989213764ULL);
	x3_1 = (NU64)(x_p0 & 9838263505978427528ULL);
	y0_1 = (NU64)(y_p1 & 1229782938247303441ULL);
	y1_1 = (NU64)(y_p1 & 2459565876494606882ULL);
	y2_1 = (NU64)(y_p1 & 4919131752989213764ULL);
	y3_1 = (NU64)(y_p1 & 9838263505978427528ULL);
	z0_1 = (NU64)((NU64)((NU64)((NU64)((NU64)(x0_1) * (NU64)(y0_1)) ^ (NU64)((NU64)(x1_1) * (NU64)(y3_1))) ^ (NU64)((NU64)(x2_1) * (NU64)(y2_1))) ^ (NU64)((NU64)(x3_1) * (NU64)(y1_1)));
	z1_1 = (NU64)((NU64)((NU64)((NU64)((NU64)(x0_1) * (NU64)(y1_1)) ^ (NU64)((NU64)(x1_1) * (NU64)(y0_1))) ^ (NU64)((NU64)(x2_1) * (NU64)(y3_1))) ^ (NU64)((NU64)(x3_1) * (NU64)(y2_1)));
	z2_1 = (NU64)((NU64)((NU64)((NU64)((NU64)(x0_1) * (NU64)(y2_1)) ^ (NU64)((NU64)(x1_1) * (NU64)(y1_1))) ^ (NU64)((NU64)(x2_1) * (NU64)(y0_1))) ^ (NU64)((NU64)(x3_1) * (NU64)(y3_1)));
	z3_1 = (NU64)((NU64)((NU64)((NU64)((NU64)(x0_1) * (NU64)(y3_1)) ^ (NU64)((NU64)(x1_1) * (NU64)(y2_1))) ^ (NU64)((NU64)(x2_1) * (NU64)(y1_1))) ^ (NU64)((NU64)(x3_1) * (NU64)(y0_1)));
	z0_1 = (NU64)(z0_1 & 1229782938247303441ULL);
	z1_1 = (NU64)(z1_1 & 2459565876494606882ULL);
	z2_1 = (NU64)(z2_1 & 4919131752989213764ULL);
	z3_1 = (NU64)(z3_1 & 9838263505978427528ULL);
	result = (NU64)((NU64)((NU64)(z0_1 | z1_1) | z2_1) | z3_1);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, ghash__pkgZnimcryptoZbcmode_u472)(NU8* y_p0, NI y_p0Len_0, NU8* h_p1, NI h_p1Len_0, NU8* data_p2, NI data_p2Len_0) {
	NU64 y0_1;
	NU64 y1_1;
	NU64 h0_1;
	NU64 h1_1;
	NU64 h2_1;
	NU64 h0r_1;
	NU64 h1r_1;
	NU64 h2r_1;
	NU64 pX60gensym13__1;
	NU64 pX60gensym15__1;
	NU64 pX60gensym17__1;
	NU64 pX60gensym19__1;
	NI length_1;
	NI offset_1;
	NU64 pX60gensym32__1;
	NU64 pX60gensym34__1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	y0_1 = (NU64)0;
	y1_1 = (NU64)0;
	h0_1 = (NU64)0;
	h1_1 = (NU64)0;
	h2_1 = (NU64)0;
	h0r_1 = (NU64)0;
	h1r_1 = (NU64)0;
	h2r_1 = (NU64)0;
	pX60gensym13__1 = (NU64)0;
	copyMem__system_u1755(((void*) ((&pX60gensym13__1))), ((void*) ((&y_p0[((NI)0)]))), ((NI)8));
	y1_1 = __builtin_bswap64(pX60gensym13__1);
	pX60gensym15__1 = (NU64)0;
	copyMem__system_u1755(((void*) ((&pX60gensym15__1))), ((void*) ((&y_p0[((NI)8)]))), ((NI)8));
	y0_1 = __builtin_bswap64(pX60gensym15__1);
	pX60gensym17__1 = (NU64)0;
	copyMem__system_u1755(((void*) ((&pX60gensym17__1))), ((void*) ((&h_p1[((NI)0)]))), ((NI)8));
	h1_1 = __builtin_bswap64(pX60gensym17__1);
	pX60gensym19__1 = (NU64)0;
	copyMem__system_u1755(((void*) ((&pX60gensym19__1))), ((void*) ((&h_p1[((NI)8)]))), ((NI)8));
	h0_1 = __builtin_bswap64(pX60gensym19__1);
	h0r_1 = rev64__pkgZnimcryptoZbcmode_u420(h0_1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	h1r_1 = rev64__pkgZnimcryptoZbcmode_u420(h1_1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	h2_1 = (NU64)(h0_1 ^ h1_1);
	h2r_1 = (NU64)(h0r_1 ^ h1r_1);
	length_1 = data_p2Len_0;
	offset_1 = ((NI)0);
	{
		while (1) {
			tyArray__dnD8kjh6rJ1Yy5jHvid0Ow tmp_1;
			NU64 y0r_1;
			NU64 y1r_1;
			NU64 y2_1;
			NU64 y2r_1;
			NU64 z0_1;
			NU64 z1_1;
			NU64 z2_1;
			NU64 z0h_1;
			NU64 z1h_1;
			NU64 z2h_1;
			NU64 v0_1;
			NU64 v1_1;
			NU64 v2_1;
			NU64 v3_1;
			NU64 T13_;
			NU64 T14_;
			NU64 T15_;
			if (!(((NI)0) < length_1)) goto LA2;
			nimZeroMem((void*)tmp_1, sizeof(tyArray__dnD8kjh6rJ1Yy5jHvid0Ow));
			y0r_1 = (NU64)0;
			y1r_1 = (NU64)0;
			y2_1 = (NU64)0;
			y2r_1 = (NU64)0;
			z0_1 = (NU64)0;
			z1_1 = (NU64)0;
			z2_1 = (NU64)0;
			z0h_1 = (NU64)0;
			z1h_1 = (NU64)0;
			z2h_1 = (NU64)0;
			v0_1 = (NU64)0;
			v1_1 = (NU64)0;
			v2_1 = (NU64)0;
			v3_1 = (NU64)0;
			{
				NU64 pX60gensym23__1;
				NU64 T7_;
				NU64 pX60gensym25__1;
				NU64 T8_;
				if (!(((NI)16) <= length_1)) goto LA5_;
				pX60gensym23__1 = (NU64)0;
				copyMem__system_u1755(((void*) ((&pX60gensym23__1))), ((void*) ((&data_p2[offset_1]))), ((NI)8));
				T7_ = (NU64)0;
				T7_ = __builtin_bswap64(pX60gensym23__1);
				y1_1 = (NU64)(y1_1 ^ T7_);
				pX60gensym25__1 = (NU64)0;
				copyMem__system_u1755(((void*) ((&pX60gensym25__1))), ((void*) ((&data_p2[(NI)(offset_1 + ((NI)8))]))), ((NI)8));
				T8_ = (NU64)0;
				T8_ = __builtin_bswap64(pX60gensym25__1);
				y0_1 = (NU64)(y0_1 ^ T8_);
				length_1 -= ((NI)16);
				offset_1 += ((NI)16);
			}
			goto LA3_;
LA5_: ;
			{
				tyObject_HSlice__RmqVCB5rHyE9cs59bZ8FgkPA T10_;
				NU64 pX60gensym28__1;
				NU64 T11_;
				NU64 pX60gensym30__1;
				NU64 T12_;
				T10_ = dotdot___stdZstrbasics_u48(((NI)0), (NI)(length_1 - ((NI)1)));
				X5BX5Deq___pkgZnimcryptoZbcmode_u762(tmp_1, T10_, (NU8*)(data_p2)+(offset_1), ((NI)((NI)(offset_1 + length_1) - ((NI)1)))-(offset_1)+1);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				pX60gensym28__1 = (NU64)0;
				copyMem__system_u1755(((void*) ((&pX60gensym28__1))), ((void*) ((&tmp_1[(((NI)0))- 0]))), ((NI)8));
				T11_ = (NU64)0;
				T11_ = __builtin_bswap64(pX60gensym28__1);
				y1_1 = (NU64)(y1_1 ^ T11_);
				pX60gensym30__1 = (NU64)0;
				copyMem__system_u1755(((void*) ((&pX60gensym30__1))), ((void*) ((&tmp_1[(((NI)8))- 0]))), ((NI)8));
				T12_ = (NU64)0;
				T12_ = __builtin_bswap64(pX60gensym30__1);
				y0_1 = (NU64)(y0_1 ^ T12_);
				length_1 = ((NI)0);
			}
LA3_: ;
			y0r_1 = rev64__pkgZnimcryptoZbcmode_u420(y0_1);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			y1r_1 = rev64__pkgZnimcryptoZbcmode_u420(y1_1);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			y2_1 = (NU64)(y0_1 ^ y1_1);
			y2r_1 = (NU64)(y0r_1 ^ y1r_1);
			z0_1 = bmul64__pkgZnimcryptoZbcmode_u400(y0_1, h0_1);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			z1_1 = bmul64__pkgZnimcryptoZbcmode_u400(y1_1, h1_1);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			z2_1 = bmul64__pkgZnimcryptoZbcmode_u400(y2_1, h2_1);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			z0h_1 = bmul64__pkgZnimcryptoZbcmode_u400(y0r_1, h0r_1);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			z1h_1 = bmul64__pkgZnimcryptoZbcmode_u400(y1r_1, h1r_1);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			z2h_1 = bmul64__pkgZnimcryptoZbcmode_u400(y2r_1, h2r_1);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			z2_1 = (NU64)(z2_1 ^ (NU64)(z0_1 ^ z1_1));
			z2h_1 = (NU64)(z2h_1 ^ (NU64)(z0h_1 ^ z1h_1));
			T13_ = (NU64)0;
			T13_ = rev64__pkgZnimcryptoZbcmode_u420(z0h_1);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			z0h_1 = (NU64)((NU64)(T13_) >> (NU64)(((NI)1) & (64 - 1)));
			T14_ = (NU64)0;
			T14_ = rev64__pkgZnimcryptoZbcmode_u420(z1h_1);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			z1h_1 = (NU64)((NU64)(T14_) >> (NU64)(((NI)1) & (64 - 1)));
			T15_ = (NU64)0;
			T15_ = rev64__pkgZnimcryptoZbcmode_u420(z2h_1);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			z2h_1 = (NU64)((NU64)(T15_) >> (NU64)(((NI)1) & (64 - 1)));
			v0_1 = z0_1;
			v1_1 = (NU64)(z0h_1 ^ z2_1);
			v2_1 = (NU64)(z1_1 ^ z2h_1);
			v3_1 = z1h_1;
			v3_1 = (NU64)((NU64)((NU64)(v3_1) << (NU64)(((NI)1) & (64 - 1))) | (NU64)((NU64)(v2_1) >> (NU64)(((NI)63) & (64 - 1))));
			v2_1 = (NU64)((NU64)((NU64)(v2_1) << (NU64)(((NI)1) & (64 - 1))) | (NU64)((NU64)(v1_1) >> (NU64)(((NI)63) & (64 - 1))));
			v1_1 = (NU64)((NU64)((NU64)(v1_1) << (NU64)(((NI)1) & (64 - 1))) | (NU64)((NU64)(v0_1) >> (NU64)(((NI)63) & (64 - 1))));
			v0_1 = (NU64)((NU64)(v0_1) << (NU64)(((NI)1) & (64 - 1)));
			v2_1 = (NU64)(v2_1 ^ (NU64)((NU64)((NU64)(v0_1 ^ (NU64)((NU64)(v0_1) >> (NU64)(((NI)1) & (64 - 1)))) ^ (NU64)((NU64)(v0_1) >> (NU64)(((NI)2) & (64 - 1)))) ^ (NU64)((NU64)(v0_1) >> (NU64)(((NI)7) & (64 - 1)))));
			v1_1 = (NU64)(v1_1 ^ (NU64)((NU64)((NU64)((NU64)(v0_1) << (NU64)(((NI)63) & (64 - 1))) ^ (NU64)((NU64)(v0_1) << (NU64)(((NI)62) & (64 - 1)))) ^ (NU64)((NU64)(v0_1) << (NU64)(((NI)57) & (64 - 1)))));
			v3_1 = (NU64)(v3_1 ^ (NU64)((NU64)((NU64)(v1_1 ^ (NU64)((NU64)(v1_1) >> (NU64)(((NI)1) & (64 - 1)))) ^ (NU64)((NU64)(v1_1) >> (NU64)(((NI)2) & (64 - 1)))) ^ (NU64)((NU64)(v1_1) >> (NU64)(((NI)7) & (64 - 1)))));
			v2_1 = (NU64)(v2_1 ^ (NU64)((NU64)((NU64)((NU64)(v1_1) << (NU64)(((NI)63) & (64 - 1))) ^ (NU64)((NU64)(v1_1) << (NU64)(((NI)62) & (64 - 1)))) ^ (NU64)((NU64)(v1_1) << (NU64)(((NI)57) & (64 - 1)))));
			y0_1 = v2_1;
			y1_1 = v3_1;
		} LA2: ;
	}
	pX60gensym32__1 = __builtin_bswap64(y1_1);
	copyMem__system_u1755(((void*) ((&y_p0[((NI)0)]))), ((void*) ((&pX60gensym32__1))), ((NI)8));
	pX60gensym34__1 = __builtin_bswap64(y0_1);
	copyMem__system_u1755(((void*) ((&y_p0[((NI)8)]))), ((void*) ((&pX60gensym34__1))), ((NI)8));
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, init__crypto_u107)(tyObject_GCM__eCD3Vqnb9c9cdir9bofS9aCo9aA* ctx_p0, NU8* key_p1, NI key_p1Len_0, NU8* iv_p2, NI iv_p2Len_0, NU8* aad_p3, NI aad_p3Len_0) {
	tyObject_RijndaelContext__NKUvxdvWF0pP2HEDIjikiQ T9_;
	tyObject_RijndaelContext__NKUvxdvWF0pP2HEDIjikiQ T16_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	{
		if (!!((((NI)16) == ((NI)16)))) goto LA3_;
		failedAssertImpl__stdZassertions_u95(TM__40YfnbOcmramUFyaunCxCg_3);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA3_: ;
	{
		if (!!((((NI)32) <= key_p1Len_0))) goto LA7_;
		failedAssertImpl__stdZassertions_u95(TM__40YfnbOcmramUFyaunCxCg_5);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA7_: ;
	burnMem__crypto_u130(ctx_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	init__crypto_u200((&(*ctx_p0).cipher), key_p1, key_p1Len_0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T9_ = (*ctx_p0).cipher;
	encrypt__crypto_u614((&T9_), (*ctx_p0).h, 16, (*ctx_p0).h, 16);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		tyObject_HSlice__RmqVCB5rHyE9cs59bZ8FgkPA T14_;
		if (!(iv_p2Len_0 == ((NI)12))) goto LA12_;
		T14_ = dotdot___stdZstrbasics_u48(((NI)0), ((NI)11));
		X5BX5Deq___pkgZnimcryptoZbcmode_u762((*ctx_p0).y, T14_, (NU8*)(iv_p2)+(((NI)0)), (((NI)11))-(((NI)0))+1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		inc128__pkgZnimcryptoZbcmode_u178((*ctx_p0).y, 16);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	goto LA10_;
LA12_: ;
	{
		tyArray__dnD8kjh6rJ1Yy5jHvid0Ow tmp_1;
		NU32 pX60gensym49__1;
		nimZeroMem((void*)tmp_1, sizeof(tyArray__dnD8kjh6rJ1Yy5jHvid0Ow));
		ghash__pkgZnimcryptoZbcmode_u472((*ctx_p0).y, 16, (*ctx_p0).h, 16, iv_p2, iv_p2Len_0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		pX60gensym49__1 = __builtin_bswap32(((NU32) ((NI)((NU64)(iv_p2Len_0) << (NU64)(((NI)3) & (64 - 1))))));
		copyMem__system_u1755(((void*) ((&tmp_1[(((NI)12))- 0]))), ((void*) ((&pX60gensym49__1))), ((NI)4));
		ghash__pkgZnimcryptoZbcmode_u472((*ctx_p0).y, 16, (*ctx_p0).h, 16, (NU8*)((tmp_1)+(((NI)0))), (((NI)15))-(((NI)0))+1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA10_: ;
	T16_ = (*ctx_p0).cipher;
	encrypt__crypto_u614((&T16_), (*ctx_p0).y, 16, (*ctx_p0).basectr, 16);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	(*ctx_p0).aadlen = ((NU64) (aad_p3Len_0));
	(*ctx_p0).datalen = 0ULL;
	{
		if (!(((NI)0) < aad_p3Len_0)) goto LA19_;
		ghash__pkgZnimcryptoZbcmode_u472((*ctx_p0).buf, 16, (*ctx_p0).h, 16, aad_p3, aad_p3Len_0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA19_: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, decrypt__crypto_u1953)(tyObject_GCM__eCD3Vqnb9c9cdir9bofS9aCo9aA* ctx_p0, NU8* input_p1, NI input_p1Len_0, NU8* output_p2, NI output_p2Len_0) {
	tyArray__dnD8kjh6rJ1Yy5jHvid0Ow ectr_1;
	NI length_1;
	NI offset_1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	{
		if (!!((input_p1Len_0 <= output_p2Len_0))) goto LA3_;
		failedAssertImpl__stdZassertions_u95(TM__40YfnbOcmramUFyaunCxCg_7);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA3_: ;
	nimZeroMem((void*)ectr_1, sizeof(tyArray__dnD8kjh6rJ1Yy5jHvid0Ow));
	length_1 = input_p1Len_0;
	offset_1 = ((NI)0);
	{
		while (1) {
			NI colontmpD_;
			NI colontmpD__2;
			NI uselen_1;
			if (!(((NI)0) < length_1)) goto LA6;
			colontmpD_ = (NI)0;
			colontmpD__2 = (NI)0;
			{
				if (!((NI)(((NI) ((*ctx_p0).coffset)) + length_1) < ((NI)16))) goto LA9_;
				colontmpD_ = length_1;
				uselen_1 = colontmpD_;
			}
			goto LA7_;
LA9_: ;
			{
				colontmpD__2 = (NI)(((NI)16) - ((NI) ((*ctx_p0).coffset)));
				uselen_1 = colontmpD__2;
			}
LA7_: ;
			{
				if (!((*ctx_p0).coffset == ((NU8)0))) goto LA14_;
				inc128__pkgZnimcryptoZbcmode_u178((*ctx_p0).y, 16);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			}
LA14_: ;
			encrypt__crypto_u614((&(*ctx_p0).cipher), (*ctx_p0).y, 16, ectr_1, 16);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			{
				NI i_1;
				NI i_2;
				i_1 = (NI)0;
				i_2 = ((NI)0);
				{
					while (1) {
						NU8 ch_1;
						if (!(i_2 < uselen_1)) goto LA18;
						i_1 = i_2;
						ch_1 = (NU8)(ectr_1[((NI)(((NI) ((*ctx_p0).coffset)) + i_1))- 0] ^ input_p1[(NI)(offset_1 + i_1)]);
						output_p2[(NI)(offset_1 + i_1)] = ch_1;
						(*ctx_p0).hbuf[((NI)(((NI) ((*ctx_p0).coffset)) + i_1))- 0] = input_p1[(NI)(offset_1 + i_1)];
						i_2 += ((NI)1);
					} LA18: ;
				}
			}
			length_1 -= uselen_1;
			offset_1 += uselen_1;
			(*ctx_p0).coffset = (NU8)((NU8)((NU8)((*ctx_p0).coffset) + (NU8)(((NU8) (uselen_1)))) & ((NU8)15));
			{
				if (!((*ctx_p0).coffset == ((NU8)0))) goto LA21_;
				ghash__pkgZnimcryptoZbcmode_u472((*ctx_p0).buf, 16, (*ctx_p0).h, 16, (NU8*)(((*ctx_p0).hbuf)+(((NI)0))), (((NI)15))-(((NI)0))+1);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			}
LA21_: ;
		} LA6: ;
	}
	(*ctx_p0).datalen += ((NU64) (input_p1Len_0));
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, getTag__crypto_u1429)(tyObject_GCM__eCD3Vqnb9c9cdir9bofS9aCo9aA* ctx_p0, NU8* tag_p1, NI tag_p1Len_0) {
	NI colontmpD_;
	NI colontmpD__2;
	tyArray__dnD8kjh6rJ1Yy5jHvid0Ow workbuf_1;
	NI taglen_1;
	NI uselen_1;
	NU64 pX60gensym55__1;
	NU64 pX60gensym57__1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	colontmpD_ = (NI)0;
	colontmpD__2 = (NI)0;
	nimZeroMem((void*)workbuf_1, sizeof(tyArray__dnD8kjh6rJ1Yy5jHvid0Ow));
	taglen_1 = tag_p1Len_0;
	{
		if (!(taglen_1 < ((NI)16))) goto LA3_;
		colontmpD_ = taglen_1;
		uselen_1 = colontmpD_;
	}
	goto LA1_;
LA3_: ;
	{
		colontmpD__2 = ((NI)16);
		uselen_1 = colontmpD__2;
	}
LA1_: ;
	{
		if (!!(((*ctx_p0).coffset == ((NU8)0)))) goto LA8_;
		ghash__pkgZnimcryptoZbcmode_u472((*ctx_p0).buf, 16, (*ctx_p0).h, 16, (NU8*)(((*ctx_p0).hbuf)+(((NI)0))), ((NI)(((NI) ((*ctx_p0).coffset)) - ((NI)1)))-(((NI)0))+1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA8_: ;
	{
		if (!(((NI)0) < taglen_1)) goto LA12_;
		copyMem__system_u1755(((void*) ((&tag_p1[((NI)0)]))), ((void*) ((&(*ctx_p0).basectr[(((NI)0))- 0]))), ((NI)(uselen_1 * ((NI)1))));
	}
LA12_: ;
	pX60gensym55__1 = __builtin_bswap64((NU64)((NU64)((*ctx_p0).aadlen) << (NU64)(((NI)3) & (64 - 1))));
	copyMem__system_u1755(((void*) ((&workbuf_1[(((NI)0))- 0]))), ((void*) ((&pX60gensym55__1))), ((NI)8));
	pX60gensym57__1 = __builtin_bswap64((NU64)((NU64)((*ctx_p0).datalen) << (NU64)(((NI)3) & (64 - 1))));
	copyMem__system_u1755(((void*) ((&workbuf_1[(((NI)8))- 0]))), ((void*) ((&pX60gensym57__1))), ((NI)8));
	ghash__pkgZnimcryptoZbcmode_u472((*ctx_p0).buf, 16, (*ctx_p0).h, 16, workbuf_1, 16);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		NI i_1;
		NI i_2;
		i_1 = (NI)0;
		i_2 = ((NI)0);
		{
			while (1) {
				if (!(i_2 < uselen_1)) goto LA16;
				i_1 = i_2;
				tag_p1[i_1] = (NU8)(tag_p1[i_1] ^ (*ctx_p0).buf[(i_1)- 0]);
				i_2 += ((NI)1);
			} LA16: ;
		}
	}
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, getTag__crypto_u1407)(tyObject_GCM__eCD3Vqnb9c9cdir9bofS9aCo9aA* ctx_p0, tyArray__dnD8kjh6rJ1Yy5jHvid0Ow Result) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	getTag__crypto_u1429(ctx_p0, Result, 16);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, encrypt__crypto_u1281)(tyObject_GCM__eCD3Vqnb9c9cdir9bofS9aCo9aA* ctx_p0, NU8* input_p1, NI input_p1Len_0, NU8* output_p2, NI output_p2Len_0) {
	tyArray__dnD8kjh6rJ1Yy5jHvid0Ow ectr_1;
	NI length_1;
	NI offset_1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	{
		if (!!((input_p1Len_0 <= output_p2Len_0))) goto LA3_;
		failedAssertImpl__stdZassertions_u95(TM__40YfnbOcmramUFyaunCxCg_9);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA3_: ;
	nimZeroMem((void*)ectr_1, sizeof(tyArray__dnD8kjh6rJ1Yy5jHvid0Ow));
	length_1 = input_p1Len_0;
	offset_1 = ((NI)0);
	{
		while (1) {
			NI colontmpD_;
			NI colontmpD__2;
			NI uselen_1;
			if (!(((NI)0) < length_1)) goto LA6;
			colontmpD_ = (NI)0;
			colontmpD__2 = (NI)0;
			{
				if (!((NI)(((NI) ((*ctx_p0).coffset)) + length_1) < ((NI)16))) goto LA9_;
				colontmpD_ = length_1;
				uselen_1 = colontmpD_;
			}
			goto LA7_;
LA9_: ;
			{
				colontmpD__2 = (NI)(((NI)16) - ((NI) ((*ctx_p0).coffset)));
				uselen_1 = colontmpD__2;
			}
LA7_: ;
			{
				if (!((*ctx_p0).coffset == ((NU8)0))) goto LA14_;
				inc128__pkgZnimcryptoZbcmode_u178((*ctx_p0).y, 16);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			}
LA14_: ;
			encrypt__crypto_u614((&(*ctx_p0).cipher), (*ctx_p0).y, 16, ectr_1, 16);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			{
				NI i_1;
				NI i_2;
				i_1 = (NI)0;
				i_2 = ((NI)0);
				{
					while (1) {
						NU8 ch_1;
						if (!(i_2 < uselen_1)) goto LA18;
						i_1 = i_2;
						ch_1 = (NU8)(ectr_1[((NI)(((NI) ((*ctx_p0).coffset)) + i_1))- 0] ^ input_p1[(NI)(offset_1 + i_1)]);
						output_p2[(NI)(offset_1 + i_1)] = ch_1;
						(*ctx_p0).hbuf[((NI)(((NI) ((*ctx_p0).coffset)) + i_1))- 0] = ch_1;
						i_2 += ((NI)1);
					} LA18: ;
				}
			}
			length_1 -= uselen_1;
			offset_1 += uselen_1;
			(*ctx_p0).coffset = (NU8)((NU8)((NU8)((*ctx_p0).coffset) + (NU8)(((NU8) (uselen_1)))) & ((NU8)15));
			{
				if (!((*ctx_p0).coffset == ((NU8)0))) goto LA21_;
				ghash__pkgZnimcryptoZbcmode_u472((*ctx_p0).buf, 16, (*ctx_p0).h, 16, (NU8*)(((*ctx_p0).hbuf)+(((NI)0))), (((NI)15))-(((NI)0))+1);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			}
LA21_: ;
		} LA6: ;
	}
	(*ctx_p0).datalen += ((NU64) (input_p1Len_0));
	}BeforeRet_: ;
}
