/* Generated by Nim Compiler v2.2.10 */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   x86_64-w64-mingw32-gcc -c -w -fmax-errors=3 -mno-ms-bitfields -fno-strict-aliasing -DWIN32_LEAN_AND_MEAN -Os -fno-ident   -I/home/kali/.choosenim/toolchains/nim-2.2.10/lib -I/home/kali/c2/agents/agent-nim -o /home/kali/c2/agents/agent-nim/nimcache_nim5min/@nwinim-3.9.4-4b7c430159be2e8b2dc4b663a9b19f7678b58f87@swinim@swinstr.nim.c.o /home/kali/c2/agents/agent-nim/nimcache_nim5min/@nwinim-3.9.4-4b7c430159be2e8b2dc4b663a9b19f7678b58f87@swinim@swinstr.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tyObject_Deque__OlSyibmU0p3M8SLisjCZsg tyObject_Deque__OlSyibmU0p3M8SLisjCZsg;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ tySequence__sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content;
typedef struct tyObject_WideCStringObj__jQbOKocsbu7Z9bKTSFtX4TQ tyObject_WideCStringObj__jQbOKocsbu7Z9bKTSFtX4TQ;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ {
  NI len; tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content* p;
};
struct tyObject_Deque__OlSyibmU0p3M8SLisjCZsg {
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ data;
	NU head;
	NU tail;
};
struct tyObject_WideCStringObj__jQbOKocsbu7Z9bKTSFtX4TQ {
	NI bytes;
	NI16* data;
};
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content { NI cap; NimStringV2 data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE NIM_THREADVAR tyObject_Deque__OlSyibmU0p3M8SLisjCZsg wstringQueue__pkgZwinimZwinstr_u834;
N_LIB_PRIVATE NIM_THREADVAR NIM_BOOL isOpenArrayStringable__pkgZwinimZwinstr_u669;
N_LIB_PRIVATE NIM_THREADVAR NIM_BOOL wstringQueueInit__pkgZwinimZwinstr_u835;
N_LIB_PRIVATE N_NIMCALL(NU16*, winstrConverterWideCStringToLPWSTR__pkgZwinimZwinstr_u807)(tyObject_WideCStringObj__jQbOKocsbu7Z9bKTSFtX4TQ x_p0) {
	NU16* result;
	result = ((NU16*) ((&x_p0.data[((NI)0)])));
	return result;
}
