/* Generated by Nim Compiler v2.2.10 */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   x86_64-w64-mingw32-gcc -c -w -fmax-errors=3 -mno-ms-bitfields -fno-strict-aliasing -DWIN32_LEAN_AND_MEAN -Os -fno-ident   -I/home/kali/.choosenim/toolchains/nim-2.2.10/lib -I/home/kali/c2/agents/agent-nim -o /home/kali/c2/agents/agent-nim/nimcache_nim5min/@ptables.nim.c.o /home/kali/c2/agents/agent-nim/nimcache_nim5min/@ptables.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tyObject_OrderedTable__alibvEreYoDQX0zEzfTleQ tyObject_OrderedTable__alibvEreYoDQX0zEzfTleQ;
typedef struct tySequence__xUV33m0d5HZLvMGUKDBm7Q tySequence__xUV33m0d5HZLvMGUKDBm7Q;
typedef struct tySequence__xUV33m0d5HZLvMGUKDBm7Q_Content tySequence__xUV33m0d5HZLvMGUKDBm7Q_Content;
typedef struct tyTuple__s8qsQCcBOMNS7M9aFeWibtQ tyTuple__s8qsQCcBOMNS7M9aFeWibtQ;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_JsonNodeObj__HuNCd9cjVf1RGJ8WXqZvVog tyObject_JsonNodeObj__HuNCd9cjVf1RGJ8WXqZvVog;
typedef struct tyObject_RefHeader__sqhyc4FSbGmPtkvXRNl9acg tyObject_RefHeader__sqhyc4FSbGmPtkvXRNl9acg;
typedef struct tySequence__YWxjq9aB9anxKHaOq65jIGKw tySequence__YWxjq9aB9anxKHaOq65jIGKw;
typedef struct tySequence__YWxjq9aB9anxKHaOq65jIGKw_Content tySequence__YWxjq9aB9anxKHaOq65jIGKw_Content;
typedef struct tyObject_NimRawSeq__2kUMFDNh0hpLnOTOSL0tSA tyObject_NimRawSeq__2kUMFDNh0hpLnOTOSL0tSA;
typedef struct tyObject_KeyError__WyMCFOyjoQlpL9bXWFR7E6w tyObject_KeyError__WyMCFOyjoQlpL9bXWFR7E6w;
typedef struct tyObject_ValueError__NZcE89crkraWmH1VkcjYX9ag tyObject_ValueError__NZcE89crkraWmH1VkcjYX9ag;
typedef struct tyObject_CatchableError__kvV4Jp5z2ULaSZq53myi9ag tyObject_CatchableError__kvV4Jp5z2ULaSZq53myi9ag;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tySequence__UIJx6FJrflnhA9a3u1VF1vA tySequence__UIJx6FJrflnhA9a3u1VF1vA;
typedef struct tySequence__UIJx6FJrflnhA9a3u1VF1vA_Content tySequence__UIJx6FJrflnhA9a3u1VF1vA_Content;
typedef struct tyObject_StackTraceEntry__UznwMnjUHK6AxZHnP9bMXEA tyObject_StackTraceEntry__UznwMnjUHK6AxZHnP9bMXEA;
struct tySequence__xUV33m0d5HZLvMGUKDBm7Q {
  NI len; tySequence__xUV33m0d5HZLvMGUKDBm7Q_Content* p;
};
struct tyObject_OrderedTable__alibvEreYoDQX0zEzfTleQ {
	tySequence__xUV33m0d5HZLvMGUKDBm7Q data;
	NI counter;
	NI first;
	NI last;
};
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tyTuple__s8qsQCcBOMNS7M9aFeWibtQ {
	NI Field0;
	NI Field1;
	NimStringV2 Field2;
	tyObject_JsonNodeObj__HuNCd9cjVf1RGJ8WXqZvVog* Field3;
};
struct tyObject_RefHeader__sqhyc4FSbGmPtkvXRNl9acg {
	NI rc;
	NI rootIdx;
};
typedef NU8 tyEnum_JsonNodeKind__AgEdEY3Szs9c2LYpGqyQ2lA;
struct tySequence__YWxjq9aB9anxKHaOq65jIGKw {
  NI len; tySequence__YWxjq9aB9anxKHaOq65jIGKw_Content* p;
};
struct tyObject_JsonNodeObj__HuNCd9cjVf1RGJ8WXqZvVog {
	NIM_BOOL isUnquoted;
	tyEnum_JsonNodeKind__AgEdEY3Szs9c2LYpGqyQ2lA kind;
union{
	struct {
	NimStringV2 str;
} _kind_1;
	struct {
	NI64 num;
} _kind_2;
	struct {
	NF fnum;
} _kind_3;
	struct {
	NIM_BOOL bval;
} _kind_4;
	struct {
	tyObject_OrderedTable__alibvEreYoDQX0zEzfTleQ fields;
} _kind_6;
	struct {
	tySequence__YWxjq9aB9anxKHaOq65jIGKw elems;
} _kind_7;
};
};
struct tyObject_NimRawSeq__2kUMFDNh0hpLnOTOSL0tSA {
	NI len;
	void* p;
};
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct RootObj {
	TNimTypeV2* m_type;
};
struct tySequence__UIJx6FJrflnhA9a3u1VF1vA {
  NI len; tySequence__UIJx6FJrflnhA9a3u1VF1vA_Content* p;
};
struct Exception {
	RootObj Sup;
	Exception* parent;
	NCSTRING name;
	NimStringV2 message;
	tySequence__UIJx6FJrflnhA9a3u1VF1vA trace;
	Exception* up;
};
struct tyObject_CatchableError__kvV4Jp5z2ULaSZq53myi9ag {
	Exception Sup;
};
struct tyObject_ValueError__NZcE89crkraWmH1VkcjYX9ag {
	tyObject_CatchableError__kvV4Jp5z2ULaSZq53myi9ag Sup;
};
struct tyObject_KeyError__WyMCFOyjoQlpL9bXWFR7E6w {
	tyObject_ValueError__NZcE89crkraWmH1VkcjYX9ag Sup;
};
struct tySequence__xUV33m0d5HZLvMGUKDBm7Q_Content { NI cap; tyTuple__s8qsQCcBOMNS7M9aFeWibtQ data[SEQ_DECL_SIZE]; };
struct tySequence__YWxjq9aB9anxKHaOq65jIGKw_Content { NI cap; tyObject_JsonNodeObj__HuNCd9cjVf1RGJ8WXqZvVog* data[SEQ_DECL_SIZE]; };
struct tyObject_StackTraceEntry__UznwMnjUHK6AxZHnP9bMXEA {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};
struct tySequence__UIJx6FJrflnhA9a3u1VF1vA_Content { NI cap; tyObject_StackTraceEntry__UznwMnjUHK6AxZHnP9bMXEA data[SEQ_DECL_SIZE]; };
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__system_u2188)(void* a_p0, int v_p1, NI size_p2);
static N_INLINE(NI, slotsNeeded__pureZcollectionsZtables_u42)(NI count_p0);
N_LIB_PRIVATE N_NIMCALL(NI, nextPowerOfTwo__pureZmath_u245)(NI x_p0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, newSeq__pureZjson_u468)(tySequence__xUV33m0d5HZLvMGUKDBm7Q* s_p0, NI len_p1);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
static N_INLINE(NIM_BOOL, nimDecRefIsLastDyn)(void* p_p0);
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1);
N_LIB_PRIVATE N_NIMCALL(void, unregisterCycle__system_u3152)(tyObject_RefHeader__sqhyc4FSbGmPtkvXRNl9acg* s_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZjson_u67)(tyObject_JsonNodeObj__HuNCd9cjVf1RGJ8WXqZvVog* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimRawDispose)(void* p_p0, NI alignment_p1);
N_LIB_PRIVATE N_NIMCALL(void, alignedDealloc)(void* p_p0, NI align_p1);
N_LIB_PRIVATE N_NIMCALL(NI, rawGet__pureZjson_u805)(tyObject_OrderedTable__alibvEreYoDQX0zEzfTleQ* t_p0, NimStringV2 key_p1, NI* hc_p2);
N_LIB_PRIVATE N_NIMCALL(NI, hash__pureZhashes_u586)(NimStringV2 x_p0);
static N_INLINE(NIM_BOOL, isFilled__pureZcollectionsZtables_u31)(NI hcode_p0);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringV2 a_p0, NimStringV2 b_p1);
static N_INLINE(NIM_BOOL, equalMem__system_u1763)(void* a_p0, void* b_p1, NI size_p2);
static N_INLINE(int, nimCmpMem)(void* a_p0, void* b_p1, NI size_p2);
static N_INLINE(NI, nextTry__pureZcollectionsZtables_u34)(NI h_p0, NI maxHash_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___pureZjson_u330)(tyObject_JsonNodeObj__HuNCd9cjVf1RGJ8WXqZvVog** dest_p0, tyObject_JsonNodeObj__HuNCd9cjVf1RGJ8WXqZvVog* src_p1);
static N_INLINE(NIM_BOOL, mustRehash__pureZjson_u1133)(tyObject_OrderedTable__alibvEreYoDQX0zEzfTleQ* t_p0);
N_LIB_PRIVATE N_NIMCALL(void, enlarge__pureZjson_u1282)(tyObject_OrderedTable__alibvEreYoDQX0zEzfTleQ* t_p0);
N_LIB_PRIVATE N_NIMCALL(void, rawInsert__pureZjson_u1665)(tyObject_OrderedTable__alibvEreYoDQX0zEzfTleQ* t_p0, tySequence__xUV33m0d5HZLvMGUKDBm7Q* data_p1, NimStringV2 key_p2, tyObject_JsonNodeObj__HuNCd9cjVf1RGJ8WXqZvVog* val_p3, NI hc_p4, NI h_p5);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___system_u2723)(NimStringV2* dest_p0, NimStringV2 src_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___system_u2720)(NimStringV2* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___pureZjson_u318)(tyObject_JsonNodeObj__HuNCd9cjVf1RGJ8WXqZvVog** dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZjson_u91)(tySequence__xUV33m0d5HZLvMGUKDBm7Q dest_p0);
N_LIB_PRIVATE N_NIMCALL(NI, rawGetKnownHC__pureZjson_u1927)(tyObject_OrderedTable__alibvEreYoDQX0zEzfTleQ* t_p0, NimStringV2 key_p1, NI hc_p2);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___pureZjson_u94)(tySequence__xUV33m0d5HZLvMGUKDBm7Q* dest_p0, tySequence__xUV33m0d5HZLvMGUKDBm7Q src_p1);
static N_INLINE(NIM_BOOL, sameSeqPayload)(void* x_p0, void* y_p1);
N_LIB_PRIVATE N_NIMCALL(void, setLen__pureZjson_u113)(tySequence__xUV33m0d5HZLvMGUKDBm7Q* s_p0, NI newlen_p1);
static N_INLINE(void, nimIncRef)(void* p_p0);
static N_INLINE(NI, pluspercent___system_u793)(NI x_p0, NI y_p1);
static N_INLINE(NI, rawGet__pureZjson_u3095)(tyObject_OrderedTable__alibvEreYoDQX0zEzfTleQ* t_p0, NimStringV2 key_p1, NI* hc_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseKeyError__pureZjson_u3352)(NimStringV2 key_p0);
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObj)(NI size_p0, NI alignment_p1);
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(void, copyMem__system_u1755)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, rawNewString)(NI space_p0);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e_p0, NCSTRING ename_p1, NCSTRING procname_p2, NCSTRING filename_p3, NI line_p4);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___pureZjson_u324)(tyObject_JsonNodeObj__HuNCd9cjVf1RGJ8WXqZvVog** dest_p0, tyObject_JsonNodeObj__HuNCd9cjVf1RGJ8WXqZvVog* src_p1);
extern TNimTypeV2 NTIv2__WyMCFOyjoQlpL9bXWFR7E6w_;
static const struct {
  NI cap; NIM_CHAR data[15+1];
} TM__4SoG2KRQy3oMm9aUzSLtGrA_2 = { 15 | NIM_STRLIT_FLAG, "key not found: " };
static const NimStringV2 TM__4SoG2KRQy3oMm9aUzSLtGrA_3 = {15, (NimStrPayload*)&TM__4SoG2KRQy3oMm9aUzSLtGrA_2};
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4172;
static N_INLINE(void, nimSetMem__system_u2188)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
	nimSetMem__system_u2188(p_p0, ((int)0), size_p1);
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4172);
	return result;
}
static N_INLINE(NI, slotsNeeded__pureZcollectionsZtables_u42)(NI count_p0) {
	NI result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	result = nextPowerOfTwo__pureZmath_u245((NI)((NI)((NI)(count_p0 / ((NI)2)) + count_p0) + ((NI)4)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1) {
	NI result;
	result = ((NI) ((NU)((NU64)(((NU) (x_p0))) - (NU64)(((NU) (y_p1))))));
	return result;
}
static N_INLINE(NIM_BOOL, nimDecRefIsLastDyn)(void* p_p0) {
	NIM_BOOL result;
	result = NIM_FALSE;
	{
		tyObject_RefHeader__sqhyc4FSbGmPtkvXRNl9acg* cell_1;
		NI T5_;
		if (!!((p_p0 == NIM_NIL))) goto LA3_;
		T5_ = (NI)0;
		T5_ = minuspercent___system_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)16));
		cell_1 = ((tyObject_RefHeader__sqhyc4FSbGmPtkvXRNl9acg*) (T5_));
		{
			if (!((NI)((*cell_1).rc & ((NI)-16)) == ((NI)0))) goto LA8_;
			result = NIM_TRUE;
		}
		goto LA6_;
LA8_: ;
		{
			(*cell_1).rc = minuspercent___system_u813((*cell_1).rc, ((NI)16));
		}
LA6_: ;
		{
			if (!result) goto LA13_;
			{
				if (!(((NI)0) < (*cell_1).rootIdx)) goto LA17_;
				unregisterCycle__system_u3152(cell_1);
			}
LA17_: ;
		}
LA13_: ;
	}
LA3_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZjson_u91)(tySequence__xUV33m0d5HZLvMGUKDBm7Q dest_p0) {
	NI colontmp_;
	colontmp_ = ((NI)0);
	{
		while (1) {
			NI T3_;
			T3_ = dest_p0.len;
			if (!(colontmp_ < T3_)) goto LA2;
			if (dest_p0.p->data[colontmp_].Field2.p && !(dest_p0.p->data[colontmp_].Field2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(dest_p0.p->data[colontmp_].Field2.p);
}
			{
				NIM_BOOL T6_;
				T6_ = (NIM_BOOL)0;
				T6_ = nimDecRefIsLastDyn(dest_p0.p->data[colontmp_].Field3);
				if (!T6_) goto LA7_;
				eqdestroy___pureZjson_u67((&(*dest_p0.p->data[colontmp_].Field3)));
				nimRawDispose(dest_p0.p->data[colontmp_].Field3, ((NI)8));
			}
LA7_: ;
			colontmp_ += ((NI)1);
		} LA2: ;
	}
	if (dest_p0.p && !(dest_p0.p->cap & NIM_STRLIT_FLAG)) {
 alignedDealloc(dest_p0.p, NIM_ALIGNOF(tyTuple__s8qsQCcBOMNS7M9aFeWibtQ));
}
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZjson_u158)(tyTuple__s8qsQCcBOMNS7M9aFeWibtQ* dest_p0) {
	if ((*dest_p0).Field2.p && !((*dest_p0).Field2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Field2.p);
}
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastDyn((*dest_p0).Field3);
		if (!T3_) goto LA4_;
		eqdestroy___pureZjson_u67((&(*(*dest_p0).Field3)));
		nimRawDispose((*dest_p0).Field3, ((NI)8));
	}
LA4_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___pureZjson_u155)(tyTuple__s8qsQCcBOMNS7M9aFeWibtQ* dest_p0) {
	(*dest_p0).Field0 = 0;
	(*dest_p0).Field1 = 0;
	(*dest_p0).Field2.len = 0; (*dest_p0).Field2.p = NIM_NIL;
	(*dest_p0).Field3 = 0;
}
N_LIB_PRIVATE N_NIMCALL(void, initOrderedTable__pureZjson_u454)(NI initialSize_p0, tyObject_OrderedTable__alibvEreYoDQX0zEzfTleQ* Result) {
	NI correctSizeX60gensym0__1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)Result, sizeof(tyObject_OrderedTable__alibvEreYoDQX0zEzfTleQ));
	correctSizeX60gensym0__1 = slotsNeeded__pureZcollectionsZtables_u42((initialSize_p0));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	(*Result).counter = ((NI)0);
	newSeq__pureZjson_u468((&(*Result).data), (correctSizeX60gensym0__1));
	(*Result).first = ((NI)-1);
	(*Result).last = ((NI)-1);
	}BeforeRet_: ;
}
static N_INLINE(NIM_BOOL, isFilled__pureZcollectionsZtables_u31)(NI hcode_p0) {
	NIM_BOOL result;
	result = !((hcode_p0 == ((NI)0)));
	return result;
}
static N_INLINE(int, nimCmpMem)(void* a_p0, void* b_p1, NI size_p2) {
	int result;
	result = memcmp(a_p0, b_p1, ((size_t) (size_p2)));
	return result;
}
static N_INLINE(NIM_BOOL, equalMem__system_u1763)(void* a_p0, void* b_p1, NI size_p2) {
	NIM_BOOL result;
	int T1_;
	T1_ = (int)0;
	T1_ = nimCmpMem(a_p0, b_p1, size_p2);
	result = (T1_ == ((NI32)0));
	return result;
}
static N_INLINE(NIM_BOOL, eqStrings)(NimStringV2 a_p0, NimStringV2 b_p1) {
	NIM_BOOL result;
	NI alen_1;
	NI blen_1;
{	result = NIM_FALSE;
	alen_1 = a_p0.len;
	blen_1 = b_p1.len;
	{
		if (!(alen_1 == blen_1)) goto LA3_;
		{
			if (!(alen_1 == ((NI)0))) goto LA7_;
			result = NIM_TRUE;
			goto BeforeRet_;
		}
LA7_: ;
		result = equalMem__system_u1763(((void*) ((&a_p0.p->data[((NI)0)]))), ((void*) ((&b_p1.p->data[((NI)0)]))), (alen_1));
		goto BeforeRet_;
	}
LA3_: ;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NI, nextTry__pureZcollectionsZtables_u34)(NI h_p0, NI maxHash_p1) {
	NI result;
	result = (NI)((NI)(h_p0 + ((NI)1)) & maxHash_p1);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, rawGet__pureZjson_u805)(tyObject_OrderedTable__alibvEreYoDQX0zEzfTleQ* t_p0, NimStringV2 key_p1, NI* hc_p2) {
	NI result;
	NI T1_;
	NI h_1;
	NI T11_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	T1_ = (NI)0;
	T1_ = hash__pureZhashes_u586(key_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	(*hc_p2) = T1_;
	{
		if (!((*hc_p2) == ((NI)0))) goto LA4_;
		(*hc_p2) = ((NI)314159265);
	}
LA4_: ;
	{
		NI T8_;
		T8_ = (*t_p0).data.len;
		if (!(T8_ == ((NI)0))) goto LA9_;
		result = ((NI)-1);
		goto BeforeRet_;
	}
LA9_: ;
	T11_ = ((*t_p0).data.len-1);
	h_1 = (NI)((*hc_p2) & T11_);
	{
		while (1) {
			NIM_BOOL T14_;
			NI T21_;
			T14_ = (NIM_BOOL)0;
			T14_ = isFilled__pureZcollectionsZtables_u31((*t_p0).data.p->data[h_1].Field0);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (!T14_) goto LA13;
			{
				NIM_BOOL T17_;
				T17_ = (NIM_BOOL)0;
				T17_ = ((*t_p0).data.p->data[h_1].Field0 == (*hc_p2));
				if (!(T17_)) goto LA18_;
				T17_ = eqStrings((*t_p0).data.p->data[h_1].Field2, key_p1);
LA18_: ;
				if (!T17_) goto LA19_;
				result = h_1;
				goto BeforeRet_;
			}
LA19_: ;
			T21_ = ((*t_p0).data.len-1);
			h_1 = nextTry__pureZcollectionsZtables_u34(h_1, T21_);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		} LA13: ;
	}
	result = (NI)(((NI)-1) - h_1);
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NIM_BOOL, mustRehash__pureZjson_u1133)(tyObject_OrderedTable__alibvEreYoDQX0zEzfTleQ* t_p0) {
	NIM_BOOL result;
	NIM_BOOL T1_;
	NI T2_;
	NI T4_;
	T1_ = (NIM_BOOL)0;
	T2_ = (*t_p0).data.len;
	T1_ = (T2_ < (NI)((*t_p0).counter + (NI)((*t_p0).counter / ((NI)2))));
	if (T1_) goto LA3_;
	T4_ = (*t_p0).data.len;
	T1_ = ((NI)(T4_ - (*t_p0).counter) < ((NI)4));
LA3_: ;
	result = T1_;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, rawInsert__pureZjson_u1665)(tyObject_OrderedTable__alibvEreYoDQX0zEzfTleQ* t_p0, tySequence__xUV33m0d5HZLvMGUKDBm7Q* data_p1, NimStringV2 key_p2, tyObject_JsonNodeObj__HuNCd9cjVf1RGJ8WXqZvVog* val_p3, NI hc_p4, NI h_p5) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqcopy___system_u2723((&(*data_p1).p->data[h_p5].Field2), key_p2);
	eqsink___pureZjson_u330(&(*data_p1).p->data[h_p5].Field3, val_p3);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	(*data_p1).p->data[h_p5].Field0 = hc_p4;
	(*data_p1).p->data[h_p5].Field1 = ((NI)-1);
	{
		if (!((*t_p0).first < ((NI)0))) goto LA3_;
		(*t_p0).first = h_p5;
	}
LA3_: ;
	{
		if (!(((NI)0) <= (*t_p0).last)) goto LA7_;
		(*data_p1).p->data[(*t_p0).last].Field1 = h_p5;
	}
LA7_: ;
	(*t_p0).last = h_p5;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, enlarge__pureZjson_u1282)(tyObject_OrderedTable__alibvEreYoDQX0zEzfTleQ* t_p0) {
	tySequence__xUV33m0d5HZLvMGUKDBm7Q n_1;
	NI T1_;
	NI h_1;
	tySequence__xUV33m0d5HZLvMGUKDBm7Q T2_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	n_1.len = 0; n_1.p = NIM_NIL;
	T1_ = (*t_p0).data.len;
	newSeq__pureZjson_u468((&n_1), ((NI)(T1_ * ((NI)2))));
	h_1 = (*t_p0).first;
	(*t_p0).first = ((NI)-1);
	(*t_p0).last = ((NI)-1);
	T2_.len = 0; T2_.p = NIM_NIL;
	T2_ = (*t_p0).data;
	(*t_p0).data = n_1;
	n_1 = T2_;
	{
		while (1) {
			NI nxt_1;
			NI eh_1;
			if (!(((NI)0) <= h_1)) goto LA4;
			nxt_1 = n_1.p->data[h_1].Field1;
			eh_1 = n_1.p->data[h_1].Field0;
			{
				NIM_BOOL T7_;
				NimStringV2 colontmpD_;
				NI j_1;
				NI T10_;
				tyObject_OrderedTable__alibvEreYoDQX0zEzfTleQ* T15_;
				tyObject_JsonNodeObj__HuNCd9cjVf1RGJ8WXqZvVog* T16_;
				T7_ = (NIM_BOOL)0;
				T7_ = isFilled__pureZcollectionsZtables_u31(eh_1);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				if (!T7_) goto LA8_;
				colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
				T10_ = ((*t_p0).data.len-1);
				j_1 = (NI)(eh_1 & T10_);
				{
					while (1) {
						NIM_BOOL T13_;
						NI T14_;
						T13_ = (NIM_BOOL)0;
						T13_ = isFilled__pureZcollectionsZtables_u31((*t_p0).data.p->data[j_1].Field0);
						if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
						if (!T13_) goto LA12;
						T14_ = ((*t_p0).data.len-1);
						j_1 = nextTry__pureZcollectionsZtables_u34(j_1, T14_);
						if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					} LA12: ;
				}
				T15_ = (tyObject_OrderedTable__alibvEreYoDQX0zEzfTleQ*)0;
				T15_ = t_p0;
				colontmpD_ = n_1.p->data[h_1].Field2;
				eqwasMoved___system_u2720((&n_1.p->data[h_1].Field2));
				T16_ = NIM_NIL;
				T16_ = n_1.p->data[h_1].Field3;
				eqwasMoved___pureZjson_u318((&n_1.p->data[h_1].Field3));
				rawInsert__pureZjson_u1665(T15_, (&(*t_p0).data), colontmpD_, T16_, n_1.p->data[h_1].Field0, j_1);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
			}
LA8_: ;
			h_1 = nxt_1;
		} LA4: ;
	}
	eqdestroy___pureZjson_u91(n_1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(NI, rawGetKnownHC__pureZjson_u1927)(tyObject_OrderedTable__alibvEreYoDQX0zEzfTleQ* t_p0, NimStringV2 key_p1, NI hc_p2) {
	NI result;
	NI h_1;
	NI T6_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	{
		NI T3_;
		T3_ = (*t_p0).data.len;
		if (!(T3_ == ((NI)0))) goto LA4_;
		result = ((NI)-1);
		goto BeforeRet_;
	}
LA4_: ;
	T6_ = ((*t_p0).data.len-1);
	h_1 = (NI)(hc_p2 & T6_);
	{
		while (1) {
			NIM_BOOL T9_;
			NI T16_;
			T9_ = (NIM_BOOL)0;
			T9_ = isFilled__pureZcollectionsZtables_u31((*t_p0).data.p->data[h_1].Field0);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (!T9_) goto LA8;
			{
				NIM_BOOL T12_;
				T12_ = (NIM_BOOL)0;
				T12_ = ((*t_p0).data.p->data[h_1].Field0 == hc_p2);
				if (!(T12_)) goto LA13_;
				T12_ = eqStrings((*t_p0).data.p->data[h_1].Field2, key_p1);
LA13_: ;
				if (!T12_) goto LA14_;
				result = h_1;
				goto BeforeRet_;
			}
LA14_: ;
			T16_ = ((*t_p0).data.len-1);
			h_1 = nextTry__pureZcollectionsZtables_u34(h_1, T16_);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		} LA8: ;
	}
	result = (NI)(((NI)-1) - h_1);
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, X5BX5Deq___pureZjson_u736)(tyObject_OrderedTable__alibvEreYoDQX0zEzfTleQ* t_p0, NimStringV2 key_p1, tyObject_JsonNodeObj__HuNCd9cjVf1RGJ8WXqZvVog* val_p2) {
	NI hc_1;
	NI index_1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	{
		NI T3_;
		NI correctSizeX60gensym13__1;
		T3_ = (*t_p0).data.len;
		if (!(T3_ == ((NI)0))) goto LA4_;
		correctSizeX60gensym13__1 = slotsNeeded__pureZcollectionsZtables_u42(((NI)32));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		(*t_p0).counter = ((NI)0);
		newSeq__pureZjson_u468((&(*t_p0).data), (correctSizeX60gensym13__1));
		(*t_p0).first = ((NI)-1);
		(*t_p0).last = ((NI)-1);
	}
LA4_: ;
	hc_1 = 0;
	index_1 = rawGet__pureZjson_u805((&(*t_p0)), key_p1, (&hc_1));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		if (!(((NI)0) <= index_1)) goto LA8_;
		eqsink___pureZjson_u330(&(*t_p0).data.p->data[index_1].Field3, val_p2);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	goto LA6_;
LA8_: ;
	{
		tyObject_OrderedTable__alibvEreYoDQX0zEzfTleQ* T21_;
		tyObject_JsonNodeObj__HuNCd9cjVf1RGJ8WXqZvVog* blitTmp_1;
		{
			NI T13_;
			NI correctSizeX60gensym18__1;
			T13_ = (*t_p0).data.len;
			if (!(T13_ == ((NI)0))) goto LA14_;
			correctSizeX60gensym18__1 = slotsNeeded__pureZcollectionsZtables_u42(((NI)32));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			(*t_p0).counter = ((NI)0);
			newSeq__pureZjson_u468((&(*t_p0).data), (correctSizeX60gensym18__1));
			(*t_p0).first = ((NI)-1);
			(*t_p0).last = ((NI)-1);
		}
LA14_: ;
		{
			NIM_BOOL T18_;
			T18_ = (NIM_BOOL)0;
			T18_ = mustRehash__pureZjson_u1133((&(*t_p0)));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (!T18_) goto LA19_;
			enlarge__pureZjson_u1282(t_p0);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			index_1 = rawGetKnownHC__pureZjson_u1927((&(*t_p0)), key_p1, hc_1);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
LA19_: ;
		index_1 = (NI)(((NI)-1) - index_1);
		T21_ = (tyObject_OrderedTable__alibvEreYoDQX0zEzfTleQ*)0;
		T21_ = t_p0;
		blitTmp_1 = val_p2;
		rawInsert__pureZjson_u1665(T21_, (&(*t_p0).data), key_p1, blitTmp_1, hc_1, index_1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		(*t_p0).counter += ((NI)1);
	}
LA6_: ;
	}BeforeRet_: ;
}
static N_INLINE(NIM_BOOL, sameSeqPayload)(void* x_p0, void* y_p1) {
	NIM_BOOL result;
	result = ((*((tyObject_NimRawSeq__2kUMFDNh0hpLnOTOSL0tSA*) (x_p0))).p == (*((tyObject_NimRawSeq__2kUMFDNh0hpLnOTOSL0tSA*) (y_p1))).p);
	return result;
}
static N_INLINE(NI, pluspercent___system_u793)(NI x_p0, NI y_p1) {
	NI result;
	result = ((NI) ((NU)((NU64)(((NU) (x_p0))) + (NU64)(((NU) (y_p1))))));
	return result;
}
static N_INLINE(void, nimIncRef)(void* p_p0) {
	NI T1_;
	NI T2_;
	T1_ = (NI)0;
	T1_ = minuspercent___system_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)16));
	T2_ = (NI)0;
	T2_ = minuspercent___system_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)16));
	(*((tyObject_RefHeader__sqhyc4FSbGmPtkvXRNl9acg*) (T1_))).rc = pluspercent___system_u793((*((tyObject_RefHeader__sqhyc4FSbGmPtkvXRNl9acg*) (T2_))).rc, ((NI)16));
}
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___pureZjson_u94)(tySequence__xUV33m0d5HZLvMGUKDBm7Q* dest_p0, tySequence__xUV33m0d5HZLvMGUKDBm7Q src_p1) {
	NI T6_;
	NI colontmp_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = sameSeqPayload(dest_p0, (&src_p1));
		if (!T3_) goto LA4_;
		goto BeforeRet_;
	}
LA4_: ;
	T6_ = src_p1.len;
	setLen__pureZjson_u113((&(*dest_p0)), T6_);
	colontmp_ = ((NI)0);
	{
		while (1) {
			NI T9_;
			T9_ = (*dest_p0).len;
			if (!(colontmp_ < T9_)) goto LA8;
			(*dest_p0).p->data[colontmp_].Field0 = src_p1.p->data[colontmp_].Field0;
			(*dest_p0).p->data[colontmp_].Field1 = src_p1.p->data[colontmp_].Field1;
			eqcopy___system_u2723((&(*dest_p0).p->data[colontmp_].Field2), src_p1.p->data[colontmp_].Field2);
			{
				if (!src_p1.p->data[colontmp_].Field3) goto LA12_;
				nimIncRef(src_p1.p->data[colontmp_].Field3);
			}
LA12_: ;
			{
				NIM_BOOL T16_;
				T16_ = (NIM_BOOL)0;
				T16_ = nimDecRefIsLastDyn((*dest_p0).p->data[colontmp_].Field3);
				if (!T16_) goto LA17_;
				eqdestroy___pureZjson_u67((&(*(*dest_p0).p->data[colontmp_].Field3)));
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				nimRawDispose((*dest_p0).p->data[colontmp_].Field3, ((NI)8));
			}
LA17_: ;
			(*dest_p0).p->data[colontmp_].Field3 = src_p1.p->data[colontmp_].Field3;
			colontmp_ += ((NI)1);
		} LA8: ;
	}
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___pureZjson_u486)(tyObject_OrderedTable__alibvEreYoDQX0zEzfTleQ* dest_p0, tyObject_OrderedTable__alibvEreYoDQX0zEzfTleQ* src_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqcopy___pureZjson_u94((&(*dest_p0).data), (*src_p1).data);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	(*dest_p0).counter = (*src_p1).counter;
	(*dest_p0).first = (*src_p1).first;
	(*dest_p0).last = (*src_p1).last;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZjson_u483)(tyObject_OrderedTable__alibvEreYoDQX0zEzfTleQ* dest_p0) {
	eqdestroy___pureZjson_u91((*dest_p0).data);
}
static N_INLINE(NI, rawGet__pureZjson_u3095)(tyObject_OrderedTable__alibvEreYoDQX0zEzfTleQ* t_p0, NimStringV2 key_p1, NI* hc_p2) {
	NI result;
	NI T1_;
	NI h_1;
	NI T11_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	T1_ = (NI)0;
	T1_ = hash__pureZhashes_u586(key_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	(*hc_p2) = T1_;
	{
		if (!((*hc_p2) == ((NI)0))) goto LA4_;
		(*hc_p2) = ((NI)314159265);
	}
LA4_: ;
	{
		NI T8_;
		T8_ = (*t_p0).data.len;
		if (!(T8_ == ((NI)0))) goto LA9_;
		result = ((NI)-1);
		goto BeforeRet_;
	}
LA9_: ;
	T11_ = ((*t_p0).data.len-1);
	h_1 = (NI)((*hc_p2) & T11_);
	{
		while (1) {
			NIM_BOOL T14_;
			NI T21_;
			T14_ = (NIM_BOOL)0;
			T14_ = isFilled__pureZcollectionsZtables_u31((*t_p0).data.p->data[h_1].Field0);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (!T14_) goto LA13;
			{
				NIM_BOOL T17_;
				T17_ = (NIM_BOOL)0;
				T17_ = ((*t_p0).data.p->data[h_1].Field0 == (*hc_p2));
				if (!(T17_)) goto LA18_;
				T17_ = eqStrings((*t_p0).data.p->data[h_1].Field2, key_p1);
LA18_: ;
				if (!T17_) goto LA19_;
				result = h_1;
				goto BeforeRet_;
			}
LA19_: ;
			T21_ = ((*t_p0).data.len-1);
			h_1 = nextTry__pureZcollectionsZtables_u34(h_1, T21_);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		} LA13: ;
	}
	result = (NI)(((NI)-1) - h_1);
	}BeforeRet_: ;
	return result;
}
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, copyMem__system_u1755)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1) {
	{
		if (!(((NI)0) < src_p1.len)) goto LA3_;
		copyMem__system_u1755(((void*) ((&(*(*dest_p0).p).data[(*dest_p0).len]))), ((void*) ((&(*src_p1.p).data[((NI)0)]))), (src_p1.len));
		(*dest_p0).len += src_p1.len;
		(*(*dest_p0).p).data[(*dest_p0).len] = 0;
	}
LA3_: ;
}
N_LIB_PRIVATE N_NOINLINE(void, raiseKeyError__pureZjson_u3352)(NimStringV2 key_p0) {
	tyObject_KeyError__WyMCFOyjoQlpL9bXWFR7E6w* T1_;
	NimStringV2 T2_;
{	T1_ = NIM_NIL;
	T1_ = (tyObject_KeyError__WyMCFOyjoQlpL9bXWFR7E6w*) nimNewObj(sizeof(tyObject_KeyError__WyMCFOyjoQlpL9bXWFR7E6w), NIM_ALIGNOF(tyObject_KeyError__WyMCFOyjoQlpL9bXWFR7E6w));
	(*T1_).Sup.Sup.Sup.Sup.m_type = (&NTIv2__WyMCFOyjoQlpL9bXWFR7E6w_);
	(*T1_).Sup.Sup.Sup.name = "KeyError";
	T2_.len = 0; T2_.p = NIM_NIL;
	T2_ = rawNewString(key_p0.len + 15);
appendString((&T2_), TM__4SoG2KRQy3oMm9aUzSLtGrA_3);
appendString((&T2_), key_p0);
	(*T1_).Sup.Sup.Sup.message = T2_;
	(*T1_).Sup.Sup.Sup.parent = ((Exception*) NIM_NIL);
	raiseExceptionEx((Exception*)T1_, "KeyError", "raiseKeyError", "tables.nim", 232);
goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__HuNCd9cjVf1RGJ8WXqZvVog**, X5BX5D___pureZjson_u3088)(tyObject_OrderedTable__alibvEreYoDQX0zEzfTleQ* t_p0, NimStringV2 key_p1) {
	tyObject_JsonNodeObj__HuNCd9cjVf1RGJ8WXqZvVog** result;
	NI hcX60gensym97__1;
	NI indexX60gensym97__1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (tyObject_JsonNodeObj__HuNCd9cjVf1RGJ8WXqZvVog**)0;
	hcX60gensym97__1 = (NI)0;
	indexX60gensym97__1 = rawGet__pureZjson_u3095((&(*t_p0)), key_p1, (&hcX60gensym97__1));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		if (!(((NI)0) <= indexX60gensym97__1)) goto LA3_;
		result = &(*t_p0).data.p->data[indexX60gensym97__1].Field3;
	}
	goto LA1_;
LA3_: ;
	{
		raiseKeyError__pureZjson_u3352(key_p1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA1_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__HuNCd9cjVf1RGJ8WXqZvVog*, getOrDefault__pureZjson_u3908)(tyObject_OrderedTable__alibvEreYoDQX0zEzfTleQ* t_p0, NimStringV2 key_p1) {
	tyObject_JsonNodeObj__HuNCd9cjVf1RGJ8WXqZvVog* result;
	NI hcX60gensym59__1;
	NI indexX60gensym59__1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = 0;
	hcX60gensym59__1 = (NI)0;
	indexX60gensym59__1 = rawGet__pureZjson_u3095(t_p0, key_p1, (&hcX60gensym59__1));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		if (!(((NI)0) <= indexX60gensym59__1)) goto LA3_;
		eqcopy___pureZjson_u324(&result, (*t_p0).data.p->data[indexX60gensym59__1].Field3);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA3_: ;
	}BeforeRet_: ;
	return result;
}
