/* Generated by Nim Compiler v2.2.10 */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   x86_64-w64-mingw32-gcc -c -w -fmax-errors=3 -mno-ms-bitfields -fno-strict-aliasing -DWIN32_LEAN_AND_MEAN -Os -fno-ident   -I/home/kali/.choosenim/toolchains/nim-2.2.10/lib -I/home/kali/c2/agents/agent-nim -o /home/kali/c2/agents/agent-nim/nimcache_test/@nwinim-3.9.4-4b7c430159be2e8b2dc4b663a9b19f7678b58f87@swinim@sinc@swinhttp.nim.c.o /home/kali/c2/agents/agent-nim/nimcache_test/@nwinim-3.9.4-4b7c430159be2e8b2dc4b663a9b19f7678b58f87@swinim@sinc@swinhttp.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
typedef N_STDCALL_PTR(void*, tyProc__81VIzYkqwzDl7rl3af0pZg) (NU16* P1_p0, NI32 P2_p1, NU16* P3_p2, NU16* P4_p3, NI32 P5_p4);
typedef N_STDCALL_PTR(void*, tyProc__RFwzZ679c39c5tm4O7Tpzjeg) (void* P1_p0, NU16* P2_p1, NU16 P3_p2, NI32 P4_p3);
typedef N_STDCALL_PTR(NI32, tyProc__ah5wcFv3UG20t2vgXBy0Fg) (void* P1_p0);
typedef N_STDCALL_PTR(void*, tyProc__VvL5F9ctiPFd9cY0CxFJmncg) (void* P1_p0, NU16* P2_p1, NU16* P3_p2, NU16* P4_p3, NU16* P5_p4, NU16** P6_p5, NI32 P7_p6);
typedef N_STDCALL_PTR(NI32, tyProc__OygtxCk9aDjhab6i7UhdJdQ) (void* P1_p0, NI32 P2_p1, void* P3_p2, NI32 P4_p3);
typedef N_STDCALL_PTR(NI32, tyProc__HfA740GE5GucMArbWnkCkw) (void* P1_p0, NU16* P2_p1, NI32 P3_p2, void* P4_p3, NI32 P5_p4, NI32 P6_p5, NI64 P7_p6);
typedef N_STDCALL_PTR(NI32, tyProc__wS8JrJMcfFBzgzuqJGOAAg) (void* P1_p0, void* P2_p1);
typedef N_STDCALL_PTR(NI32, tyProc__5V5gHAr7e9bsH0OKztxYmCw) (void* P1_p0, NI32 P2_p1, NU16* P3_p2, void* P4_p3, NI32* P5_p4, NI32* P6_p5);
typedef N_STDCALL_PTR(NI32, tyProc__mID4zaJ5rXbvlxUmzwPGLw) (void* P1_p0, void* P2_p1, NI32 P3_p2, NI32* P4_p3);
N_LIB_PRIVATE N_NIMCALL(void*, nimLoadLibrary)(NimStringV2 path_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimLoadLibraryError)(NimStringV2 path_p0);
N_LIB_PRIVATE N_NIMCALL(void*, nimGetProcAddr)(void* lib_p0, NCSTRING name_p1);
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__PLHL6a8C9aYpZJjcflvi9b4g_4 = { 7 | NIM_STRLIT_FLAG, "winhttp" };
static const NimStringV2 TM__PLHL6a8C9aYpZJjcflvi9b4g_5 = {7, (NimStrPayload*)&TM__PLHL6a8C9aYpZJjcflvi9b4g_4};
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__PLHL6a8C9aYpZJjcflvi9b4g_6 = { 7 | NIM_STRLIT_FLAG, "winhttp" };
static const NimStringV2 TM__PLHL6a8C9aYpZJjcflvi9b4g_7 = {7, (NimStrPayload*)&TM__PLHL6a8C9aYpZJjcflvi9b4g_6};
static void* TM__PLHL6a8C9aYpZJjcflvi9b4g_2;
tyProc__81VIzYkqwzDl7rl3af0pZg Dl_2248147427_;
tyProc__RFwzZ679c39c5tm4O7Tpzjeg Dl_2248147403_;
tyProc__ah5wcFv3UG20t2vgXBy0Fg Dl_2248147401_;
tyProc__VvL5F9ctiPFd9cY0CxFJmncg Dl_2248147433_;
tyProc__OygtxCk9aDjhab6i7UhdJdQ Dl_2248147486_;
tyProc__HfA740GE5GucMArbWnkCkw Dl_2248147469_;
tyProc__wS8JrJMcfFBzgzuqJGOAAg Dl_2248147466_;
tyProc__5V5gHAr7e9bsH0OKztxYmCw Dl_2248147449_;
tyProc__mID4zaJ5rXbvlxUmzwPGLw Dl_2248147461_;
N_LIB_PRIVATE N_NIMCALL(void, atnwinimminus3dot9dot4minus4b7c430159be2e8b2dc4b663a9b19f7678b58f87atswinimatsincatswinhttpdotnim_DatInit000)(void) {
if (!((TM__PLHL6a8C9aYpZJjcflvi9b4g_2 = nimLoadLibrary(TM__PLHL6a8C9aYpZJjcflvi9b4g_5))
)) nimLoadLibraryError(TM__PLHL6a8C9aYpZJjcflvi9b4g_7);
	Dl_2248147427_ = (tyProc__81VIzYkqwzDl7rl3af0pZg) nimGetProcAddr(TM__PLHL6a8C9aYpZJjcflvi9b4g_2, "WinHttpOpen");
	Dl_2248147403_ = (tyProc__RFwzZ679c39c5tm4O7Tpzjeg) nimGetProcAddr(TM__PLHL6a8C9aYpZJjcflvi9b4g_2, "WinHttpConnect");
	Dl_2248147401_ = (tyProc__ah5wcFv3UG20t2vgXBy0Fg) nimGetProcAddr(TM__PLHL6a8C9aYpZJjcflvi9b4g_2, "WinHttpCloseHandle");
	Dl_2248147433_ = (tyProc__VvL5F9ctiPFd9cY0CxFJmncg) nimGetProcAddr(TM__PLHL6a8C9aYpZJjcflvi9b4g_2, "WinHttpOpenRequest");
	Dl_2248147486_ = (tyProc__OygtxCk9aDjhab6i7UhdJdQ) nimGetProcAddr(TM__PLHL6a8C9aYpZJjcflvi9b4g_2, "WinHttpSetOption");
	Dl_2248147469_ = (tyProc__HfA740GE5GucMArbWnkCkw) nimGetProcAddr(TM__PLHL6a8C9aYpZJjcflvi9b4g_2, "WinHttpSendRequest");
	Dl_2248147466_ = (tyProc__wS8JrJMcfFBzgzuqJGOAAg) nimGetProcAddr(TM__PLHL6a8C9aYpZJjcflvi9b4g_2, "WinHttpReceiveResponse");
	Dl_2248147449_ = (tyProc__5V5gHAr7e9bsH0OKztxYmCw) nimGetProcAddr(TM__PLHL6a8C9aYpZJjcflvi9b4g_2, "WinHttpQueryHeaders");
	Dl_2248147461_ = (tyProc__mID4zaJ5rXbvlxUmzwPGLw) nimGetProcAddr(TM__PLHL6a8C9aYpZJjcflvi9b4g_2, "WinHttpReadData");
}

