/* Generated by Nim Compiler v2.2.10 */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   x86_64-w64-mingw32-gcc -c -w -fmax-errors=3 -mno-ms-bitfields -fno-strict-aliasing -DWIN32_LEAN_AND_MEAN -Os -fno-ident   -I/home/kali/.choosenim/toolchains/nim-2.2.10/lib -I/home/kali/c2/agents/agent-nim -o /home/kali/c2/agents/agent-nim/nimcache_test/@nwinim-3.9.4-4b7c430159be2e8b2dc4b663a9b19f7678b58f87@swinim@sinc@swinbase.nim.c.o /home/kali/c2/agents/agent-nim/nimcache_test/@nwinim-3.9.4-4b7c430159be2e8b2dc4b663a9b19f7678b58f87@swinim@sinc@swinbase.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
typedef N_STDCALL_PTR(NI, tyProc__E5YB9csXgVe1kveJGRzh5OQ) (NIM_CHAR* lpLibFileName_p0);
typedef N_STDCALL_PTR(void*, tyProc__0jr8jiP1mbzQ6RKBrEEqrw) (NI hModule_p0, NIM_CHAR* lpProcName_p1);
typedef N_STDCALL_PTR(NI32, tyProc__p7k7hzRLl9cL8zqB8iUhO9cA) (void* lpAddress_p0, NI64 dwSize_p1, NI32 flNewProtect_p2, NI32* lpflOldProtect_p3);
typedef N_STDCALL_PTR(NI32, tyProc__RqPJ327ezwqplysPaezU3Q) (NU16* lpName_p0, NU16* lpBuffer_p1, NI32 nSize_p2);
typedef N_STDCALL_PTR(NI32, tyProc__9bXer9a4ps9aSGctILcxWReVw) (void);
typedef N_STDCALL_PTR(NI32, tyProc__zs1G9aN0hsG4qr4I6t6Agtg) (NI hModule_p0, NU16* lpFilename_p1, NI32 nSize_p2);
typedef N_STDCALL_PTR(NI, tyProc__uryidYWkntM7ddjZSyxvyQ) (void);
typedef N_STDCALL_PTR(NI64, tyProc__pdvM9cE5kOE4yT8D0B1TnYQ) (NI hHeap_p0, NI32 dwFlags_p1, void* lpMem_p2);
typedef N_STDCALL_PTR(void*, tyProc__bREaOok5B7e9c9crOwTPdBhg) (void* lpAddress_p0, NI64 dwSize_p1, NI32 flAllocationType_p2, NI32 flProtect_p3);
typedef N_STDCALL_PTR(NI32, tyProc__qzER9a83At0GuyLU6E9cw7Lw) (void* lpAddress_p0, NI64 dwSize_p1, NI32 dwFreeType_p2);
N_LIB_PRIVATE N_NIMCALL(void*, nimLoadLibrary)(NimStringV2 path_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimLoadLibraryError)(NimStringV2 path_p0);
N_LIB_PRIVATE N_NIMCALL(void*, nimGetProcAddr)(void* lib_p0, NCSTRING name_p1);
static const struct {
  NI cap; NIM_CHAR data[8+1];
} TM__EKPJb3OgiuhODcUARs3zIQ_4 = { 8 | NIM_STRLIT_FLAG, "kernel32" };
static const NimStringV2 TM__EKPJb3OgiuhODcUARs3zIQ_5 = {8, (NimStrPayload*)&TM__EKPJb3OgiuhODcUARs3zIQ_4};
static const struct {
  NI cap; NIM_CHAR data[8+1];
} TM__EKPJb3OgiuhODcUARs3zIQ_6 = { 8 | NIM_STRLIT_FLAG, "kernel32" };
static const NimStringV2 TM__EKPJb3OgiuhODcUARs3zIQ_7 = {8, (NimStrPayload*)&TM__EKPJb3OgiuhODcUARs3zIQ_6};
static void* TM__EKPJb3OgiuhODcUARs3zIQ_2;
tyProc__E5YB9csXgVe1kveJGRzh5OQ Dl_2013270634_;
tyProc__0jr8jiP1mbzQ6RKBrEEqrw Dl_2013268496_;
tyProc__p7k7hzRLl9cL8zqB8iUhO9cA Dl_2013268535_;
tyProc__E5YB9csXgVe1kveJGRzh5OQ Dl_2013268394_;
tyProc__RqPJ327ezwqplysPaezU3Q Dl_2013268753_;
tyProc__9bXer9a4ps9aSGctILcxWReVw Dl_2013268980_;
tyProc__zs1G9aN0hsG4qr4I6t6Agtg Dl_2013268390_;
tyProc__uryidYWkntM7ddjZSyxvyQ Dl_2013268305_;
tyProc__pdvM9cE5kOE4yT8D0B1TnYQ Dl_2013268301_;
tyProc__bREaOok5B7e9c9crOwTPdBhg Dl_2013268526_;
tyProc__qzER9a83At0GuyLU6E9cw7Lw Dl_2013268531_;
N_LIB_PRIVATE N_NIMCALL(void, atnwinimminus3dot9dot4minus4b7c430159be2e8b2dc4b663a9b19f7678b58f87atswinimatsincatswinbasedotnim_DatInit000)(void) {
if (!((TM__EKPJb3OgiuhODcUARs3zIQ_2 = nimLoadLibrary(TM__EKPJb3OgiuhODcUARs3zIQ_5))
)) nimLoadLibraryError(TM__EKPJb3OgiuhODcUARs3zIQ_7);
	Dl_2013270634_ = (tyProc__E5YB9csXgVe1kveJGRzh5OQ) nimGetProcAddr(TM__EKPJb3OgiuhODcUARs3zIQ_2, "LoadLibraryA");
	Dl_2013268496_ = (tyProc__0jr8jiP1mbzQ6RKBrEEqrw) nimGetProcAddr(TM__EKPJb3OgiuhODcUARs3zIQ_2, "GetProcAddress");
	Dl_2013268535_ = (tyProc__p7k7hzRLl9cL8zqB8iUhO9cA) nimGetProcAddr(TM__EKPJb3OgiuhODcUARs3zIQ_2, "VirtualProtect");
	Dl_2013268394_ = (tyProc__E5YB9csXgVe1kveJGRzh5OQ) nimGetProcAddr(TM__EKPJb3OgiuhODcUARs3zIQ_2, "GetModuleHandleA");
	Dl_2013268753_ = (tyProc__RqPJ327ezwqplysPaezU3Q) nimGetProcAddr(TM__EKPJb3OgiuhODcUARs3zIQ_2, "GetEnvironmentVariableW");
	Dl_2013268980_ = (tyProc__9bXer9a4ps9aSGctILcxWReVw) nimGetProcAddr(TM__EKPJb3OgiuhODcUARs3zIQ_2, "GetCurrentProcessId");
	Dl_2013268390_ = (tyProc__zs1G9aN0hsG4qr4I6t6Agtg) nimGetProcAddr(TM__EKPJb3OgiuhODcUARs3zIQ_2, "GetModuleFileNameW");
	Dl_2013268305_ = (tyProc__uryidYWkntM7ddjZSyxvyQ) nimGetProcAddr(TM__EKPJb3OgiuhODcUARs3zIQ_2, "GetProcessHeap");
	Dl_2013268301_ = (tyProc__pdvM9cE5kOE4yT8D0B1TnYQ) nimGetProcAddr(TM__EKPJb3OgiuhODcUARs3zIQ_2, "HeapSize");
	Dl_2013268526_ = (tyProc__bREaOok5B7e9c9crOwTPdBhg) nimGetProcAddr(TM__EKPJb3OgiuhODcUARs3zIQ_2, "VirtualAlloc");
	Dl_2013268531_ = (tyProc__qzER9a83At0GuyLU6E9cw7Lw) nimGetProcAddr(TM__EKPJb3OgiuhODcUARs3zIQ_2, "VirtualFree");
}

