/* Generated by Nim Compiler v2.2.10 */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   x86_64-w64-mingw32-gcc -c -w -fmax-errors=3 -mno-ms-bitfields -fno-strict-aliasing -DWIN32_LEAN_AND_MEAN -Os -fno-ident   -I/home/kali/.choosenim/toolchains/nim-2.2.10/lib -I/home/kali/c2/agents/agent-nim -o /home/kali/c2/agents/agent-nim/nimcache_test/@pbase64.nim.c.o /home/kali/c2/agents/agent-nim/nimcache_test/@pbase64.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_ValueError__NZcE89crkraWmH1VkcjYX9ag tyObject_ValueError__NZcE89crkraWmH1VkcjYX9ag;
typedef struct tyObject_CatchableError__kvV4Jp5z2ULaSZq53myi9ag tyObject_CatchableError__kvV4Jp5z2ULaSZq53myi9ag;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tySequence__UIJx6FJrflnhA9a3u1VF1vA tySequence__UIJx6FJrflnhA9a3u1VF1vA;
typedef struct tySequence__UIJx6FJrflnhA9a3u1VF1vA_Content tySequence__UIJx6FJrflnhA9a3u1VF1vA_Content;
typedef struct tyObject_StackTraceEntry__UznwMnjUHK6AxZHnP9bMXEA tyObject_StackTraceEntry__UznwMnjUHK6AxZHnP9bMXEA;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
typedef NIM_CHAR tyArray__bErjiHmvISNmC2iIqkq21Q[256];
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct RootObj {
	TNimTypeV2* m_type;
};
struct tySequence__UIJx6FJrflnhA9a3u1VF1vA {
  NI len; tySequence__UIJx6FJrflnhA9a3u1VF1vA_Content* p;
};
struct Exception {
	RootObj Sup;
	Exception* parent;
	NCSTRING name;
	NimStringV2 message;
	tySequence__UIJx6FJrflnhA9a3u1VF1vA trace;
	Exception* up;
};
struct tyObject_CatchableError__kvV4Jp5z2ULaSZq53myi9ag {
	Exception Sup;
};
struct tyObject_ValueError__NZcE89crkraWmH1VkcjYX9ag {
	tyObject_CatchableError__kvV4Jp5z2ULaSZq53myi9ag Sup;
};
struct tyObject_StackTraceEntry__UznwMnjUHK6AxZHnP9bMXEA {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};
struct tySequence__UIJx6FJrflnhA9a3u1VF1vA_Content { NI cap; tyObject_StackTraceEntry__UznwMnjUHK6AxZHnP9bMXEA data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NIMCALL(NI, decodeSize__pureZbase64_u484)(NI size_p0);
N_LIB_PRIVATE N_NIMCALL(void, setLengthStrV2)(NimStringV2* s_p0, NI newLen_p1);
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObj)(NI size_p0, NI alignment_p1);
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(void, copyMem__system_u1755)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, appendChar)(NimStringV2* dest_p0, NIM_CHAR c_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___systemZdollars_u14)(NI xX60gensym0__p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, rawNewString)(NI space_p0);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e_p0, NCSTRING ename_p1, NCSTRING procname_p2, NCSTRING filename_p3, NI line_p4);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2* s_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimPrepareStrMutationImpl__system_u2462)(NimStringV2* s_p0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static const struct {
  NI cap; NIM_CHAR data[0+1];
} TM__2L6xrRPz7CWDB3T1R9cDN5A_2 = { 0 | NIM_STRLIT_FLAG, "" };
static const NimStringV2 TM__2L6xrRPz7CWDB3T1R9cDN5A_3 = {0, (NimStrPayload*)&TM__2L6xrRPz7CWDB3T1R9cDN5A_2};
extern TNimTypeV2 NTIv2__NZcE89crkraWmH1VkcjYX9ag_;
static const struct {
  NI cap; NIM_CHAR data[33+1];
} TM__2L6xrRPz7CWDB3T1R9cDN5A_4 = { 33 | NIM_STRLIT_FLAG, "Invalid base64 format character `" };
static const NimStringV2 TM__2L6xrRPz7CWDB3T1R9cDN5A_5 = {33, (NimStrPayload*)&TM__2L6xrRPz7CWDB3T1R9cDN5A_4};
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__2L6xrRPz7CWDB3T1R9cDN5A_6 = { 7 | NIM_STRLIT_FLAG, "` (ord " };
static const NimStringV2 TM__2L6xrRPz7CWDB3T1R9cDN5A_7 = {7, (NimStrPayload*)&TM__2L6xrRPz7CWDB3T1R9cDN5A_6};
static const struct {
  NI cap; NIM_CHAR data[14+1];
} TM__2L6xrRPz7CWDB3T1R9cDN5A_8 = { 14 | NIM_STRLIT_FLAG, ") at location " };
static const NimStringV2 TM__2L6xrRPz7CWDB3T1R9cDN5A_9 = {14, (NimStrPayload*)&TM__2L6xrRPz7CWDB3T1R9cDN5A_8};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__2L6xrRPz7CWDB3T1R9cDN5A_10 = { 1 | NIM_STRLIT_FLAG, "." };
static const NimStringV2 TM__2L6xrRPz7CWDB3T1R9cDN5A_11 = {1, (NimStrPayload*)&TM__2L6xrRPz7CWDB3T1R9cDN5A_10};
static const NimStringV2 TM__2L6xrRPz7CWDB3T1R9cDN5A_12 = {33, (NimStrPayload*)&TM__2L6xrRPz7CWDB3T1R9cDN5A_4};
static const NimStringV2 TM__2L6xrRPz7CWDB3T1R9cDN5A_13 = {7, (NimStrPayload*)&TM__2L6xrRPz7CWDB3T1R9cDN5A_6};
static const NimStringV2 TM__2L6xrRPz7CWDB3T1R9cDN5A_14 = {14, (NimStrPayload*)&TM__2L6xrRPz7CWDB3T1R9cDN5A_8};
static const NimStringV2 TM__2L6xrRPz7CWDB3T1R9cDN5A_15 = {1, (NimStrPayload*)&TM__2L6xrRPz7CWDB3T1R9cDN5A_10};
static const NimStringV2 TM__2L6xrRPz7CWDB3T1R9cDN5A_16 = {33, (NimStrPayload*)&TM__2L6xrRPz7CWDB3T1R9cDN5A_4};
static const NimStringV2 TM__2L6xrRPz7CWDB3T1R9cDN5A_17 = {7, (NimStrPayload*)&TM__2L6xrRPz7CWDB3T1R9cDN5A_6};
static const NimStringV2 TM__2L6xrRPz7CWDB3T1R9cDN5A_18 = {14, (NimStrPayload*)&TM__2L6xrRPz7CWDB3T1R9cDN5A_8};
static const NimStringV2 TM__2L6xrRPz7CWDB3T1R9cDN5A_19 = {1, (NimStrPayload*)&TM__2L6xrRPz7CWDB3T1R9cDN5A_10};
static const NimStringV2 TM__2L6xrRPz7CWDB3T1R9cDN5A_20 = {33, (NimStrPayload*)&TM__2L6xrRPz7CWDB3T1R9cDN5A_4};
static const NimStringV2 TM__2L6xrRPz7CWDB3T1R9cDN5A_21 = {7, (NimStrPayload*)&TM__2L6xrRPz7CWDB3T1R9cDN5A_6};
static const NimStringV2 TM__2L6xrRPz7CWDB3T1R9cDN5A_22 = {14, (NimStrPayload*)&TM__2L6xrRPz7CWDB3T1R9cDN5A_8};
static const NimStringV2 TM__2L6xrRPz7CWDB3T1R9cDN5A_23 = {1, (NimStrPayload*)&TM__2L6xrRPz7CWDB3T1R9cDN5A_10};
static const NimStringV2 TM__2L6xrRPz7CWDB3T1R9cDN5A_24 = {33, (NimStrPayload*)&TM__2L6xrRPz7CWDB3T1R9cDN5A_4};
static const NimStringV2 TM__2L6xrRPz7CWDB3T1R9cDN5A_25 = {7, (NimStrPayload*)&TM__2L6xrRPz7CWDB3T1R9cDN5A_6};
static const NimStringV2 TM__2L6xrRPz7CWDB3T1R9cDN5A_26 = {14, (NimStrPayload*)&TM__2L6xrRPz7CWDB3T1R9cDN5A_8};
static const NimStringV2 TM__2L6xrRPz7CWDB3T1R9cDN5A_27 = {1, (NimStrPayload*)&TM__2L6xrRPz7CWDB3T1R9cDN5A_10};
static const NimStringV2 TM__2L6xrRPz7CWDB3T1R9cDN5A_28 = {33, (NimStrPayload*)&TM__2L6xrRPz7CWDB3T1R9cDN5A_4};
static const NimStringV2 TM__2L6xrRPz7CWDB3T1R9cDN5A_29 = {7, (NimStrPayload*)&TM__2L6xrRPz7CWDB3T1R9cDN5A_6};
static const NimStringV2 TM__2L6xrRPz7CWDB3T1R9cDN5A_30 = {14, (NimStrPayload*)&TM__2L6xrRPz7CWDB3T1R9cDN5A_8};
static const NimStringV2 TM__2L6xrRPz7CWDB3T1R9cDN5A_31 = {1, (NimStrPayload*)&TM__2L6xrRPz7CWDB3T1R9cDN5A_10};
static const NimStringV2 TM__2L6xrRPz7CWDB3T1R9cDN5A_32 = {33, (NimStrPayload*)&TM__2L6xrRPz7CWDB3T1R9cDN5A_4};
static const NimStringV2 TM__2L6xrRPz7CWDB3T1R9cDN5A_33 = {7, (NimStrPayload*)&TM__2L6xrRPz7CWDB3T1R9cDN5A_6};
static const NimStringV2 TM__2L6xrRPz7CWDB3T1R9cDN5A_34 = {14, (NimStrPayload*)&TM__2L6xrRPz7CWDB3T1R9cDN5A_8};
static const NimStringV2 TM__2L6xrRPz7CWDB3T1R9cDN5A_35 = {1, (NimStrPayload*)&TM__2L6xrRPz7CWDB3T1R9cDN5A_10};
static const NimStringV2 TM__2L6xrRPz7CWDB3T1R9cDN5A_36 = {33, (NimStrPayload*)&TM__2L6xrRPz7CWDB3T1R9cDN5A_4};
static const NimStringV2 TM__2L6xrRPz7CWDB3T1R9cDN5A_37 = {7, (NimStrPayload*)&TM__2L6xrRPz7CWDB3T1R9cDN5A_6};
static const NimStringV2 TM__2L6xrRPz7CWDB3T1R9cDN5A_38 = {14, (NimStrPayload*)&TM__2L6xrRPz7CWDB3T1R9cDN5A_8};
static const NimStringV2 TM__2L6xrRPz7CWDB3T1R9cDN5A_39 = {1, (NimStrPayload*)&TM__2L6xrRPz7CWDB3T1R9cDN5A_10};
static const NimStringV2 TM__2L6xrRPz7CWDB3T1R9cDN5A_40 = {33, (NimStrPayload*)&TM__2L6xrRPz7CWDB3T1R9cDN5A_4};
static const NimStringV2 TM__2L6xrRPz7CWDB3T1R9cDN5A_41 = {7, (NimStrPayload*)&TM__2L6xrRPz7CWDB3T1R9cDN5A_6};
static const NimStringV2 TM__2L6xrRPz7CWDB3T1R9cDN5A_42 = {14, (NimStrPayload*)&TM__2L6xrRPz7CWDB3T1R9cDN5A_8};
static const NimStringV2 TM__2L6xrRPz7CWDB3T1R9cDN5A_43 = {1, (NimStrPayload*)&TM__2L6xrRPz7CWDB3T1R9cDN5A_10};
N_LIB_PRIVATE NIM_CONST tyArray__bErjiHmvISNmC2iIqkq21Q decodeTable__pureZbase64_u480 = {255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
62,
255,
62,
255,
63,
52,
53,
54,
55,
56,
57,
58,
59,
60,
61,
255,
255,
255,
255,
255,
255,
255,
0,
1,
2,
3,
4,
5,
6,
7,
8,
9,
10,
11,
12,
13,
14,
15,
16,
17,
18,
19,
20,
21,
22,
23,
24,
25,
255,
255,
255,
255,
63,
255,
26,
27,
28,
29,
30,
31,
32,
33,
34,
35,
36,
37,
38,
39,
40,
41,
42,
43,
44,
45,
46,
47,
48,
49,
50,
51,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255}
;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4172;
N_LIB_PRIVATE N_NIMCALL(NI, decodeSize__pureZbase64_u484)(NI size_p0) {
	NI result;
{	result = (NI)((NI)((NI)(size_p0 * ((NI)3)) / ((NI)4)) + ((NI)6));
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, copyMem__system_u1755)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1) {
	{
		if (!(((NI)0) < src_p1.len)) goto LA3_;
		copyMem__system_u1755(((void*) ((&(*(*dest_p0).p).data[(*dest_p0).len]))), ((void*) ((&(*src_p1.p).data[((NI)0)]))), (src_p1.len));
		(*dest_p0).len += src_p1.len;
		(*(*dest_p0).p).data[(*dest_p0).len] = 0;
	}
LA3_: ;
}
static N_INLINE(void, appendChar)(NimStringV2* dest_p0, NIM_CHAR c_p1) {
	(*(*dest_p0).p).data[(*dest_p0).len] = c_p1;
	(*dest_p0).len += ((NI)1);
	(*(*dest_p0).p).data[(*dest_p0).len] = 0;
}
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2* s_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = !(((*s_p0).p == ((NimStrPayload*) NIM_NIL)));
		if (!(T3_)) goto LA4_;
		T3_ = ((NI)((*(*s_p0).p).cap & ((NI)IL64(4611686018427387904))) == ((NI)IL64(4611686018427387904)));
LA4_: ;
		if (!T3_) goto LA5_;
		nimPrepareStrMutationImpl__system_u2462(s_p0);
	}
LA5_: ;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4172);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, decode__pureZbase64_u481)(NimStringV2 s_p0) {
	NimStringV2 result;
	NI T5_;
	NI inputIndex_1;
	NI outputIndex_1;
	NI inputLen_1;
	NI inputEnds_1;
	NI leftLen_1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = TM__2L6xrRPz7CWDB3T1R9cDN5A_3;
	{
		if (!(s_p0.len == ((NI)0))) goto LA3_;
		goto BeforeRet_;
	}
LA3_: ;
	T5_ = (NI)0;
	T5_ = decodeSize__pureZbase64_u484(s_p0.len);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	setLengthStrV2((&result), (T5_));
	inputIndex_1 = ((NI)0);
	outputIndex_1 = ((NI)0);
	inputLen_1 = s_p0.len;
	inputEnds_1 = ((NI)0);
	{
		while (1) {
			NIM_BOOL T8_;
			T8_ = (NIM_BOOL)0;
			T8_ = (((NI)0) < inputLen_1);
			if (!(T8_)) goto LA9_;
			T8_ = (((NU8)(s_p0.p->data[(NI)(inputLen_1 - ((NI)1))])) == ((NU8)(10)) || ((NU8)(s_p0.p->data[(NI)(inputLen_1 - ((NI)1))])) == ((NU8)(13)) || ((NU8)(s_p0.p->data[(NI)(inputLen_1 - ((NI)1))])) == ((NU8)(32)) || ((NU8)(s_p0.p->data[(NI)(inputLen_1 - ((NI)1))])) == ((NU8)(61)));
LA9_: ;
			if (!T8_) goto LA7;
			inputLen_1 -= ((NI)1);
		} LA7: ;
	}
	inputEnds_1 = (NI)(inputLen_1 - ((NI)4));
	{
		while (1) {
			NI a_1;
			NI b_1;
			NI c_1;
			NI d_1;
			if (!(inputIndex_1 <= inputEnds_1)) goto LA11;
			{
				while (1) {
					if (!(((NU8)(s_p0.p->data[inputIndex_1])) == ((NU8)(10)) || ((NU8)(s_p0.p->data[inputIndex_1])) == ((NU8)(13)) || ((NU8)(s_p0.p->data[inputIndex_1])) == ((NU8)(32)))) goto LA13;
					inputIndex_1 += ((NI)1);
				} LA13: ;
			}
			{
				if (!(inputEnds_1 < inputIndex_1)) goto LA16_;
				goto LA10;
			}
LA16_: ;
			a_1 = ((NI) (((NU8)(decodeTable__pureZbase64_u480[(((NU8)(s_p0.p->data[inputIndex_1])))- 0]))));
			{
				NimStringV2 colontmpD_;
				NimStringV2 colontmpD__2;
				tyObject_ValueError__NZcE89crkraWmH1VkcjYX9ag* T23_;
				NimStringV2 T24_;
				if (!(a_1 == ((NI)255))) goto LA20_;
				colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
				colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
				T23_ = NIM_NIL;
				T23_ = (tyObject_ValueError__NZcE89crkraWmH1VkcjYX9ag*) nimNewObj(sizeof(tyObject_ValueError__NZcE89crkraWmH1VkcjYX9ag), NIM_ALIGNOF(tyObject_ValueError__NZcE89crkraWmH1VkcjYX9ag));
				(*T23_).Sup.Sup.Sup.m_type = (&NTIv2__NZcE89crkraWmH1VkcjYX9ag_);
				(*T23_).Sup.Sup.name = "ValueError";
				T24_.len = 0; T24_.p = NIM_NIL;
				colontmpD_ = dollar___systemZdollars_u14(((NU8)(s_p0.p->data[inputIndex_1])));
				if (NIM_UNLIKELY(*nimErr_)) goto LA22_;
				colontmpD__2 = dollar___systemZdollars_u14(inputIndex_1);
				if (NIM_UNLIKELY(*nimErr_)) goto LA22_;
				T24_ = rawNewString(colontmpD_.len + colontmpD__2.len + 56);
appendString((&T24_), TM__2L6xrRPz7CWDB3T1R9cDN5A_5);
appendChar((&T24_), s_p0.p->data[inputIndex_1]);
appendString((&T24_), TM__2L6xrRPz7CWDB3T1R9cDN5A_7);
appendString((&T24_), colontmpD_);
appendString((&T24_), TM__2L6xrRPz7CWDB3T1R9cDN5A_9);
appendString((&T24_), colontmpD__2);
appendString((&T24_), TM__2L6xrRPz7CWDB3T1R9cDN5A_11);
				(*T23_).Sup.Sup.message = T24_;
				(*T23_).Sup.Sup.parent = ((Exception*) NIM_NIL);
				raiseExceptionEx((Exception*)T23_, "ValueError", "decode", "base64.nim", 232);
goto LA22_;
				{
					LA22_:;
				}
				{
					if (colontmpD__2.p && !(colontmpD__2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__2.p);
}
					if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
				}
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			}
LA20_: ;
			inputIndex_1 += ((NI)1);
			b_1 = ((NI) (((NU8)(decodeTable__pureZbase64_u480[(((NU8)(s_p0.p->data[inputIndex_1])))- 0]))));
			{
				NimStringV2 colontmpD__3;
				NimStringV2 colontmpD__4;
				tyObject_ValueError__NZcE89crkraWmH1VkcjYX9ag* T32_;
				NimStringV2 T33_;
				if (!(b_1 == ((NI)255))) goto LA29_;
				colontmpD__3.len = 0; colontmpD__3.p = NIM_NIL;
				colontmpD__4.len = 0; colontmpD__4.p = NIM_NIL;
				T32_ = NIM_NIL;
				T32_ = (tyObject_ValueError__NZcE89crkraWmH1VkcjYX9ag*) nimNewObj(sizeof(tyObject_ValueError__NZcE89crkraWmH1VkcjYX9ag), NIM_ALIGNOF(tyObject_ValueError__NZcE89crkraWmH1VkcjYX9ag));
				(*T32_).Sup.Sup.Sup.m_type = (&NTIv2__NZcE89crkraWmH1VkcjYX9ag_);
				(*T32_).Sup.Sup.name = "ValueError";
				T33_.len = 0; T33_.p = NIM_NIL;
				colontmpD__3 = dollar___systemZdollars_u14(((NU8)(s_p0.p->data[inputIndex_1])));
				if (NIM_UNLIKELY(*nimErr_)) goto LA31_;
				colontmpD__4 = dollar___systemZdollars_u14(inputIndex_1);
				if (NIM_UNLIKELY(*nimErr_)) goto LA31_;
				T33_ = rawNewString(colontmpD__3.len + colontmpD__4.len + 56);
appendString((&T33_), TM__2L6xrRPz7CWDB3T1R9cDN5A_12);
appendChar((&T33_), s_p0.p->data[inputIndex_1]);
appendString((&T33_), TM__2L6xrRPz7CWDB3T1R9cDN5A_13);
appendString((&T33_), colontmpD__3);
appendString((&T33_), TM__2L6xrRPz7CWDB3T1R9cDN5A_14);
appendString((&T33_), colontmpD__4);
appendString((&T33_), TM__2L6xrRPz7CWDB3T1R9cDN5A_15);
				(*T32_).Sup.Sup.message = T33_;
				(*T32_).Sup.Sup.parent = ((Exception*) NIM_NIL);
				raiseExceptionEx((Exception*)T32_, "ValueError", "decode", "base64.nim", 232);
goto LA31_;
				{
					LA31_:;
				}
				{
					if (colontmpD__4.p && !(colontmpD__4.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__4.p);
}
					if (colontmpD__3.p && !(colontmpD__3.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__3.p);
}
				}
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			}
LA29_: ;
			inputIndex_1 += ((NI)1);
			c_1 = ((NI) (((NU8)(decodeTable__pureZbase64_u480[(((NU8)(s_p0.p->data[inputIndex_1])))- 0]))));
			{
				NimStringV2 colontmpD__5;
				NimStringV2 colontmpD__6;
				tyObject_ValueError__NZcE89crkraWmH1VkcjYX9ag* T41_;
				NimStringV2 T42_;
				if (!(c_1 == ((NI)255))) goto LA38_;
				colontmpD__5.len = 0; colontmpD__5.p = NIM_NIL;
				colontmpD__6.len = 0; colontmpD__6.p = NIM_NIL;
				T41_ = NIM_NIL;
				T41_ = (tyObject_ValueError__NZcE89crkraWmH1VkcjYX9ag*) nimNewObj(sizeof(tyObject_ValueError__NZcE89crkraWmH1VkcjYX9ag), NIM_ALIGNOF(tyObject_ValueError__NZcE89crkraWmH1VkcjYX9ag));
				(*T41_).Sup.Sup.Sup.m_type = (&NTIv2__NZcE89crkraWmH1VkcjYX9ag_);
				(*T41_).Sup.Sup.name = "ValueError";
				T42_.len = 0; T42_.p = NIM_NIL;
				colontmpD__5 = dollar___systemZdollars_u14(((NU8)(s_p0.p->data[inputIndex_1])));
				if (NIM_UNLIKELY(*nimErr_)) goto LA40_;
				colontmpD__6 = dollar___systemZdollars_u14(inputIndex_1);
				if (NIM_UNLIKELY(*nimErr_)) goto LA40_;
				T42_ = rawNewString(colontmpD__5.len + colontmpD__6.len + 56);
appendString((&T42_), TM__2L6xrRPz7CWDB3T1R9cDN5A_16);
appendChar((&T42_), s_p0.p->data[inputIndex_1]);
appendString((&T42_), TM__2L6xrRPz7CWDB3T1R9cDN5A_17);
appendString((&T42_), colontmpD__5);
appendString((&T42_), TM__2L6xrRPz7CWDB3T1R9cDN5A_18);
appendString((&T42_), colontmpD__6);
appendString((&T42_), TM__2L6xrRPz7CWDB3T1R9cDN5A_19);
				(*T41_).Sup.Sup.message = T42_;
				(*T41_).Sup.Sup.parent = ((Exception*) NIM_NIL);
				raiseExceptionEx((Exception*)T41_, "ValueError", "decode", "base64.nim", 232);
goto LA40_;
				{
					LA40_:;
				}
				{
					if (colontmpD__6.p && !(colontmpD__6.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__6.p);
}
					if (colontmpD__5.p && !(colontmpD__5.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__5.p);
}
				}
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			}
LA38_: ;
			inputIndex_1 += ((NI)1);
			d_1 = ((NI) (((NU8)(decodeTable__pureZbase64_u480[(((NU8)(s_p0.p->data[inputIndex_1])))- 0]))));
			{
				NimStringV2 colontmpD__7;
				NimStringV2 colontmpD__8;
				tyObject_ValueError__NZcE89crkraWmH1VkcjYX9ag* T50_;
				NimStringV2 T51_;
				if (!(d_1 == ((NI)255))) goto LA47_;
				colontmpD__7.len = 0; colontmpD__7.p = NIM_NIL;
				colontmpD__8.len = 0; colontmpD__8.p = NIM_NIL;
				T50_ = NIM_NIL;
				T50_ = (tyObject_ValueError__NZcE89crkraWmH1VkcjYX9ag*) nimNewObj(sizeof(tyObject_ValueError__NZcE89crkraWmH1VkcjYX9ag), NIM_ALIGNOF(tyObject_ValueError__NZcE89crkraWmH1VkcjYX9ag));
				(*T50_).Sup.Sup.Sup.m_type = (&NTIv2__NZcE89crkraWmH1VkcjYX9ag_);
				(*T50_).Sup.Sup.name = "ValueError";
				T51_.len = 0; T51_.p = NIM_NIL;
				colontmpD__7 = dollar___systemZdollars_u14(((NU8)(s_p0.p->data[inputIndex_1])));
				if (NIM_UNLIKELY(*nimErr_)) goto LA49_;
				colontmpD__8 = dollar___systemZdollars_u14(inputIndex_1);
				if (NIM_UNLIKELY(*nimErr_)) goto LA49_;
				T51_ = rawNewString(colontmpD__7.len + colontmpD__8.len + 56);
appendString((&T51_), TM__2L6xrRPz7CWDB3T1R9cDN5A_20);
appendChar((&T51_), s_p0.p->data[inputIndex_1]);
appendString((&T51_), TM__2L6xrRPz7CWDB3T1R9cDN5A_21);
appendString((&T51_), colontmpD__7);
appendString((&T51_), TM__2L6xrRPz7CWDB3T1R9cDN5A_22);
appendString((&T51_), colontmpD__8);
appendString((&T51_), TM__2L6xrRPz7CWDB3T1R9cDN5A_23);
				(*T50_).Sup.Sup.message = T51_;
				(*T50_).Sup.Sup.parent = ((Exception*) NIM_NIL);
				raiseExceptionEx((Exception*)T50_, "ValueError", "decode", "base64.nim", 232);
goto LA49_;
				{
					LA49_:;
				}
				{
					if (colontmpD__8.p && !(colontmpD__8.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__8.p);
}
					if (colontmpD__7.p && !(colontmpD__7.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__7.p);
}
				}
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			}
LA47_: ;
			inputIndex_1 += ((NI)1);
			nimPrepareStrMutationV2((&result));
			result.p->data[outputIndex_1] = ((NIM_CHAR) ((NI)((NI)((NI)((NU64)(a_1) << (NU64)(((NI)2) & (64 - 1))) | (NI)((NI64)(b_1) >> (NU64)(((NI)4) & (64 - 1)))) & ((NI)255))));
			outputIndex_1 += ((NI)1);
			nimPrepareStrMutationV2((&result));
			result.p->data[outputIndex_1] = ((NIM_CHAR) ((NI)((NI)((NI)((NU64)(b_1) << (NU64)(((NI)4) & (64 - 1))) | (NI)((NI64)(c_1) >> (NU64)(((NI)2) & (64 - 1)))) & ((NI)255))));
			outputIndex_1 += ((NI)1);
			nimPrepareStrMutationV2((&result));
			result.p->data[outputIndex_1] = ((NIM_CHAR) ((NI)((NI)((NI)((NU64)(c_1) << (NU64)(((NI)6) & (64 - 1))) | (NI)((NI64)(d_1) >> (NU64)(((NI)0) & (64 - 1)))) & ((NI)255))));
			outputIndex_1 += ((NI)1);
		} LA11: ;
	} LA10: ;
	leftLen_1 = ((NI)((NI)(inputIndex_1 - inputLen_1) % ((NI)4)) > 0? ((NI)((NI)(inputIndex_1 - inputLen_1) % ((NI)4))) : -((NI)((NI)(inputIndex_1 - inputLen_1) % ((NI)4))));
	{
		NI a_2;
		NI b_2;
		if (!(leftLen_1 == ((NI)2))) goto LA56_;
		a_2 = ((NI) (((NU8)(decodeTable__pureZbase64_u480[(((NU8)(s_p0.p->data[inputIndex_1])))- 0]))));
		{
			NimStringV2 colontmpD__9;
			NimStringV2 colontmpD__10;
			tyObject_ValueError__NZcE89crkraWmH1VkcjYX9ag* T63_;
			NimStringV2 T64_;
			if (!(a_2 == ((NI)255))) goto LA60_;
			colontmpD__9.len = 0; colontmpD__9.p = NIM_NIL;
			colontmpD__10.len = 0; colontmpD__10.p = NIM_NIL;
			T63_ = NIM_NIL;
			T63_ = (tyObject_ValueError__NZcE89crkraWmH1VkcjYX9ag*) nimNewObj(sizeof(tyObject_ValueError__NZcE89crkraWmH1VkcjYX9ag), NIM_ALIGNOF(tyObject_ValueError__NZcE89crkraWmH1VkcjYX9ag));
			(*T63_).Sup.Sup.Sup.m_type = (&NTIv2__NZcE89crkraWmH1VkcjYX9ag_);
			(*T63_).Sup.Sup.name = "ValueError";
			T64_.len = 0; T64_.p = NIM_NIL;
			colontmpD__9 = dollar___systemZdollars_u14(((NU8)(s_p0.p->data[inputIndex_1])));
			if (NIM_UNLIKELY(*nimErr_)) goto LA62_;
			colontmpD__10 = dollar___systemZdollars_u14(inputIndex_1);
			if (NIM_UNLIKELY(*nimErr_)) goto LA62_;
			T64_ = rawNewString(colontmpD__9.len + colontmpD__10.len + 56);
appendString((&T64_), TM__2L6xrRPz7CWDB3T1R9cDN5A_24);
appendChar((&T64_), s_p0.p->data[inputIndex_1]);
appendString((&T64_), TM__2L6xrRPz7CWDB3T1R9cDN5A_25);
appendString((&T64_), colontmpD__9);
appendString((&T64_), TM__2L6xrRPz7CWDB3T1R9cDN5A_26);
appendString((&T64_), colontmpD__10);
appendString((&T64_), TM__2L6xrRPz7CWDB3T1R9cDN5A_27);
			(*T63_).Sup.Sup.message = T64_;
			(*T63_).Sup.Sup.parent = ((Exception*) NIM_NIL);
			raiseExceptionEx((Exception*)T63_, "ValueError", "decode", "base64.nim", 232);
goto LA62_;
			{
				LA62_:;
			}
			{
				if (colontmpD__10.p && !(colontmpD__10.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__10.p);
}
				if (colontmpD__9.p && !(colontmpD__9.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__9.p);
}
			}
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
LA60_: ;
		inputIndex_1 += ((NI)1);
		b_2 = ((NI) (((NU8)(decodeTable__pureZbase64_u480[(((NU8)(s_p0.p->data[inputIndex_1])))- 0]))));
		{
			NimStringV2 colontmpD__11;
			NimStringV2 colontmpD__12;
			tyObject_ValueError__NZcE89crkraWmH1VkcjYX9ag* T72_;
			NimStringV2 T73_;
			if (!(b_2 == ((NI)255))) goto LA69_;
			colontmpD__11.len = 0; colontmpD__11.p = NIM_NIL;
			colontmpD__12.len = 0; colontmpD__12.p = NIM_NIL;
			T72_ = NIM_NIL;
			T72_ = (tyObject_ValueError__NZcE89crkraWmH1VkcjYX9ag*) nimNewObj(sizeof(tyObject_ValueError__NZcE89crkraWmH1VkcjYX9ag), NIM_ALIGNOF(tyObject_ValueError__NZcE89crkraWmH1VkcjYX9ag));
			(*T72_).Sup.Sup.Sup.m_type = (&NTIv2__NZcE89crkraWmH1VkcjYX9ag_);
			(*T72_).Sup.Sup.name = "ValueError";
			T73_.len = 0; T73_.p = NIM_NIL;
			colontmpD__11 = dollar___systemZdollars_u14(((NU8)(s_p0.p->data[inputIndex_1])));
			if (NIM_UNLIKELY(*nimErr_)) goto LA71_;
			colontmpD__12 = dollar___systemZdollars_u14(inputIndex_1);
			if (NIM_UNLIKELY(*nimErr_)) goto LA71_;
			T73_ = rawNewString(colontmpD__11.len + colontmpD__12.len + 56);
appendString((&T73_), TM__2L6xrRPz7CWDB3T1R9cDN5A_28);
appendChar((&T73_), s_p0.p->data[inputIndex_1]);
appendString((&T73_), TM__2L6xrRPz7CWDB3T1R9cDN5A_29);
appendString((&T73_), colontmpD__11);
appendString((&T73_), TM__2L6xrRPz7CWDB3T1R9cDN5A_30);
appendString((&T73_), colontmpD__12);
appendString((&T73_), TM__2L6xrRPz7CWDB3T1R9cDN5A_31);
			(*T72_).Sup.Sup.message = T73_;
			(*T72_).Sup.Sup.parent = ((Exception*) NIM_NIL);
			raiseExceptionEx((Exception*)T72_, "ValueError", "decode", "base64.nim", 232);
goto LA71_;
			{
				LA71_:;
			}
			{
				if (colontmpD__12.p && !(colontmpD__12.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__12.p);
}
				if (colontmpD__11.p && !(colontmpD__11.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__11.p);
}
			}
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
LA69_: ;
		inputIndex_1 += ((NI)1);
		nimPrepareStrMutationV2((&result));
		result.p->data[outputIndex_1] = ((NIM_CHAR) ((NI)((NI)((NI)((NU64)(a_2) << (NU64)(((NI)2) & (64 - 1))) | (NI)((NI64)(b_2) >> (NU64)(((NI)4) & (64 - 1)))) & ((NI)255))));
		outputIndex_1 += ((NI)1);
	}
	goto LA54_;
LA56_: ;
	{
		NI a_3;
		NI b_3;
		NI c_2;
		if (!(leftLen_1 == ((NI)3))) goto LA77_;
		a_3 = ((NI) (((NU8)(decodeTable__pureZbase64_u480[(((NU8)(s_p0.p->data[inputIndex_1])))- 0]))));
		{
			NimStringV2 colontmpD__13;
			NimStringV2 colontmpD__14;
			tyObject_ValueError__NZcE89crkraWmH1VkcjYX9ag* T84_;
			NimStringV2 T85_;
			if (!(a_3 == ((NI)255))) goto LA81_;
			colontmpD__13.len = 0; colontmpD__13.p = NIM_NIL;
			colontmpD__14.len = 0; colontmpD__14.p = NIM_NIL;
			T84_ = NIM_NIL;
			T84_ = (tyObject_ValueError__NZcE89crkraWmH1VkcjYX9ag*) nimNewObj(sizeof(tyObject_ValueError__NZcE89crkraWmH1VkcjYX9ag), NIM_ALIGNOF(tyObject_ValueError__NZcE89crkraWmH1VkcjYX9ag));
			(*T84_).Sup.Sup.Sup.m_type = (&NTIv2__NZcE89crkraWmH1VkcjYX9ag_);
			(*T84_).Sup.Sup.name = "ValueError";
			T85_.len = 0; T85_.p = NIM_NIL;
			colontmpD__13 = dollar___systemZdollars_u14(((NU8)(s_p0.p->data[inputIndex_1])));
			if (NIM_UNLIKELY(*nimErr_)) goto LA83_;
			colontmpD__14 = dollar___systemZdollars_u14(inputIndex_1);
			if (NIM_UNLIKELY(*nimErr_)) goto LA83_;
			T85_ = rawNewString(colontmpD__13.len + colontmpD__14.len + 56);
appendString((&T85_), TM__2L6xrRPz7CWDB3T1R9cDN5A_32);
appendChar((&T85_), s_p0.p->data[inputIndex_1]);
appendString((&T85_), TM__2L6xrRPz7CWDB3T1R9cDN5A_33);
appendString((&T85_), colontmpD__13);
appendString((&T85_), TM__2L6xrRPz7CWDB3T1R9cDN5A_34);
appendString((&T85_), colontmpD__14);
appendString((&T85_), TM__2L6xrRPz7CWDB3T1R9cDN5A_35);
			(*T84_).Sup.Sup.message = T85_;
			(*T84_).Sup.Sup.parent = ((Exception*) NIM_NIL);
			raiseExceptionEx((Exception*)T84_, "ValueError", "decode", "base64.nim", 232);
goto LA83_;
			{
				LA83_:;
			}
			{
				if (colontmpD__14.p && !(colontmpD__14.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__14.p);
}
				if (colontmpD__13.p && !(colontmpD__13.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__13.p);
}
			}
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
LA81_: ;
		inputIndex_1 += ((NI)1);
		b_3 = ((NI) (((NU8)(decodeTable__pureZbase64_u480[(((NU8)(s_p0.p->data[inputIndex_1])))- 0]))));
		{
			NimStringV2 colontmpD__15;
			NimStringV2 colontmpD__16;
			tyObject_ValueError__NZcE89crkraWmH1VkcjYX9ag* T93_;
			NimStringV2 T94_;
			if (!(b_3 == ((NI)255))) goto LA90_;
			colontmpD__15.len = 0; colontmpD__15.p = NIM_NIL;
			colontmpD__16.len = 0; colontmpD__16.p = NIM_NIL;
			T93_ = NIM_NIL;
			T93_ = (tyObject_ValueError__NZcE89crkraWmH1VkcjYX9ag*) nimNewObj(sizeof(tyObject_ValueError__NZcE89crkraWmH1VkcjYX9ag), NIM_ALIGNOF(tyObject_ValueError__NZcE89crkraWmH1VkcjYX9ag));
			(*T93_).Sup.Sup.Sup.m_type = (&NTIv2__NZcE89crkraWmH1VkcjYX9ag_);
			(*T93_).Sup.Sup.name = "ValueError";
			T94_.len = 0; T94_.p = NIM_NIL;
			colontmpD__15 = dollar___systemZdollars_u14(((NU8)(s_p0.p->data[inputIndex_1])));
			if (NIM_UNLIKELY(*nimErr_)) goto LA92_;
			colontmpD__16 = dollar___systemZdollars_u14(inputIndex_1);
			if (NIM_UNLIKELY(*nimErr_)) goto LA92_;
			T94_ = rawNewString(colontmpD__15.len + colontmpD__16.len + 56);
appendString((&T94_), TM__2L6xrRPz7CWDB3T1R9cDN5A_36);
appendChar((&T94_), s_p0.p->data[inputIndex_1]);
appendString((&T94_), TM__2L6xrRPz7CWDB3T1R9cDN5A_37);
appendString((&T94_), colontmpD__15);
appendString((&T94_), TM__2L6xrRPz7CWDB3T1R9cDN5A_38);
appendString((&T94_), colontmpD__16);
appendString((&T94_), TM__2L6xrRPz7CWDB3T1R9cDN5A_39);
			(*T93_).Sup.Sup.message = T94_;
			(*T93_).Sup.Sup.parent = ((Exception*) NIM_NIL);
			raiseExceptionEx((Exception*)T93_, "ValueError", "decode", "base64.nim", 232);
goto LA92_;
			{
				LA92_:;
			}
			{
				if (colontmpD__16.p && !(colontmpD__16.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__16.p);
}
				if (colontmpD__15.p && !(colontmpD__15.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__15.p);
}
			}
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
LA90_: ;
		inputIndex_1 += ((NI)1);
		c_2 = ((NI) (((NU8)(decodeTable__pureZbase64_u480[(((NU8)(s_p0.p->data[inputIndex_1])))- 0]))));
		{
			NimStringV2 colontmpD__17;
			NimStringV2 colontmpD__18;
			tyObject_ValueError__NZcE89crkraWmH1VkcjYX9ag* T102_;
			NimStringV2 T103_;
			if (!(c_2 == ((NI)255))) goto LA99_;
			colontmpD__17.len = 0; colontmpD__17.p = NIM_NIL;
			colontmpD__18.len = 0; colontmpD__18.p = NIM_NIL;
			T102_ = NIM_NIL;
			T102_ = (tyObject_ValueError__NZcE89crkraWmH1VkcjYX9ag*) nimNewObj(sizeof(tyObject_ValueError__NZcE89crkraWmH1VkcjYX9ag), NIM_ALIGNOF(tyObject_ValueError__NZcE89crkraWmH1VkcjYX9ag));
			(*T102_).Sup.Sup.Sup.m_type = (&NTIv2__NZcE89crkraWmH1VkcjYX9ag_);
			(*T102_).Sup.Sup.name = "ValueError";
			T103_.len = 0; T103_.p = NIM_NIL;
			colontmpD__17 = dollar___systemZdollars_u14(((NU8)(s_p0.p->data[inputIndex_1])));
			if (NIM_UNLIKELY(*nimErr_)) goto LA101_;
			colontmpD__18 = dollar___systemZdollars_u14(inputIndex_1);
			if (NIM_UNLIKELY(*nimErr_)) goto LA101_;
			T103_ = rawNewString(colontmpD__17.len + colontmpD__18.len + 56);
appendString((&T103_), TM__2L6xrRPz7CWDB3T1R9cDN5A_40);
appendChar((&T103_), s_p0.p->data[inputIndex_1]);
appendString((&T103_), TM__2L6xrRPz7CWDB3T1R9cDN5A_41);
appendString((&T103_), colontmpD__17);
appendString((&T103_), TM__2L6xrRPz7CWDB3T1R9cDN5A_42);
appendString((&T103_), colontmpD__18);
appendString((&T103_), TM__2L6xrRPz7CWDB3T1R9cDN5A_43);
			(*T102_).Sup.Sup.message = T103_;
			(*T102_).Sup.Sup.parent = ((Exception*) NIM_NIL);
			raiseExceptionEx((Exception*)T102_, "ValueError", "decode", "base64.nim", 232);
goto LA101_;
			{
				LA101_:;
			}
			{
				if (colontmpD__18.p && !(colontmpD__18.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__18.p);
}
				if (colontmpD__17.p && !(colontmpD__17.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__17.p);
}
			}
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
LA99_: ;
		inputIndex_1 += ((NI)1);
		nimPrepareStrMutationV2((&result));
		result.p->data[outputIndex_1] = ((NIM_CHAR) ((NI)((NI)((NI)((NU64)(a_3) << (NU64)(((NI)2) & (64 - 1))) | (NI)((NI64)(b_3) >> (NU64)(((NI)4) & (64 - 1)))) & ((NI)255))));
		outputIndex_1 += ((NI)1);
		nimPrepareStrMutationV2((&result));
		result.p->data[outputIndex_1] = ((NIM_CHAR) ((NI)((NI)((NI)((NU64)(b_3) << (NU64)(((NI)4) & (64 - 1))) | (NI)((NI64)(c_2) >> (NU64)(((NI)2) & (64 - 1)))) & ((NI)255))));
		outputIndex_1 += ((NI)1);
	}
	goto LA54_;
LA77_: ;
LA54_: ;
	setLengthStrV2((&result), (outputIndex_1));
	}BeforeRet_: ;
	return result;
}
