/* Generated by Nim Compiler v2.2.10 */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   x86_64-w64-mingw32-gcc -c -w -fmax-errors=3 -mno-ms-bitfields -fno-strict-aliasing -DWIN32_LEAN_AND_MEAN -Os -fno-ident   -I/home/kali/.choosenim/toolchains/nim-2.2.10/lib -I/home/kali/c2/agents/agent-nim -o /home/kali/c2/agents/agent-nim/nimcache_test/@pstd@sprivate@sospaths2.nim.c.o /home/kali/c2/agents/agent-nim/nimcache_test/@pstd@sprivate@sospaths2.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_WideCStringObj__jQbOKocsbu7Z9bKTSFtX4TQ tyObject_WideCStringObj__jQbOKocsbu7Z9bKTSFtX4TQ;
typedef struct tyTuple__UV3llMMYFckfui8YMBuUZA tyTuple__UV3llMMYFckfui8YMBuUZA;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tyObject_WideCStringObj__jQbOKocsbu7Z9bKTSFtX4TQ {
	NI bytes;
	NI16* data;
};
typedef N_STDCALL_PTR(NI32, tyProc__aMOow6Lp4fo8dW2ko9aU3pg) (NI32 nBufferLength_p0, NI16* lpBuffer_p1);
typedef NI16 tyUncheckedArray__Tyd4y3haUOOHTj71TPIRag[1];
struct tyTuple__UV3llMMYFckfui8YMBuUZA {
	NimStringV2 Field0;
	NimStringV2 Field1;
};
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__system_u2188)(void* a_p0, int v_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(tyObject_WideCStringObj__jQbOKocsbu7Z9bKTSFtX4TQ, newWideCString__stdZwidestrs_u278)(NI size_p0);
static N_INLINE(NI16*, toWideCString__stdZwidestrs_u49)(tyObject_WideCStringObj__jQbOKocsbu7Z9bKTSFtX4TQ x_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseOSError__stdZoserrors_u122)(NI32 errorCode_p0, NimStringV2 additionalInfo_p1);
N_LIB_PRIVATE N_NIMCALL(NI32, osLastError__stdZoserrors_u125)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___stdZwidestrs_u35)(tyObject_WideCStringObj__jQbOKocsbu7Z9bKTSFtX4TQ* a_p0, tyObject_WideCStringObj__jQbOKocsbu7Z9bKTSFtX4TQ b_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___stdZwidestrs_u7)(tyObject_WideCStringObj__jQbOKocsbu7Z9bKTSFtX4TQ a_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___system_u2729)(NimStringV2* dest_p0, NimStringV2 src_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___stdZwidestrs_u397)(tyObject_WideCStringObj__jQbOKocsbu7Z9bKTSFtX4TQ s_p0, NI estimate_p1, NI replacement_p2);
static N_INLINE(void, eqdestroy___system_u281)(NimStringV2 x_p0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_NIMCALL(NimStringV2, rawNewString)(NI cap_p0);
N_LIB_PRIVATE N_NIMCALL(void, joinPathImpl__stdZprivateZospaths2_u48)(NimStringV2* result_p0, NI* state_p1, NimStringV2 tail_p2);
static N_INLINE(NIM_CHAR, X5BX5D___system_u8612)(NimStringV2 s_p0, NI i_p1);
static N_INLINE(NIM_CHAR*, X5BX5D___system_u8664)(NimStringV2* s_p0, NI i_p1);
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2* s_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimPrepareStrMutationImpl__system_u2462)(NimStringV2* s_p0);
N_LIB_PRIVATE N_NIMCALL(void, normalizePathEnd__stdZprivateZospaths2_u19)(NimStringV2* path_p0, NIM_BOOL trailingSep_p1);
N_LIB_PRIVATE N_NIMCALL(void, setLengthStrV2)(NimStringV2* s_p0, NI newLen_p1);
static N_INLINE(void, nimAddCharV1)(NimStringV2* s_p0, NIM_CHAR c_p1);
N_LIB_PRIVATE N_NIMCALL(void, prepareAdd)(NimStringV2* s_p0, NI addLen_p1);
N_LIB_PRIVATE N_NIMCALL(void, addNormalizePath__pureZpathnorm_u87)(NimStringV2 x_p0, NimStringV2* result_p1, NI* state_p2, NIM_CHAR dirSep_p3);
N_LIB_PRIVATE N_NIMCALL(void, nossplitPath)(NimStringV2 path_p0, tyTuple__UV3llMMYFckfui8YMBuUZA* Result);
N_LIB_PRIVATE N_NIMCALL(void, splitDrive__stdZprivateZntpath_u2)(NimStringV2 p_p0, tyTuple__UV3llMMYFckfui8YMBuUZA* Result);
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___system_u2720)(NimStringV2* dest_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, substr__system_u9189)(NimStringV2 s_p0, NI first_p1, NI last_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, substr__system_u9202)(NimStringV2 s_p0, NI first_p1);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___stdZprivateZntpath_u119)(tyTuple__UV3llMMYFckfui8YMBuUZA* dest_p0);
static const struct {
  NI cap; NIM_CHAR data[0+1];
} TM__O1zDbSYyG8zQytyoZAh0dg_2 = { 0 | NIM_STRLIT_FLAG, "" };
static const NimStringV2 TM__O1zDbSYyG8zQytyoZAh0dg_3 = {0, (NimStrPayload*)&TM__O1zDbSYyG8zQytyoZAh0dg_2};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__O1zDbSYyG8zQytyoZAh0dg_4 = { 1 | NIM_STRLIT_FLAG, "\\" };
static const NimStringV2 TM__O1zDbSYyG8zQytyoZAh0dg_5 = {1, (NimStrPayload*)&TM__O1zDbSYyG8zQytyoZAh0dg_4};
static const NimStringV2 TM__O1zDbSYyG8zQytyoZAh0dg_6 = {0, (NimStrPayload*)&TM__O1zDbSYyG8zQytyoZAh0dg_2};
extern tyProc__aMOow6Lp4fo8dW2ko9aU3pg Dl_1509949622_;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4172;
static N_INLINE(void, nimSetMem__system_u2188)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
	nimSetMem__system_u2188(p_p0, ((int)0), size_p1);
}
static N_INLINE(NI16*, toWideCString__stdZwidestrs_u49)(tyObject_WideCStringObj__jQbOKocsbu7Z9bKTSFtX4TQ x_p0) {
	NI16* result;
	result = x_p0.data;
	return result;
}
static N_INLINE(void, eqdestroy___system_u281)(NimStringV2 x_p0) {
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4172);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nosgetCurrentDir)(void) {
	NimStringV2 result;
	tyObject_WideCStringObj__jQbOKocsbu7Z9bKTSFtX4TQ res_1;
	NI32 bufsize_1;
NIM_BOOL oldNimErrFin1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimZeroMem((void*)(&res_1), sizeof(tyObject_WideCStringObj__jQbOKocsbu7Z9bKTSFtX4TQ));
	bufsize_1 = ((NI32)260);
	res_1 = newWideCString__stdZwidestrs_u278(((NI) (bufsize_1)));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		while (1) {
			NI32 L_1;
			NI16* T4_;
			T4_ = (NI16*)0;
			T4_ = toWideCString__stdZwidestrs_u49(res_1);
			if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
			L_1 = Dl_1509949622_(bufsize_1, T4_);
			{
				NI32 T9_;
				if (!(L_1 == ((NI32)0))) goto LA7_;
				T9_ = (NI32)0;
				T9_ = osLastError__stdZoserrors_u125();
				if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
				raiseOSError__stdZoserrors_u122(T9_, TM__O1zDbSYyG8zQytyoZAh0dg_3);
				if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
			}
			goto LA5_;
LA7_: ;
			{
				tyObject_WideCStringObj__jQbOKocsbu7Z9bKTSFtX4TQ T13_;
				if (!(bufsize_1 < L_1)) goto LA11_;
				T13_ = newWideCString__stdZwidestrs_u278(((NI) (L_1)));
				if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___stdZwidestrs_u7(T13_); goto LA1_;}
				eqsink___stdZwidestrs_u35((&res_1), T13_);
				if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
				bufsize_1 = L_1;
			}
			goto LA5_;
LA11_: ;
			{
				NimStringV2 T15_;
				T15_.len = 0; T15_.p = NIM_NIL;
				T15_ = dollar___stdZwidestrs_u397(res_1, ((NI) (L_1)), ((NI)65533));
				if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u281(T15_); goto LA1_;}
				eqsink___system_u2729((&result), T15_);
				goto LA2;
			}
LA5_: ;
		}
	} LA2: ;
	{
		LA1_:;
	}
	{
		oldNimErrFin1_ = *nimErr_; *nimErr_ = NIM_FALSE;
		eqdestroy___stdZwidestrs_u7(res_1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		*nimErr_ = oldNimErrFin1_;
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NIM_CHAR, X5BX5D___system_u8612)(NimStringV2 s_p0, NI i_p1) {
	NIM_CHAR result;
	result = s_p0.p->data[(NI)(s_p0.len - i_p1)];
	return result;
}
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2* s_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = !(((*s_p0).p == ((NimStrPayload*) NIM_NIL)));
		if (!(T3_)) goto LA4_;
		T3_ = ((NI)((*(*s_p0).p).cap & ((NI)IL64(4611686018427387904))) == ((NI)IL64(4611686018427387904)));
LA4_: ;
		if (!T3_) goto LA5_;
		nimPrepareStrMutationImpl__system_u2462(s_p0);
	}
LA5_: ;
}
static N_INLINE(NIM_CHAR*, X5BX5D___system_u8664)(NimStringV2* s_p0, NI i_p1) {
	NIM_CHAR* result;
	nimPrepareStrMutationV2((&(*s_p0)));
	result = (&(*s_p0).p->data[(NI)((*s_p0).len - i_p1)]);
	return result;
}
static N_INLINE(void, nimAddCharV1)(NimStringV2* s_p0, NIM_CHAR c_p1) {
	prepareAdd(s_p0, ((NI)1));
	(*(*s_p0).p).data[(*s_p0).len] = c_p1;
	(*s_p0).len += ((NI)1);
	(*(*s_p0).p).data[(*s_p0).len] = 0;
}
N_LIB_PRIVATE N_NIMCALL(void, normalizePathEnd__stdZprivateZospaths2_u19)(NimStringV2* path_p0, NIM_BOOL trailingSep_p1) {
	NI i_1;
{	{
		if (!((*path_p0).len == ((NI)0))) goto LA3_;
		goto BeforeRet_;
	}
LA3_: ;
	i_1 = (*path_p0).len;
	{
		while (1) {
			if (!(((NI)1) <= i_1)) goto LA6;
			{
				if (!(((NU8)((*path_p0).p->data[(NI)(i_1 - ((NI)1))])) == ((NU8)(92)) || ((NU8)((*path_p0).p->data[(NI)(i_1 - ((NI)1))])) == ((NU8)(47)))) goto LA9_;
				i_1 -= ((NI)1);
			}
			goto LA7_;
LA9_: ;
			{
				NIM_BOOL T12_;
				NIM_BOOL T13_;
				T12_ = (NIM_BOOL)0;
				T13_ = (NIM_BOOL)0;
				T13_ = ((NU8)((*path_p0).p->data[(NI)(i_1 - ((NI)1))]) == (NU8)(46));
				if (!(T13_)) goto LA14_;
				T13_ = (((NI)2) <= i_1);
LA14_: ;
				T12_ = T13_;
				if (!(T12_)) goto LA15_;
				T12_ = (((NU8)((*path_p0).p->data[(NI)(i_1 - ((NI)2))])) == ((NU8)(92)) || ((NU8)((*path_p0).p->data[(NI)(i_1 - ((NI)2))])) == ((NU8)(47)));
LA15_: ;
				if (!T12_) goto LA16_;
				i_1 -= ((NI)1);
			}
			goto LA7_;
LA16_: ;
			{
				goto LA5;
			}
LA7_: ;
		} LA6: ;
	} LA5: ;
	{
		if (!trailingSep_p1) goto LA21_;
		setLengthStrV2((&(*path_p0)), (i_1));
		nimAddCharV1((&(*path_p0)), 92);
	}
	goto LA19_;
LA21_: ;
	{
		if (!(((NI)0) < i_1)) goto LA24_;
		setLengthStrV2((&(*path_p0)), (i_1));
	}
	goto LA19_;
LA24_: ;
	{
		eqsink___system_u2729((&(*path_p0)), TM__O1zDbSYyG8zQytyoZAh0dg_5);
	}
LA19_: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, joinPathImpl__stdZprivateZospaths2_u48)(NimStringV2* result_p0, NI* state_p1, NimStringV2 tail_p2) {
	NIM_BOOL trailingSep_1;
	NIM_BOOL T1_;
	NIM_BOOL T2_;
	NIM_CHAR T4_;
	NIM_BOOL T6_;
	NIM_BOOL T8_;
	NIM_CHAR* T10_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	T1_ = (NIM_BOOL)0;
	T2_ = (NIM_BOOL)0;
	T2_ = (((NI)0) < tail_p2.len);
	if (!(T2_)) goto LA3_;
	T4_ = (NIM_CHAR)0;
	T4_ = X5BX5D___system_u8612(tail_p2, ((NI)1));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T2_ = (((NU8)(T4_)) == ((NU8)(92)) || ((NU8)(T4_)) == ((NU8)(47)));
LA3_: ;
	T1_ = T2_;
	if (T1_) goto LA5_;
	T6_ = (NIM_BOOL)0;
	T6_ = (tail_p2.len == ((NI)0));
	if (!(T6_)) goto LA7_;
	T8_ = (NIM_BOOL)0;
	T8_ = (((NI)0) < (*result_p0).len);
	if (!(T8_)) goto LA9_;
	T10_ = (NIM_CHAR*)0;
	T10_ = X5BX5D___system_u8664(result_p0, ((NI)1));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T8_ = (((NU8)((*T10_))) == ((NU8)(92)) || ((NU8)((*T10_))) == ((NU8)(47)));
LA9_: ;
	T6_ = T8_;
LA7_: ;
	T1_ = T6_;
LA5_: ;
	trailingSep_1 = T1_;
	normalizePathEnd__stdZprivateZospaths2_u19(result_p0, NIM_FALSE);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	addNormalizePath__pureZpathnorm_u87(tail_p2, result_p0, state_p1, 92);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	normalizePathEnd__stdZprivateZospaths2_u19(result_p0, trailingSep_1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nosjoinPath)(NimStringV2 head_p0, NimStringV2 tail_p1) {
	NimStringV2 result;
	NI state_1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	result = rawNewString(((NI)(head_p0.len + tail_p1.len)));
	state_1 = ((NI)0);
	joinPathImpl__stdZprivateZospaths2_u48((&result), (&state_1), head_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	joinPathImpl__stdZprivateZospaths2_u48((&result), (&state_1), tail_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, nossplitPath)(NimStringV2 path_p0, tyTuple__UV3llMMYFckfui8YMBuUZA* Result) {
	tyTuple__UV3llMMYFckfui8YMBuUZA tmpTuple_1;
	NimStringV2 drive_1;
	NimStringV2 splitpath_1;
	NI stop_1;
	NI sepPos_1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)Result, sizeof(tyTuple__UV3llMMYFckfui8YMBuUZA));
	nimZeroMem((void*)(&tmpTuple_1), sizeof(tyTuple__UV3llMMYFckfui8YMBuUZA));
	drive_1.len = 0; drive_1.p = NIM_NIL;
	splitpath_1.len = 0; splitpath_1.p = NIM_NIL;
	splitDrive__stdZprivateZntpath_u2(path_p0, (&tmpTuple_1));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	drive_1 = tmpTuple_1.Field0;
	eqwasMoved___system_u2720((&tmpTuple_1.Field0));
	splitpath_1 = tmpTuple_1.Field1;
	eqwasMoved___system_u2720((&tmpTuple_1.Field1));
	stop_1 = drive_1.len;
	sepPos_1 = ((NI)-1);
	{
		NI i_1;
		NI colontmp_;
		NI res_1;
		i_1 = (NI)0;
		colontmp_ = (NI)0;
		colontmp_ = (NI)(path_p0.len - ((NI)1));
		res_1 = colontmp_;
		{
			while (1) {
				if (!(stop_1 <= res_1)) goto LA4;
				i_1 = ((NI) (res_1));
				{
					if (!(((NU8)(path_p0.p->data[i_1])) == ((NU8)(92)) || ((NU8)(path_p0.p->data[i_1])) == ((NU8)(47)))) goto LA7_;
					sepPos_1 = i_1;
					goto LA2;
				}
LA7_: ;
				res_1 -= ((NI)1);
			} LA4: ;
		}
	} LA2: ;
	{
		NI colontmpD_;
		NI colontmpD__2;
		NI T13_;
		NimStringV2 T20_;
		NimStringV2 T21_;
		if (!(((NI)0) <= sepPos_1)) goto LA11_;
		colontmpD_ = (NI)0;
		colontmpD__2 = (NI)0;
		T13_ = (NI)0;
		{
			NIM_BOOL T16_;
			T16_ = (NIM_BOOL)0;
			T16_ = NIM_LIKELY((((NI)1) <= sepPos_1));
			if (!T16_) goto LA17_;
			colontmpD_ = (NI)(sepPos_1 - ((NI)1));
			T13_ = colontmpD_;
		}
		goto LA14_;
LA17_: ;
		{
			colontmpD__2 = ((NI)0);
			T13_ = colontmpD__2;
		}
LA14_: ;
		T20_.len = 0; T20_.p = NIM_NIL;
		T20_ = substr__system_u9189(path_p0, ((NI)0), T13_);
		eqsink___system_u2729((&(*Result).Field0), T20_);
		T21_.len = 0; T21_.p = NIM_NIL;
		T21_ = substr__system_u9202(path_p0, (NI)(sepPos_1 + ((NI)1)));
		eqsink___system_u2729((&(*Result).Field1), T21_);
	}
	goto LA9_;
LA11_: ;
	{
		eqsink___system_u2729((&(*Result).Field0), drive_1);
		eqwasMoved___system_u2720((&drive_1));
		eqsink___system_u2729((&(*Result).Field1), splitpath_1);
		eqwasMoved___system_u2720((&splitpath_1));
	}
LA9_: ;
	{
		LA1_:;
	}
	{
		if (splitpath_1.p && !(splitpath_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(splitpath_1.p);
}
		if (drive_1.p && !(drive_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(drive_1.p);
}
		eqdestroy___stdZprivateZntpath_u119((&tmpTuple_1));
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nosextractFilename)(NimStringV2 path_p0) {
	NimStringV2 result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (path_p0.len == ((NI)0));
		if (T3_) goto LA4_;
		T3_ = (((NU8)(path_p0.p->data[(NI)(path_p0.len - ((NI)1))])) == ((NU8)(92)) || ((NU8)(path_p0.p->data[(NI)(path_p0.len - ((NI)1))])) == ((NU8)(47)));
LA4_: ;
		if (!T3_) goto LA5_;
		result = TM__O1zDbSYyG8zQytyoZAh0dg_6;
	}
	goto LA1_;
LA5_: ;
	{
		tyTuple__UV3llMMYFckfui8YMBuUZA colontmpD_;
		nimZeroMem((void*)(&colontmpD_), sizeof(tyTuple__UV3llMMYFckfui8YMBuUZA));
		nossplitPath(path_p0, (&colontmpD_));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		result = colontmpD_.Field1;
		eqwasMoved___system_u2720((&colontmpD_.Field1));
		eqdestroy___stdZprivateZntpath_u119((&colontmpD_));
	}
LA1_: ;
	}BeforeRet_: ;
	return result;
}
