/* Generated by Nim Compiler v2.2.10 */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   x86_64-w64-mingw32-gcc -c -w -fmax-errors=3 -mno-ms-bitfields -fno-strict-aliasing -DWIN32_LEAN_AND_MEAN -Os -fno-ident   -I/home/kali/.choosenim/toolchains/nim-2.2.10/lib -I/home/kali/c2/agents/agent-nim -o /home/kali/c2/agents/agent-nim/nimcache_test/@punicode.nim.c.o /home/kali/c2/agents/agent-nim/nimcache_test/@punicode.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
static N_INLINE(NIM_BOOL, lteqpercent___system_u1092)(NI32 x_p0, NI32 y_p1);
N_LIB_PRIVATE N_NIMCALL(void, setLengthStrV2)(NimStringV2* s_p0, NI newLen_p1);
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2* s_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimPrepareStrMutationImpl__system_u2462)(NimStringV2* s_p0);
static const struct {
  NI cap; NIM_CHAR data[0+1];
} TM__e1RUVS0Bw7xmj9cnDPXLJMQ_2 = { 0 | NIM_STRLIT_FLAG, "" };
static const NimStringV2 TM__e1RUVS0Bw7xmj9cnDPXLJMQ_3 = {0, (NimStrPayload*)&TM__e1RUVS0Bw7xmj9cnDPXLJMQ_2};
static N_INLINE(NIM_BOOL, lteqpercent___system_u1092)(NI32 x_p0, NI32 y_p1) {
	NIM_BOOL result;
	result = ((NU32)(((NU32) (x_p0))) <= (NU32)(((NU32) (y_p1))));
	return result;
}
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2* s_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = !(((*s_p0).p == ((NimStrPayload*) NIM_NIL)));
		if (!(T3_)) goto LA4_;
		T3_ = ((NI)((*(*s_p0).p).cap & ((NI)IL64(4611686018427387904))) == ((NI)IL64(4611686018427387904)));
LA4_: ;
		if (!T3_) goto LA5_;
		nimPrepareStrMutationImpl__system_u2462(s_p0);
	}
LA5_: ;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nuctoUTF8)(NI32 c_p0) {
	NimStringV2 result;
	NI32 iX60gensym21__1;
	result = TM__e1RUVS0Bw7xmj9cnDPXLJMQ_3;
	iX60gensym21__1 = c_p0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = lteqpercent___system_u1092(iX60gensym21__1, ((NI32)127));
		if (!T3_) goto LA4_;
		setLengthStrV2((&result), ((NI)1));
		nimPrepareStrMutationV2((&result));
		result.p->data[((NI)0)] = ((NIM_CHAR) (((NI) (iX60gensym21__1))));
	}
	goto LA1_;
LA4_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = lteqpercent___system_u1092(iX60gensym21__1, ((NI32)2047));
		if (!T7_) goto LA8_;
		setLengthStrV2((&result), ((NI)2));
		nimPrepareStrMutationV2((&result));
		result.p->data[((NI)0)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)6) & (32 - 1))) | ((NI32)192))))));
		nimPrepareStrMutationV2((&result));
		result.p->data[((NI)1)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)(iX60gensym21__1 & ((NI32)63)) | ((NI32)128))))));
	}
	goto LA1_;
LA8_: ;
	{
		NIM_BOOL T11_;
		T11_ = (NIM_BOOL)0;
		T11_ = lteqpercent___system_u1092(iX60gensym21__1, ((NI32)65535));
		if (!T11_) goto LA12_;
		setLengthStrV2((&result), ((NI)3));
		nimPrepareStrMutationV2((&result));
		result.p->data[((NI)0)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)12) & (32 - 1))) | ((NI32)224))))));
		nimPrepareStrMutationV2((&result));
		result.p->data[((NI)1)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)6) & (32 - 1))) & ((NI32)63)) | ((NI32)128))))));
		nimPrepareStrMutationV2((&result));
		result.p->data[((NI)2)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)(iX60gensym21__1 & ((NI32)63)) | ((NI32)128))))));
	}
	goto LA1_;
LA12_: ;
	{
		NIM_BOOL T15_;
		T15_ = (NIM_BOOL)0;
		T15_ = lteqpercent___system_u1092(iX60gensym21__1, ((NI32)2097151));
		if (!T15_) goto LA16_;
		setLengthStrV2((&result), ((NI)4));
		nimPrepareStrMutationV2((&result));
		result.p->data[((NI)0)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)18) & (32 - 1))) | ((NI32)240))))));
		nimPrepareStrMutationV2((&result));
		result.p->data[((NI)1)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)12) & (32 - 1))) & ((NI32)63)) | ((NI32)128))))));
		nimPrepareStrMutationV2((&result));
		result.p->data[((NI)2)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)6) & (32 - 1))) & ((NI32)63)) | ((NI32)128))))));
		nimPrepareStrMutationV2((&result));
		result.p->data[((NI)3)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)(iX60gensym21__1 & ((NI32)63)) | ((NI32)128))))));
	}
	goto LA1_;
LA16_: ;
	{
		NIM_BOOL T19_;
		T19_ = (NIM_BOOL)0;
		T19_ = lteqpercent___system_u1092(iX60gensym21__1, ((NI32)67108863));
		if (!T19_) goto LA20_;
		setLengthStrV2((&result), ((NI)5));
		nimPrepareStrMutationV2((&result));
		result.p->data[((NI)0)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)24) & (32 - 1))) | ((NI32)248))))));
		nimPrepareStrMutationV2((&result));
		result.p->data[((NI)1)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)18) & (32 - 1))) & ((NI32)63)) | ((NI32)128))))));
		nimPrepareStrMutationV2((&result));
		result.p->data[((NI)2)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)12) & (32 - 1))) & ((NI32)63)) | ((NI32)128))))));
		nimPrepareStrMutationV2((&result));
		result.p->data[((NI)3)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)6) & (32 - 1))) & ((NI32)63)) | ((NI32)128))))));
		nimPrepareStrMutationV2((&result));
		result.p->data[((NI)4)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)(iX60gensym21__1 & ((NI32)63)) | ((NI32)128))))));
	}
	goto LA1_;
LA20_: ;
	{
		NIM_BOOL T23_;
		T23_ = (NIM_BOOL)0;
		T23_ = lteqpercent___system_u1092(iX60gensym21__1, ((NI32)2147483647));
		if (!T23_) goto LA24_;
		setLengthStrV2((&result), ((NI)6));
		nimPrepareStrMutationV2((&result));
		result.p->data[((NI)0)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)30) & (32 - 1))) | ((NI32)252))))));
		nimPrepareStrMutationV2((&result));
		result.p->data[((NI)1)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)24) & (32 - 1))) & ((NI32)63)) | ((NI32)128))))));
		nimPrepareStrMutationV2((&result));
		result.p->data[((NI)2)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)18) & (32 - 1))) & ((NI32)63)) | ((NI32)128))))));
		nimPrepareStrMutationV2((&result));
		result.p->data[((NI)3)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)12) & (32 - 1))) & ((NI32)63)) | ((NI32)128))))));
		nimPrepareStrMutationV2((&result));
		result.p->data[((NI)4)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)6) & (32 - 1))) & ((NI32)63)) | ((NI32)128))))));
		nimPrepareStrMutationV2((&result));
		result.p->data[((NI)5)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)(iX60gensym21__1 & ((NI32)63)) | ((NI32)128))))));
	}
	goto LA1_;
LA24_: ;
	{
	}
LA1_: ;
	return result;
}
