/* Generated by Nim Compiler v2.2.10 */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   x86_64-w64-mingw32-gcc -c -w -fmax-errors=3 -mno-ms-bitfields -fno-strict-aliasing -DWIN32_LEAN_AND_MEAN -Os -fno-ident   -I/home/kali/.choosenim/toolchains/nim-2.2.10/lib -I/home/kali/c2/agents/agent-nim -o /home/kali/c2/agents/agent-nim/nimcache_final/@pstd@ssyncio.nim.c.o /home/kali/c2/agents/agent-nim/nimcache_final/@pstd@ssyncio.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <io.h>
#include <stdio.h>
#include <fcntl.h>
#include <string.h>
#include <errno.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_WideCStringObj__jQbOKocsbu7Z9bKTSFtX4TQ tyObject_WideCStringObj__jQbOKocsbu7Z9bKTSFtX4TQ;
typedef struct tyObject_IOError__DxZ2JM72pLUaxjq9asr9aWqA tyObject_IOError__DxZ2JM72pLUaxjq9asr9aWqA;
typedef struct tyObject_CatchableError__kvV4Jp5z2ULaSZq53myi9ag tyObject_CatchableError__kvV4Jp5z2ULaSZq53myi9ag;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tySequence__UIJx6FJrflnhA9a3u1VF1vA tySequence__UIJx6FJrflnhA9a3u1VF1vA;
typedef struct tySequence__UIJx6FJrflnhA9a3u1VF1vA_Content tySequence__UIJx6FJrflnhA9a3u1VF1vA_Content;
typedef struct tyObject_StackTraceEntry__UznwMnjUHK6AxZHnP9bMXEA tyObject_StackTraceEntry__UznwMnjUHK6AxZHnP9bMXEA;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
typedef NU8 tyEnum_FileMode__ykUWlTdrdFfRWwmg78tXCw;
struct tyObject_WideCStringObj__jQbOKocsbu7Z9bKTSFtX4TQ {
	NI bytes;
	NI16* data;
};
typedef NI16 tyUncheckedArray__Tyd4y3haUOOHTj71TPIRag[1];
typedef NCSTRING tyArray__i9cnI556NHiQO17hC9cJxx9cA[5];
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct RootObj {
	TNimTypeV2* m_type;
};
struct tySequence__UIJx6FJrflnhA9a3u1VF1vA {
  NI len; tySequence__UIJx6FJrflnhA9a3u1VF1vA_Content* p;
};
struct Exception {
	RootObj Sup;
	Exception* parent;
	NCSTRING name;
	NimStringV2 message;
	tySequence__UIJx6FJrflnhA9a3u1VF1vA trace;
	Exception* up;
};
struct tyObject_CatchableError__kvV4Jp5z2ULaSZq53myi9ag {
	Exception Sup;
};
struct tyObject_IOError__DxZ2JM72pLUaxjq9asr9aWqA {
	tyObject_CatchableError__kvV4Jp5z2ULaSZq53myi9ag Sup;
};
struct tyObject_StackTraceEntry__UznwMnjUHK6AxZHnP9bMXEA {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};
struct tySequence__UIJx6FJrflnhA9a3u1VF1vA_Content { NI cap; tyObject_StackTraceEntry__UznwMnjUHK6AxZHnP9bMXEA data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, open__stdZsyncio_u535)(FILE** f_p0, NimStringV2 filename_p1, tyEnum_FileMode__ykUWlTdrdFfRWwmg78tXCw mode_p2, NI bufSize_p3);
N_LIB_PRIVATE N_NIMCALL(void*, fopen__stdZsyncio_u500)(NCSTRING filename_p0, NCSTRING mode_p1);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__system_u2188)(void* a_p0, int v_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(tyObject_WideCStringObj__jQbOKocsbu7Z9bKTSFtX4TQ, newWideCString__stdZwidestrs_u322)(NCSTRING s_p0);
static N_INLINE(NI16*, toWideCString__stdZwidestrs_u49)(tyObject_WideCStringObj__jQbOKocsbu7Z9bKTSFtX4TQ x_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___stdZwidestrs_u7)(tyObject_WideCStringObj__jQbOKocsbu7Z9bKTSFtX4TQ a_p0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0);
N_LIB_PRIVATE N_NIMCALL(void, write__stdZsyncio_u272)(FILE* f_p0, NimStringV2 s_p1);
N_LIB_PRIVATE N_NIMCALL(void, writeWindows__stdZsyncio_u255)(FILE* f_p0, NimStringV2 s_p1, NIM_BOOL doRaise_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseEIO__stdZsyncio_u93)(NimStringV2 msg_p0);
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObj)(NI size_p0, NI alignment_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, eqdup___system_u2726)(NimStringV2 src_p0);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e_p0, NCSTRING ename_p1, NCSTRING procname_p2, NCSTRING filename_p3, NI line_p4);
N_LIB_PRIVATE N_NIMCALL(void, close__stdZsyncio_u290)(FILE* f_p0);
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(void, copyMem__system_u1755)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, rawNewString)(NI space_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, readAll__stdZsyncio_u480)(FILE* file_p0);
N_LIB_PRIVATE N_NIMCALL(NI64, rawFileSize__stdZsyncio_u463)(FILE* file_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, readAllFile__stdZsyncio_u471)(FILE* file_p0, NI64 len_p1);
N_NIMCALL(NimStringV2, mnewString)(NI len_p0);
N_LIB_PRIVATE N_NIMCALL(NI, readBuffer__stdZsyncio_u166)(FILE* f_p0, void* buffer_p1, NI len_p2);
N_LIB_PRIVATE N_NIMCALL(void, checkErr__stdZsyncio_u163)(FILE* f_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___systemZdollars_u29)(NI32 xX60gensym3__p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, cstrToNimstr)(NCSTRING str_p0);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, endOfFile__stdZsyncio_u467)(FILE* f_p0);
N_LIB_PRIVATE N_NIMCALL(void, setLengthStrV2)(NimStringV2* s_p0, NI newLen_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, readAllBuffer__stdZsyncio_u458)(FILE* file_p0);
N_LIB_PRIVATE N_NIMCALL(void, prepareAdd)(NimStringV2* s_p0, NI addLen_p1);
N_LIB_PRIVATE N_NIMCALL(void, nimTestErrorFlag)(void);
extern TNimTypeV2 NTIv2__DxZ2JM72pLUaxjq9asr9aWqA_;
static const struct {
  NI cap; NIM_CHAR data[27+1];
} TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_2 = { 27 | NIM_STRLIT_FLAG, "cannot write string to file" };
static const NimStringV2 TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_3 = {27, (NimStrPayload*)&TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_2};
static const NimStringV2 TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_4 = {27, (NimStrPayload*)&TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_2};
static const struct {
  NI cap; NIM_CHAR data[13+1];
} TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_5 = { 13 | NIM_STRLIT_FLAG, "cannot open: " };
static const NimStringV2 TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_6 = {13, (NimStrPayload*)&TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_5};
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_7 = { 7 | NIM_STRLIT_FLAG, "errno: " };
static const NimStringV2 TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_8 = {7, (NimStrPayload*)&TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_7};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_9 = { 2 | NIM_STRLIT_FLAG, " `" };
static const NimStringV2 TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_10 = {2, (NimStrPayload*)&TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_9};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_11 = { 1 | NIM_STRLIT_FLAG, "`" };
static const NimStringV2 TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_12 = {1, (NimStrPayload*)&TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_11};
static const struct {
  NI cap; NIM_CHAR data[0+1];
} TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_13 = { 0 | NIM_STRLIT_FLAG, "" };
static const NimStringV2 TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_14 = {0, (NimStrPayload*)&TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_13};
static const NimStringV2 TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_15 = {13, (NimStrPayload*)&TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_5};
N_LIB_PRIVATE NIM_CONST tyArray__i9cnI556NHiQO17hC9cJxx9cA FormatOpen__stdZsyncio_u534 = {"rbN",
"wbN",
"w+bN",
"r+bN",
"abN"}
;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4172;
static N_INLINE(void, nimSetMem__system_u2188)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
	nimSetMem__system_u2188(p_p0, ((int)0), size_p1);
}
static N_INLINE(NI16*, toWideCString__stdZwidestrs_u49)(tyObject_WideCStringObj__jQbOKocsbu7Z9bKTSFtX4TQ x_p0) {
	NI16* result;
	result = x_p0.data;
	return result;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4172);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void*, fopen__stdZsyncio_u500)(NCSTRING filename_p0, NCSTRING mode_p1) {
	void* result;
	tyObject_WideCStringObj__jQbOKocsbu7Z9bKTSFtX4TQ f_1;
	tyObject_WideCStringObj__jQbOKocsbu7Z9bKTSFtX4TQ m_1;
	NI16* T1_;
	NI16* T2_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (void*)0;
	nimZeroMem((void*)(&f_1), sizeof(tyObject_WideCStringObj__jQbOKocsbu7Z9bKTSFtX4TQ));
	nimZeroMem((void*)(&m_1), sizeof(tyObject_WideCStringObj__jQbOKocsbu7Z9bKTSFtX4TQ));
	f_1 = newWideCString__stdZwidestrs_u322(filename_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	m_1 = newWideCString__stdZwidestrs_u322(mode_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T1_ = (NI16*)0;
	T1_ = toWideCString__stdZwidestrs_u49(f_1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T2_ = (NI16*)0;
	T2_ = toWideCString__stdZwidestrs_u49(m_1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result = _wfopen(T1_, T2_);
	eqdestroy___stdZwidestrs_u7(m_1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	eqdestroy___stdZwidestrs_u7(f_1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0) {
	NCSTRING result;
	{
		if (!(s_p0.len == ((NI)0))) goto LA3_;
		result = "";
	}
	goto LA1_;
LA3_: ;
	{
		result = ((NCSTRING) ((*s_p0.p).data));
	}
LA1_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, open__stdZsyncio_u535)(FILE** f_p0, NimStringV2 filename_p1, tyEnum_FileMode__ykUWlTdrdFfRWwmg78tXCw mode_p2, NI bufSize_p3) {
	NIM_BOOL result;
	void* p_1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	p_1 = fopen__stdZsyncio_u500(nimToCStringConv(filename_p1), FormatOpen__stdZsyncio_u534[(mode_p2)- 0]);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		FILE* f2_1;
		if (!!((p_1 == NIM_NIL))) goto LA3_;
		f2_1 = ((FILE*) (p_1));
		result = NIM_TRUE;
		(*f_p0) = ((FILE*) (p_1));
		{
			NIM_BOOL T7_;
			int T11_;
			T7_ = (NIM_BOOL)0;
			T7_ = (((NI)0) < bufSize_p3);
			if (!(T7_)) goto LA8_;
			T7_ = ((NU64)(((NU) (bufSize_p3))) <= (NU64)(((NU)-1)));
LA8_: ;
			if (!T7_) goto LA9_;
			T11_ = (int)0;
			T11_ = setvbuf((*f_p0), NIM_NIL, _IOFBF, ((size_t) (bufSize_p3)));
			(void)(T11_);
		}
		goto LA5_;
LA9_: ;
		{
			int T15_;
			if (!(bufSize_p3 == ((NI)0))) goto LA13_;
			T15_ = (int)0;
			T15_ = setvbuf((*f_p0), NIM_NIL, _IONBF, ((size_t)0));
			(void)(T15_);
		}
		goto LA5_;
LA13_: ;
LA5_: ;
	}
	goto LA1_;
LA3_: ;
	{
		result = NIM_FALSE;
	}
LA1_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NOINLINE(void, raiseEIO__stdZsyncio_u93)(NimStringV2 msg_p0) {
	NimStringV2 colontmpD_;
	tyObject_IOError__DxZ2JM72pLUaxjq9asr9aWqA* T1_;
{	T1_ = NIM_NIL;
	T1_ = (tyObject_IOError__DxZ2JM72pLUaxjq9asr9aWqA*) nimNewObj(sizeof(tyObject_IOError__DxZ2JM72pLUaxjq9asr9aWqA), NIM_ALIGNOF(tyObject_IOError__DxZ2JM72pLUaxjq9asr9aWqA));
	(*T1_).Sup.Sup.Sup.m_type = (&NTIv2__DxZ2JM72pLUaxjq9asr9aWqA_);
	(*T1_).Sup.Sup.name = "IOError";
	colontmpD_ = eqdup___system_u2726(msg_p0);
	(*T1_).Sup.Sup.message = colontmpD_;
	(*T1_).Sup.Sup.parent = ((Exception*) NIM_NIL);
	raiseExceptionEx((Exception*)T1_, "IOError", "raiseEIO", "syncio.nim", 161);
goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, writeWindows__stdZsyncio_u255)(FILE* f_p0, NimStringV2 s_p1, NIM_BOOL doRaise_p2) {
	NI i_1;
	int T1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	T1_ = (int)0;
	T1_ = fprintf(f_p0, "%s", nimToCStringConv(s_p1));
	i_1 = ((NI) (T1_));
	{
		while (1) {
			if (!(i_1 < s_p1.len)) goto LA3;
			{
				int w_1;
				if (!((NU8)(s_p1.p->data[i_1]) == (NU8)(0))) goto LA6_;
				w_1 = fputc(0, f_p0);
				{
					if (!!((w_1 == ((NI32)0)))) goto LA10_;
					{
						if (!doRaise_p2) goto LA14_;
						raiseEIO__stdZsyncio_u93(TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_3);
						if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					}
LA14_: ;
					goto LA2;
				}
LA10_: ;
				i_1 += ((NI)1);
			}
			goto LA4_;
LA6_: ;
			{
				int w_2;
				w_2 = fprintf(f_p0, "%s", (&s_p1.p->data[i_1]));
				{
					if (!(w_2 <= ((NI32)0))) goto LA19_;
					{
						if (!doRaise_p2) goto LA23_;
						raiseEIO__stdZsyncio_u93(TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_4);
						if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					}
LA23_: ;
					goto LA2;
				}
LA19_: ;
				i_1 += w_2;
			}
LA4_: ;
		} LA3: ;
	} LA2: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, write__stdZsyncio_u272)(FILE* f_p0, NimStringV2 s_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	writeWindows__stdZsyncio_u255(f_p0, s_p1, NIM_TRUE);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, close__stdZsyncio_u290)(FILE* f_p0) {
	{
		int T5_;
		if (!!((f_p0 == 0))) goto LA3_;
		T5_ = (int)0;
		T5_ = fclose(f_p0);
		(void)(T5_);
	}
LA3_: ;
}
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, copyMem__system_u1755)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1) {
	{
		if (!(((NI)0) < src_p1.len)) goto LA3_;
		copyMem__system_u1755(((void*) ((&(*(*dest_p0).p).data[(*dest_p0).len]))), ((void*) ((&(*src_p1.p).data[((NI)0)]))), (src_p1.len));
		(*dest_p0).len += src_p1.len;
		(*(*dest_p0).p).data[(*dest_p0).len] = 0;
	}
LA3_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, writeFile__stdZsyncio_u617)(NimStringV2 filename_p0, NimStringV2 content_p1) {
	FILE* f_1;
NIM_BOOL oldNimErrFin6_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	f_1 = ((FILE*) NIM_NIL);
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = open__stdZsyncio_u535(&f_1, filename_p0, ((tyEnum_FileMode__ykUWlTdrdFfRWwmg78tXCw)1), ((NI)-1));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!T3_) goto LA4_;
		write__stdZsyncio_u272(f_1, content_p1);
		if (NIM_UNLIKELY(*nimErr_)) goto LA6_;
		{
			LA6_:;
		}
		{
			oldNimErrFin6_ = *nimErr_; *nimErr_ = NIM_FALSE;
			close__stdZsyncio_u290(f_1);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			*nimErr_ = oldNimErrFin6_;
		}
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	goto LA1_;
LA4_: ;
	{
		tyObject_IOError__DxZ2JM72pLUaxjq9asr9aWqA* T10_;
		NimStringV2 T11_;
		T10_ = NIM_NIL;
		T10_ = (tyObject_IOError__DxZ2JM72pLUaxjq9asr9aWqA*) nimNewObj(sizeof(tyObject_IOError__DxZ2JM72pLUaxjq9asr9aWqA), NIM_ALIGNOF(tyObject_IOError__DxZ2JM72pLUaxjq9asr9aWqA));
		(*T10_).Sup.Sup.Sup.m_type = (&NTIv2__DxZ2JM72pLUaxjq9asr9aWqA_);
		(*T10_).Sup.Sup.name = "IOError";
		T11_.len = 0; T11_.p = NIM_NIL;
		T11_ = rawNewString(filename_p0.len + 13);
appendString((&T11_), TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_6);
appendString((&T11_), filename_p0);
		(*T10_).Sup.Sup.message = T11_;
		(*T10_).Sup.Sup.parent = ((Exception*) NIM_NIL);
		raiseExceptionEx((Exception*)T10_, "IOError", "writeFile", "syncio.nim", 894);
goto BeforeRet_;
	}
LA1_: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(NI64, rawFileSize__stdZsyncio_u463)(FILE* file_p0) {
	NI64 result;
	NI64 oldPos_1;
	int T1_;
	int T2_;
	oldPos_1 = _ftelli64(file_p0);
	T1_ = (int)0;
	T1_ = _fseeki64(file_p0, IL64(0), ((int)2));
	(void)(T1_);
	result = _ftelli64(file_p0);
	T2_ = (int)0;
	T2_ = _fseeki64(file_p0, oldPos_1, ((int)0));
	(void)(T2_);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, checkErr__stdZsyncio_u163)(FILE* f_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	{
		int T3_;
		NimStringV2 msg_1;
		NimStringV2 colontmpD_;
		NimStringV2 colontmpD__2;
		NimStringV2 T7_;
		NCSTRING T8_;
		T3_ = (int)0;
		T3_ = ferror(f_p0);
		if (!!((T3_ == ((NI32)0)))) goto LA4_;
		msg_1.len = 0; msg_1.p = NIM_NIL;
		colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
		colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
		T7_.len = 0; T7_.p = NIM_NIL;
		colontmpD_ = dollar___systemZdollars_u29(errno);
		if (NIM_UNLIKELY(*nimErr_)) goto LA6_;
		T8_ = (NCSTRING)0;
		T8_ = strerror(errno);
		colontmpD__2 = cstrToNimstr(T8_);
		T7_ = rawNewString(colontmpD_.len + colontmpD__2.len + 10);
appendString((&T7_), TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_8);
appendString((&T7_), colontmpD_);
appendString((&T7_), TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_10);
appendString((&T7_), colontmpD__2);
appendString((&T7_), TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_12);
		msg_1 = T7_;
		clearerr(f_p0);
		raiseEIO__stdZsyncio_u93(msg_1);
		if (NIM_UNLIKELY(*nimErr_)) goto LA6_;
		{
			LA6_:;
		}
		{
			if (colontmpD__2.p && !(colontmpD__2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__2.p);
}
			if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
			if (msg_1.p && !(msg_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(msg_1.p);
}
		}
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA4_: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(NI, readBuffer__stdZsyncio_u166)(FILE* f_p0, void* buffer_p1, NI len_p2) {
	NI result;
	size_t T1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	T1_ = (size_t)0;
	T1_ = fread(buffer_p1, ((size_t)1), ((size_t) (len_p2)), f_p0);
	result = ((NI) (T1_));
	{
		if (!!((result == len_p2))) goto LA4_;
		checkErr__stdZsyncio_u163(f_p0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA4_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, endOfFile__stdZsyncio_u467)(FILE* f_p0) {
	NIM_BOOL result;
	int c_1;
	int T1_;
{	c_1 = fgetc(f_p0);
	T1_ = (int)0;
	T1_ = ungetc(c_1, f_p0);
	(void)(T1_);
	result = (c_1 < ((NI32)0));
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, readAllBuffer__stdZsyncio_u458)(FILE* file_p0) {
	NimStringV2 result;
	NimStringV2 buffer_1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	buffer_1.len = 0; buffer_1.p = NIM_NIL;
	result = TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_14;
	buffer_1 = mnewString(((NI)4000));
	{
		while (1) {
			NI bytesRead_1;
			bytesRead_1 = readBuffer__stdZsyncio_u166(file_p0, ((void*) ((&buffer_1.p->data[((NI)0)]))), ((NI)4000));
			if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
			{
				if (!(bytesRead_1 == ((NI)4000))) goto LA6_;
				prepareAdd((&result), buffer_1.len + 0);
appendString((&result), buffer_1);
			}
			goto LA4_;
LA6_: ;
			{
				setLengthStrV2((&buffer_1), (bytesRead_1));
				prepareAdd((&result), buffer_1.len + 0);
appendString((&result), buffer_1);
				goto LA2;
			}
LA4_: ;
		}
	} LA2: ;
	{
		LA1_:;
	}
	{
		if (buffer_1.p && !(buffer_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(buffer_1.p);
}
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, readAllFile__stdZsyncio_u471)(FILE* file_p0, NI64 len_p1) {
	NimStringV2 result;
	NI bytes_1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	result = mnewString(((NI) (len_p1)));
	bytes_1 = readBuffer__stdZsyncio_u166(file_p0, ((void*) ((&result.p->data[((NI)0)]))), ((NI) (len_p1)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = endOfFile__stdZsyncio_u467(file_p0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!T3_) goto LA4_;
		{
			if (!(((NI64) (bytes_1)) < len_p1)) goto LA8_;
			setLengthStrV2((&result), (bytes_1));
		}
LA8_: ;
	}
	goto LA1_;
LA4_: ;
	{
		NimStringV2 colontmpD_;
		colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
		colontmpD_ = readAllBuffer__stdZsyncio_u458(file_p0);
		if (NIM_UNLIKELY(*nimErr_)) goto LA11_;
		prepareAdd((&result), colontmpD_.len + 0);
appendString((&result), colontmpD_);
		{
			LA11_:;
		}
		{
			if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
		}
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA1_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, readAll__stdZsyncio_u480)(FILE* file_p0) {
	NimStringV2 result;
	NI64 colontmpD_;
	NI64 colontmpD__2;
	NI64 len_1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	colontmpD_ = (NI64)0;
	colontmpD__2 = (NI64)0;
	{
		if (!!((file_p0 == stdin))) goto LA3_;
		colontmpD_ = rawFileSize__stdZsyncio_u463(file_p0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		len_1 = colontmpD_;
	}
	goto LA1_;
LA3_: ;
	{
		colontmpD__2 = IL64(-1);
		len_1 = colontmpD__2;
	}
LA1_: ;
	{
		if (!(IL64(0) < len_1)) goto LA8_;
		result = readAllFile__stdZsyncio_u471(file_p0, len_1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	goto LA6_;
LA8_: ;
	{
		result = readAllBuffer__stdZsyncio_u458(file_p0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA6_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, readFile__stdZsyncio_u612)(NimStringV2 filename_p0) {
	NimStringV2 result;
	FILE* f_1;
NIM_BOOL oldNimErrFin6_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	f_1 = ((FILE*) NIM_NIL);
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = open__stdZsyncio_u535(&f_1, filename_p0, ((tyEnum_FileMode__ykUWlTdrdFfRWwmg78tXCw)0), ((NI)-1));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!T3_) goto LA4_;
		result = readAll__stdZsyncio_u480(f_1);
		if (NIM_UNLIKELY(*nimErr_)) goto LA6_;
		{
			LA6_:;
		}
		{
			oldNimErrFin6_ = *nimErr_; *nimErr_ = NIM_FALSE;
			close__stdZsyncio_u290(f_1);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			*nimErr_ = oldNimErrFin6_;
		}
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	goto LA1_;
LA4_: ;
	{
		tyObject_IOError__DxZ2JM72pLUaxjq9asr9aWqA* T10_;
		NimStringV2 T11_;
		T10_ = NIM_NIL;
		T10_ = (tyObject_IOError__DxZ2JM72pLUaxjq9asr9aWqA*) nimNewObj(sizeof(tyObject_IOError__DxZ2JM72pLUaxjq9asr9aWqA), NIM_ALIGNOF(tyObject_IOError__DxZ2JM72pLUaxjq9asr9aWqA));
		(*T10_).Sup.Sup.Sup.m_type = (&NTIv2__DxZ2JM72pLUaxjq9asr9aWqA_);
		(*T10_).Sup.Sup.name = "IOError";
		T11_.len = 0; T11_.p = NIM_NIL;
		T11_ = rawNewString(filename_p0.len + 13);
appendString((&T11_), TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_15);
appendString((&T11_), filename_p0);
		(*T10_).Sup.Sup.message = T11_;
		(*T10_).Sup.Sup.parent = ((Exception*) NIM_NIL);
		raiseExceptionEx((Exception*)T10_, "IOError", "readFile", "syncio.nim", 881);
goto BeforeRet_;
	}
LA1_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, atpstdatssynciodotnim_Init000)(void) {
{
	int T1_;
	int T2_;
	int T3_;
	T1_ = (int)0;
	T1_ = _fileno(stdin);
	_setmode(T1_, _O_BINARY);
	T2_ = (int)0;
	T2_ = _fileno(stdout);
	_setmode(T2_, _O_BINARY);
	T3_ = (int)0;
	T3_ = _fileno(stderr);
	_setmode(T3_, _O_BINARY);
	nimTestErrorFlag();
}
}

