/* Generated by Nim Compiler v2.2.10 */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   x86_64-w64-mingw32-gcc -c -w -fmax-errors=3 -mno-ms-bitfields -fno-strict-aliasing -DWIN32_LEAN_AND_MEAN -Os -fno-ident   -I/home/kali/.choosenim/toolchains/nim-2.2.10/lib -I/home/kali/c2/agents/agent-nim -o /home/kali/c2/agents/agent-nim/nimcache_final/@pwinlean.nim.c.o /home/kali/c2/agents/agent-nim/nimcache_final/@pwinlean.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tyObject_GUID__sP1Ck4rtaSQ4Loia9a1yAmg tyObject_GUID__sP1Ck4rtaSQ4Loia9a1yAmg;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_SECURITY_ATTRIBUTES__9bhLIPSmjOM57xx9buGk4ikQ tyObject_SECURITY_ATTRIBUTES__9bhLIPSmjOM57xx9buGk4ikQ;
typedef struct tyObject_STARTUPINFO__ZQ9ciMsZVvVf8P0rtQ09bUCw tyObject_STARTUPINFO__ZQ9ciMsZVvVf8P0rtQ09bUCw;
typedef struct tyObject_PROCESS_INFORMATION__Qr2jyNkBR7zRkYbPVoaJdA tyObject_PROCESS_INFORMATION__Qr2jyNkBR7zRkYbPVoaJdA;
typedef struct tyObject_WIN32_FIND_DATA__Ygx8jNn4fKnE0Znor9bYRxQ tyObject_WIN32_FIND_DATA__Ygx8jNn4fKnE0Znor9bYRxQ;
typedef NI8 tyArray__RGsHGOi9bnu5uBb7LyMV9aPg[8];
struct tyObject_GUID__sP1Ck4rtaSQ4Loia9a1yAmg {
	NI32 D1;
	NI16 D2;
	NI16 D3;
	tyArray__RGsHGOi9bnu5uBb7LyMV9aPg D4;
};
typedef N_STDCALL_PTR(NCSTRING, tyProc__zlYMfOxBV4VSYbrZMjd2xQ) (int family_p0, void* paddr_p1, NCSTRING pStringBuffer_p2, NI32 stringBufSize_p3);
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
typedef N_STDCALL_PTR(void, tyProc__Tjolzh1w2dIIpj3oCDGPFw) (NI32 dwMilliseconds_p0);
typedef N_STDCALL_PTR(NI32, tyProc__EN454t29c8zxeqsCUHjc1Pw) (NI* hReadPipe_p0, NI* hWritePipe_p1, tyObject_SECURITY_ATTRIBUTES__9bhLIPSmjOM57xx9buGk4ikQ* lpPipeAttributes_p2, NI32 nSize_p3);
typedef N_STDCALL_PTR(NI32, tyProc__aO673xGTLLxou7P7GxoCXA) (NI32 dwFlags_p0, void* lpSource_p1, NI32 dwMessageId_p2, NI32 dwLanguageId_p3, void* lpBuffer_p4, NI32 nSize_p5, void* arguments_p6);
typedef N_STDCALL_PTR(void, tyProc__im9buRnIvptJfzdASYMEbBA) (void* p_p0);
typedef N_STDCALL_PTR(NI32, tyProc__9bXer9a4ps9aSGctILcxWReVw) (void);
typedef N_STDCALL_PTR(NI32, tyProc__mBVOPXmpGfUrrbA9a5K9cMbQ) (NI hObject_p0, NI32 dwMask_p1, NI32 dwFlags_p2);
typedef N_STDCALL_PTR(NI, tyProc__EYP7RqT3MHXHmseMIXVbTg) (NI16* lpName_p0, NI32 dwOpenMode_p1, NI32 dwPipeMode_p2, NI32 nMaxInstances_p3, NI32 nOutBufferSize_p4, NI32 nInBufferSize_p5, NI32 nDefaultTimeOut_p6, tyObject_SECURITY_ATTRIBUTES__9bhLIPSmjOM57xx9buGk4ikQ* lpSecurityAttributes_p7);
typedef N_STDCALL_PTR(NI, tyProc__Q9box9as0S1hHKH9cSO3MGDDA) (NI16* lpFileName_p0, NI32 dwDesiredAccess_p1, NI32 dwShareMode_p2, void* lpSecurityAttributes_p3, NI32 dwCreationDisposition_p4, NI32 dwFlagsAndAttributes_p5, NI hTemplateFile_p6);
typedef N_STDCALL_PTR(NI, tyProc__uryidYWkntM7ddjZSyxvyQ) (void);
typedef N_STDCALL_PTR(NI32, tyProc__oew1DfaGl5XhHmnBK0HYXQ) (NI hSourceProcessHandle_p0, NI hSourceHandle_p1, NI hTargetProcessHandle_p2, NI* lpTargetHandle_p3, NI32 dwDesiredAccess_p4, NI32 bInheritHandle_p5, NI32 dwOptions_p6);
typedef N_STDCALL_PTR(NI32, tyProc__P13srMBg9b3d3yEV9aW4NCoA) (NI hObject_p0);
typedef N_STDCALL_PTR(NI, tyProc__zP2zGemcuVRvOUE82f9a0Pw) (NI32 nStdHandle_p0);
typedef N_STDCALL_PTR(NI32, tyProc__Fg6EvxtNiMAMAT6csVhm9cA) (NI16* lpApplicationName_p0, NI16* lpCommandLine_p1, tyObject_SECURITY_ATTRIBUTES__9bhLIPSmjOM57xx9buGk4ikQ* lpProcessAttributes_p2, tyObject_SECURITY_ATTRIBUTES__9bhLIPSmjOM57xx9buGk4ikQ* lpThreadAttributes_p3, NI32 bInheritHandles_p4, NI32 dwCreationFlags_p5, NI16* lpEnvironment_p6, NI16* lpCurrentDirectory_p7, tyObject_STARTUPINFO__ZQ9ciMsZVvVf8P0rtQ09bUCw* lpStartupInfo_p8, tyObject_PROCESS_INFORMATION__Qr2jyNkBR7zRkYbPVoaJdA* lpProcessInformation_p9);
typedef N_STDCALL_PTR(NI32, tyProc__9ajZYMGL5GqiRFqiCC367oA) (NI hFile_p0, void* buffer_p1, NI32 nNumberOfBytesToRead_p2, NI32* lpNumberOfBytesRead_p3, void* lpOverlapped_p4);
typedef N_STDCALL_PTR(NI32, tyProc__FprzxJFfqQdWyyGxiUsmeQ) (NI hHandle_p0, NI32 dwMilliseconds_p1);
typedef N_STDCALL_PTR(NI32, tyProc__KxeGXN001TReCr89ca9c5bng) (NI hProcess_p0, NI32* lpExitCode_p1);
typedef N_STDCALL_PTR(NI32, tyProc__aMOow6Lp4fo8dW2ko9aU3pg) (NI32 nBufferLength_p0, NI16* lpBuffer_p1);
typedef N_STDCALL_PTR(NI32, tyProc__5sqIMptsyAfPn3c9cPj4DOA) (NI16* lpPathName_p0);
typedef N_STDCALL_PTR(NI, tyProc__lCGM9cmBs4TguFMTOt5tjdg) (NI16* lpFileName_p0, tyObject_WIN32_FIND_DATA__Ygx8jNn4fKnE0Znor9bYRxQ* lpFindFileData_p1);
typedef N_STDCALL_PTR(NI32, tyProc__8P9av0E1YQu1ox9bSSjVfDjA) (NI hFindFile_p0, tyObject_WIN32_FIND_DATA__Ygx8jNn4fKnE0Znor9bYRxQ* lpFindFileData_p1);
typedef N_STDCALL_PTR(void, tyProc__ofoySXaAAlxxs9bQS9a1etlg) (NI hFindFile_p0);
N_LIB_PRIVATE N_NIMCALL(void*, loadLib__pureZdynlib_u3)(NimStringV2 path_p0, NIM_BOOL globalSymbols_p1);
N_LIB_PRIVATE N_NIMCALL(void*, symAddr__pureZdynlib_u74)(void* lib_p0, NCSTRING name_p1);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void*, nimLoadLibrary)(NimStringV2 path_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimLoadLibraryError)(NimStringV2 path_p0);
N_LIB_PRIVATE N_NIMCALL(void*, nimGetProcAddr)(void* lib_p0, NCSTRING name_p1);
N_LIB_PRIVATE N_NIMCALL(void, nimTestErrorFlag)(void);
static const struct {
  NI cap; NIM_CHAR data[10+1];
} TM__k6kyf4Co79a84IkK9blFuQVA_2 = { 10 | NIM_STRLIT_FLAG, "Ws2_32.dll" };
static const NimStringV2 TM__k6kyf4Co79a84IkK9blFuQVA_3 = {10, (NimStrPayload*)&TM__k6kyf4Co79a84IkK9blFuQVA_2};
static const struct {
  NI cap; NIM_CHAR data[8+1];
} TM__k6kyf4Co79a84IkK9blFuQVA_6 = { 8 | NIM_STRLIT_FLAG, "kernel32" };
static const NimStringV2 TM__k6kyf4Co79a84IkK9blFuQVA_7 = {8, (NimStrPayload*)&TM__k6kyf4Co79a84IkK9blFuQVA_6};
static const struct {
  NI cap; NIM_CHAR data[8+1];
} TM__k6kyf4Co79a84IkK9blFuQVA_8 = { 8 | NIM_STRLIT_FLAG, "kernel32" };
static const NimStringV2 TM__k6kyf4Co79a84IkK9blFuQVA_9 = {8, (NimStrPayload*)&TM__k6kyf4Co79a84IkK9blFuQVA_8};
N_LIB_PRIVATE tyObject_GUID__sP1Ck4rtaSQ4Loia9a1yAmg WSAID_CONNECTEX__windowsZwinlean_u723 = {((NI32)631375801), ((NI16)-8717), ((NI16)18016), {((NI8)-114),
((NI8)-23),
((NI8)118),
((NI8)-27),
((NI8)-116),
((NI8)116),
((NI8)6),
((NI8)62)}
}
;
N_LIB_PRIVATE tyObject_GUID__sP1Ck4rtaSQ4Loia9a1yAmg WSAID_ACCEPTEX__windowsZwinlean_u724 = {((NI32)-1254720015), ((NI16)-13396), ((NI16)4559), {((NI8)-107),
((NI8)-54),
((NI8)0),
((NI8)-128),
((NI8)95),
((NI8)72),
((NI8)-95),
((NI8)-110)}
}
;
N_LIB_PRIVATE tyObject_GUID__sP1Ck4rtaSQ4Loia9a1yAmg WSAID_GETACCEPTEXSOCKADDRS__windowsZwinlean_u725 = {((NI32)-1254720014), ((NI16)-13396), ((NI16)4559), {((NI8)-107),
((NI8)-54),
((NI8)0),
((NI8)-128),
((NI8)95),
((NI8)72),
((NI8)-95),
((NI8)-110)}
}
;
N_LIB_PRIVATE tyProc__zlYMfOxBV4VSYbrZMjd2xQ inet_ntop_real__windowsZwinlean_u796 = NIM_NIL;
N_LIB_PRIVATE void* ws2__windowsZwinlean_u797;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4172;
static void* TM__k6kyf4Co79a84IkK9blFuQVA_4;
tyProc__Tjolzh1w2dIIpj3oCDGPFw Dl_1509949738_;
tyProc__EN454t29c8zxeqsCUHjc1Pw Dl_1509949557_;
tyProc__aO673xGTLLxou7P7GxoCXA Dl_1509949612_;
tyProc__im9buRnIvptJfzdASYMEbBA Dl_1509949620_;
tyProc__9bXer9a4ps9aSGctILcxWReVw Dl_1509949609_;
tyProc__mBVOPXmpGfUrrbA9a5K9cMbQ Dl_1509950044_;
tyProc__EYP7RqT3MHXHmseMIXVbTg Dl_1509949562_;
tyProc__Q9box9as0S1hHKH9cSO3MGDDA Dl_1509950049_;
tyProc__uryidYWkntM7ddjZSyxvyQ Dl_1509950048_;
tyProc__oew1DfaGl5XhHmnBK0HYXQ Dl_1509950033_;
tyProc__P13srMBg9b3d3yEV9aW4NCoA Dl_1509949543_;
tyProc__zP2zGemcuVRvOUE82f9a0Pw Dl_1509949602_;
tyProc__Fg6EvxtNiMAMAT6csVhm9cA Dl_1509949578_;
tyProc__9ajZYMGL5GqiRFqiCC367oA Dl_1509949545_;
tyProc__9ajZYMGL5GqiRFqiCC367oA Dl_1509949551_;
tyProc__FprzxJFfqQdWyyGxiUsmeQ Dl_1509949593_;
tyProc__KxeGXN001TReCr89ca9c5bng Dl_1509949599_;
tyProc__aMOow6Lp4fo8dW2ko9aU3pg Dl_1509949622_;
tyProc__5sqIMptsyAfPn3c9cPj4DOA Dl_1509949625_;
tyProc__lCGM9cmBs4TguFMTOt5tjdg Dl_1509949689_;
tyProc__8P9av0E1YQu1ox9bSSjVfDjA Dl_1509949692_;
tyProc__ofoySXaAAlxxs9bQS9a1etlg Dl_1509949695_;
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4172);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, atpwinleandotnim_Init000)(void) {
{
	void* T1_;
NIM_BOOL* nimErr_;
nimErr_ = nimErrorFlag();
	T1_ = (void*)0;
	T1_ = loadLib__pureZdynlib_u3(TM__k6kyf4Co79a84IkK9blFuQVA_3, NIM_FALSE);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	ws2__windowsZwinlean_u797 = T1_;
	{
		void* T6_;
		if (!!((ws2__windowsZwinlean_u797 == NIM_NIL))) goto LA4_;
		T6_ = (void*)0;
		T6_ = symAddr__pureZdynlib_u74(ws2__windowsZwinlean_u797, "inet_ntop");
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		inet_ntop_real__windowsZwinlean_u796 = ((tyProc__zlYMfOxBV4VSYbrZMjd2xQ) (T6_));
	}
LA4_: ;
	BeforeRet_: ;
	nimTestErrorFlag();
}
}

N_LIB_PRIVATE N_NIMCALL(void, atpwinleandotnim_DatInit000)(void) {
if (!((TM__k6kyf4Co79a84IkK9blFuQVA_4 = nimLoadLibrary(TM__k6kyf4Co79a84IkK9blFuQVA_7))
)) nimLoadLibraryError(TM__k6kyf4Co79a84IkK9blFuQVA_9);
	Dl_1509949738_ = (tyProc__Tjolzh1w2dIIpj3oCDGPFw) nimGetProcAddr(TM__k6kyf4Co79a84IkK9blFuQVA_4, "Sleep");
	Dl_1509949557_ = (tyProc__EN454t29c8zxeqsCUHjc1Pw) nimGetProcAddr(TM__k6kyf4Co79a84IkK9blFuQVA_4, "CreatePipe");
	Dl_1509949612_ = (tyProc__aO673xGTLLxou7P7GxoCXA) nimGetProcAddr(TM__k6kyf4Co79a84IkK9blFuQVA_4, "FormatMessageW");
	Dl_1509949620_ = (tyProc__im9buRnIvptJfzdASYMEbBA) nimGetProcAddr(TM__k6kyf4Co79a84IkK9blFuQVA_4, "LocalFree");
	Dl_1509949609_ = (tyProc__9bXer9a4ps9aSGctILcxWReVw) nimGetProcAddr(TM__k6kyf4Co79a84IkK9blFuQVA_4, "GetLastError");
	Dl_1509950044_ = (tyProc__mBVOPXmpGfUrrbA9a5K9cMbQ) nimGetProcAddr(TM__k6kyf4Co79a84IkK9blFuQVA_4, "SetHandleInformation");
	Dl_1509949562_ = (tyProc__EYP7RqT3MHXHmseMIXVbTg) nimGetProcAddr(TM__k6kyf4Co79a84IkK9blFuQVA_4, "CreateNamedPipeW");
	Dl_1509950049_ = (tyProc__Q9box9as0S1hHKH9cSO3MGDDA) nimGetProcAddr(TM__k6kyf4Co79a84IkK9blFuQVA_4, "CreateFileW");
	Dl_1509950048_ = (tyProc__uryidYWkntM7ddjZSyxvyQ) nimGetProcAddr(TM__k6kyf4Co79a84IkK9blFuQVA_4, "GetCurrentProcess");
	Dl_1509950033_ = (tyProc__oew1DfaGl5XhHmnBK0HYXQ) nimGetProcAddr(TM__k6kyf4Co79a84IkK9blFuQVA_4, "DuplicateHandle");
	Dl_1509949543_ = (tyProc__P13srMBg9b3d3yEV9aW4NCoA) nimGetProcAddr(TM__k6kyf4Co79a84IkK9blFuQVA_4, "CloseHandle");
	Dl_1509949602_ = (tyProc__zP2zGemcuVRvOUE82f9a0Pw) nimGetProcAddr(TM__k6kyf4Co79a84IkK9blFuQVA_4, "GetStdHandle");
	Dl_1509949578_ = (tyProc__Fg6EvxtNiMAMAT6csVhm9cA) nimGetProcAddr(TM__k6kyf4Co79a84IkK9blFuQVA_4, "CreateProcessW");
	Dl_1509949545_ = (tyProc__9ajZYMGL5GqiRFqiCC367oA) nimGetProcAddr(TM__k6kyf4Co79a84IkK9blFuQVA_4, "ReadFile");
	Dl_1509949551_ = (tyProc__9ajZYMGL5GqiRFqiCC367oA) nimGetProcAddr(TM__k6kyf4Co79a84IkK9blFuQVA_4, "WriteFile");
	Dl_1509949593_ = (tyProc__FprzxJFfqQdWyyGxiUsmeQ) nimGetProcAddr(TM__k6kyf4Co79a84IkK9blFuQVA_4, "WaitForSingleObject");
	Dl_1509949599_ = (tyProc__KxeGXN001TReCr89ca9c5bng) nimGetProcAddr(TM__k6kyf4Co79a84IkK9blFuQVA_4, "GetExitCodeProcess");
	Dl_1509949622_ = (tyProc__aMOow6Lp4fo8dW2ko9aU3pg) nimGetProcAddr(TM__k6kyf4Co79a84IkK9blFuQVA_4, "GetCurrentDirectoryW");
	Dl_1509949625_ = (tyProc__5sqIMptsyAfPn3c9cPj4DOA) nimGetProcAddr(TM__k6kyf4Co79a84IkK9blFuQVA_4, "SetCurrentDirectoryW");
	Dl_1509949689_ = (tyProc__lCGM9cmBs4TguFMTOt5tjdg) nimGetProcAddr(TM__k6kyf4Co79a84IkK9blFuQVA_4, "FindFirstFileW");
	Dl_1509949692_ = (tyProc__8P9av0E1YQu1ox9bSSjVfDjA) nimGetProcAddr(TM__k6kyf4Co79a84IkK9blFuQVA_4, "FindNextFileW");
	Dl_1509949695_ = (tyProc__ofoySXaAAlxxs9bQS9a1etlg) nimGetProcAddr(TM__k6kyf4Co79a84IkK9blFuQVA_4, "FindClose");
}

