#!/bin/bash
# build_pic.sh — Rebuild evasion_pic_bytes.h from evasion_pic.c
#
# Run whenever evasion_pic.c changes.  The generated evasion_pic_bytes.h is
# committed alongside the source so that the server build step is a single
# gcc invocation with no two-step dependency.
#
# Usage:
#   cd agents/agent-c && bash build_pic.sh

set -e
cd "$(dirname "$0")"

CC=x86_64-w64-mingw32-gcc
LD=x86_64-w64-mingw32-ld
OC=x86_64-w64-mingw32-objcopy

echo "[1/4] Compiling evasion_pic.c ..."
$CC -O1 -nostdlib \
  -fno-asynchronous-unwind-tables \
  -fno-stack-protector \
  -fno-stack-check \
  -fno-ident \
  -mno-stack-arg-probe \
  -ffunction-sections \
  -Wall -Wno-unused-function \
  -c evasion_pic.c -o evasion_pic.o

echo "[2/4] Checking for external references ..."
RELOCS=$(x86_64-w64-mingw32-objdump -r evasion_pic.o | \
         grep -v '^\s*$\|file format\|RELOCATION\|\.text\$' || true)
if [ -n "$RELOCS" ]; then
  echo "ERROR: unexpected external relocations:"
  echo "$RELOCS"
  exit 1
fi
echo "    Clean (only intra-.text relocations)."

echo "[3/4] Linking and extracting .text ..."
$CC -O1 -nostdlib \
  -fno-asynchronous-unwind-tables \
  -fno-stack-protector \
  -fno-stack-check \
  -fno-ident \
  -mno-stack-arg-probe \
  -Wl,--entry=pic_fill_exports \
  -Wl,--subsystem=windows \
  -Wl,--no-seh \
  evasion_pic.o -o evasion_pic.exe
$OC --only-section=.text -O binary evasion_pic.exe evasion_pic.bin
SIZE=$(wc -c < evasion_pic.bin)
echo "    Shellcode size: ${SIZE} bytes"

echo "[4/4] Generating evasion_pic_bytes.h ..."
python3 - <<'PYEOF'
import os
data = open('evasion_pic.bin','rb').read()
out = []
out.append('/* Auto-generated by build_pic.sh — do not edit manually */')
out.append('static const unsigned char evasion_pic_bin[] = {')
line = []
for i, b in enumerate(data):
    line.append('0x{:02x}'.format(b))
    if len(line) == 12:
        out.append('    ' + ', '.join(line) + ',')
        line = []
if line:
    out.append('    ' + ', '.join(line))
out.append('};')
out.append('static const unsigned int evasion_pic_bin_len = {};'.format(len(data)))
open('evasion_pic_bytes.h','w').write('\n'.join(out)+'\n')
PYEOF

echo ""
echo "Done.  Verify with:"
echo "  x86_64-w64-mingw32-objdump -d evasion_pic.exe | head -40"
echo "  (pic_fill_exports should be at the first address in .text)"
