/* Generated by Nim Compiler v2.2.10 */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   x86_64-w64-mingw32-gcc -c -w -fmax-errors=3 -mno-ms-bitfields -fno-strict-aliasing -DWIN32_LEAN_AND_MEAN -Os -fno-ident   -I/home/kali/.choosenim/toolchains/nim-2.2.10/lib -I/home/kali/c2/agents/agent-nim -o /home/kali/c2/agents/agent-nim/nimcache_http/@posproc.nim.c.o /home/kali/c2/agents/agent-nim/nimcache_http/@posproc.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tyTuple__XOVT24GHXwqiEj5GCsEGCA tyTuple__XOVT24GHXwqiEj5GCsEGCA;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_StringTableObj__MtedWbN0LmvZq2M8UCJLpA tyObject_StringTableObj__MtedWbN0LmvZq2M8UCJLpA;
typedef struct tyObject_ProcessObj__UmZS0xU7o5OSPf9bpi5tgIA tyObject_ProcessObj__UmZS0xU7o5OSPf9bpi5tgIA;
typedef struct tyObject_StreamObj__59a9bMG3hIslwPg3r9aB4JTRg tyObject_StreamObj__59a9bMG3hIslwPg3r9aB4JTRg;
typedef struct RootObj RootObj;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tyObject_WideCStringObj__jQbOKocsbu7Z9bKTSFtX4TQ tyObject_WideCStringObj__jQbOKocsbu7Z9bKTSFtX4TQ;
typedef struct tyObject_STARTUPINFO__ZQ9ciMsZVvVf8P0rtQ09bUCw tyObject_STARTUPINFO__ZQ9ciMsZVvVf8P0rtQ09bUCw;
typedef struct tyObject_PROCESS_INFORMATION__Qr2jyNkBR7zRkYbPVoaJdA tyObject_PROCESS_INFORMATION__Qr2jyNkBR7zRkYbPVoaJdA;
typedef struct tyObject_RefHeader__sqhyc4FSbGmPtkvXRNl9acg tyObject_RefHeader__sqhyc4FSbGmPtkvXRNl9acg;
typedef struct tyObject_GcEnv__85WwC9a1qDcL9aPJ9b1qr0g2Q tyObject_GcEnv__85WwC9a1qDcL9aPJ9b1qr0g2Q;
typedef struct tyObject_CellSeq__tmpRNCI2baMQRvZpqUI72g tyObject_CellSeq__tmpRNCI2baMQRvZpqUI72g;
typedef struct tyTuple__N4J9cV4JZGem3ljqqj5rT0Q tyTuple__N4J9cV4JZGem3ljqqj5rT0Q;
typedef struct tyObject_CellSeq__bUU9cGCnoYZUQbR5GgWvc0g tyObject_CellSeq__bUU9cGCnoYZUQbR5GgWvc0g;
typedef struct tyTuple__WEETd9ajw9a010wvV0CoGNuw tyTuple__WEETd9ajw9a010wvV0CoGNuw;
typedef struct tyObject_SECURITY_ATTRIBUTES__9bhLIPSmjOM57xx9buGk4ikQ tyObject_SECURITY_ATTRIBUTES__9bhLIPSmjOM57xx9buGk4ikQ;
typedef struct tyTuple__0hEbbYmlam6yzyW5MFo9cjg tyTuple__0hEbbYmlam6yzyW5MFo9cjg;
typedef struct tySequence__xv3aaFd3JCw8NbmALHiezQ tySequence__xv3aaFd3JCw8NbmALHiezQ;
typedef struct tySequence__xv3aaFd3JCw8NbmALHiezQ_Content tySequence__xv3aaFd3JCw8NbmALHiezQ_Content;
typedef struct tyTuple__sPaDkVPSC0MkcoXCxPH9ccA tyTuple__sPaDkVPSC0MkcoXCxPH9ccA;
typedef struct tyObject_HSlice__RmqVCB5rHyE9cs59bZ8FgkPA tyObject_HSlice__RmqVCB5rHyE9cs59bZ8FgkPA;
typedef struct tyObject_FileHandleStreamcolonObjectType___zP8ssNQ49cn0fN87jk4EGjA tyObject_FileHandleStreamcolonObjectType___zP8ssNQ49cn0fN87jk4EGjA;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
typedef NU8 tySet_tyEnum_ProcessOption__O0VnkOD1kPGXGbZ5LEvw9cw;
struct tyTuple__XOVT24GHXwqiEj5GCsEGCA {
	NimStringV2 Field0;
	NI Field1;
};
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct RootObj {
	TNimTypeV2* m_type;
};
struct tyObject_ProcessObj__UmZS0xU7o5OSPf9bpi5tgIA {
	RootObj Sup;
	NI fProcessHandle;
	NI fThreadHandle;
	NI inHandle;
	NI outHandle;
	NI errHandle;
	NI id;
	tyObject_StreamObj__59a9bMG3hIslwPg3r9aB4JTRg* inStream;
	tyObject_StreamObj__59a9bMG3hIslwPg3r9aB4JTRg* outStream;
	tyObject_StreamObj__59a9bMG3hIslwPg3r9aB4JTRg* errStream;
	int exitStatus;
	NIM_BOOL exitFlag;
	tySet_tyEnum_ProcessOption__O0VnkOD1kPGXGbZ5LEvw9cw options;
};
struct tyObject_WideCStringObj__jQbOKocsbu7Z9bKTSFtX4TQ {
	NI bytes;
	NI16* data;
};
struct tyObject_STARTUPINFO__ZQ9ciMsZVvVf8P0rtQ09bUCw {
	NI32 cb;
	NCSTRING lpReserved;
	NCSTRING lpDesktop;
	NCSTRING lpTitle;
	NI32 dwX;
	NI32 dwY;
	NI32 dwXSize;
	NI32 dwYSize;
	NI32 dwXCountChars;
	NI32 dwYCountChars;
	NI32 dwFillAttribute;
	NI32 dwFlags;
	NI16 wShowWindow;
	NI16 cbReserved2;
	void* lpReserved2;
	NI hStdInput;
	NI hStdOutput;
	NI hStdError;
};
struct tyObject_PROCESS_INFORMATION__Qr2jyNkBR7zRkYbPVoaJdA {
	NI hProcess;
	NI hThread;
	NI32 dwProcessId;
	NI32 dwThreadId;
};
struct tyObject_RefHeader__sqhyc4FSbGmPtkvXRNl9acg {
	NI rc;
	NI rootIdx;
};
struct tyObject_CellSeq__tmpRNCI2baMQRvZpqUI72g {
	NI len;
	NI cap;
	tyTuple__N4J9cV4JZGem3ljqqj5rT0Q* d;
};
struct tyObject_CellSeq__bUU9cGCnoYZUQbR5GgWvc0g {
	NI len;
	NI cap;
	tyTuple__WEETd9ajw9a010wvV0CoGNuw* d;
};
struct tyObject_GcEnv__85WwC9a1qDcL9aPJ9b1qr0g2Q {
	tyObject_CellSeq__tmpRNCI2baMQRvZpqUI72g traceStack;
	tyObject_CellSeq__bUU9cGCnoYZUQbR5GgWvc0g toFree;
	NI freed;
	NI touched;
	NI edges;
	NI rcSum;
	NIM_BOOL keepThreshold;
};
struct tyTuple__N4J9cV4JZGem3ljqqj5rT0Q {
	void** Field0;
	TNimTypeV2* Field1;
};
typedef NU8 tyEnum_ProcessOption__O0VnkOD1kPGXGbZ5LEvw9cw;
struct tyObject_SECURITY_ATTRIBUTES__9bhLIPSmjOM57xx9buGk4ikQ {
	NI32 nLength;
	void* lpSecurityDescriptor;
	NI32 bInheritHandle;
};
typedef N_STDCALL_PTR(NI32, tyProc__EN454t29c8zxeqsCUHjc1Pw) (NI* hReadPipe_p0, NI* hWritePipe_p1, tyObject_SECURITY_ATTRIBUTES__9bhLIPSmjOM57xx9buGk4ikQ* lpPipeAttributes_p2, NI32 nSize_p3);
typedef N_STDCALL_PTR(NI32, tyProc__mBVOPXmpGfUrrbA9a5K9cMbQ) (NI hObject_p0, NI32 dwMask_p1, NI32 dwFlags_p2);
typedef N_STDCALL_PTR(NI, tyProc__EYP7RqT3MHXHmseMIXVbTg) (NI16* lpName_p0, NI32 dwOpenMode_p1, NI32 dwPipeMode_p2, NI32 nMaxInstances_p3, NI32 nOutBufferSize_p4, NI32 nInBufferSize_p5, NI32 nDefaultTimeOut_p6, tyObject_SECURITY_ATTRIBUTES__9bhLIPSmjOM57xx9buGk4ikQ* lpSecurityAttributes_p7);
typedef NI16 tyUncheckedArray__Tyd4y3haUOOHTj71TPIRag[1];
typedef N_STDCALL_PTR(NI, tyProc__Q9box9as0S1hHKH9cSO3MGDDA) (NI16* lpFileName_p0, NI32 dwDesiredAccess_p1, NI32 dwShareMode_p2, void* lpSecurityAttributes_p3, NI32 dwCreationDisposition_p4, NI32 dwFlagsAndAttributes_p5, NI hTemplateFile_p6);
typedef N_STDCALL_PTR(NI, tyProc__uryidYWkntM7ddjZSyxvyQ) (void);
typedef N_STDCALL_PTR(NI32, tyProc__oew1DfaGl5XhHmnBK0HYXQ) (NI hSourceProcessHandle_p0, NI hSourceHandle_p1, NI hTargetProcessHandle_p2, NI* lpTargetHandle_p3, NI32 dwDesiredAccess_p4, NI32 bInheritHandle_p5, NI32 dwOptions_p6);
typedef N_STDCALL_PTR(NI32, tyProc__P13srMBg9b3d3yEV9aW4NCoA) (NI hObject_p0);
typedef N_STDCALL_PTR(NI, tyProc__zP2zGemcuVRvOUE82f9a0Pw) (NI32 nStdHandle_p0);
struct tyTuple__0hEbbYmlam6yzyW5MFo9cjg {
	NCSTRING Field0;
	NI Field1;
};
struct tySequence__xv3aaFd3JCw8NbmALHiezQ {
  NI len; tySequence__xv3aaFd3JCw8NbmALHiezQ_Content* p;
};
typedef NU8 tyEnum_StringTableMode__Q4xtjX0i9boA82iPpoyBhdQ;
struct tyObject_StringTableObj__MtedWbN0LmvZq2M8UCJLpA {
	RootObj Sup;
	NI counter;
	tySequence__xv3aaFd3JCw8NbmALHiezQ data;
	tyEnum_StringTableMode__Q4xtjX0i9boA82iPpoyBhdQ mode;
};
struct tyTuple__sPaDkVPSC0MkcoXCxPH9ccA {
	NimStringV2 Field0;
	NimStringV2 Field1;
	NIM_BOOL Field2;
};
typedef NimStringV2 tyArray__YgExxhfgKcesA5EOUj1MOA[1];
typedef N_STDCALL_PTR(NI32, tyProc__Fg6EvxtNiMAMAT6csVhm9cA) (NI16* lpApplicationName_p0, NI16* lpCommandLine_p1, tyObject_SECURITY_ATTRIBUTES__9bhLIPSmjOM57xx9buGk4ikQ* lpProcessAttributes_p2, tyObject_SECURITY_ATTRIBUTES__9bhLIPSmjOM57xx9buGk4ikQ* lpThreadAttributes_p3, NI32 bInheritHandles_p4, NI32 dwCreationFlags_p5, NI16* lpEnvironment_p6, NI16* lpCurrentDirectory_p7, tyObject_STARTUPINFO__ZQ9ciMsZVvVf8P0rtQ09bUCw* lpStartupInfo_p8, tyObject_PROCESS_INFORMATION__Qr2jyNkBR7zRkYbPVoaJdA* lpProcessInformation_p9);
typedef NimStringV2 tyArray__TonP9cxJgj8gXu71dWIyNlA[1];
typedef N_NIMCALL_PTR(void, tyProc__8mqxViv8YWQQERlypIPj7A) (tyObject_StreamObj__59a9bMG3hIslwPg3r9aB4JTRg* s_p0);
typedef N_NIMCALL_PTR(NIM_BOOL, tyProc__AO2K7Qm0IKWo0Ft5qmZ61g) (tyObject_StreamObj__59a9bMG3hIslwPg3r9aB4JTRg* s_p0);
typedef N_NIMCALL_PTR(void, tyProc__edEQxoj4ZH9a68n4Z9bKMpzg) (tyObject_StreamObj__59a9bMG3hIslwPg3r9aB4JTRg* s_p0, NI pos_p1);
typedef N_NIMCALL_PTR(NI, tyProc__hYjIfmER3nDMnsDy9cOEcAg) (tyObject_StreamObj__59a9bMG3hIslwPg3r9aB4JTRg* s_p0);
typedef N_NIMCALL_PTR(NI, tyProc__P0Y69akwtLf59cgIe6qHSrKg) (tyObject_StreamObj__59a9bMG3hIslwPg3r9aB4JTRg* s_p0, NimStringV2* buffer_p1, tyObject_HSlice__RmqVCB5rHyE9cs59bZ8FgkPA slice_p2);
typedef N_NIMCALL_PTR(NIM_BOOL, tyProc__UzEh4OemSD9a71GEKbG1OGw) (tyObject_StreamObj__59a9bMG3hIslwPg3r9aB4JTRg* s_p0, NimStringV2* line_p1);
typedef N_NIMCALL_PTR(NI, tyProc__sgEamweDDOD9a5DdG0W9c1BA) (tyObject_StreamObj__59a9bMG3hIslwPg3r9aB4JTRg* s_p0, void* buffer_p1, NI bufLen_p2);
typedef N_NIMCALL_PTR(void, tyProc__Qpg3mKpS3gJljuzIS3PjtA) (tyObject_StreamObj__59a9bMG3hIslwPg3r9aB4JTRg* s_p0, void* buffer_p1, NI bufLen_p2);
struct tyObject_StreamObj__59a9bMG3hIslwPg3r9aB4JTRg {
	RootObj Sup;
	tyProc__8mqxViv8YWQQERlypIPj7A closeImpl;
	tyProc__AO2K7Qm0IKWo0Ft5qmZ61g atEndImpl;
	tyProc__edEQxoj4ZH9a68n4Z9bKMpzg setPositionImpl;
	tyProc__hYjIfmER3nDMnsDy9cOEcAg getPositionImpl;
	tyProc__P0Y69akwtLf59cgIe6qHSrKg readDataStrImpl;
	tyProc__UzEh4OemSD9a71GEKbG1OGw readLineImpl;
	tyProc__sgEamweDDOD9a5DdG0W9c1BA readDataImpl;
	tyProc__sgEamweDDOD9a5DdG0W9c1BA peekDataImpl;
	tyProc__Qpg3mKpS3gJljuzIS3PjtA writeDataImpl;
	tyProc__8mqxViv8YWQQERlypIPj7A flushImpl;
};
struct tyObject_FileHandleStreamcolonObjectType___zP8ssNQ49cn0fN87jk4EGjA {
	tyObject_StreamObj__59a9bMG3hIslwPg3r9aB4JTRg Sup;
	NI handle;
	NIM_BOOL atTheEnd;
};
typedef N_STDCALL_PTR(NI32, tyProc__9ajZYMGL5GqiRFqiCC367oA) (NI hFile_p0, void* buffer_p1, NI32 nNumberOfBytesToRead_p2, NI32* lpNumberOfBytesRead_p3, void* lpOverlapped_p4);
typedef N_STDCALL_PTR(NI32, tyProc__FprzxJFfqQdWyyGxiUsmeQ) (NI hHandle_p0, NI32 dwMilliseconds_p1);
typedef N_STDCALL_PTR(NI32, tyProc__KxeGXN001TReCr89ca9c5bng) (NI hProcess_p0, NI32* lpExitCode_p1);
struct tySequence__xv3aaFd3JCw8NbmALHiezQ_Content { NI cap; tyTuple__sPaDkVPSC0MkcoXCxPH9ccA data[SEQ_DECL_SIZE]; };
struct tyObject_HSlice__RmqVCB5rHyE9cs59bZ8FgkPA {
	NI a;
	NI b;
};
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__system_u2188)(void* a_p0, int v_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(tyObject_ProcessObj__UmZS0xU7o5OSPf9bpi5tgIA*, nospstartProcess)(NimStringV2 command_p0, NimStringV2 workingDir_p1, NimStringV2* args_p2, NI args_p2Len_0, tyObject_StringTableObj__MtedWbN0LmvZq2M8UCJLpA* env_p3, tySet_tyEnum_ProcessOption__O0VnkOD1kPGXGbZ5LEvw9cw options_p4);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZosproc_u228)(tyObject_ProcessObj__UmZS0xU7o5OSPf9bpi5tgIA* dest_p0);
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicDyn)(void* p_p0);
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1);
N_LIB_PRIVATE N_NOINLINE(void, rememberCycle__system_u3522)(NIM_BOOL isDestroyAction_p0, tyObject_RefHeader__sqhyc4FSbGmPtkvXRNl9acg* s_p1, TNimTypeV2* desc_p2);
N_LIB_PRIVATE N_NIMCALL(void, nimDestroyAndDispose)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObj)(NI size_p0, NI alignment_p1);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__pureZosproc_u1876)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZosproc_u248)(tyObject_ProcessObj__UmZS0xU7o5OSPf9bpi5tgIA* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___pureZosproc_u260)(tyObject_ProcessObj__UmZS0xU7o5OSPf9bpi5tgIA* dest_p0, void* env_p1);
static N_INLINE(void, nimTraceRefDyn)(void* q_p0, void* env_p1);
static N_INLINE(void, add__system_u3043)(tyObject_CellSeq__tmpRNCI2baMQRvZpqUI72g* s_p0, void** c_p1, TNimTypeV2* t_p2);
N_LIB_PRIVATE N_NIMCALL(void, resize__system_u3051)(tyObject_CellSeq__tmpRNCI2baMQRvZpqUI72g* s_p0);
static N_INLINE(NI, pluspercent___system_u793)(NI x_p0, NI y_p1);
N_LIB_PRIVATE N_NIMCALL(void, createPipeHandles__pureZosproc_u968)(NI* rdHandle_p0, NI* wrHandle_p1);
N_LIB_PRIVATE N_NOINLINE(void, raiseOSError__stdZoserrors_u122)(NI32 errorCode_p0, NimStringV2 additionalInfo_p1);
N_LIB_PRIVATE N_NIMCALL(NI32, osLastError__stdZoserrors_u125)(void);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, createAllPipeHandles__pureZosproc_u917)(tyObject_STARTUPINFO__ZQ9ciMsZVvVf8P0rtQ09bUCw* si_p0, NI* stdin_p1, NI* stdout_p2, NI* stderr_p3, NI hash_p4);
N_LIB_PRIVATE N_NIMCALL(tyObject_WideCStringObj__jQbOKocsbu7Z9bKTSFtX4TQ, newWideCString__stdZwidestrs_u325)(NimStringV2 s_p0);
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(void, copyMem__system_u1755)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___systemZdollars_u14)(NI xX60gensym0__p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, rawNewString)(NI space_p0);
static N_INLINE(NI16*, toWideCString__stdZwidestrs_u49)(tyObject_WideCStringObj__jQbOKocsbu7Z9bKTSFtX4TQ x_p0);
N_LIB_PRIVATE N_NIMCALL(NI, myDup__pureZosproc_u912)(NI h_p0, NI32 inherit_p1);
static N_INLINE(void, closeHandleCheck__pureZosproc_u767)(NI handle_p0);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___stdZwidestrs_u7)(tyObject_WideCStringObj__jQbOKocsbu7Z9bKTSFtX4TQ a_p0);
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, buildCommandLine__pureZosproc_u858)(NimStringV2 a_p0, NimStringV2* args_p1, NI args_p1Len_0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nospquoteShell)(NimStringV2 s_p0);
static N_INLINE(void, nimAddCharV1)(NimStringV2* s_p0, NIM_CHAR c_p1);
N_LIB_PRIVATE N_NIMCALL(void, prepareAdd)(NimStringV2* s_p0, NI addLen_p1);
N_LIB_PRIVATE N_NIMCALL(tyTuple__0hEbbYmlam6yzyW5MFo9cjg, buildEnv__pureZosproc_u870)(tyObject_StringTableObj__MtedWbN0LmvZq2M8UCJLpA* env_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___system_u2723)(NimStringV2* dest_p0, NimStringV2 src_p1);
N_LIB_PRIVATE N_NOCONV(void*, alloc0Impl__system_u1773)(NI size_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, cstrToNimstr)(NCSTRING str_p0);
N_LIB_PRIVATE N_NIMCALL(void, echoBinSafe)(NimStringV2* args_p0, NI args_p0Len_0);
N_LIB_PRIVATE N_NIMCALL(tyObject_WideCStringObj__jQbOKocsbu7Z9bKTSFtX4TQ, newWideCString__stdZwidestrs_u322)(NCSTRING s_p0);
N_LIB_PRIVATE N_NIMCALL(tyObject_WideCStringObj__jQbOKocsbu7Z9bKTSFtX4TQ, newWideCString__stdZwidestrs_u297)(NCSTRING source_p0, NI L_p1);
static N_INLINE(void, fileClose__pureZosproc_u774)(NI* h_p0);
static N_INLINE(NIM_BOOL, eqeq___system_u9141)(NCSTRING x_p0, NCSTRING y_p1);
N_LIB_PRIVATE N_NOCONV(void, dealloc)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, nospclose)(tyObject_ProcessObj__UmZS0xU7o5OSPf9bpi5tgIA* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, close__pureZstreams_u57)(tyObject_StreamObj__59a9bMG3hIslwPg3r9aB4JTRg* s_p0);
N_LIB_PRIVATE N_NIMCALL(void, closeThreadAndProcessHandle__pureZosproc_u1115)(tyObject_ProcessObj__UmZS0xU7o5OSPf9bpi5tgIA* p_p0);
N_LIB_PRIVATE N_NIMCALL(tyObject_StreamObj__59a9bMG3hIslwPg3r9aB4JTRg*, nospoutputStream)(tyObject_ProcessObj__UmZS0xU7o5OSPf9bpi5tgIA* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___pureZstreams_u797)(tyObject_StreamObj__59a9bMG3hIslwPg3r9aB4JTRg** dest_p0, tyObject_StreamObj__59a9bMG3hIslwPg3r9aB4JTRg* src_p1);
N_LIB_PRIVATE N_NIMCALL(tyObject_FileHandleStreamcolonObjectType___zP8ssNQ49cn0fN87jk4EGjA*, newFileHandleStream__pureZosproc_u855)(NI handle_p0);
N_LIB_PRIVATE N_NIMCALL(void, hsClose__pureZosproc_u772)(tyObject_StreamObj__59a9bMG3hIslwPg3r9aB4JTRg* s_p0);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, hsAtEnd__pureZosproc_u837)(tyObject_StreamObj__59a9bMG3hIslwPg3r9aB4JTRg* s_p0);
N_LIB_PRIVATE N_NIMCALL(NI, hsReadData__pureZosproc_u840)(tyObject_StreamObj__59a9bMG3hIslwPg3r9aB4JTRg* s_p0, void* buffer_p1, NI bufLen_p2);
N_LIB_PRIVATE N_NIMCALL(void, hsWriteData__pureZosproc_u848)(tyObject_StreamObj__59a9bMG3hIslwPg3r9aB4JTRg* s_p0, void* buffer_p1, NI bufLen_p2);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZosproc_u780)(tyObject_FileHandleStreamcolonObjectType___zP8ssNQ49cn0fN87jk4EGjA* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___pureZstreams_u789)(tyObject_StreamObj__59a9bMG3hIslwPg3r9aB4JTRg** dest_p0, tyObject_StreamObj__59a9bMG3hIslwPg3r9aB4JTRg* src_p1, NIM_BOOL cyclic_p2);
N_LIB_PRIVATE N_NIMCALL(void, write__pureZstreams_u221)(tyObject_StreamObj__59a9bMG3hIslwPg3r9aB4JTRg* s_p0, NimStringV2 x_p1);
N_LIB_PRIVATE N_NIMCALL(tyObject_StreamObj__59a9bMG3hIslwPg3r9aB4JTRg*, nospinputStream)(tyObject_ProcessObj__UmZS0xU7o5OSPf9bpi5tgIA* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZstreams_u786)(tyObject_StreamObj__59a9bMG3hIslwPg3r9aB4JTRg* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___system_u2720)(NimStringV2* dest_p0);
N_NIMCALL(NimStringV2, rawNewString)(NI cap_p0);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, readLine__pureZstreams_u668)(tyObject_StreamObj__59a9bMG3hIslwPg3r9aB4JTRg* s_p0, NimStringV2* line_p1);
N_LIB_PRIVATE N_NIMCALL(NI, nosppeekExitCode)(tyObject_ProcessObj__UmZS0xU7o5OSPf9bpi5tgIA* p_p0);
N_LIB_PRIVATE TNimTypeV2 NTIv2__UmZS0xU7o5OSPf9bpi5tgIA_;
static const struct {
  NI cap; NIM_CHAR data[0+1];
} TM__HZdw8BhppcTQo8DIK46LSg_3 = { 0 | NIM_STRLIT_FLAG, "" };
static const NimStringV2 TM__HZdw8BhppcTQo8DIK46LSg_4 = {0, (NimStrPayload*)&TM__HZdw8BhppcTQo8DIK46LSg_3};
static const NimStringV2 TM__HZdw8BhppcTQo8DIK46LSg_5 = {0, (NimStrPayload*)&TM__HZdw8BhppcTQo8DIK46LSg_3};
static const NimStringV2 TM__HZdw8BhppcTQo8DIK46LSg_6 = {0, (NimStrPayload*)&TM__HZdw8BhppcTQo8DIK46LSg_3};
static const NimStringV2 TM__HZdw8BhppcTQo8DIK46LSg_7 = {0, (NimStrPayload*)&TM__HZdw8BhppcTQo8DIK46LSg_3};
static const struct {
  NI cap; NIM_CHAR data[15+1];
} TM__HZdw8BhppcTQo8DIK46LSg_8 = { 15 | NIM_STRLIT_FLAG, "\\\\.\\pipe\\stdout" };
static const NimStringV2 TM__HZdw8BhppcTQo8DIK46LSg_9 = {15, (NimStrPayload*)&TM__HZdw8BhppcTQo8DIK46LSg_8};
static const struct {
  NI cap; NIM_CHAR data[14+1];
} TM__HZdw8BhppcTQo8DIK46LSg_10 = { 14 | NIM_STRLIT_FLAG, "\\\\.\\pipe\\stdin" };
static const NimStringV2 TM__HZdw8BhppcTQo8DIK46LSg_11 = {14, (NimStrPayload*)&TM__HZdw8BhppcTQo8DIK46LSg_10};
static const NimStringV2 TM__HZdw8BhppcTQo8DIK46LSg_12 = {0, (NimStrPayload*)&TM__HZdw8BhppcTQo8DIK46LSg_3};
static const NimStringV2 TM__HZdw8BhppcTQo8DIK46LSg_13 = {0, (NimStrPayload*)&TM__HZdw8BhppcTQo8DIK46LSg_3};
static const NimStringV2 TM__HZdw8BhppcTQo8DIK46LSg_14 = {0, (NimStrPayload*)&TM__HZdw8BhppcTQo8DIK46LSg_3};
static const NimStringV2 TM__HZdw8BhppcTQo8DIK46LSg_15 = {0, (NimStrPayload*)&TM__HZdw8BhppcTQo8DIK46LSg_3};
static const NimStringV2 TM__HZdw8BhppcTQo8DIK46LSg_16 = {0, (NimStrPayload*)&TM__HZdw8BhppcTQo8DIK46LSg_3};
static const NimStringV2 TM__HZdw8BhppcTQo8DIK46LSg_17 = {0, (NimStrPayload*)&TM__HZdw8BhppcTQo8DIK46LSg_3};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__HZdw8BhppcTQo8DIK46LSg_19 = { 1 | NIM_STRLIT_FLAG, "=" };
static const NimStringV2 TM__HZdw8BhppcTQo8DIK46LSg_20 = {1, (NimStrPayload*)&TM__HZdw8BhppcTQo8DIK46LSg_19};
static const struct {
  NI cap; NIM_CHAR data[30+1];
} TM__HZdw8BhppcTQo8DIK46LSg_21 = { 30 | NIM_STRLIT_FLAG, "Requested command not found: \'" };
static const NimStringV2 TM__HZdw8BhppcTQo8DIK46LSg_22 = {30, (NimStrPayload*)&TM__HZdw8BhppcTQo8DIK46LSg_21};
static const struct {
  NI cap; NIM_CHAR data[12+1];
} TM__HZdw8BhppcTQo8DIK46LSg_23 = { 12 | NIM_STRLIT_FLAG, "\'. OS error:" };
static const NimStringV2 TM__HZdw8BhppcTQo8DIK46LSg_24 = {12, (NimStrPayload*)&TM__HZdw8BhppcTQo8DIK46LSg_23};
N_LIB_PRIVATE TNimTypeV2 NTIv2__zP8ssNQ49cn0fN87jk4EGjA_;
static const NimStringV2 TM__HZdw8BhppcTQo8DIK46LSg_26 = {0, (NimStrPayload*)&TM__HZdw8BhppcTQo8DIK46LSg_3};
static const NimStringV2 TM__HZdw8BhppcTQo8DIK46LSg_27 = {0, (NimStrPayload*)&TM__HZdw8BhppcTQo8DIK46LSg_3};
static const NimStringV2 TM__HZdw8BhppcTQo8DIK46LSg_28 = {0, (NimStrPayload*)&TM__HZdw8BhppcTQo8DIK46LSg_3};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__HZdw8BhppcTQo8DIK46LSg_29 = { 1 | NIM_STRLIT_FLAG, "\012" };
static const NimStringV2 TM__HZdw8BhppcTQo8DIK46LSg_30 = {1, (NimStrPayload*)&TM__HZdw8BhppcTQo8DIK46LSg_29};
static NIM_CONST tyTuple__0hEbbYmlam6yzyW5MFo9cjg TM__HZdw8BhppcTQo8DIK46LSg_18 = {((NCSTRING) NIM_NIL),
((NI)-1)}
;
static NIM_CONST NU32 TM__HZdw8BhppcTQo8DIK46LSg_2[2] = {3701606400, 1716704000};
N_LIB_PRIVATE TNimTypeV2 NTIv2__UmZS0xU7o5OSPf9bpi5tgIA_ = {.destructor = (void*)rttiDestroy__pureZosproc_u1876, .size = sizeof(tyObject_ProcessObj__UmZS0xU7o5OSPf9bpi5tgIA), .align = (NI16) NIM_ALIGNOF(tyObject_ProcessObj__UmZS0xU7o5OSPf9bpi5tgIA), .depth = 1, .display = TM__HZdw8BhppcTQo8DIK46LSg_2, .traceImpl = (void*)eqtrace___pureZosproc_u260, .flags = 0};
extern tyProc__EN454t29c8zxeqsCUHjc1Pw Dl_1509949557_;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4172;
extern tyProc__mBVOPXmpGfUrrbA9a5K9cMbQ Dl_1509950044_;
extern tyProc__EYP7RqT3MHXHmseMIXVbTg Dl_1509949562_;
extern tyProc__Q9box9as0S1hHKH9cSO3MGDDA Dl_1509950049_;
extern tyProc__uryidYWkntM7ddjZSyxvyQ Dl_1509950048_;
extern tyProc__oew1DfaGl5XhHmnBK0HYXQ Dl_1509950033_;
extern tyProc__P13srMBg9b3d3yEV9aW4NCoA Dl_1509949543_;
extern tyProc__zP2zGemcuVRvOUE82f9a0Pw Dl_1509949602_;
extern tyProc__Fg6EvxtNiMAMAT6csVhm9cA Dl_1509949578_;
static NIM_CONST NU32 TM__HZdw8BhppcTQo8DIK46LSg_25[3] = {3701606400, 3750501120, 4281118720};
N_LIB_PRIVATE TNimTypeV2 NTIv2__zP8ssNQ49cn0fN87jk4EGjA_ = {.destructor = (void*)NIM_NIL, .size = sizeof(tyObject_FileHandleStreamcolonObjectType___zP8ssNQ49cn0fN87jk4EGjA), .align = (NI16) NIM_ALIGNOF(tyObject_FileHandleStreamcolonObjectType___zP8ssNQ49cn0fN87jk4EGjA), .depth = 2, .display = TM__HZdw8BhppcTQo8DIK46LSg_25, .traceImpl = (void*)NIM_NIL, .flags = 0};
extern tyProc__9ajZYMGL5GqiRFqiCC367oA Dl_1509949545_;
extern tyProc__9ajZYMGL5GqiRFqiCC367oA Dl_1509949551_;
extern tyProc__FprzxJFfqQdWyyGxiUsmeQ Dl_1509949593_;
extern tyProc__KxeGXN001TReCr89ca9c5bng Dl_1509949599_;
static N_INLINE(void, nimSetMem__system_u2188)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
	nimSetMem__system_u2188(p_p0, ((int)0), size_p1);
}
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1) {
	NI result;
	result = ((NI) ((NU)((NU64)(((NU) (x_p0))) - (NU64)(((NU) (y_p1))))));
	return result;
}
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicDyn)(void* p_p0) {
	NIM_BOOL result;
	result = NIM_FALSE;
	{
		tyObject_RefHeader__sqhyc4FSbGmPtkvXRNl9acg* cell_1;
		NI T5_;
		if (!!((p_p0 == NIM_NIL))) goto LA3_;
		T5_ = (NI)0;
		T5_ = minuspercent___system_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)16));
		cell_1 = ((tyObject_RefHeader__sqhyc4FSbGmPtkvXRNl9acg*) (T5_));
		{
			if (!((NI)((*cell_1).rc & ((NI)-16)) == ((NI)0))) goto LA8_;
			result = NIM_TRUE;
		}
		goto LA6_;
LA8_: ;
		{
			(*cell_1).rc = minuspercent___system_u813((*cell_1).rc, ((NI)16));
		}
LA6_: ;
		rememberCycle__system_u3522(result, cell_1, (*((TNimTypeV2**) (p_p0))));
	}
LA3_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZosproc_u228)(tyObject_ProcessObj__UmZS0xU7o5OSPf9bpi5tgIA* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn(dest_p0);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose(dest_p0);
	}
LA4_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZosproc_u248)(tyObject_ProcessObj__UmZS0xU7o5OSPf9bpi5tgIA* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).errStream);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).errStream);
	}
LA4_: ;
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).outStream);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).outStream);
	}
LA9_: ;
	{
		NIM_BOOL T13_;
		T13_ = (NIM_BOOL)0;
		T13_ = nimDecRefIsLastCyclicDyn((*dest_p0).inStream);
		if (!T13_) goto LA14_;
		nimDestroyAndDispose((*dest_p0).inStream);
	}
LA14_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__pureZosproc_u1876)(void* dest_p0) {
	eqdestroy___pureZosproc_u248(((tyObject_ProcessObj__UmZS0xU7o5OSPf9bpi5tgIA*) (dest_p0)));
}
static N_INLINE(NI, pluspercent___system_u793)(NI x_p0, NI y_p1) {
	NI result;
	result = ((NI) ((NU)((NU64)(((NU) (x_p0))) + (NU64)(((NU) (y_p1))))));
	return result;
}
static N_INLINE(void, add__system_u3043)(tyObject_CellSeq__tmpRNCI2baMQRvZpqUI72g* s_p0, void** c_p1, TNimTypeV2* t_p2) {
	void** colontmp_;
	TNimTypeV2* colontmp__2;
	{
		if (!((*s_p0).cap <= (*s_p0).len)) goto LA3_;
		resize__system_u3051(s_p0);
	}
LA3_: ;
	colontmp_ = c_p1;
	colontmp__2 = t_p2;
	(*s_p0).d[(*s_p0).len].Field0 = colontmp_;
	(*s_p0).d[(*s_p0).len].Field1 = colontmp__2;
	(*s_p0).len = pluspercent___system_u793((*s_p0).len, ((NI)1));
}
static N_INLINE(void, nimTraceRefDyn)(void* q_p0, void* env_p1) {
	void** p_1;
	p_1 = ((void**) (q_p0));
	{
		tyObject_GcEnv__85WwC9a1qDcL9aPJ9b1qr0g2Q* j_1;
		if (!!(((*p_1) == NIM_NIL))) goto LA3_;
		j_1 = ((tyObject_GcEnv__85WwC9a1qDcL9aPJ9b1qr0g2Q*) (env_p1));
		add__system_u3043((&(*j_1).traceStack), p_1, (*((TNimTypeV2**) ((*p_1)))));
	}
LA3_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___pureZosproc_u260)(tyObject_ProcessObj__UmZS0xU7o5OSPf9bpi5tgIA* dest_p0, void* env_p1) {
	nimTraceRefDyn(&(*dest_p0).inStream, env_p1);
	nimTraceRefDyn(&(*dest_p0).outStream, env_p1);
	nimTraceRefDyn(&(*dest_p0).errStream, env_p1);
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4172);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, createPipeHandles__pureZosproc_u968)(NI* rdHandle_p0, NI* wrHandle_p1) {
	tyObject_SECURITY_ATTRIBUTES__9bhLIPSmjOM57xx9buGk4ikQ sa_1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&sa_1), sizeof(tyObject_SECURITY_ATTRIBUTES__9bhLIPSmjOM57xx9buGk4ikQ));
	sa_1.nLength = ((int)24);
	sa_1.lpSecurityDescriptor = NIM_NIL;
	sa_1.bInheritHandle = ((NI32)1);
	{
		NI32 T3_;
		NI32 T6_;
		T3_ = (NI32)0;
		T3_ = Dl_1509949557_(rdHandle_p0, wrHandle_p1, (&sa_1), ((NI32)0));
		if (!(T3_ == ((NI32)0))) goto LA4_;
		T6_ = (NI32)0;
		T6_ = osLastError__stdZoserrors_u125();
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		raiseOSError__stdZoserrors_u122(T6_, TM__HZdw8BhppcTQo8DIK46LSg_4);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA4_: ;
	}BeforeRet_: ;
}
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, copyMem__system_u1755)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1) {
	{
		if (!(((NI)0) < src_p1.len)) goto LA3_;
		copyMem__system_u1755(((void*) ((&(*(*dest_p0).p).data[(*dest_p0).len]))), ((void*) ((&(*src_p1.p).data[((NI)0)]))), (src_p1.len));
		(*dest_p0).len += src_p1.len;
		(*(*dest_p0).p).data[(*dest_p0).len] = 0;
	}
LA3_: ;
}
static N_INLINE(NI16*, toWideCString__stdZwidestrs_u49)(tyObject_WideCStringObj__jQbOKocsbu7Z9bKTSFtX4TQ x_p0) {
	NI16* result;
	result = x_p0.data;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, myDup__pureZosproc_u912)(NI h_p0, NI32 inherit_p1) {
	NI result;
	NI thisProc_1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	thisProc_1 = Dl_1509950048_();
	{
		NI32 T3_;
		NI32 T6_;
		T3_ = (NI32)0;
		T3_ = Dl_1509950033_(thisProc_1, h_p0, thisProc_1, (&result), ((NI32)0), inherit_p1, ((NI32)2));
		if (!(T3_ == ((NI32)0))) goto LA4_;
		T6_ = (NI32)0;
		T6_ = osLastError__stdZoserrors_u125();
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		raiseOSError__stdZoserrors_u122(T6_, TM__HZdw8BhppcTQo8DIK46LSg_15);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA4_: ;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(void, closeHandleCheck__pureZosproc_u767)(NI handle_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	{
		NI32 T3_;
		NI32 T6_;
		T3_ = (NI32)0;
		T3_ = Dl_1509949543_(handle_p0);
		if (!(T3_ == ((NI32)0))) goto LA4_;
		T6_ = (NI32)0;
		T6_ = osLastError__stdZoserrors_u125();
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		raiseOSError__stdZoserrors_u122(T6_, TM__HZdw8BhppcTQo8DIK46LSg_17);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA4_: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, createAllPipeHandles__pureZosproc_u917)(tyObject_STARTUPINFO__ZQ9ciMsZVvVf8P0rtQ09bUCw* si_p0, NI* stdin_p1, NI* stdout_p2, NI* stderr_p3, NI hash_p4) {
	tyObject_WideCStringObj__jQbOKocsbu7Z9bKTSFtX4TQ pipeOutName_1;
	NimStringV2 colontmpD_;
	NimStringV2 colontmpD__2;
	tyObject_WideCStringObj__jQbOKocsbu7Z9bKTSFtX4TQ pipeInName_1;
	NimStringV2 colontmpD__3;
	NimStringV2 colontmpD__4;
	tyObject_SECURITY_ATTRIBUTES__9bhLIPSmjOM57xx9buGk4ikQ sa_1;
	NimStringV2 T2_;
	NimStringV2 T3_;
	NI pipeOut_1;
	NI16* T4_;
	NI pipeIn_1;
	NI16* T10_;
	NI16* T16_;
	NI T22_;
	NI16* T23_;
	NI T29_;
	NI T30_;
NIM_BOOL oldNimErrFin1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&pipeOutName_1), sizeof(tyObject_WideCStringObj__jQbOKocsbu7Z9bKTSFtX4TQ));
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
	nimZeroMem((void*)(&pipeInName_1), sizeof(tyObject_WideCStringObj__jQbOKocsbu7Z9bKTSFtX4TQ));
	colontmpD__3.len = 0; colontmpD__3.p = NIM_NIL;
	colontmpD__4.len = 0; colontmpD__4.p = NIM_NIL;
	nimZeroMem((void*)(&sa_1), sizeof(tyObject_SECURITY_ATTRIBUTES__9bhLIPSmjOM57xx9buGk4ikQ));
	sa_1.nLength = ((int)24);
	sa_1.lpSecurityDescriptor = NIM_NIL;
	sa_1.bInheritHandle = ((NI32)1);
	T2_.len = 0; T2_.p = NIM_NIL;
	colontmpD_ = dollar___systemZdollars_u14(hash_p4);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T2_ = rawNewString(colontmpD_.len + 15);
appendString((&T2_), TM__HZdw8BhppcTQo8DIK46LSg_9);
appendString((&T2_), colontmpD_);
	colontmpD__2 = T2_;
	pipeOutName_1 = newWideCString__stdZwidestrs_u325(colontmpD__2);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T3_.len = 0; T3_.p = NIM_NIL;
	colontmpD__3 = dollar___systemZdollars_u14(hash_p4);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T3_ = rawNewString(colontmpD__3.len + 14);
appendString((&T3_), TM__HZdw8BhppcTQo8DIK46LSg_11);
appendString((&T3_), colontmpD__3);
	colontmpD__4 = T3_;
	pipeInName_1 = newWideCString__stdZwidestrs_u325(colontmpD__4);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T4_ = (NI16*)0;
	T4_ = toWideCString__stdZwidestrs_u49(pipeOutName_1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	pipeOut_1 = Dl_1509949562_(T4_, ((NI32)-2147483647), ((NI32)1), ((NI32)1), ((NI32)1024), ((NI32)1024), ((NI32)0), (&sa_1));
	{
		NI32 T9_;
		if (!(pipeOut_1 == ((NI)-1))) goto LA7_;
		T9_ = (NI32)0;
		T9_ = osLastError__stdZoserrors_u125();
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		raiseOSError__stdZoserrors_u122(T9_, TM__HZdw8BhppcTQo8DIK46LSg_12);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	}
LA7_: ;
	T10_ = (NI16*)0;
	T10_ = toWideCString__stdZwidestrs_u49(pipeInName_1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	pipeIn_1 = Dl_1509949562_(T10_, ((NI32)-2147483646), ((NI32)1), ((NI32)1), ((NI32)1024), ((NI32)1024), ((NI32)0), (&sa_1));
	{
		NI32 T15_;
		if (!(pipeIn_1 == ((NI)-1))) goto LA13_;
		T15_ = (NI32)0;
		T15_ = osLastError__stdZoserrors_u125();
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		raiseOSError__stdZoserrors_u122(T15_, TM__HZdw8BhppcTQo8DIK46LSg_13);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	}
LA13_: ;
	T16_ = (NI16*)0;
	T16_ = toWideCString__stdZwidestrs_u49(pipeOutName_1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	(*si_p0).hStdOutput = Dl_1509950049_(T16_, ((NI32)1048578), ((NI32)0), ((void*) ((&sa_1))), ((NI32)3), ((NI32)128), ((NI)0));
	{
		NI32 T21_;
		if (!((*si_p0).hStdOutput == ((NI)-1))) goto LA19_;
		T21_ = (NI32)0;
		T21_ = osLastError__stdZoserrors_u125();
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		raiseOSError__stdZoserrors_u122(T21_, TM__HZdw8BhppcTQo8DIK46LSg_14);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	}
LA19_: ;
	T22_ = (NI)0;
	T22_ = myDup__pureZosproc_u912((*si_p0).hStdOutput, ((NI32)1));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	(*si_p0).hStdError = T22_;
	T23_ = (NI16*)0;
	T23_ = toWideCString__stdZwidestrs_u49(pipeInName_1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	(*si_p0).hStdInput = Dl_1509950049_(T23_, ((NI32)1048577), ((NI32)0), ((void*) ((&sa_1))), ((NI32)3), ((NI32)128), ((NI)0));
	{
		NI32 T28_;
		if (!((*si_p0).hStdInput == ((NI)-1))) goto LA26_;
		T28_ = (NI32)0;
		T28_ = osLastError__stdZoserrors_u125();
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		raiseOSError__stdZoserrors_u122(T28_, TM__HZdw8BhppcTQo8DIK46LSg_16);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	}
LA26_: ;
	T29_ = (NI)0;
	T29_ = myDup__pureZosproc_u912(pipeIn_1, ((NI32)0));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	(*stdin_p1) = T29_;
	T30_ = (NI)0;
	T30_ = myDup__pureZosproc_u912(pipeOut_1, ((NI32)0));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	(*stdout_p2) = T30_;
	closeHandleCheck__pureZosproc_u767(pipeIn_1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	closeHandleCheck__pureZosproc_u767(pipeOut_1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	(*stderr_p3) = (*stdout_p2);
	{
		LA1_:;
	}
	{
		oldNimErrFin1_ = *nimErr_; *nimErr_ = NIM_FALSE;
		if (colontmpD__4.p && !(colontmpD__4.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__4.p);
}
		if (colontmpD__3.p && !(colontmpD__3.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__3.p);
}
		eqdestroy___stdZwidestrs_u7(pipeInName_1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (colontmpD__2.p && !(colontmpD__2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__2.p);
}
		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
		eqdestroy___stdZwidestrs_u7(pipeOutName_1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		*nimErr_ = oldNimErrFin1_;
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0) {
	NCSTRING result;
	{
		if (!(s_p0.len == ((NI)0))) goto LA3_;
		result = "";
	}
	goto LA1_;
LA3_: ;
	{
		result = ((NCSTRING) ((*s_p0.p).data));
	}
LA1_: ;
	return result;
}
static N_INLINE(void, nimAddCharV1)(NimStringV2* s_p0, NIM_CHAR c_p1) {
	prepareAdd(s_p0, ((NI)1));
	(*(*s_p0).p).data[(*s_p0).len] = c_p1;
	(*s_p0).len += ((NI)1);
	(*(*s_p0).p).data[(*s_p0).len] = 0;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, buildCommandLine__pureZosproc_u858)(NimStringV2 a_p0, NimStringV2* args_p1, NI args_p1Len_0) {
	NimStringV2 result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	result = nospquoteShell(a_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		NI i_1;
		NI colontmp_;
		NI res_1;
		i_1 = (NI)0;
		colontmp_ = (NI)0;
		colontmp_ = (args_p1Len_0-1);
		res_1 = ((NI)0);
		{
			while (1) {
				NimStringV2 colontmpD_;
				if (!(res_1 <= colontmp_)) goto LA3;
				colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
				i_1 = ((NI) (res_1));
				nimAddCharV1((&result), 32);
				colontmpD_ = nospquoteShell(args_p1[i_1]);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				prepareAdd((&result), colontmpD_.len + 0);
appendString((&result), colontmpD_);
				res_1 += ((NI)1);
				if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
			} LA3: ;
		}
	}
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyTuple__0hEbbYmlam6yzyW5MFo9cjg, buildEnv__pureZosproc_u870)(tyObject_StringTableObj__MtedWbN0LmvZq2M8UCJLpA* env_p0) {
	tyTuple__0hEbbYmlam6yzyW5MFo9cjg result;
	NI L_1;
	NCSTRING str_1;
	void* T10_;
	nimZeroMem((void*)(&result), sizeof(tyTuple__0hEbbYmlam6yzyW5MFo9cjg));
	L_1 = ((NI)0);
	{
		NimStringV2 key_1;
		NimStringV2 val_1;
		key_1.len = 0; key_1.p = NIM_NIL;
		val_1.len = 0; val_1.p = NIM_NIL;
		{
			NI h_1;
			NI colontmp_;
			NI T3_;
			NI res_1;
			h_1 = (NI)0;
			colontmp_ = (NI)0;
			T3_ = ((*env_p0).data.len-1);
			colontmp_ = T3_;
			res_1 = ((NI)0);
			{
				while (1) {
					if (!(res_1 <= colontmp_)) goto LA5;
					h_1 = ((NI) (res_1));
					{
						if (!(*env_p0).data.p->data[h_1].Field2) goto LA8_;
						eqcopy___system_u2723((&key_1), (*env_p0).data.p->data[h_1].Field0);
						eqcopy___system_u2723((&val_1), (*env_p0).data.p->data[h_1].Field1);
						L_1 += (NI)((NI)(key_1.len + val_1.len) + ((NI)2));
					}
LA8_: ;
					res_1 += ((NI)1);
				} LA5: ;
			}
		}
		if (val_1.p && !(val_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(val_1.p);
}
		if (key_1.p && !(key_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(key_1.p);
}
	}
	T10_ = (void*)0;
	T10_ = alloc0Impl__system_u1773(((NI)(L_1 + ((NI)2))));
	str_1 = ((NCSTRING) (T10_));
	L_1 = ((NI)0);
	{
		NimStringV2 key_2;
		NimStringV2 val_2;
		key_2.len = 0; key_2.p = NIM_NIL;
		val_2.len = 0; val_2.p = NIM_NIL;
		{
			NI h_2;
			NI colontmp__2;
			NI T13_;
			NI res_2;
			h_2 = (NI)0;
			colontmp__2 = (NI)0;
			T13_ = ((*env_p0).data.len-1);
			colontmp__2 = T13_;
			res_2 = ((NI)0);
			{
				while (1) {
					if (!(res_2 <= colontmp__2)) goto LA15;
					h_2 = ((NI) (res_2));
					{
						NimStringV2 x_1;
						NimStringV2 T20_;
						if (!(*env_p0).data.p->data[h_2].Field2) goto LA18_;
						x_1.len = 0; x_1.p = NIM_NIL;
						eqcopy___system_u2723((&key_2), (*env_p0).data.p->data[h_2].Field0);
						eqcopy___system_u2723((&val_2), (*env_p0).data.p->data[h_2].Field1);
						T20_.len = 0; T20_.p = NIM_NIL;
						T20_ = rawNewString(key_2.len + val_2.len + 1);
appendString((&T20_), key_2);
appendString((&T20_), TM__HZdw8BhppcTQo8DIK46LSg_20);
appendString((&T20_), val_2);
						x_1 = T20_;
						copyMem__system_u1755(((void*) ((&str_1[L_1]))), ((void*) (nimToCStringConv(x_1))), ((NI)(x_1.len + ((NI)1))));
						L_1 += (NI)(x_1.len + ((NI)1));
						if (x_1.p && !(x_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(x_1.p);
}
					}
LA18_: ;
					res_2 += ((NI)1);
				} LA15: ;
			}
		}
		if (val_2.p && !(val_2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(val_2.p);
}
		if (key_2.p && !(key_2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(key_2.p);
}
	}
	result.Field0 = str_1;
	result.Field1 = L_1;
	return result;
}
static N_INLINE(void, fileClose__pureZosproc_u774)(NI* h_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	{
		if (!(((NI)4) < (*h_p0))) goto LA3_;
		closeHandleCheck__pureZosproc_u767((*h_p0));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		(*h_p0) = ((NI)-1);
	}
LA3_: ;
	}BeforeRet_: ;
}
static N_INLINE(NIM_BOOL, eqeq___system_u9141)(NCSTRING x_p0, NCSTRING y_p1) {
	NIM_BOOL result;
	{
		if (!(((void*) (x_p0)) == ((void*) (y_p1)))) goto LA3_;
		result = NIM_TRUE;
	}
	goto LA1_;
LA3_: ;
	{
		NIM_BOOL T6_;
		T6_ = (NIM_BOOL)0;
		T6_ = (((void*) (x_p0)) == NIM_NIL);
		if (T6_) goto LA7_;
		T6_ = (((void*) (y_p1)) == NIM_NIL);
LA7_: ;
		if (!T6_) goto LA8_;
		result = NIM_FALSE;
	}
	goto LA1_;
LA8_: ;
	{
		int T11_;
		T11_ = (int)0;
		T11_ = strcmp(x_p0, y_p1);
		result = (T11_ == ((NI32)0));
	}
LA1_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, closeThreadAndProcessHandle__pureZosproc_u1115)(tyObject_ProcessObj__UmZS0xU7o5OSPf9bpi5tgIA* p_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	{
		if (!!(((*p_p0).fThreadHandle == ((NI)0)))) goto LA3_;
		closeHandleCheck__pureZosproc_u767((*p_p0).fThreadHandle);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		(*p_p0).fThreadHandle = ((NI)0);
	}
LA3_: ;
	{
		if (!!(((*p_p0).fProcessHandle == ((NI)0)))) goto LA7_;
		closeHandleCheck__pureZosproc_u767((*p_p0).fProcessHandle);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		(*p_p0).fProcessHandle = ((NI)0);
	}
LA7_: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, nospclose)(tyObject_ProcessObj__UmZS0xU7o5OSPf9bpi5tgIA* p_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	{
		if (!!((((*p_p0).options &((NU8)1<<((NU)((((tyEnum_ProcessOption__O0VnkOD1kPGXGbZ5LEvw9cw)4)))&7U)))!=0))) goto LA3_;
		{
			if (!((*p_p0).inStream == ((tyObject_StreamObj__59a9bMG3hIslwPg3r9aB4JTRg*) NIM_NIL))) goto LA7_;
			fileClose__pureZosproc_u774((&(*p_p0).inHandle));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
		goto LA5_;
LA7_: ;
		{
			close__pureZstreams_u57((*p_p0).inStream);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
LA5_: ;
		{
			if (!!(((*p_p0).outHandle == (*p_p0).errHandle))) goto LA12_;
			fileClose__pureZosproc_u774((&(*p_p0).errHandle));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
LA12_: ;
		fileClose__pureZosproc_u774((&(*p_p0).outHandle));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA3_: ;
	closeThreadAndProcessHandle__pureZosproc_u1115(p_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_ProcessObj__UmZS0xU7o5OSPf9bpi5tgIA*, nospstartProcess)(NimStringV2 command_p0, NimStringV2 workingDir_p1, NimStringV2* args_p2, NI args_p2Len_0, tyObject_StringTableObj__MtedWbN0LmvZq2M8UCJLpA* env_p3, tySet_tyEnum_ProcessOption__O0VnkOD1kPGXGbZ5LEvw9cw options_p4) {
	tyObject_ProcessObj__UmZS0xU7o5OSPf9bpi5tgIA* result;
	NimStringV2 cmdRoot_1;
	tyObject_WideCStringObj__jQbOKocsbu7Z9bKTSFtX4TQ tmp_1;
	tyObject_WideCStringObj__jQbOKocsbu7Z9bKTSFtX4TQ ee_1;
	tyObject_WideCStringObj__jQbOKocsbu7Z9bKTSFtX4TQ wwd_1;
	tyObject_STARTUPINFO__ZQ9ciMsZVvVf8P0rtQ09bUCw si_1;
	tyObject_PROCESS_INFORMATION__Qr2jyNkBR7zRkYbPVoaJdA procInfo_1;
	NI success_1;
	NI hi_1;
	NI ho_1;
	NI he_1;
	NCSTRING cmdl_1;
	NCSTRING wd_1;
	tyTuple__0hEbbYmlam6yzyW5MFo9cjg e_1;
	tyObject_WideCStringObj__jQbOKocsbu7Z9bKTSFtX4TQ T56_;
	NI32 flags_1;
	NI16* T66_;
	NI16* T67_;
	NI16* T68_;
	NI32 T69_;
	NI32 lastError_1;
NIM_BOOL oldNimErrFin1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	cmdRoot_1.len = 0; cmdRoot_1.p = NIM_NIL;
	nimZeroMem((void*)(&tmp_1), sizeof(tyObject_WideCStringObj__jQbOKocsbu7Z9bKTSFtX4TQ));
	nimZeroMem((void*)(&ee_1), sizeof(tyObject_WideCStringObj__jQbOKocsbu7Z9bKTSFtX4TQ));
	nimZeroMem((void*)(&wwd_1), sizeof(tyObject_WideCStringObj__jQbOKocsbu7Z9bKTSFtX4TQ));
	nimZeroMem((void*)(&si_1), sizeof(tyObject_STARTUPINFO__ZQ9ciMsZVvVf8P0rtQ09bUCw));
	nimZeroMem((void*)(&procInfo_1), sizeof(tyObject_PROCESS_INFORMATION__Qr2jyNkBR7zRkYbPVoaJdA));
	success_1 = (NI)0;
	hi_1 = (NI)0;
	ho_1 = (NI)0;
	he_1 = (NI)0;
	eqdestroy___pureZosproc_u228(result);
	result = (tyObject_ProcessObj__UmZS0xU7o5OSPf9bpi5tgIA*) nimNewObj(sizeof(tyObject_ProcessObj__UmZS0xU7o5OSPf9bpi5tgIA), NIM_ALIGNOF(tyObject_ProcessObj__UmZS0xU7o5OSPf9bpi5tgIA));
	(*result).Sup.m_type = (&NTIv2__UmZS0xU7o5OSPf9bpi5tgIA_);
	(*result).options = options_p4;
	(*result).exitFlag = NIM_TRUE;
	si_1.cb = ((int)104);
	{
		if (!!(((options_p4 &((NU8)1<<((NU)((((tyEnum_ProcessOption__O0VnkOD1kPGXGbZ5LEvw9cw)4)))&7U)))!=0))) goto LA4_;
		si_1.dwFlags = ((NI32)256);
		{
			if (!!(((options_p4 &((NU8)1<<((NU)((((tyEnum_ProcessOption__O0VnkOD1kPGXGbZ5LEvw9cw)5)))&7U)))!=0))) goto LA8_;
			createPipeHandles__pureZosproc_u968((&si_1.hStdInput), (&hi_1));
			if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
			createPipeHandles__pureZosproc_u968((&ho_1), (&si_1.hStdOutput));
			if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
			{
				if (!((options_p4 &((NU8)1<<((NU)((((tyEnum_ProcessOption__O0VnkOD1kPGXGbZ5LEvw9cw)3)))&7U)))!=0)) goto LA12_;
				si_1.hStdError = si_1.hStdOutput;
				he_1 = ho_1;
			}
			goto LA10_;
LA12_: ;
			{
				createPipeHandles__pureZosproc_u968((&he_1), (&si_1.hStdError));
				if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
				{
					NI32 T17_;
					NI32 T20_;
					T17_ = (NI32)0;
					T17_ = Dl_1509950044_(he_1, ((NI32)1), ((NI32)0));
					if (!(T17_ == ((NI32)0))) goto LA18_;
					T20_ = (NI32)0;
					T20_ = osLastError__stdZoserrors_u125();
					if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
					raiseOSError__stdZoserrors_u122(T20_, TM__HZdw8BhppcTQo8DIK46LSg_5);
					if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
				}
LA18_: ;
			}
LA10_: ;
			{
				NI32 T23_;
				NI32 T26_;
				T23_ = (NI32)0;
				T23_ = Dl_1509950044_(hi_1, ((NI32)1), ((NI32)0));
				if (!(T23_ == ((NI32)0))) goto LA24_;
				T26_ = (NI32)0;
				T26_ = osLastError__stdZoserrors_u125();
				if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
				raiseOSError__stdZoserrors_u122(T26_, TM__HZdw8BhppcTQo8DIK46LSg_6);
				if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
			}
LA24_: ;
			{
				NI32 T29_;
				NI32 T32_;
				T29_ = (NI32)0;
				T29_ = Dl_1509950044_(ho_1, ((NI32)1), ((NI32)0));
				if (!(T29_ == ((NI32)0))) goto LA30_;
				T32_ = (NI32)0;
				T32_ = osLastError__stdZoserrors_u125();
				if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
				raiseOSError__stdZoserrors_u122(T32_, TM__HZdw8BhppcTQo8DIK46LSg_7);
				if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
			}
LA30_: ;
		}
		goto LA6_;
LA8_: ;
		{
			createAllPipeHandles__pureZosproc_u917((&si_1), (&hi_1), (&ho_1), (&he_1), ((NI) (result)));
			if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		}
LA6_: ;
		(*result).inHandle = hi_1;
		(*result).outHandle = ho_1;
		(*result).errHandle = he_1;
	}
	goto LA2_;
LA4_: ;
	{
		si_1.hStdError = Dl_1509949602_(((NI32)-12));
		si_1.hStdInput = Dl_1509949602_(((NI32)-10));
		si_1.hStdOutput = Dl_1509949602_(((NI32)-11));
		(*result).inHandle = si_1.hStdInput;
		(*result).outHandle = si_1.hStdOutput;
		(*result).errHandle = si_1.hStdError;
	}
LA2_: ;
	cmdl_1 = (NCSTRING)0;
	{
		if (!((options_p4 &((NU8)1<<((NU)((((tyEnum_ProcessOption__O0VnkOD1kPGXGbZ5LEvw9cw)2)))&7U)))!=0)) goto LA37_;
		cmdl_1 = nimToCStringConv(command_p0);
	}
	goto LA35_;
LA37_: ;
	{
		cmdRoot_1 = buildCommandLine__pureZosproc_u858(command_p0, args_p2, args_p2Len_0);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		cmdl_1 = nimToCStringConv(cmdRoot_1);
	}
LA35_: ;
	wd_1 = ((NCSTRING) NIM_NIL);
	e_1 = TM__HZdw8BhppcTQo8DIK46LSg_18;
	{
		if (!(((NI)0) < workingDir_p1.len)) goto LA42_;
		wd_1 = nimToCStringConv(workingDir_p1);
	}
LA42_: ;
	{
		if (!!((env_p3 == ((tyObject_StringTableObj__MtedWbN0LmvZq2M8UCJLpA*) NIM_NIL)))) goto LA46_;
		e_1 = buildEnv__pureZosproc_u870(env_p3);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	}
LA46_: ;
	{
		NimStringV2 colontmpD_;
		tyArray__YgExxhfgKcesA5EOUj1MOA T53_;
		if (!((options_p4 &((NU8)1<<((NU)((((tyEnum_ProcessOption__O0VnkOD1kPGXGbZ5LEvw9cw)0)))&7U)))!=0)) goto LA50_;
		colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
		colontmpD_ = cstrToNimstr(cmdl_1);
		T53_[0] = colontmpD_;
		echoBinSafe(T53_, 1);
		{
			LA52_:;
		}
		{
			if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
		}
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	}
LA50_: ;
	tmp_1 = newWideCString__stdZwidestrs_u322(cmdl_1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		if (!(e_1.Field0 == 0)) goto LA59_;
		ee_1 = newWideCString__stdZwidestrs_u322(((NCSTRING) NIM_NIL));
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	}
	goto LA57_;
LA59_: ;
	{
		ee_1 = newWideCString__stdZwidestrs_u297(e_1.Field0, e_1.Field1);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	}
LA57_: ;
	wwd_1 = newWideCString__stdZwidestrs_u322(wd_1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	flags_1 = ((NI32)1056);
	{
		if (!((options_p4 &((NU8)1<<((NU)((((tyEnum_ProcessOption__O0VnkOD1kPGXGbZ5LEvw9cw)6)))&7U)))!=0)) goto LA64_;
		flags_1 = (NI32)(flags_1 | ((NI32)134217728));
	}
LA64_: ;
	T66_ = (NI16*)0;
	T66_ = toWideCString__stdZwidestrs_u49(tmp_1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T67_ = (NI16*)0;
	T67_ = toWideCString__stdZwidestrs_u49(ee_1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T68_ = (NI16*)0;
	T68_ = toWideCString__stdZwidestrs_u49(wwd_1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T69_ = (NI32)0;
	T69_ = Dl_1509949578_(((NI16*) NIM_NIL), T66_, ((tyObject_SECURITY_ATTRIBUTES__9bhLIPSmjOM57xx9buGk4ikQ*) NIM_NIL), ((tyObject_SECURITY_ATTRIBUTES__9bhLIPSmjOM57xx9buGk4ikQ*) NIM_NIL), ((NI32)1), flags_1, T67_, T68_, (&si_1), (&procInfo_1));
	success_1 = ((NI) (T69_));
	lastError_1 = osLastError__stdZoserrors_u125();
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		if (!!(((options_p4 &((NU8)1<<((NU)((((tyEnum_ProcessOption__O0VnkOD1kPGXGbZ5LEvw9cw)4)))&7U)))!=0))) goto LA72_;
		fileClose__pureZosproc_u774((&si_1.hStdInput));
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		fileClose__pureZosproc_u774((&si_1.hStdOutput));
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		{
			if (!!(((options_p4 &((NU8)1<<((NU)((((tyEnum_ProcessOption__O0VnkOD1kPGXGbZ5LEvw9cw)3)))&7U)))!=0))) goto LA76_;
			fileClose__pureZosproc_u774((&si_1.hStdError));
			if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		}
LA76_: ;
	}
LA72_: ;
	{
		NIM_BOOL T80_;
		T80_ = (NIM_BOOL)0;
		T80_ = eqeq___system_u9141(e_1.Field0, ((NCSTRING) NIM_NIL));
		if (!!(T80_)) goto LA81_;
		dealloc(((void*) (e_1.Field0)));
	}
LA81_: ;
	{
		if (!(success_1 == ((NI)0))) goto LA85_;
		{
			if (!(((*result).options &((NU8)1<<((NU)((((tyEnum_ProcessOption__O0VnkOD1kPGXGbZ5LEvw9cw)5)))&7U)))!=0)) goto LA89_;
			nospclose(result);
			if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		}
LA89_: ;
		switch (((NI) (lastError_1))) {
		case ((NI)87):
		case ((NI)2):
		{
			NimStringV2 colontmpD__2;
			NimStringV2 T93_;
			colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
			T93_.len = 0; T93_.p = NIM_NIL;
			T93_ = rawNewString(command_p0.len + 42);
appendString((&T93_), TM__HZdw8BhppcTQo8DIK46LSg_22);
appendString((&T93_), command_p0);
appendString((&T93_), TM__HZdw8BhppcTQo8DIK46LSg_24);
			colontmpD__2 = T93_;
			raiseOSError__stdZoserrors_u122(lastError_1, colontmpD__2);
			if (NIM_UNLIKELY(*nimErr_)) goto LA92_;
			{
				LA92_:;
			}
			{
				if (colontmpD__2.p && !(colontmpD__2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__2.p);
}
			}
			if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		}
		break;
		default:
		{
			raiseOSError__stdZoserrors_u122(lastError_1, command_p0);
			if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		}
		break;
		}
	}
LA85_: ;
	(*result).fProcessHandle = procInfo_1.hProcess;
	(*result).fThreadHandle = procInfo_1.hThread;
	(*result).id = ((NI) (procInfo_1.dwProcessId));
	(*result).exitFlag = NIM_FALSE;
	{
		LA1_:;
	}
	{
		oldNimErrFin1_ = *nimErr_; *nimErr_ = NIM_FALSE;
		eqdestroy___stdZwidestrs_u7(wwd_1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		eqdestroy___stdZwidestrs_u7(ee_1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		eqdestroy___stdZwidestrs_u7(tmp_1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (cmdRoot_1.p && !(cmdRoot_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(cmdRoot_1.p);
}
		*nimErr_ = oldNimErrFin1_;
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, hsClose__pureZosproc_u772)(tyObject_StreamObj__59a9bMG3hIslwPg3r9aB4JTRg* s_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	fileClose__pureZosproc_u774((&(*((tyObject_FileHandleStreamcolonObjectType___zP8ssNQ49cn0fN87jk4EGjA*) (s_p0))).handle));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, hsAtEnd__pureZosproc_u837)(tyObject_StreamObj__59a9bMG3hIslwPg3r9aB4JTRg* s_p0) {
	NIM_BOOL result;
{	result = (*((tyObject_FileHandleStreamcolonObjectType___zP8ssNQ49cn0fN87jk4EGjA*) (s_p0))).atTheEnd;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, hsReadData__pureZosproc_u840)(tyObject_StreamObj__59a9bMG3hIslwPg3r9aB4JTRg* s_p0, void* buffer_p1, NI bufLen_p2) {
	NI result;
	tyObject_FileHandleStreamcolonObjectType___zP8ssNQ49cn0fN87jk4EGjA* s_2;
	NI32 br_1;
	NI32 a_1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	s_2 = NIM_NIL;
	s_2 = ((tyObject_FileHandleStreamcolonObjectType___zP8ssNQ49cn0fN87jk4EGjA*) (s_p0));
	{
		if (!(*s_2).atTheEnd) goto LA3_;
		result = ((NI)0);
		goto BeforeRet_;
	}
LA3_: ;
	br_1 = (NI32)0;
	a_1 = Dl_1509949545_((*s_2).handle, buffer_p1, ((int) (bufLen_p2)), (&br_1), NIM_NIL);
	{
		NIM_BOOL T7_;
		NI32 T11_;
		T7_ = (NIM_BOOL)0;
		T7_ = (a_1 == ((NI32)0));
		if (!(T7_)) goto LA8_;
		T7_ = !((br_1 == ((NI32)0)));
LA8_: ;
		if (!T7_) goto LA9_;
		T11_ = (NI32)0;
		T11_ = osLastError__stdZoserrors_u125();
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		raiseOSError__stdZoserrors_u122(T11_, TM__HZdw8BhppcTQo8DIK46LSg_26);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA9_: ;
	(*s_2).atTheEnd = (br_1 == ((NI32)0));
	result = ((NI) (br_1));
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, hsWriteData__pureZosproc_u848)(tyObject_StreamObj__59a9bMG3hIslwPg3r9aB4JTRg* s_p0, void* buffer_p1, NI bufLen_p2) {
	tyObject_FileHandleStreamcolonObjectType___zP8ssNQ49cn0fN87jk4EGjA* s_2;
	NI32 bytesWritten_1;
	NI32 a_1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	s_2 = NIM_NIL;
	s_2 = ((tyObject_FileHandleStreamcolonObjectType___zP8ssNQ49cn0fN87jk4EGjA*) (s_p0));
	bytesWritten_1 = (NI32)0;
	a_1 = Dl_1509949551_((*s_2).handle, buffer_p1, ((int) (bufLen_p2)), (&bytesWritten_1), NIM_NIL);
	{
		NI32 T5_;
		if (!(a_1 == ((NI32)0))) goto LA3_;
		T5_ = (NI32)0;
		T5_ = osLastError__stdZoserrors_u125();
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		raiseOSError__stdZoserrors_u122(T5_, TM__HZdw8BhppcTQo8DIK46LSg_27);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA3_: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_FileHandleStreamcolonObjectType___zP8ssNQ49cn0fN87jk4EGjA*, newFileHandleStream__pureZosproc_u855)(NI handle_p0) {
	tyObject_FileHandleStreamcolonObjectType___zP8ssNQ49cn0fN87jk4EGjA* result;
	tyObject_FileHandleStreamcolonObjectType___zP8ssNQ49cn0fN87jk4EGjA* T1_;
	T1_ = NIM_NIL;
	T1_ = (tyObject_FileHandleStreamcolonObjectType___zP8ssNQ49cn0fN87jk4EGjA*) nimNewObj(sizeof(tyObject_FileHandleStreamcolonObjectType___zP8ssNQ49cn0fN87jk4EGjA), NIM_ALIGNOF(tyObject_FileHandleStreamcolonObjectType___zP8ssNQ49cn0fN87jk4EGjA));
	(*T1_).Sup.Sup.m_type = (&NTIv2__zP8ssNQ49cn0fN87jk4EGjA_);
	(*T1_).handle = handle_p0;
	(*T1_).Sup.closeImpl = hsClose__pureZosproc_u772;
	(*T1_).Sup.atEndImpl = hsAtEnd__pureZosproc_u837;
	(*T1_).Sup.readDataImpl = hsReadData__pureZosproc_u840;
	(*T1_).Sup.writeDataImpl = hsWriteData__pureZosproc_u848;
	result = T1_;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZosproc_u780)(tyObject_FileHandleStreamcolonObjectType___zP8ssNQ49cn0fN87jk4EGjA* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn(dest_p0);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose(dest_p0);
	}
LA4_: ;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_StreamObj__59a9bMG3hIslwPg3r9aB4JTRg*, nospoutputStream)(tyObject_ProcessObj__UmZS0xU7o5OSPf9bpi5tgIA* p_p0) {
	tyObject_StreamObj__59a9bMG3hIslwPg3r9aB4JTRg* result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	{
		tyObject_FileHandleStreamcolonObjectType___zP8ssNQ49cn0fN87jk4EGjA* T5_;
		if (!((*p_p0).outStream == ((tyObject_StreamObj__59a9bMG3hIslwPg3r9aB4JTRg*) NIM_NIL))) goto LA3_;
		T5_ = NIM_NIL;
		T5_ = newFileHandleStream__pureZosproc_u855((*p_p0).outHandle);
		if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___pureZosproc_u780(T5_); goto BeforeRet_;}
		eqsink___pureZstreams_u797(&(*p_p0).outStream, &T5_->Sup);
	}
LA3_: ;
	eqcopy___pureZstreams_u789(&result, (*p_p0).outStream, NIM_FALSE);
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_StreamObj__59a9bMG3hIslwPg3r9aB4JTRg*, nospinputStream)(tyObject_ProcessObj__UmZS0xU7o5OSPf9bpi5tgIA* p_p0) {
	tyObject_StreamObj__59a9bMG3hIslwPg3r9aB4JTRg* result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	{
		tyObject_FileHandleStreamcolonObjectType___zP8ssNQ49cn0fN87jk4EGjA* T5_;
		if (!((*p_p0).inStream == ((tyObject_StreamObj__59a9bMG3hIslwPg3r9aB4JTRg*) NIM_NIL))) goto LA3_;
		T5_ = NIM_NIL;
		T5_ = newFileHandleStream__pureZosproc_u855((*p_p0).inHandle);
		if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___pureZosproc_u780(T5_); goto BeforeRet_;}
		eqsink___pureZstreams_u797(&(*p_p0).inStream, &T5_->Sup);
	}
LA3_: ;
	eqcopy___pureZstreams_u789(&result, (*p_p0).inStream, NIM_FALSE);
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, nosppeekExitCode)(tyObject_ProcessObj__UmZS0xU7o5OSPf9bpi5tgIA* p_p0) {
	NI result;
	NIM_BOOL b_1;
	NI32 T5_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	{
		if (!(*p_p0).exitFlag) goto LA3_;
		result = ((NI) ((*p_p0).exitStatus));
		goto BeforeRet_;
	}
LA3_: ;
	result = ((NI)-1);
	T5_ = (NI32)0;
	T5_ = Dl_1509949593_((*p_p0).fProcessHandle, ((NI32)0));
	b_1 = (T5_ == ((NI32)258));
	{
		NI32 status_1;
		NI32 T10_;
		if (!!(b_1)) goto LA8_;
		status_1 = (NI32)0;
		T10_ = (NI32)0;
		T10_ = Dl_1509949599_((*p_p0).fProcessHandle, (&status_1));
		(void)(T10_);
		(*p_p0).exitFlag = NIM_TRUE;
		(*p_p0).exitStatus = status_1;
		closeThreadAndProcessHandle__pureZosproc_u1115(p_p0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		result = ((NI) (status_1));
	}
LA8_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyTuple__XOVT24GHXwqiEj5GCsEGCA, execCmdEx__pureZosproc_u1806)(NimStringV2 command_p0, tySet_tyEnum_ProcessOption__O0VnkOD1kPGXGbZ5LEvw9cw options_p1, tyObject_StringTableObj__MtedWbN0LmvZq2M8UCJLpA* env_p2, NimStringV2 workingDir_p3, NimStringV2 input_p4) {
	tyTuple__XOVT24GHXwqiEj5GCsEGCA result;
	tyObject_ProcessObj__UmZS0xU7o5OSPf9bpi5tgIA* p_1;
	tyObject_StreamObj__59a9bMG3hIslwPg3r9aB4JTRg* outp_1;
	tyObject_StreamObj__59a9bMG3hIslwPg3r9aB4JTRg* colontmpD_;
	NimStringV2 colontmp_;
	NimStringV2 line_1;
	tyArray__TonP9cxJgj8gXu71dWIyNlA T2_;
	NI colontmp__2;
	NimStringV2 blitTmp_1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&result), sizeof(tyTuple__XOVT24GHXwqiEj5GCsEGCA));
	p_1 = NIM_NIL;
	outp_1 = NIM_NIL;
	colontmpD_ = NIM_NIL;
	colontmp_.len = 0; colontmp_.p = NIM_NIL;
	line_1.len = 0; line_1.p = NIM_NIL;
	p_1 = nospstartProcess(command_p0, workingDir_p3, T2_, 0, env_p2, (options_p1 | 4));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	outp_1 = nospoutputStream(p_1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		tyObject_StreamObj__59a9bMG3hIslwPg3r9aB4JTRg* colontmpD__2;
		if (!(((NI)0) < input_p4.len)) goto LA5_;
		colontmpD__2 = NIM_NIL;
		colontmpD__2 = nospinputStream(p_1);
		if (NIM_UNLIKELY(*nimErr_)) goto LA7_;
		write__pureZstreams_u221(colontmpD__2, input_p4);
		if (NIM_UNLIKELY(*nimErr_)) goto LA7_;
		{
			LA7_:;
		}
		{
			eqdestroy___pureZstreams_u786(colontmpD__2);
		}
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	}
LA5_: ;
	colontmpD_ = nospinputStream(p_1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	close__pureZstreams_u57(colontmpD_);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	colontmp_ = TM__HZdw8BhppcTQo8DIK46LSg_28;
	colontmp__2 = ((NI)-1);
	blitTmp_1 = colontmp_;
	eqwasMoved___system_u2720((&colontmp_));
	result.Field0 = blitTmp_1;
	result.Field1 = colontmp__2;
	line_1 = rawNewString(((NI)120));
	{
		while (1) {
			{
				NIM_BOOL T14_;
				T14_ = (NIM_BOOL)0;
				T14_ = readLine__pureZstreams_u668(outp_1, (&line_1));
				if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
				if (!T14_) goto LA15_;
				prepareAdd((&result.Field0), line_1.len + 0);
appendString((&result.Field0), line_1);
				prepareAdd((&result.Field0), 1);
appendString((&result.Field0), TM__HZdw8BhppcTQo8DIK46LSg_30);
			}
			goto LA12_;
LA15_: ;
			{
				NI T18_;
				T18_ = (NI)0;
				T18_ = nosppeekExitCode(p_1);
				if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
				result.Field1 = T18_;
				{
					if (!!((result.Field1 == ((NI)-1)))) goto LA21_;
					goto LA10;
				}
LA21_: ;
			}
LA12_: ;
		}
	} LA10: ;
	nospclose(p_1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		LA1_:;
	}
	{
		if (line_1.p && !(line_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(line_1.p);
}
		if (colontmp_.p && !(colontmp_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmp_.p);
}
		eqdestroy___pureZstreams_u786(colontmpD_);
		eqdestroy___pureZstreams_u786(outp_1);
		eqdestroy___pureZosproc_u228(p_1);
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZosproc_u1850)(tyTuple__XOVT24GHXwqiEj5GCsEGCA* dest_p0) {
	if ((*dest_p0).Field0.p && !((*dest_p0).Field0.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Field0.p);
}
}
