/* Generated by Nim Compiler v2.2.10 */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   x86_64-w64-mingw32-gcc -c -w -fmax-errors=3 -mno-ms-bitfields -fno-strict-aliasing -DWIN32_LEAN_AND_MEAN -Os -fno-ident   -I/home/kali/.choosenim/toolchains/nim-2.2.10/lib -I/home/kali/c2/agents/agent-nim -o /home/kali/c2/agents/agent-nim/nimcache_http/@prandom.nim.c.o /home/kali/c2/agents/agent-nim/nimcache_http/@prandom.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <windows.h>
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tyObject_Rand__Da3XLwSUBwRe8DHcl72ltA tyObject_Rand__Da3XLwSUBwRe8DHcl72ltA;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
struct tyObject_Rand__Da3XLwSUBwRe8DHcl72ltA {
	NU64 a0;
	NU64 a1;
};
typedef NU8 tyArray__dnD8kjh6rJ1Yy5jHvid0Ow[16];
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
typedef NU64 tyArray__taWZDEZhXZ6W9aPxa9aL9aXaA[2];
static N_INLINE(void, initLock__coreZlocks_u7)(CRITICAL_SECTION* lock_p0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(tyObject_Rand__Da3XLwSUBwRe8DHcl72ltA, initRand__pureZrandom_u315)(void);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__system_u2188)(void* a_p0, int v_p1, NI size_p2);
static N_INLINE(void, acquire__coreZlocks_u14)(CRITICAL_SECTION* lock_p0);
static N_INLINE(NIM_BOOL, isValid__pureZrandom_u16)(tyObject_Rand__Da3XLwSUBwRe8DHcl72ltA r_p0);
N_LIB_PRIVATE N_NIMCALL(tyObject_Rand__Da3XLwSUBwRe8DHcl72ltA, getRandomState__pureZrandom_u317)(void);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, urandom__stdZsysrand_u32)(NU8* dest_p0, NI dest_p0Len_0);
static N_INLINE(void, copyMem__system_u1755)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(void, quit__system_u8540)(NimStringV2 errormsg_p0, NI errorcode_p1);
N_LIB_PRIVATE N_NIMCALL(void, skipRandomNumbers__pureZrandom_u45)(tyObject_Rand__Da3XLwSUBwRe8DHcl72ltA* s_p0);
N_LIB_PRIVATE N_NIMCALL(NU64, next__pureZrandom_u36)(tyObject_Rand__Da3XLwSUBwRe8DHcl72ltA* r_p0);
N_LIB_PRIVATE N_NIMCALL(NU64, rotl__pureZrandom_u24)(NU64 x_p0, NU64 k_p1);
static N_INLINE(void, release__coreZlocks_u16)(CRITICAL_SECTION* lock_p0);
N_LIB_PRIVATE N_NIMCALL(NI, rand__pureZrandom_u114)(tyObject_Rand__Da3XLwSUBwRe8DHcl72ltA* r_p0, NI max_p1);
N_LIB_PRIVATE N_NIMCALL(NU64, rand__pureZrandom_u118)(tyObject_Rand__Da3XLwSUBwRe8DHcl72ltA* r_p0, NU64 max_p1);
N_LIB_PRIVATE N_NIMCALL(NF, rand__pureZrandom_u146)(tyObject_Rand__Da3XLwSUBwRe8DHcl72ltA* r_p0, NF max_p1);
N_LIB_PRIVATE N_NIMCALL(void, nimTestErrorFlag)(void);
static const struct {
  NI cap; NIM_CHAR data[81+1];
} TM__AIKkgex03Z1j45JceakCTA_2 = { 81 | NIM_STRLIT_FLAG, "Failed to initializes baseState in random module as sysrand.urandom doesn\'t work." };
static const NimStringV2 TM__AIKkgex03Z1j45JceakCTA_3 = {81, (NimStrPayload*)&TM__AIKkgex03Z1j45JceakCTA_2};
N_LIB_PRIVATE NIM_CONST tyObject_Rand__Da3XLwSUBwRe8DHcl72ltA DefaultRandSeed__pureZrandom_u14 = {7616934476015405061ULL, 15122295919272093642ULL}
;
N_LIB_PRIVATE NIM_CONST tyArray__taWZDEZhXZ6W9aPxa9aL9aXaA helper__pureZrandom_u47 = {13739361407582206667ULL,
15594563132006766882ULL}
;
N_LIB_PRIVATE tyObject_Rand__Da3XLwSUBwRe8DHcl72ltA state__pureZrandom_u15;
N_LIB_PRIVATE CRITICAL_SECTION baseSeedLock__pureZrandom_u313;
N_LIB_PRIVATE tyObject_Rand__Da3XLwSUBwRe8DHcl72ltA baseState__pureZrandom_u314;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4172;
static N_INLINE(void, initLock__coreZlocks_u7)(CRITICAL_SECTION* lock_p0) {
	InitializeCriticalSection(lock_p0);
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4172);
	return result;
}
static N_INLINE(void, nimSetMem__system_u2188)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
	nimSetMem__system_u2188(p_p0, ((int)0), size_p1);
}
static N_INLINE(void, acquire__coreZlocks_u14)(CRITICAL_SECTION* lock_p0) {
	EnterCriticalSection(lock_p0);
}
static N_INLINE(NIM_BOOL, isValid__pureZrandom_u16)(tyObject_Rand__Da3XLwSUBwRe8DHcl72ltA r_p0) {
	NIM_BOOL result;
	NIM_BOOL T1_;
	T1_ = (NIM_BOOL)0;
	T1_ = (r_p0.a0 == 0ULL);
	if (!(T1_)) goto LA2_;
	T1_ = (r_p0.a1 == 0ULL);
LA2_: ;
	result = !(T1_);
	return result;
}
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, copyMem__system_u1755)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
N_LIB_PRIVATE N_NIMCALL(tyObject_Rand__Da3XLwSUBwRe8DHcl72ltA, getRandomState__pureZrandom_u317)(void) {
	tyObject_Rand__Da3XLwSUBwRe8DHcl72ltA result;
	tyArray__dnD8kjh6rJ1Yy5jHvid0Ow urand_1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&result), sizeof(tyObject_Rand__Da3XLwSUBwRe8DHcl72ltA));
	nimZeroMem((void*)urand_1, sizeof(tyArray__dnD8kjh6rJ1Yy5jHvid0Ow));
	nimZeroMem((void*)urand_1, sizeof(tyArray__dnD8kjh6rJ1Yy5jHvid0Ow));
	{
		NI i_1;
		NI res_1;
		i_1 = (NI)0;
		res_1 = ((NI)0);
		{
			while (1) {
				if (!(res_1 <= ((NI)7))) goto LA3;
				i_1 = ((NI) (res_1));
				{
					NIM_BOOL T6_;
					T6_ = (NIM_BOOL)0;
					T6_ = urandom__stdZsysrand_u32(urand_1, 16);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					if (!T6_) goto LA7_;
					copyMem__system_u1755(((void*) ((&result))), ((void*) ((&urand_1[(((NI)0))- 0]))), ((NI)16));
					{
						NIM_BOOL T11_;
						T11_ = (NIM_BOOL)0;
						T11_ = isValid__pureZrandom_u16(result);
						if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
						if (!T11_) goto LA12_;
						goto LA1;
					}
LA12_: ;
				}
LA7_: ;
				res_1 += ((NI)1);
			} LA3: ;
		}
	} LA1: ;
	{
		NIM_BOOL T16_;
		T16_ = (NIM_BOOL)0;
		T16_ = isValid__pureZrandom_u16(result);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!!(T16_)) goto LA17_;
		quit__system_u8540(TM__AIKkgex03Z1j45JceakCTA_3, ((NI)1));
	}
LA17_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NU64, rotl__pureZrandom_u24)(NU64 x_p0, NU64 k_p1) {
	NU64 result;
	result = (NU64)((NU64)((NU64)(x_p0) << (NU64)(k_p1 & (64 - 1))) | (NU64)((NU64)(x_p0) >> (NU64)((NU64)((NU64)(64ULL) - (NU64)(k_p1)) & (64 - 1))));
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NU64, next__pureZrandom_u36)(tyObject_Rand__Da3XLwSUBwRe8DHcl72ltA* r_p0) {
	NU64 result;
	NU64 s0_1;
	NU64 s1_1;
	NU64 T1_;
	NU64 T2_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	s0_1 = (*r_p0).a0;
	s1_1 = (*r_p0).a1;
	result = (NU64)((NU64)(s0_1) + (NU64)(s1_1));
	s1_1 = (NU64)(s1_1 ^ s0_1);
	T1_ = (NU64)0;
	T1_ = rotl__pureZrandom_u24(s0_1, 55ULL);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	(*r_p0).a0 = (NU64)((NU64)(T1_ ^ s1_1) ^ (NU64)((NU64)(s1_1) << (NU64)(((NI)14) & (64 - 1))));
	T2_ = (NU64)0;
	T2_ = rotl__pureZrandom_u24(s1_1, 36ULL);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	(*r_p0).a1 = T2_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, skipRandomNumbers__pureZrandom_u45)(tyObject_Rand__Da3XLwSUBwRe8DHcl72ltA* s_p0) {
	NU64 s0_1;
	NU64 s1_1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	s0_1 = 0ULL;
	s1_1 = 0ULL;
	{
		NI i_1;
		NI res_1;
		i_1 = (NI)0;
		res_1 = ((NI)0);
		{
			while (1) {
				if (!(res_1 <= ((NI)1))) goto LA3;
				i_1 = ((NI) (res_1));
				{
					NI b_1;
					NI i_2;
					b_1 = (NI)0;
					i_2 = ((NI)0);
					{
						while (1) {
							NU64 T11_;
							if (!(i_2 < ((NI)64))) goto LA6;
							b_1 = i_2;
							{
								if (!!(((NU64)(helper__pureZrandom_u47[(i_1)- 0] & (NU64)((NU64)(1ULL) << (NU64)(((NU64) (b_1)) & (64 - 1)))) == 0ULL))) goto LA9_;
								s0_1 = (NU64)(s0_1 ^ (*s_p0).a0);
								s1_1 = (NU64)(s1_1 ^ (*s_p0).a1);
							}
LA9_: ;
							T11_ = (NU64)0;
							T11_ = next__pureZrandom_u36(s_p0);
							if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
							(void)(T11_);
							i_2 += ((NI)1);
						} LA6: ;
					}
				}
				res_1 += ((NI)1);
			} LA3: ;
		}
	}
	(*s_p0).a0 = s0_1;
	(*s_p0).a1 = s1_1;
	}BeforeRet_: ;
}
static N_INLINE(void, release__coreZlocks_u16)(CRITICAL_SECTION* lock_p0) {
	LeaveCriticalSection(lock_p0);
}
N_LIB_PRIVATE N_NIMCALL(tyObject_Rand__Da3XLwSUBwRe8DHcl72ltA, initRand__pureZrandom_u315)(void) {
	tyObject_Rand__Da3XLwSUBwRe8DHcl72ltA result;
NIM_BOOL oldNimErrFin1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&result), sizeof(tyObject_Rand__Da3XLwSUBwRe8DHcl72ltA));
	acquire__coreZlocks_u14((&baseSeedLock__pureZrandom_u313));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		NIM_BOOL T4_;
		tyObject_Rand__Da3XLwSUBwRe8DHcl72ltA T7_;
		T4_ = (NIM_BOOL)0;
		T4_ = isValid__pureZrandom_u16(baseState__pureZrandom_u314);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		if (!!(T4_)) goto LA5_;
		nimZeroMem((void*)(&T7_), sizeof(tyObject_Rand__Da3XLwSUBwRe8DHcl72ltA));
		T7_ = getRandomState__pureZrandom_u317();
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		baseState__pureZrandom_u314 = T7_;
	}
LA5_: ;
	result = baseState__pureZrandom_u314;
	skipRandomNumbers__pureZrandom_u45((&baseState__pureZrandom_u314));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		LA1_:;
	}
	{
		oldNimErrFin1_ = *nimErr_; *nimErr_ = NIM_FALSE;
		release__coreZlocks_u16((&baseSeedLock__pureZrandom_u313));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		*nimErr_ = oldNimErrFin1_;
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, randomize__pureZrandom_u377)(void) {
	tyObject_Rand__Da3XLwSUBwRe8DHcl72ltA T1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&T1_), sizeof(tyObject_Rand__Da3XLwSUBwRe8DHcl72ltA));
	T1_ = initRand__pureZrandom_u315();
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	state__pureZrandom_u15 = T1_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(NU64, rand__pureZrandom_u118)(tyObject_Rand__Da3XLwSUBwRe8DHcl72ltA* r_p0, NU64 max_p1) {
	NU64 result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NU64)0;
	{
		if (!(max_p1 == 0ULL)) goto LA3_;
		goto BeforeRet_;
	}
	goto LA1_;
LA3_: ;
	{
		NU64 max_2;
		NI iters_1;
		max_2 = max_p1;
		{
			if (!(max_2 == 18446744073709551615ULL)) goto LA8_;
			result = next__pureZrandom_u36(r_p0);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			goto BeforeRet_;
		}
LA8_: ;
		iters_1 = ((NI)0);
		{
			while (1) {
				NU64 x_1;
				x_1 = next__pureZrandom_u36(r_p0);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				{
					NIM_BOOL T14_;
					T14_ = (NIM_BOOL)0;
					T14_ = ((NU64)(x_1) <= (NU64)((NU64)((NU64)(18446744073709551615ULL) - (NU64)((NU64)((NU64)(18446744073709551615ULL) % (NU64)(max_2))))));
					if (T14_) goto LA15_;
					T14_ = (((NI)20) < iters_1);
LA15_: ;
					if (!T14_) goto LA16_;
					result = (NU64)((NU64)(x_1) % (NU64)((NU64)((NU64)(max_2) + (NU64)(1ULL))));
					goto BeforeRet_;
				}
				goto LA12_;
LA16_: ;
				{
					iters_1 += ((NI)1);
				}
LA12_: ;
			}
		}
	}
LA1_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, rand__pureZrandom_u114)(tyObject_Rand__Da3XLwSUBwRe8DHcl72ltA* r_p0, NI max_p1) {
	NI result;
	NU64 T1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	T1_ = (NU64)0;
	T1_ = rand__pureZrandom_u118(r_p0, ((NU64) (max_p1)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result = ((NI) (T1_));
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, rand__pureZrandom_u143)(NI max_p0) {
	NI result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	result = rand__pureZrandom_u114((&state__pureZrandom_u15), (max_p0));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NF, rand__pureZrandom_u146)(tyObject_Rand__Da3XLwSUBwRe8DHcl72ltA* r_p0, NF max_p1) {
	NF result;
	NU64 x_1;
	NU64 u_1;
	union { NU64 source; NF dest; } LOC1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NF)0;
	x_1 = next__pureZrandom_u36(r_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	u_1 = (NU64)(4607182418800017408ULL | (NU64)((NU64)(x_1) >> (NU64)(12ULL & (64 - 1))));
	LOC1.source = u_1;
	result = ((NF)(((NF)(LOC1.dest) - (NF)(1.0))) * (NF)(max_p1));
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NF, rand__pureZrandom_u183)(NF max_p0) {
	NF result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NF)0;
	result = rand__pureZrandom_u146((&state__pureZrandom_u15), (max_p0));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, atprandomdotnim_Init000)(void) {
{
NIM_BOOL* nimErr_;
nimErr_ = nimErrorFlag();
	state__pureZrandom_u15 = DefaultRandSeed__pureZrandom_u14;
	initLock__coreZlocks_u7((&baseSeedLock__pureZrandom_u313));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	BeforeRet_: ;
	nimTestErrorFlag();
}
}

