/* Generated by Nim Compiler v2.2.10 */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   x86_64-w64-mingw32-gcc -c -w -fmax-errors=3 -mno-ms-bitfields -fno-strict-aliasing -DWIN32_LEAN_AND_MEAN -Os -fno-ident   -I/home/kali/.choosenim/toolchains/nim-2.2.10/lib -I/home/kali/c2/agents/agent-nim -o /home/kali/c2/agents/agent-nim/nimcache_nim5/@nnimcrypto-0.7.3-f72b90fe3f4da09efa482de4f8729e7ee4abea2f@snimcrypto@sutils.nim.c.o /home/kali/c2/agents/agent-nim/nimcache_nim5/@nnimcrypto-0.7.3-f72b90fe3f4da09efa482de4f8729e7ee4abea2f@snimcrypto@sutils.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include "windows.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
N_LIB_PRIVATE N_NIMCALL(void, burnMem__pkgZnimcryptoZutils_u303)(void* p_p0, NI size_p1) {
	SecureZeroMemory(p_p0, ((size_t) (size_p1)));
}
