/* Generated by Nim Compiler v2.2.10 */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   x86_64-w64-mingw32-gcc -c -w -fmax-errors=3 -mno-ms-bitfields -fno-strict-aliasing -DWIN32_LEAN_AND_MEAN -Os -fno-ident   -I/home/kali/.choosenim/toolchains/nim-2.2.10/lib -I/home/kali/c2/agents/agent-nim -o /home/kali/c2/agents/agent-nim/nimcache_nim5/@pstd@sprivate@soscommon.nim.c.o /home/kali/c2/agents/agent-nim/nimcache_nim5/@pstd@sprivate@soscommon.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_WIN32_FIND_DATA__Ygx8jNn4fKnE0Znor9bYRxQ tyObject_WIN32_FIND_DATA__Ygx8jNn4fKnE0Znor9bYRxQ;
typedef struct tyObject_WideCStringObj__jQbOKocsbu7Z9bKTSFtX4TQ tyObject_WideCStringObj__jQbOKocsbu7Z9bKTSFtX4TQ;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tyObject_WideCStringObj__jQbOKocsbu7Z9bKTSFtX4TQ {
	NI bytes;
	NI16* data;
};
typedef N_STDCALL_PTR(NI, tyProc__lCGM9cmBs4TguFMTOt5tjdg) (NI16* lpFileName_p0, tyObject_WIN32_FIND_DATA__Ygx8jNn4fKnE0Znor9bYRxQ* lpFindFileData_p1);
typedef NI16 tyUncheckedArray__Tyd4y3haUOOHTj71TPIRag[1];
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__system_u2188)(void* a_p0, int v_p1, NI size_p2);
static N_INLINE(NI16*, toWideCString__stdZwidestrs_u49)(tyObject_WideCStringObj__jQbOKocsbu7Z9bKTSFtX4TQ x_p0);
N_LIB_PRIVATE N_NIMCALL(tyObject_WideCStringObj__jQbOKocsbu7Z9bKTSFtX4TQ, newWideCString__stdZwidestrs_u325)(NimStringV2 s_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___stdZwidestrs_u7)(tyObject_WideCStringObj__jQbOKocsbu7Z9bKTSFtX4TQ a_p0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
extern tyProc__lCGM9cmBs4TguFMTOt5tjdg Dl_1509949689_;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4172;
static N_INLINE(void, nimSetMem__system_u2188)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
	nimSetMem__system_u2188(p_p0, ((int)0), size_p1);
}
static N_INLINE(NI16*, toWideCString__stdZwidestrs_u49)(tyObject_WideCStringObj__jQbOKocsbu7Z9bKTSFtX4TQ x_p0) {
	NI16* result;
	result = x_p0.data;
	return result;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4172);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, findFirstFile__stdZprivateZoscommon_u24)(NimStringV2 a_p0, tyObject_WIN32_FIND_DATA__Ygx8jNn4fKnE0Znor9bYRxQ* b_p1) {
	NI result;
	tyObject_WideCStringObj__jQbOKocsbu7Z9bKTSFtX4TQ colontmpD_;
	NI16* T1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	nimZeroMem((void*)(&colontmpD_), sizeof(tyObject_WideCStringObj__jQbOKocsbu7Z9bKTSFtX4TQ));
	colontmpD_ = newWideCString__stdZwidestrs_u325(a_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T1_ = (NI16*)0;
	T1_ = toWideCString__stdZwidestrs_u49(colontmpD_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result = Dl_1509949689_(T1_, b_p1);
	eqdestroy___stdZwidestrs_u7(colontmpD_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
